### ISSUE TITLE
Crash on connecting to MQTT using ALPN

### ISSUE THREAD

**Issue by beersheba** [aws-amplify/aws-sdk-android#1004]
**Describe the bug**
I'm getting crash on connecting to MQTT using ALPN.

```
06-02 09:47:27.824 17143-17143/com.appcard.androidterminal E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.appcard.androidterminal, PID: 17143
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.appcard.androidterminal-2/base.apk"],nativeLibraryDirectories=[/data/app/com.appcard.androidterminal-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libconscrypt_jni.so"
        at java.lang.Runtime.loadLibrary(Runtime.java:367)
        at java.lang.System.loadLibrary(System.java:988)
        at org.conscrypt.NativeCryptoJni.init(NativeCryptoJni.java:28)
        at org.conscrypt.NativeCrypto.<clinit>(NativeCrypto.java:65)
        at org.conscrypt.OpenSSLProvider.<init>(OpenSSLProvider.java:60)
        at org.conscrypt.OpenSSLProvider.<init>(OpenSSLProvider.java:53)
        at org.conscrypt.OpenSSLProvider.<init>(OpenSSLProvider.java:49)
        at com.amazonaws.mobileconnectors.iot.AWSIotSslUtility.getSocketFactoryWithKeyStore(AWSIotSslUtility.java:69)
        at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.connect(AWSIotMqttManager.java:803)
        at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.connectUsingALPN(AWSIotMqttManager.java:735)
```

**To Reproduce**
A code sample or steps:
```
        mMqttManager = new AWSIotMqttManager(thingName, thingUrl);
        mMqttManager.setMaxAutoReconnectAttempts(-1);
        KeyStore clientKeyStore = AWSIotKeystoreHelper.getIotKeystore(CERTIFICATE_ID,
                keystorePath, KEYSTORE_NAME, KEYSTORE_PASSWORD);
        mMqttManager.connectUsingALPN(clientKeyStore, mqttCallback);
```

**Which AWS service(s) are affected?**
AWS IoT

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.13.4
 - Device: Lp PT7003_AC
 - Android Version: 5.1
 - Specific to simulators: No

**Additional context**
Connect on port 8883 works fine.

**Comment by desokroshan** [comment]
Can you please share more context around the snippet? The snippet you have shared works fine for me and does not reproduce the error.

**Comment by beersheba** [comment]
Crash happens in `NativeCryptoJni.init()`, on this line:
`System.loadLibrary("conscrypt_jni");`

There are other JNI libs used in the project.
Path to them defined in app build.gradle
```
sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    } 
```
May this be the reason?

**Comment by desokroshan** [comment]
I would strongly suspect that to be the case. Modifying the default source set configuration to point to different directory for prebuilt .so files changes the place where Gradle looks to gather file for each component of the source set and being unable to locate `libconscrypt_jni.so` throws up the stack trace you shared. Could you try to reproduce this issue in the following sample app with the setting that you have for jni libraries : 
https://github.com/awslabs/aws-sdk-android-samples/tree/master/AndroidPubSub

You can replace [the connect method](https://github.com/awslabs/aws-sdk-android-samples/blob/master/AndroidPubSub/src/com/amazonaws/demo/androidpubsub/PubSubActivity.java#L92) with `connectUsingALPN` without having to change anything else. Thanks!

**Comment by beersheba** [comment]
@desokroshan Can't build the sample app in Android Studio 3.4.1. Getting this error:
`Gradle sync failed: Plugin with id 'com.android.application' not found.`

Please suggest.

**Comment by desokroshan** [comment]
@beersheba I have created  a PR, referenced above, updating the gradle version in the sample to the latest. Can you please try it out confirm if it works?

**Comment by beersheba** [comment]
> @beersheba I have created a PR, referenced above, updating the gradle version in the sample to the latest. Can you please try it out confirm if it works?

Yes, branch update-pubsub-sample can be built on my side

**Comment by beersheba** [comment]
@desokroshan crash is reproduced with AndroidPubSub project.
It happens on adding

```
ndk {
            abiFilters "armeabi"
        }
```
to `defaultConfig` of **build.gradle**

**Comment by beersheba** [comment]
@desokroshan can you please check it and provide an update?

**Comment by desokroshan** [comment]
@beersheba Can you elaborate on why you need this directive? I am not very familiar with it so can't comment on a workaround for handling this. What is clear though is that it's obstructing linker from locating the required binaries.

**Comment by beersheba** [comment]
Because I develop for armeabi device and use JNI libs (*.so). 
All my libs reside in src/main/jniLibs/armeabi directory.
I use this directive since Gradle 4, otherwise, my libs are not available to use.

**Comment by raphkim** [comment]
Unfortunately, Google currently only has support for four architectures on their [conscrypt_jni.so library](https://github.com/google/conscrypt#android). Exclusively filtering for 'armeabi' will not include any binary in your APK, causing your app to be unable to locate the library. I would suggest removing the abiFilter to allow the binaries to be zipped with APK and seeing if an armeabi device is compatible with any.

**Comment by beersheba** [comment]
@raphkim thank you very much! 

I found a workaround:
1. renamed *.so directory to armeabi-v7a
2 changed gradle abiFilters to "armeabi-v7a" 

and it works )
