### ISSUE TITLE
Add acknowledge callback to subscribeToTopic() like the iOS IoT SDK has

### ISSUE THREAD

**Issue by jarvis32123** [aws-amplify/aws-sdk-android#1005]
The iOS IoT SDK has an acknowledge callback that is fired when you successfully subscribe to a topic. This is very useful.

Can you add the same thing to the android version?

Thank you.

**Comment by desokroshan** [comment]
@jarvis32123 This was released in the version 2.14.2 of the SDK.

**Comment by jarvis32123** [comment]
@desokroshan I just updated the SDK to 2.2.13 and now the callback is gone?
