### ISSUE TITLE
Video upload fails to Amazon S3 bucket inconsistently

### ISSUE THREAD

**Issue by partheebanj** [aws-amplify/aws-sdk-android#1006]
**Describe the bug**
Uploading videos to Amazon S3 fails inconsistently. I have been able to upload videos successfully, but there are certain instances when the upload fails with the following error: com.amazonaws.AmazonClientException: Unable to execute HTTP request: connect timed out. 

**To Reproduce**
Uploading videos to Amazon S3

Your code

                val key = AccountSessionManager.awsPath(remoteKey, bucket,t)
                val bucketName = AccountSessionManager.awsBucket(bucket,t)

                val clientConfiguration = ClientConfiguration()
                        .withMaxErrorRetry(3) // 3 retries
                        .withConnectionTimeout(120000) // 120,000 ms
                        .withSocketTimeout(120000) // 120,000 ms

                val credentials = BasicSessionCredentials(t!!.accessKeyId, t.secretAccessKey, t.sessionToken)
                val s3Client = AmazonS3Client(credentials, Constants.S3Region, clientConfiguration)

                val transferUtility = TransferUtility
                        .builder()
                        .s3Client(s3Client)
                        .context(mContext)
                        .build()

                val uploadObserver = transferUtility.upload(bucketName, key, file)

**Which AWS service(s) are affected?**
Amazon S3

**Expected behavior**
Video upload successfully without any failures

 - AWS Android SDK Version: 2.13.0
 - Device: Samsung
 - Specific to simulators: No

The internet connection speed is good and I have been able to successfully upload many videos except some. Trying to upload again works fine, but want to know the root cause on why I am getting this error.

**Comment by kvasukib** [comment]
@partheebanj Thank you for reporting to us. The exception you reported occurs when the network goes offline when a transfer is in progress. We have two recommendations to checkpoint the transfer and then resume when network comes back online.

1) Using a `TransferService` will register a callback with Android to get notified of the network connectivity changes. When network goes offline, the ongoing transfers are paused and when the network comes back online, the ongoing transfers are resumed. `TransferService` can handle this irrespective of the app being in background or foreground.

2) Using a `TransferNetworkLossHandler`: You can create an object of this handler and register it in your application. By doing so, when network goes offline, the ongoing transfers are paused and when the network comes back online, the ongoing transfers are resumed. `TransferNetworkLossHandler` only works when the app is in foreground. To make this work when your app is in background, you need to wrap the creation of this handler in an Android component (like a Service, etc.)

**Comment by partheebanj** [comment]
` tsIntent = Intent(applicationContext, TransferService::class.java)
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val notification: Notification = Notification.Builder(this, channelId)
                    .setContentTitle("Upload Service running")
                    .setContentText("Video Upload in process")
                    .setContentIntent(pendingIntent)
                    .setTicker("ticker")
                    .build()

            tsIntent?.putExtra(TransferService.INTENT_KEY_NOTIFICATION, notification)
            tsIntent?.putExtra(TransferService.INTENT_KEY_NOTIFICATION_ID, 113)
            applicationContext.startForegroundService(tsIntent)
        } else {
            applicationContext.startService(tsIntent)
        }`

We are already using TransferService. In spite of using this, we are facing upload failures inconsistently.

**Comment by kvasukib** [comment]
@partheebanj Thank you for the information. Do you get a `onStateChanged()` callback with `WAITING_FOR_NETWORK` state when you use `TransferService`? Also have you declared `TransferService` in the `AndroidManifest.xml` file?

**Comment by partheebanj** [comment]
```
     override fun onStateChanged(id: Int, state: TransferState?) {
                        if (state == TransferState.COMPLETED) {
                            awsCallback?.onSuccess("AWS_COMPLETED")
                            Log.d(TAG, "File $remoteKey upload completed")
                        } else if (state == TransferState.FAILED) {
                            awsCallback?.onFailure(Error("AWS_UPLOAD_FAILED"))
                            Log.d(TAG, "File $remoteKey upload failed")
                        } 
                    }
```

We are currently using onStateChanged with TransferState.COMPLETED and TransferState.FAILED

**Comment by kvasukib** [comment]
The `TransferUtility` when used with `TransferNetworkLossHandler` pauses the transfers when network goes offline. However there are certain circumstances where the transfer cannot be paused and eventually fails with `TransferState` set to `FAILED`.

1) When app is in background and if there is an active transfer that is in progress and network goes offline, it depends how `TransferNetworkLossHandler` is registered with the app.
  * If you just registered `TransferNetworkLossHandler` in your app, you are responsible for app being in background and the handler would not be functional when the app is in background and hence the transfer could fail.
  * If you used `TransferService`, then it would work in Android API levels up-to 25 (pre-Oreo). However, if you run on a device running Oreo and above, you need to pass a valid notification object while starting `TransferService` using `startForegroundService`, else the transfer could fail.

2) There could be a race condition between the worker thread that is actually doing the transfer and setting the transfer state and the thread that receives the network broadcast from OS and pauses the transfer. This could result in the transfer erring out with `FAILED` state.

**Comment by partheebanj** [comment]
- We are not using TransferNetworkLossHandler exclusively in our project, but it is being used within the AWS SDK (in TransferUtility).

- We are using TransferService as Foreground Service in Oreo and above OS devices.

**Please specify a way to detect and avoid a race condition as mentioned in point 2 above.**

**Comment by gitnarqt** [comment]
I had the same issue #1190 and was able to solve it by increasing my connection timeout and socket timeout to 5 minutes.

**Comment by raphkim** [comment]
Hi @partheebanj 

We have identified the root cause of your problem to be how `TransferUtility` is currently implemented to handle interrupted transfers from an actual network loss (as detected by Android OS). In such case, the transfer state will be set to `WAITING_FOR_NETWORK` and resume itself automatically upon regaining connection. Otherwise, transfer state will be set to `FAILED` and it will need to be resumed manually by the app. 

As such, an interruption due to `SocketTimeoutException` (which was likely caused by weak connection or lack of computing resources) will not be automatically recovered by the `TransferNetworkLossHandler`. Would you be able to confirm that this matches your case?

I wrote some integration tests to reproduce this condition in this [pull request](https://github.com/aws-amplify/aws-sdk-android/pull/1214) if you would like more information. As you may have discovered, such failed transfer can still be resumed without losing data by using `transferUtility.resume(id)`.
