### ISSUE TITLE
AndroidKeyStore with aws

### ISSUE THREAD

**Issue by rahulkapoor1** [aws-amplify/aws-sdk-android#1008]
**Describe the bug**
I am trying to use single keystore which is provided by a provider AndroidKeystore. I am using same key to save multiple certs.

After sending that Keystore to a client, I am getting EOF exception before connection establishment. When I try with single cert in my AndroidKeystore, it start working.

**My assumption** 
I can send a same Keystore which can have multiple certs in it and client will iterate over all certs to find out matching certs exist or not.

**To Reproduce**
Add multiple cert in AndroidKeystore and submit it to client.

**Screenshots**
![aws_eof](https://user-images.githubusercontent.com/4366112/59047731-061aa600-88a2-11e9-8020-d8ecb4fb89f0.png)

**Comment by desokroshan** [comment]
@rahulkapoor1 Thanks for reaching out. The connect APIs do not explicitly iterate over all the certificates in the KeyStore to ensure a matching cert but you can use [`AWSIotKeystoreHelper.getIotKeystore`](https://github.com/aws-amplify/aws-sdk-android/blob/1d492dc7d8ad37a14596ddc337ba1a0733ec1182/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotKeystoreHelper.java#L207-L252), specify your KeyStore and id of the certificate you want to use and the utility would return a KeyStore with just the specified certificate which you can then use with the connect API. Please take a look at the following snippet to see how you can use the utilities provided in SDK to suit your use case :

https://github.com/awslabs/aws-sdk-android-samples/blob/master/AndroidPubSub/src/com/amazonaws/demo/androidpubsub/PubSubActivity.java#L230-L237
