### ISSUE TITLE
Update Mutation with null values

### ISSUE THREAD

**Issue by Crisp3333** [aws-amplify/aws-sdk-android#1009]
**State your question**
I have an application where certain fields can be null. However, I notice updating fields that contains non-null values, cannot be updated to null. A work around is just setting null fields to the string value `"null"` and checking for this string value during query time, or for update mutation. The work a round is not a hassle, but I was just wondering if this is how `graphql` is implemented to treat `null` values passed in as a "no update" to the intended field.

In the code snippet below for `userInput`, `conversation_id` and `description` are nullable fields. However only the `descritpion` field will be updated, while the `conversation_id` will remain as the same value in the database so no update for that field.

**Which AWS Services are you utilizing?**
AppSync

**Provide code snippets (if applicable)**
`ModelUserFilterInput modelUserFilterInput = ModelUserFilterInput.builder()
                    .id(filterInput)
                    .build();`

`UpdateUserInput userInput = UpdateUserInput.builder()
                    .id(userid)
                    .conversation_id(null)
                    .description("subject")
                    .build();`

`UpdateUserMutation updateUserMutation = UpdateUserMutation.builder()
                    .input(userInput)
                    .build();`

**Environment(please complete the following information):**
 - SDK Version: [2.9.0]

**Device Information (please complete the following information):**
 - Device: [Pixel, Simulator]
 - Android Version: [Q]

**Comment by desokroshan** [comment]
Closing in favor of https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/194
