### ISSUE TITLE
Using "withMaxFaces" with "IndexFacesRequest" with Rekognition SDK

### ISSUE THREAD

**Issue by semaspahi** [aws-amplify/aws-sdk-android#1016]
Hello, as in this https://docs.aws.amazon.com/rekognition/latest/dg/add-faces-to-collection-procedure.html documentation I want to use "withMaxFaces" with "IndexFacesRequest" but realized that mobile SDK doesn't support it.

I'm using AWS Rekognition service with SDK Version: 2.13.6 
implementation 'com.amazonaws:aws-android-sdk-rekognition:2.13.6'

I am trying to add max 1 person(biggest face) to my collection. For now I am adding photo with IndexFacesRequest and after that I am keeping 1 faceId and using DeleteFacesRequest for the rest of all faceIds but it is not a good solution. Being able to use "withMaxFaces" with "IndexFacesRequest" will be better. We use GDPR in app and I am adding then deleting faces without permission. Any plans for supporting "withMaxFaces" with "IndexFacesRequest" as in JavaSDK?

**Comment by kvasukib** [comment]
@semaspahi Thank you for reporting to us. We are working on to update the low-level client with the latest changes from Amazon Rekognition.

**Comment by kvasukib** [comment]
@semaspahi The Rekognition SDK in Android has been updated in `2.14.0` version. Please upgrade to the latest and let us know if it work for you.
