### ISSUE TITLE
Useage of google auth

### ISSUE THREAD

**Issue by itdextrous** [aws-amplify/aws-sdk-android#1019]
Hello sir/ma'am 
please assist me how i can use google integeration in aws conginto

**Comment by kvasukib** [comment]
@itdextrous Can you provide more details around what issue you are running into while integration Google SignIn with Amazon Cognito?

Here is the [link](https://aws-amplify.github.io/docs/android/authentication#google-with-cognito-identity) to our docs which explains how to integrate Google SignIn with Amazon Cognito.
