### ISSUE TITLE
Unable to add TagResource in amazon SNS

### ISSUE THREAD

**Issue by Junaid1111** [aws-amplify/aws-sdk-android#1020]
Hi,
I have tried many different gradle links starting from 2.2.9 to 2.13.6 but still tagresource function is missing....!

Amazon SNS Offical Docs say you can add tag to amazon sns Topic...!

https://docs.aws.amazon.com/sns/latest/dg/sns-tutorial-list-add-remove-tags-for-topic.html

but i am unable to find that function...!

**Comment by kvasukib** [comment]
@Junaid1111 Sorry for the inconvenience caused. We are looking into generating the SDK for the updated model.

**Comment by Junaid1111** [comment]
Any Update???

**Comment by mlabieniec** [comment]
We have planning today and will take a look at pulling this in.

**Comment by Junaid1111** [comment]
Please let me known when its done,
Thanks,

**Comment by raphkim** [comment]
Hi @Junaid1111 ,

Thank you for waiting. The requested change was merged and we plan to make it available in release 2.16.0. I hope this resolves your issue.
