### ISSUE TITLE
Unable to get attribute 'UserSub' in response of /signUpInBackground API call

### ISSUE THREAD

**Issue by sim7087** [aws-amplify/aws-sdk-android#1041]
**Which AWS Services is the feature request for?**
Retrieval of 'UserSub' in signUpInBackground/ signUp API's response.

**Is your feature request related to a problem? Please describe.**
Actually, UserSub is basically a Cognito UUID which helps us find users in the backend through this uniques identifier. So, retrieving it at the time of sign up was required in the application. Because of this limitation in the android SDK we couldn't deliver this feature. On the other hand we were able to retrieve sub's value in IOS SDK.

**Describe the solution you'd like**
Add an extra argument 'userSub' in the onSuccess callback of signUpInBackgroun/signUp API.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by kvasukib** [comment]
@sim7087 Are you using `AWSMobileClient` (`aws-android-sdk-mobile-client`)? The `SignUpResult` returned from SignIn https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/results/SignUpResult.java currently does not have the `userSub`. We will add it to `SignUpResult`.

**Comment by Gperez88** [comment]
@sim7087 do you found workaround?

**Comment by sim7087** [comment]
Yes I found workaround. Now, I am using REST API for retrieving UserSub

**Comment by crj92** [comment]
@sim7087 Hi, I a using com.amazonaws:aws-android-sdk-cognitoidentityprovider, for signup process. Can you hint on the api call for the workaround you mentioned, Thanks in Advance.

**Comment by desokroshan** [comment]
@crj92 I have submitted a PR which changes SignUpHandler to receive `SignUpResult` in the callback. The `SignUpResult` can be used to obtain userSub. Can you work off of the PR and let me know if you have any issues?

**Comment by desokroshan** [comment]
This has been release in version 2.16.0 of the SDK.

**Comment by aakivbhatia** [comment]
Can we have this fixed in iOS SDK as well ? Couldnt find in v2.12.2

**Comment by sim7087** [comment]
It is already fixed in ios SDK. I got this issue on android SDK

**Comment by aakivbhatia** [comment]
@sim7087 SignupResult doesnt have UserSub in it.

**Comment by WathikAhmed** [comment]
Question:
Is userSub like a permanent user ID for the users? Because on the Amplify Admin UI it says Unique identifier (username) which means it is regarding the username as the ID for the user? Im looking for something a little more distinguishable because the users may want to change their username in the future and so a separate ID would be a lot more reliable.
