### ISSUE TITLE
How to refresh the Refresh Token?

### ISSUE THREAD

**Issue by shubhamssinghal** [aws-amplify/aws-sdk-android#1042]
I am using AWS SDK for authentication
After every 1 hour , refresh token get expired so how to regenerate the refresh token or refresh the session so that user does not need to login again

**Comment by rohandubal** [comment]
Hello @shubhamssinghal 

You can update the refresh token duration from service side (max of 10 years is possible) to ensure that new token is fetched always. If the duration of refresh token is shorter, the user will have to sign in again.

Thanks,
Rohan

**Comment by shubhamssinghal** [comment]
Hello @rohandubal 
Sorry for misunderstanding, what i want is to get new Id and access Token as it expires after every one hr. as per Doc Id and access token can be regenerate with the help of refresh token. initiateAuth method. But not able to access this method in my sdk. Can you please share some example code to update Tokens.

**Comment by royjit** [comment]
Hi @shubhamssinghal,

Please refer [here](https://aws-amplify.github.io/docs/android/authentication#token-fetch-and-refresh) on documentation and code sample for refreshing token. 
To initialize an app with auth you can refer [here](https://aws-amplify.github.io/docs/android/authentication#initialization).

**Comment by desokroshan** [comment]
Closing since this is well-past its "closing-soon" days.
