### ISSUE TITLE
How to know expiration time of refresh token?

### ISSUE THREAD

**Issue by shubhamssinghal** [aws-amplify/aws-sdk-android#1043]
Is there any function in aws android sdk to know expiration time of refresh token as we want to check if it is less than or equal to 1 hr or not ?

**Comment by rohandubal** [comment]
Hello @shubhamssinghal 

There isn't a way in which I believe we can know the expiry of refresh token. I will . check with service team and update back.  

Thanks,
Rohan

**Comment by shubhamssinghal** [comment]
Hello @rohandubal 
If any method exist please convey me
Thank You

**Comment by shubhamssinghal** [comment]
Hello @rohandubal , Normally we have provided 10 years in refresh token expiration time, But we are performing AdminGlobalSignout method to revoke all sessions of a user, if he login via new device. As per doc it takes 1 hr to revoke tokens, Thats why i need to know is there a work around to know expiration time of refreshToken.

**Comment by rohandubal** [comment]
Hello @shubhamssinghal 

I checked with the service team, and this is currently not supported.

Thanks,
Rohan
