### ISSUE TITLE
 Re-generate Access and Id token after every 1 hour in android

### ISSUE THREAD

**Issue by shubhamssinghal** [aws-amplify/aws-sdk-android#1050]
To get new Id and Access token we are using this **AWSJAVASDK-cognitoidp** method 
 --   implementation 'com.amazonaws:aws-java-sdk-cognitoidp:1.11.360'

But in **AWSAndroidSdk-cognitoidentityprovider**  we do not have adminInitiateAuth method of class AdminInitiateAuthResult which is found only in above **AWSJavaSDK** 
 --  implementation 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.6.3'

When I use both dependency then duplicate class error encountered how to resolve this error?
Else can you please help me to re-generate Access and Id token after every 1 hour in android.

**Comment by palpatim** [comment]
@shubhamssinghal 

The JavaSDK is not compatible with Android, so the duplicate class error is expected.

We suggest using [AWSMobileClient](https://aws-amplify.github.io/docs/android/authentication) for authentication, which transparently handles token refreshes as needed.
