### ISSUE TITLE
(Android & iOS) Cognito Hosted UI : After re-login - shouldn't ask for OTP

### ISSUE THREAD

**Issue by narindermalik2** [aws-amplify/aws-sdk-android#1053]
**Describe the bug**
**Is your feature request related to a problem? Please describe.**
Generally cognito's behaviour is that once a user has logged in by entering credentials and OTP, re-login only requires entering credentials but not OTP again. However, in the case of using the cognito hosted UI. OTP screen comes on every login

**To Reproduce**
1. Create a cognito hosted UI app
2. login using credentials (username and password) and OTP
3. signout from the app
4. login again
5. after entering username and password, OTP screen comes

**Expected behavior**

**Screenshots**
OTP screen shouldn't come second time onwards.

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 - Device: android and iOS both
 - OS: have checked on iOS9+ and android (7+)
 

**Additional context**
Nothing

**Comment by royjit** [comment]
Hi, Thank you for reaching out. Could you please share the settings that you use in your Cognito user pools? Also are you using AWSMobileClient ?
