### ISSUE TITLE
Multiple Push Notification Channels with Pinpoint

### ISSUE THREAD

**Issue by AlexKashi** [aws-amplify/aws-sdk-android#1055]
**State your question**
I created an app that has multiple push notification channels, eg feed comments, likes, messages. 

Is there a workaround enable/disable push notifications for each channel individually. When creating an EndpointProfile, on the android device, optOut is an all or nothing approach.

To send the push notification I am using a Lambda function and calling the [send_users_messages](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/pinpoint.html#Pinpoint.Client.send_users_messages) method.

**Which AWS Services are you utilizing?**
Pinpoint

**Environment(please complete the following information):**
 - SDK Version: 2.13.1
**Device Information (please complete the following information):**
 - Device: Pixel XL, Simulator V28

**Comment by palpatim** [comment]
In Pinpoint terms, "Channel" is a delivery method like Email, APNS, or FCM. As such, a customer opts in or out to that channel on an all-or-nothing basis. It sounds like what you could do is set endpoint attributes with notification preferences, define [Pinpoint segments](https://docs.aws.amazon.com/pinpoint/latest/developerguide/audience-define.html) with those more granular preferences, and deliver notifications to those segments.

Please see the [Pinpoint documentation](https://docs.aws.amazon.com/pinpoint/index.html) for more information on those topics.

**Comment by AlexKashi** [comment]
Thank you for the timely response. 

After examining the pinpoint documentation I am aware that I can specify notification preferences by adding custom endpoint attributes to my endpoint profile.  

I am finding it difficult to understand how to generate a segment for a single user. It seems as though I would have to make a different segment for each user by hardcoding the userId in a user attribute. Then I would need a separate event-driven campaign for each segment. This design would quickly hit the AWS Campaign Limits.

It seems as though creating a campaign is overkill for notifying a single user about a: like on their photo, a new message, etc. 

The [send_user_messages](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/pinpoint.html#Pinpoint.Client.send_users_messages) method allows for the specification of a category for APNSMessages, but such a parameter is missing from GCMMessage.

Is there any way of specifying the notification type for FCM push notifications using send_messages/send_user_messages so that Android has fine-grained control over which messages to allow/deny? 

Or is there a more scalable way to multiple types of event-driven push notifications to individual users using campaigns?

Thanks for your help.

**Comment by AlexKashi** [comment]
I figured it out. In a lambda function, you can send a push notification to a client with the send_user_messages API, while including a custom data field encoding the Android notification channel.
 
```
responseSendMsg = client.send_users_messages(
            ApplicationId=appId,
            SendUsersMessageRequest ={
                'MessageConfiguration': {
                    'GCMMessage': {
                        'Action': 'DEEP_LINK',
                        'Body': message,
                        'Priority': 'High',
                        'SilentPush': False,
                        'TimeToLive': 36000,
                        'Title': appName,
                        "Url": url,
                        "Data":{
                            "android_channel_id":"MESSAGE_CHANNEL"
                        }
                    }
                },
                'Users': {userId:{}},
                'TraceId': 'test Trace Id' + str(round(time.time()*1000))
            })
```

In the Android App on can specify the notificationChannelId in the [NotificationDetails](https://aws-amplify.github.io/aws-sdk-android/docs/reference/com/amazonaws/mobileconnectors/pinpoint/targeting/notification/NotificationDetails.html) builder that gets passed to the [handleCampaignPush](https://aws-amplify.github.io/aws-sdk-android/docs/reference/com/amazonaws/mobileconnectors/pinpoint/targeting/notification/NotificationClient.html) method.
