### ISSUE TITLE
 Image URL for S3 Image. S3 configured for Authenticated Users  

### ISSUE THREAD

**Issue by virtualprodigy** [aws-amplify/aws-sdk-android#1063]
**State your question**
 Is there a way to get a URL for images stored on s3? 
I set up my S3 bucket using the `Amplify CLI` to allow authenticated users to view images stored in an `S3 bucket`. I am used amplify to setup an `Amazon Cognito User Pool` to provide access to `S3`. I tried manually constructing the URL in the format `"https://[application.bucket].s3.amazonaws.com/[key]"` but it seems that whenever I try to display the images the app cannot access the S3 image resource. Do I need to sign the get request URL that goes to S3? Or is there a way to ask S3 for the URL to the images?

**Which AWS Services are you utilizing?**
  S3
 Cognito
**Provide code snippets (if applicable)**

#### *Upload Image using Transfer Util (Kotlin)*
```
 val fileKey = "public/${AWSMobileClient.getInstance().username}_recipe_image${Date()}"
        val s3BucketName = getString(R.string.s3_recipe_photos_bucket)

        try {
            val transferObserver: TransferObserver = transferUtil.upload(s3BucketName, fileKey, file)
            val progressBar: ProgressBar = findViewById(R.id.uploadProgressbar)

            transferObserver.setTransferListener(object : TransferListener {
                override fun onStateChanged(id: Int, state: TransferState?) {
                    if (TransferState.COMPLETED == state) {
                        Log.d(TAG, "Upload finished, deleting temp file")
                        // info: recipe.photourl =  "https://[application.bucket].s3.amazonaws.com/[key]"
//                        recipe.photourl =  "https://$s3BucketName.s3.amazonaws.com/${ URLEncoder.encode(fileKey, "UTF-8") }"
                        recipe.photourl =   URLEncoder.encode(fileKey, "UTF-8")
                        Log.d(TAG, "S3 Image Url ${recipe.photourl}" )
                        deleteFile(file.name)

                        onResult(true)
                    }
                }
```

#### *Display image in list adapter*

```
mImageLoader.displayImage(recipe.getPhotourl(), mImageView, mDisplayImageOptions, mImageLoadingListener);
```
*Note: the photo url is in the format `"https://[application.bucket].s3.amazonaws.com/[key]"`*

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]
   Amplify Version: 0.1.34
    Android Studio: 3.3.1

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 Pixel 2 
 - Android Version: [e.g. Nougat 7.1.2] 
    9.0
 - Specific to simulators:
 Pixel 2 

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by kvasukib** [comment]
@virtualprodigy Thank you for reporting to us.

You can generate a pre-signed URL for the object you are accessing and use the pre-signed URL as the image URL.

You can look at one of our tests (https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-s3-test/src/androidTest/java/com/amazonaws/services/s3/model/GeneratePresignedUrlRequestIntegrationTest.java#L135) for reference on how to generate a pre-signed URL using our SDK and how to operate with the URL.

**Comment by virtualprodigy** [comment]
@kvasukib This was exactly what I needed. Thank you so much.
