### ISSUE TITLE
Error execute createMediaSource using sdk version 2.13.+

### ISSUE THREAD

**Issue by addodelgrossi** [aws-amplify/aws-sdk-android#1065]
**Describe the bug**
When you run the `kinesisVideoClient.createMediaSource` method, the error is returned:

```
E / KinesisVideoAndroidClient: 2019-07-06T15: 12Z T2202: EXCEPTION: ResourceNotFoundException: Service call failed .: The requested stream is not found or not active. (Service: AWSKinesisVideo; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: ba0da9da-faea-461f-919a-354ec7c48a42)
```

The problem occurs when using sdk **com.amazonaws: aws-android-sdk-kinesisvideo: 2.13.** +, If you use the **com.amazonaws: aws-android-sdk-kinesisvideo: 2.11.**  The problem does not occur.

**To Reproduce**
You can reproduce the problem using the AWS AmazonKinesisVideoDemoApp sample project.

```
            mKinesisVideoClient = KinesisVideoAndroidClientFactory.createKinesisVideoClient(
                    getActivity(),
                    KinesisVideoDemoApp.KINESIS_VIDEO_REGION,
                    KinesisVideoDemoApp.getCredentialsProvider());

            mCameraMediaSource = (AndroidCameraMediaSource) mKinesisVideoClient
                    .createMediaSource(mStreamName, mConfiguration);
```

**Which AWS service(s) are affected?**
Kinesis Video Stream

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.13.+
 - Device: Pixel XL, Simulator
 - Android Version: API 28
 - Specific to simulators: No

**Comment by kvasukib** [comment]
@zhiyua-git Can you have a look at this? Thanks.

**Comment by addodelgrossi** [comment]
@zhiyua-git some idea ? Unfortunately only working with version 11, when updating occurs the error above. Thanks.

**Comment by palpatim** [comment]
The fix for this has been released on https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.14.1

Please let us know if you have any questions.

**Comment by zhiyua-git** [comment]
Hi @palpatim , Can you also update the version to be 2.14+? Thanks.
https://github.com/awslabs/aws-sdk-android-samples/blob/master/AmazonKinesisVideoDemoApp/build.gradle#L50

**Comment by palpatim** [comment]
@zhiyua-git Thanks for the catch! The script we use to bump versions didn't catch that build.gradle's pattern.

**Comment by addodelgrossi** [comment]
resolved, thanks !
