### ISSUE TITLE
Cannot evaluate $Proxy6.toString()

### ISSUE THREAD

**Issue by Gingeskahn18** [aws-amplify/aws-sdk-android#1067]
**Describe the bug**
My problem is when I'm trying to create the client which request the apis this error is throwed:

Method threw 'com.amazonaws.mobileconnectors.apigateway.ApiClientException' exception. Cannot evaluate $Proxy6.toString().

Your code
apiClient = new ApiClientFactory()
        .credentialsProvider(AWSMobileClient.getInstance())
        .build(FacebookrestapiClient.class);

**Which AWS service(s) are affected?**
Amplify

**Expected behavior**
Try to connect RestApiclient

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.13
 - Device: Huawei P30
 - Android Version: Newest

**Comment by BaranEm** [comment]
I have the same issue here. Tried every possible solution I found in the web, but nothing worked..

**Comment by Gingeskahn18** [comment]
@BaranEm 

Whats thinks you tried?

**Comment by Gingeskahn18** [comment]
> I have the same issue here. Tried every possible solution I found in the web, but nothing worked..

Morning. What thinks you tried?

**Comment by BaranEm** [comment]
@Gingeskahn18 I searched the web & the aws forum for the issue, but nothing helped. In my case not `$Proxy6.toString()` was thrown, but `$Proxy0.toString()`. My code (communication with backend apis) works now and this error is still thrown, but only presented to me when debugging. 

Something must be wrong with the way you are creating the client I guess. I'm not sure whether it will help you, but I'll just post the way I create our aws client:


        developerProvider = new AWSDeveloperAuthenticationProvider(
                null,
                AWSConfigKeys.Identity.AWSIdentityPoolId,
                applicationContext,
                Regions.EU_CENTRAL_1);

        CognitoCachingCredentialsProvider credentialsProvider =
                new CognitoCachingCredentialsProvider(
                    applicationContext,
                    developerProvider,
                    Regions.EU_CENTRAL_1);

        final ApiClientFactory factory = new ApiClientFactory()
                .credentialsProvider(credentialsProvider);

        sdkClient = factory.build(TestClient.class);

**Comment by eeatonaws** [comment]
Hi @Gingeskahn18, using the code you provided and the latest version of the AWS SDK for Android, I only observe the error when debugging the app but not when running the app. If you are using Android Studio, you can fix the error when debugging the app by right clicking on the `proxy` variable in the debugger and selecting “View as” and then “Object”. This will display the variable in the debugger as an object rather than trying to use its `toString()` method, which in this case isn’t supported.
