### ISSUE TITLE
Add Tag to Video Stream is not implemented KinesisVideoClient

### ISSUE THREAD

**Issue by addodelgrossi** [aws-amplify/aws-sdk-android#1068]
**Which AWS Services is the feature request for?**
Add a tag to a Video Stream

**Is your feature request related to a problem? Please describe.**
Tags are important resources for video identification and classification.

**Describe the solution you'd like**
The video is created with two defaults tags that the SDK includes, but they are not possible to change through the SDK.

**Describe alternatives you've considered**
I tried using AmazonKinesisClient and the addTagsToStream method but it says it does not find *Stream*, I do not think you consider video stream

**Comment by palpatim** [comment]
@MushMal could you take a look at this?

**Comment by zhiyua-git** [comment]
Hi @addodelgrossi ,

You can call tagStream for your case. https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-kinesisvideo/src/main/java/com/amazonaws/services/kinesisvideo/AWSKinesisVideo.java#L323

You can also remove the tags if you don't want the default tags. https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-kinesisvideo/src/main/java/com/amazonaws/services/kinesisvideo/AWSKinesisVideo.java#L353

**Comment by addodelgrossi** [comment]
@zhiyua-git thanks Thanks for the answer.

I tried to use tagStream right after uploading the video, but I always have the error:

```
com.amazonaws.services.kinesisvideo.model.ResourceNotFoundException: The requested stream is not found or not active. (Service: AWSKinesisVideo; Status Code: 404; Error Code:
```

the stream information is correct, is there any sequence, I used AWSKinesisVideoClient

**Comment by zhiyua-git** [comment]
What region are you in? You will need to pass the region of your stream when you construct AmazonKinesisVideo, then use it to call tagStream(), if region is not set, it will default to us-west-2.

**Comment by addodelgrossi** [comment]
Yes, I am using the same region.

Only it was necessary to use two distinct objects.

The first KinesisVideoClient to create Video, and the second AWSKinesisVideoClient to tag, would this sequence?

The KinesisVideoClient object does not support the tagStream.

**Comment by zhiyua-git** [comment]
Are you calling AWSKinesisVideoClient.tagStream() right after you call MediaSource.start()? It will take some time (usually ~1 - 3 seconds) before the stream is created and changed to ACTIVE status. You can use AWSKinesisVideoClient.describeStream() to make sure the stream is in ACTIVE status before calling AWSKinesisVideoClient.tagStream().

**Comment by addodelgrossi** [comment]
Thanks @zhiyua-git ! I put a longer time after creation and it worked.
