### ISSUE TITLE
How to clear active user session in Android Cognito

### ISSUE THREAD

**Issue by alphaDroid89** [aws-amplify/aws-sdk-android#1073]
Hi Team, 

Here is my use case,

Consider my user name and password as "alpha01@xyz.com" and "Hello@1234" respectively.

- I logged in my application with the above valid credentials I got the expected result.
- Now I Kill/remove the application from the stack by using the recent button.
- As per my requirement, I need to force the user to log in at each time my application is launched.
- **Now the problem is, I tried to log in with password which is a similar pattern of above eg "Abcd@1234". it was successfully logged into.**

The expected result it should through an error, but Its allow to login.

if I try with "Abcd@123" or I log out the user properly its shows the expected results ie "Invalid user name/password".

Am referring  the code form[https://github.com/keivanK1/Cognito-Android-Studio/blob/login-github/app/src/main/java/de/cryptiot/indoorfarming/Cognito.java]

Kindly advice how can I resolve this. Thanks in advance

**Comment by palpatim** [comment]
@alphaDroid89 

If you require users to sign in on every app launch, the best way to ensure that behavior would be to sign out at every app launch prior to presenting any UI. Simply providing a sign in UI at app launch isn't sufficient to clear locally cached tokens.

> Now the problem is, I tried to log in with password which is a similar pattern of above eg "Abcd@1234". it was successfully logged into.

Are you saying that the login succeeds even when signing in with the wrong password? Signing in while the user is already signed in is not a supported use case (in fact, I'm a little surprised you didn't see some kind of "invalid state" error when doing that). The correct flow is to sign the user out first.

**Comment by alphaDroid89** [comment]
@palpatim Thanks for the quick response. Am also trying to log out the user before application launch.  In that case, some time logout call will go onFailure block.

**Comment by palpatim** [comment]
@alphaDroid89 Can you provide a small sample app that reproduces this behavior, for example by modifying the [existing User Pools sample](https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonCognitoYourUserPoolsDemo)? I'm puzzled by the behavior description, but without more details as to your call pattern, I'm reluctant to offer any theories.

**Comment by alphaDroid89** [comment]
@palpatim  Sure I will send a sample app with an above-mentioed use case, meantime can you please guild me how to clear "CognitoidentityserviceproviderCache". If I clear this cache my problem will be solved.

**Comment by palpatim** [comment]
I'm not sure what `CognitoidentityserviceproviderCache` is referring to, but you can clear the CognitoCachingCredentialsProvider's cache using the [`clear()` method](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-core/src/main/java/com/amazonaws/auth/CognitoCachingCredentialsProvider.java#L537) to clear the cached credentials **and** identity. You can call `clearCredentials()` to just clear the credentials, maintaining the cached identity.

**Comment by alphaDroid89** [comment]
@palpatim Thanks for your response, I already did the same. Your response makes me much confident on what it did. Thanks for your support.

**Comment by palpatim** [comment]
Sounds good. I'll close this for now. If you get time to reproduce the issue where you were apparently able to sign in using different credentials, please file a new issue with details (and hopefully a sample). :)
