### ISSUE TITLE
Add public method to determine if CognitoUser is signed in with valid session in Android SDK

### ISSUE THREAD

**Issue by spencerelliott** [aws-amplify/aws-sdk-android#1085]
**Which AWS Services is the feature request for?**
Android Cognito User Pools SDK

**Is your feature request related to a problem? Please describe.**
It is not feasible to use `AWSMobileClient` for my current project, so I am not able to use the workaround provided in #260. I need to be able to see if a user has signed in and has valid credentials for my logic.

**Describe the solution you'd like**
Either make `CognitoUser.getCachedSession` public, or provide a `CognitoUser.isSignedIn` method similar to the iOS Cognito Identity Provider SDK.

**Comment by gpanshu** [comment]
AWSMobileClient is now deprecated in V2 of Amplify. I would recommend that you move to Amplify V2 SDK for Android and use Amplify.Auth.SignIn and fetchAuthSession to determine the current session.
