### ISSUE TITLE
Where to put the CA certificate in PubSub project

### ISSUE THREAD

**Issue by Akefhabbal** [aws-amplify/aws-sdk-android#1100]
Hi,

I'm using AWSIoT in my android app and I made certificates and attached policy to them, then I saved those certificates on my server, and when the app requests them I send the 3 certificates to the app which are CA, Certificate, and PrivateKey and I save them in the Keystore. The problem is when I want to save the certificates I use this funciton
`AWSIotKeystoreHelper.saveCertificateAndPrivateKey(String certId, String certPem, String keyPem, String keystorePath, String keystoreName, String keystorePassword)`
This function doesn't require the CA certificate why?
However, I could connect to the MQTT but with unauthenticated policy but when I attach it with authenticated policy the app cannot connect to MQTT.

Regards.

**Comment by desokroshan** [comment]
@Akefhabbal Thanks for reaching out. CA certificate should not be required every time client connects to IoT. Certificate Id and private key alone should be enough. Can you please share the error/stacktrace for the case where your app fails to connect to AWS IoT?
