### ISSUE TITLE
putObject get error on android

### ISSUE THREAD

**Issue by 8600862** [aws-amplify/aws-sdk-android#1101]
I try implementation different version of sdk from 'com.amazonaws:aws-android-sdk-s3:2.8.+' to 'com.amazonaws:aws-android-sdk-s3:2.14.+'

when I putObject to our s3 on android, get error:
Copy Source must mention the source bucket and key: sourcebucket/sourcekey (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: f87f38d8-b346-11e9-8706-b496913358d8)
400
InvalidArgument
Client
f87f38d8-b346-11e9-8706-b496913358d8

createBucket listObjects getObject copyObject on android all fine
all this method (include putObject ) on windows (java) is fine

**Comment by 8600862** [comment]
I find the reason is we not support trunk upload signature. then I disable chunk like:
S3ClientOptions.Builder builder = S3ClientOptions.builder();
        builder.disableChunkedEncoding();
        builder.setPathStyleAccess(true);
        clientOptions = builder.build();
boolean disabled = clientOptions.isChunkedEncodingDisabled();
and disabled shows true, but the error is the same

**Comment by raphkim** [comment]
Hello @8600862,

I'm sorry that you are having trouble with this issue.

Would you be able to provide the code snippets where you configure your S3 client and call putObject?
