### ISSUE TITLE
Upload Fails with error Log tag "AwsChunkedEncodingInputStream" exceeds limit of 23 characters

### ISSUE THREAD

**Issue by lionheart1060** [aws-amplify/aws-sdk-android#1103]
**State your question**
Getting error while uploading any file from Android 6.0.1

**Which AWS Services are you utilizing?**  - S3

**Provide code snippets (if applicable)**
08-01 09:39:43.977 8286-9177/? D/UploadTask: Failed to upload: 2 due to Log tag "AwsChunkedEncodingInputStream" exceeds limit of 23 characters
<img width="890" alt="螢幕快照 2019-08-01 上午10 28 02" src="https://user-images.githubusercontent.com/53545072/62258900-59931580-b447-11e9-8b48-4828967199b0.png">

**Environment(please complete the following information):**
 - SDK Version: 2.13.1

**Device Information (please complete the following information):**
 - Device : LENOVO Lenovo PB2-690M
 - Android Version: [e.g. Marshmallow 6.0.1]
 - Specific to simulators: No

**Comment by desokroshan** [comment]
@lionheart1060 Thanks for reporting the problem. Can you please work off of the [PR](https://github.com/aws-amplify/aws-sdk-android/pull/1105) and let us know if it fixes your issue?

**Comment by lionheart1060** [comment]
@desokroshan Thanks for reply
I'm kinda new to android studio, i should be using sdk version : 2.14.2 on branch roshan/Issue#1103 
? But i can't find the newest version though...<img width="937" alt="螢幕快照 2019-08-02 下午2 37 24" src="https://user-images.githubusercontent.com/53545072/62347174-caaff700-b533-11e9-8873-5595ee47a19b.png">

**Comment by desokroshan** [comment]
Version 2.14.2 isn't published yet so you will not be able to find it in Android Studio. You can do the following to use the PR code in you app : 

1. In a freshly cloned repo, checkout the branch "roshan/Issue#1103"
2. Import the "aws-android-sdk-s3" module by File -> New -> Import Module..., provide path to `aws-android-sdk-s3` module from the branch above and follow the dialog instructions to add the module. You should now be able to see module called `aws-android-sdk-s3` in the project navigator on the left-hand side.
3.  Add dependency on the newly added module as `api project(':aws-android-sdk-s3')` in the app's build.gradle

You should now be able to use the source code in PR in your app. Let me know if you have issues.

**Comment by lionheart1060** [comment]
Thanks a lot, it worked!

**Comment by desokroshan** [comment]
> Thanks a lot, it worked!

Thanks for the confirmation. I will work on getting the PR out in next release.

**Comment by love-311** [comment]
> Thanks for the confirmation. I will work on getting the PR out in next release.

**Comment by lionheart1060** [comment]
@desokroshan My apologies. Seems like version 2.15.0 will include the modifications of long log tags, any information for release date? Issue #1105 was merged around 5 days ago though.
Thanks.

**Comment by lionheart1060** [comment]
@desokroshan Hi. I'm glad that version 2.15.0 is now released, but now i'm still encountering the problem for every log tag that is over 23 characters.
<img width="1363" alt="螢幕快照 2019-08-20 下午6 25 44" src="https://user-images.githubusercontent.com/53545072/63335259-ff1b1400-c377-11e9-9bb8-1da5c67c012a.png">
Please revisit the issue again.

**Comment by desokroshan** [comment]
@lionheart1060 The fix has been released in the latest version 2.15.0. Please let us know if you face any issues. Thanks!

**Comment by lionheart1060** [comment]
@desokroshan Sorry, I'm having the problem actually using 2.15.0 though... (when I'm constructing AmazonS3Client in this case above)

**Comment by lionheart1060** [comment]
@datkinnguyen My apologies, seems like i'm using the outdated org.apache.commons.logging.LogFactory which doesn't implement getLog (i suppose?). It works fine now after modifying my source using the latest version.

**Comment by desokroshan** [comment]
Thanks for the confirmation. Closing.
