### ISSUE TITLE
Video upload not working on mobile network

### ISSUE THREAD

**Issue by dkch90** [aws-amplify/aws-sdk-android#1113]
**Describe the bug**
I'm uploading videos on s3. Its working fine but whenever cancel the video and upload it again, on mobile network its not working, actually not getting progress update for this. The same thing  is working well on wifi and in case of small size video. I'm not able to fix the issue. please suggest the proper solutions. Thanks 

**Code:**```
**Upload and resume Code:**
```
PowerManager powerManager = (PowerManager) mContext.getSystemService(Context.POWER_SERVICE);
            PowerManager.WakeLock wakeLock = null;
            if (powerManager != null) {
                wakeLock = powerManager.newWakeLock(PowerManager.SCREEN_DIM_WAKE_LOCK, TAG);
                wakeLock.acquire();
            }

            TransferObserver uploadObserver = getTransferFileID(mtransferUtility, videoUploadRequest);
            if(uploadObserver != null){
                uploadObserver = mtransferUtility.resume(uploadObserver.getId());
                float percentDonef = ((float) uploadObserver.getBytesTransferred() / (float) uploadObserver.getBytesTotal()) * 100;
                int percentDone = (int) percentDonef;
                mView.onProgressChange(percentDone + "%");
                mView.onVideoUploadingStatus("Resume init");
                return;
            } else {
                uploadObserver = mtransferUtility.upload(mbucketName, videoUploadRequest.getS3FilePath(), new File(videoUploadRequest.getFilePathtoUploadOnS3()), CannedAccessControlList.PublicRead);
                mView.onVideoUploadingStatus("Upload init");
            }

            PowerManager.WakeLock finalWakeLock = wakeLock;
            uploadObserver.setTransferListener(new TransferListener() {
                @Override
                public void onStateChanged(int id, TransferState state) {
                    new Handler().postDelayed(() -> {
                        mView.onVideoUploadingStatus(state.name());
                        if (TransferState.COMPLETED == state) {
                            videoUploadRequest.setStatus(VideoUploadRequestState.UPLOADED);
                            mView.onVideoPreviewResponse(videoUploadRequest.getS3AbsoluteFilePath(), videoUploadRequest.getGoverneyeFileID(), videoUploadRequest.getS3FileName());
                            if (finalWakeLock != null) finalWakeLock.release();
                        } else if (TransferState.PAUSED == state) {
                            mView.onResponseFailure(new Exception("Error while upload video"), false);
                        }
                    },10);
                }

                @Override
                public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                    new Handler().postDelayed(() -> {
                        float percentDonef = ((float) bytesCurrent / (float) bytesTotal) * 100;
                        int percentDone = (int) percentDonef;
                        mView.onProgressChange(percentDone + "%");
                    },10);
                }

                @Override
                public void onError(int id, Exception ex) {
                    mView.onResponseFailure(new Exception("Error while upload video"), false);

                }
            });
```
**Cancel Code**
```
TransferObserver uploadObserver = getTransferFileID(mtransferUtility, videoUploadRequest);
            if(uploadObserver != null) {
                mtransferUtility.deleteTransferRecord(uploadObserver.getId());
                uploadObserver.refresh();
                uploadObserver.cleanTransferListener();

            }
```
**Expected Behavior:**
Uploading should work even when we cancel video and upload it again. 

AWS SDK Version:****
2.14.0

**Comment by palpatim** [comment]
@dkch90 

Could you please provide more detail to help us troubleshoot this issue? At a bare minimum, we'd like the information we request in the "Bug Report" template when you file a new issue (see below). Especially important are clear steps to reproduce, code and/or configuration snippets, your SDK version, and any relevant error or log messages you're seeing in the device logs.

---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
A code sample or steps:
```
Your code
```

**Which AWS service(s) are affected?**

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [e.g. 2.6.25]
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators: [e.g. Yes/No]

**Additional context**
Add any other context about the problem here.

**Comment by dkch90** [comment]
@palpatim I have updated my question have posted code as well. please look hope now this is clear to you.

**Comment by raphkim** [comment]
Hi @dkch90 

Thank you for reporting this issue. May I ask why you chose not to use the built in `TransferUtility.cancel(transferId)` API to cancel your transfers? Would you be able to try it with that instead and let us know the result? Thanks!
