### ISSUE TITLE
Sign in user with any unique id in Cognito

### ISSUE THREAD

**Issue by JeetSA** [aws-amplify/aws-sdk-android#1117]
In our application, we have a feature that we can scan the RFID card. The card will be holding the unique ref id of the user created on AWS Cognito.

We need to implement a functionality like when user scans the RFID card, user will directly logged into the application.

**So is there any method for sign in in cognito with any unique id of Cognito and without password? Or is there any other way to achieve this functionality?**

**We are using following AWS Services.**

- com.amazonaws:aws-android-sdk-core:2.13.2
- com.amazonaws:aws-android-sdk-apigateway-core:2.13.2
- com.amazonaws:aws-android-sdk-mobile-client:2.13.+@aar
- com.amazonaws:aws-android-sdk-auth-userpools:2.13.+@aar
- com.amazonaws:aws-android-sdk-appsync:2.7.9

**Environment:**
 - SDK Version: 2.13.2

**Comment by desokroshan** [comment]
@JeetSA Thanks for reaching out. Cognito does not support sign in without password out-of-the-box but this feature can be implemented with Cognito custom authentication feature. Please refer to the following blog for details on how to implement it : 
https://aws.amazon.com/blogs/mobile/implementing-passwordless-email-authentication-with-amazon-cognito/

Android SDK however does not support custom auth feature currently. We are tracking this feature request in following issues : 
https://github.com/aws-amplify/aws-sdk-android/issues/1123
https://github.com/aws-amplify/aws-sdk-android/issues/634

Please subscribe to these to be notified of updates on the request.
