### ISSUE TITLE
How to manually refresh CognitoUserSession in Android?

### ISSUE THREAD

**Issue by Guneetgstar** [aws-amplify/aws-sdk-android#1119]
In our application logic, the user claims gets changed according to the user interactions with the app and so the ID Token. If the old ID Token is sent to the cloud the request might get rejected. I need a way so that I can forcefully update the ID Token which is a valid case for me as by default Cognito uses cached tokens and only refreshes it after 3 hrs and I cant depend on that (at least if I surely know that the ID Token has been changed). ### Is there a way to do that?

****
aws-android-sdk-cognitoidentityprovider
 - SDK Version: [2.14.2]

**Comment by Guneetgstar** [comment]
Any updates @desokroshan ?

**Comment by sachinavm12** [comment]
@awsmobilesdk Any update on this?

**Comment by desokroshan** [comment]
@Guneetgstar Thanks for reaching out. For your specific use case you do not need to manually refresh the token. Even if user attribute changes during user's interaction with the app the access and Id token will still be valid as long as they have not expired. The tokens are validated by their signature and typically the claims in the token are not checked during token validation and thus changes in claims will not affect the validity of the token. So for your case you do not have to worry about manually refreshing the token. Refer to the following documentation to know more about the token validation process : https://aws.amazon.com/premiumsupport/knowledge-center/decode-verify-cognito-json-token/. When the tokens expire(typically in about an hour), SDK automatically refreshes access and Id Token for you as long as you have valid Refresh Token. The tokens will be updated with new user claims once it is refreshed by the SDK.

**Comment by desokroshan** [comment]
@sachinavm12 SDK currently does not support manual refresh of tokens. We are tracking this request in https://github.com/aws-amplify/aws-sdk-android/issues/696. We will post all updates regarding this feature request there. Thanks for your patience!
