### ISSUE TITLE
push open rates has not updated in aws pinpoint console

### ISSUE THREAD

**Issue by dakeshi** [aws-amplify/aws-sdk-android#1122]
**Describe the bug**
It has not updated push open rates in the console even though I got push message successfully and opened its message on the device. 

**Which AWS service(s) are affected?**
pinpoint

**Expected behavior**
increasing push open rates if recipients opened it

**Screenshots**
![Amazon_Pinpoint_Console](https://user-images.githubusercontent.com/8563047/62755930-d6aa3480-bab0-11e9-9438-4b479664e50e.png)

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: com.amazonaws:aws-android-sdk-pinpoint:2.14.2, com.amazonaws:aws-android-sdk-mobile-client:2.14.2
 - Device: NEXUS 5X
 - Android Version: 8.1.0

**Additional context**
How to solve this issue. (in iOS integration with pinpoint, there is no such issues)

**Comment by jpignata** [comment]
I couldn't reproduce this issue. Please let me know if you're still seeing this by reopening this and we'll investigate.
