### ISSUE TITLE
Facebook access token does not authenticate on cognito pool [Android]

### ISSUE THREAD

**Issue by chirag-ss** [aws-amplify/aws-sdk-android#1131]
I am getting an error: NotAuthorizedException: Token is not from a supported provider of this identity pool.

I am using dependancy: com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.9.1

Below is my code once I get access token from Facebook,
credentialsProvider = new CognitoCachingCredentialsProvider(
                getApplicationContext(), // Context
                BuildConfig.AWS_IDENTITY_POOL_ID, // Identity Pool ID
                AppHelper.getCognitoRegion()// Region
        );
Map<String, String> logins = new HashMap<String, String>();
logins.put("graph.facebook.com", AccessToken.getCurrentAccessToken().getToken());
credentialsProvider.setLogins(logins);
credentialsProvider.refresh();

**Environment:**
 - SDK Version: [e.g. 2.9.1]

**Device Information :**
 - Device: [e.g. OnePlus 5T]
 - Android Version: [e.g. Pie 9]

**Comment by desokroshan** [comment]
@chirag-ss Thanks for reaching out. Can you please share more details around this. 
1. Have you added facebook as an authentication provider for the identity pool in the AWS Console?
2. What SDK version are you using?

Also, we recommend using AWSMobileClient for most of the common authentication use cases. Have a look at the following document for details on how to use facebook sign-in in your app : 

https://aws-amplify.github.io/docs/android/authentication#federated-identities-social-sign-in

**Comment by chirag-ss** [comment]
Yes @desokroshan, I have added Facebook as an authentication provider for the identity pool. Also, I have gone through all the steps in the below link,
https://docs.aws.amazon.com/cognito/latest/developerguide/facebook.html

I am using cognitoidentityprovider SDK, I have already mentioned the dependency which I am using. (com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.9.1)
https://mvnrepository.com/artifact/com.amazonaws/aws-android-sdk-cognitoidentityprovider/2.9.1

I know that the recommended way to implement social sign-in is AWSMobileClient but I can't implement it into my project as of now. I'll migrate in the near future.

Let me know if you need any other details to resolve this query.
