### ISSUE TITLE
How to detect if user is blocked when token is still valid without calling cognitoUser.getDetails()?

### ISSUE THREAD

**Issue by alex-Lotus** [aws-amplify/aws-sdk-android#1132]
We want to check if user became blocked when app moved to foreground and log him out. Would be great if SDK will support this natively like cognitoUser.isBlocked() or isActive().

**Comment by desokroshan** [comment]
@alex-Lotus  Can you provide more details around your use-case. Are you using [AWSMobileClient](https://github.com/aws-amplify/aws-sdk-android/tree/master/aws-android-sdk-mobile-client) or are you using our [Cognito User Pools SDK](https://github.com/aws-amplify/aws-sdk-android/tree/master/aws-android-sdk-cognitoidentityprovider)? Do you mean blocked when refesh token is invalid and user needs to sign in?

**Comment by alex-Lotus** [comment]
We using Cognito User Pools SDK, blocking means user access token, refresh token and idToken are invalidated

**Comment by desokroshan** [comment]
Thanks for the clarification. We recommend using AWSMobileClient for your Auth use case. Is there a reason you are not able to use AWSMobileClient? 
If all the tokens including Refresh Token, have expired and your app attempts to call an AWS Service, AWSMobileClient will dispatch a state notification that a re-login is required. At this point you can choose to present app user with a login screen and call AWSMobileClient.getInstance().signIn() or perform a custom business logic. You can register to listen for this state change anywhere in your app as follows : 

```java
AWSMobileClient.getInstance().addUserStateListener(new UserStateListener() {
    @Override
    public void onUserStateChanged(UserStateDetails userStateDetails) {
        switch (userStateDetails.getUserState()){
            case SIGNED_OUT:
                // user clicked signout button and signedout
                Log.i("userState", "user signed out");
                break;
            case SIGNED_OUT_USER_POOLS_TOKENS_INVALID:
                Log.i("userState", "need to login again.");
                AWSMobileClient.getInstance().signIn(username, password, null, new Callback<SignInResult>() {
                    //... 
                });
                //Alternatively call .showSignIn()
                break;
            default:
                Log.i("userState", "unsupported");
        }
    }
});
```

If your use case does not require a re-login, you can terminate the call and unblock the user with a call to releaseSignInWait().
Does that help with your use case. Do let me know if you have a scenario that prevents you from using AWSMobileClient and mandates use of Cognito User Pool SDK.
