### ISSUE TITLE
How can I use the sdk source code in my project

### ISSUE THREAD

**Issue by Ranchee** [aws-amplify/aws-sdk-android#1148]
**State your question**
I'm using AmazonKinesisVideo,but I want to made some change in the sdk，How can I use the sdk source code(with my change) in my project
**Which AWS Services are you utilizing?**
AmazonKinesisVideo
**Environment(please complete the following information):**
 - SDK Version: 2.14.+

**Comment by desokroshan** [comment]
@jet-le Thanks for reaching out. Entire Android SDK is structured as separate module for each of the AWS service. Consequently you can import the required module in your project just like any other android library using instructions here: https://developer.android.com/studio/projects/add-app-module#ImportAModule
Once you have added it to your project you can add dependency on it in your app code by adding following in your app build script's dependency section : 
`implementation project(':aws-android-sdk-kinesisvideo')`

**Comment by Ranchee** [comment]
I've resolved the issue,thank you very much.
