### ISSUE TITLE
Android cognito passwordless sign-in

### ISSUE THREAD

**Issue by MichalCR** [aws-amplify/aws-sdk-android#1160]
**State your question**
Hi,

I'm trying to use cognito passwordless sign-in feature. I follow this example: https://aws.amazon.com/blogs/mobile/implementing-passwordless-email-authentication-with-amazon-cognito/ and deployed lambda functions. I'm able to register the user but when I'm trying to login him using this method: 

`AWSMobileClient.getInstance().signIn("<email>", "<password>", null, new Callback<SignInResult>() {});`

 I'm getting following error: 

`com.amazonaws.services.cognitoidentityprovider.model.InvalidParameterException: Only custom auth (lambda driven) is enabled for this client. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: ...)`

Can you please tell how to sign-in the user to Cognito via Android Amplify SDK when I'm using lambda functions.  

**Which AWS Services are you utilizing?**
Amazon Cognito

**Provide code snippets (if applicable)**
`AWSMobileClient.getInstance().signIn("<email>", "<password>", null, new Callback<SignInResult>() {});`

**Environment(please complete the following information):**
- Amplify SDK Version: 2.15.+
- Android SDK Version: 28

**Device Information (please complete the following information):**
 - Device: Pixel XL2, Simulator
 - Android Version: 9, API 28
 - Specific to simulators: NO

**Comment by desokroshan** [comment]
@MichalCR Were you able to resolve the issue?

**Comment by SubirZ** [comment]
Hi @desokroshan,
I am trying to implement the passwordless signIn, but in the mobile SDK sign-in method has a mandatory password field, on providing null/""(blank) password it throws an error.

for blank password:""
Sign-in errorIncorrect username or password. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 47494e68-687c-4eb1-aae3-8c2a3a886355)

for null password:null
Sign-in errorFailed to find password in authentication details to response to PASSWORD_VERIFIER challenge.

Is there any way to fix this.

**Comment by LinearLogic** [comment]
For anyone running into this, @desokroshan's [snippet](https://github.com/aws-amplify/aws-sdk-android/issues/1160#issuecomment-525407716) works like a charm, just not with the authflow lambdas deployed by the [Serverless App](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:520945424137:applications~amazon-cognito-passwordless-email-auth) referenced in [the blog post](https://aws.amazon.com/blogs/mobile/implementing-passwordless-email-authentication-with-amazon-cognito/) @MichalCR mentioned. I was able to tweak the DefineAuthChallenge and CreateAuthChallenge lambdas to achieve OTP auth on Android without breaking existing OTP auth on iOS/ReactNative.

[Here's a gist with the lambdas I'm using.](https://gist.github.com/LinearLogic/c36ab942f830fcda63a43357d9f73718) I've commented the substantive changes to the Serverless App lambdas (just one line in each) to document the ways in which the Android SDK's behavior diverges from the Javascript SDK, to the best of my limited knowledge. Hopefully this helps others keep what remains of their hair and get back to hacking.

**Comment by desokroshan** [comment]
@SubirZ We have released support for passwordless sign in MobileClient in 2.16.0. You can find documentation [here](https://aws-amplify.github.io/docs/android/authentication#customizing-authentication-flow). You can pass a dummy password and should not run into error. Please give it a try and let me know if you see issues?

**Comment by desokroshan** [comment]
@LinearLogic Yeah the lambdas in blog post does not work. You can use Amplify CLI to get lambda templates that you can then use to tweak to meet your use case. 
https://aws-amplify.github.io/docs/cli-toolchain/cognito-triggers

**Comment by tomsterritt** [comment]
@desokroshan I'm also trying to use custom auth flow, using 2.16.0 and similar lambda as the gist above and passing a dummy password, however I get the error:
`Auth signIn error USER_SRP_AUTH is not enabled for the client. (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID:...`

**Comment by ximenaperez** [comment]
I'm getting the same error @desokroshan , did you find out what the problem was?

**Comment by dhaval85** [comment]
I am getting the same error. But only in Android emulator.

**Comment by BilliDevs** [comment]
there is no proper documentation on this from last 3 days just exploring and exploring can anyone ??

**Comment by banji180** [comment]
@BilliDevs we don’t currently support passwordless out of the box.

**Comment by tylerjroach** [comment]
@BilliDevs It looks like some of the links in this issue are out of date. Have you taken a look at https://docs.amplify.aws/lib/auth/signin_with_custom_flow/q/platform/android/?
