### ISSUE TITLE
AWS Amplify MFA mobile phone Verification and Authentication

### ISSUE THREAD

**Issue by chikason** [aws-amplify/aws-sdk-android#1161]
**Am not receiving Authentication and Verification code on my mobile phone after registration. It was working before but suddenly stopped working.**

**AWS Amplify for Android**
```java
        AWSMobileClient.getInstance().signUp(username, password, attributes, attributes,
                new Callback<SignUpResult>() {
                    @Override
                    public void onResult(SignUpResult result) {
                        runOnUiThread(() -> confirmUser(result));
                    }

                    @Override
                    public void onError(Exception e) {
                        Log.e("error","this is the problem detail: "+ e.getMessage());
                        if(e.getMessage().contains("User already exists")){
                            makeToast("Username already exist");
                        }
                    }
                });
```

**Environment(please complete the following information):**
 - SDK Version: amplify cli 1.12.0

**Comment by chikason** [comment]
![Screenshot_20190828-202043_1567020156974](https://user-images.githubusercontent.com/52418760/63886938-81888100-c9d3-11e9-9157-7a62cae87dd8.png)
![Screenshot_20190828-202117_1567020125498](https://user-images.githubusercontent.com/52418760/63886958-936a2400-c9d3-11e9-9d4e-df03f7c8c4b5.png)


Does this screenshot have what you asked me of or is the configuration generated by the CLI that's inside my amplify folder

**Comment by desokroshan** [comment]
@chikason Thanks for sharing the details. You configuration looks fine to me. I was not able to reproduce the issue using this configuration. Another potential reason for not receiving the confirmation code could be that you have hit your SNS quota which is used to send the confirmation messages. Can you check if that is the case?

**Comment by richardmcclellan** [comment]
Closing due to no response.  Please open a new issue if this is still a problem.
