### ISSUE TITLE
Is this the correct usage? MobileClient storing CognitoId after successful Sign up

### ISSUE THREAD

**Issue by bobguy1234** [aws-amplify/aws-sdk-android#1163]
I'm using the AWSMobileClient to signup a new user. After they successfully sign up I would like to store their unique uuid aka "sub" id in my SQL database. 

    AWSMobileClient.getInstance().signUp(username, password, attributes, null, new 
    Callback<SignUpResult>() {
    @Override
    public void onResult(final SignUpResult signUpResult) {
        runOnUiThread(new Runnable() {
        @Override
        public void run() {
            //Successful signing up a new user
            //What would I do here?
        }
    });
    }

    @Override
    public void onError(Exception e) {
        Log.e(TAG, "Sign-up error", e);
    }

 The user successfully signs up, would I make a post request to my database in the callback method? What happens if the user's network fails during midcall or something else happens and the post request doesn't successfully record the user's uuid. What would be the correct way of doing this?

**Comment by desokroshan** [comment]
@bobguy1234  PR https://github.com/aws-amplify/aws-sdk-android/pull/1107 has been released in the version 2.15.2 of the SDK. Please feel free to try it out and let me know if you have any feedback.

**Comment by kvasukib** [comment]
Closing this issue as the code changes to expose `userSub` through `SignUpResult` is released.
