### ISSUE TITLE
Uploading files in Android Q not possible without creating temporary file

### ISSUE THREAD

**Issue by zach-snell** [aws-amplify/aws-sdk-android#1165]
**Which AWS Services is the feature request for?**
AmazonSDK S3

**Is your feature request related to a problem? Please describe.**
Android changes to scoped storage makes it impossible to get direct filepaths to create File objects needed for uploading.

https://developer.android.com/preview/privacy/scoped-storage

**Describe the solution you'd like**
A method of uploading that works with the allowed access.

I think this will likely have to work with a type returned by ContentResolver. Likely utilizing a FileDescriptor or the yielded InputStream.

**Describe alternatives you've considered**
One potential work around is to create a "tmp" file of the file you want to upload in order to get a File object.
However, this means we have to copy any file that needs to be uploaded into our application storage/cache.

**Additional context**
This change is set to apply retroactively to older targets of android per the notes of Android Q.

**Comment by TrekSoft** [comment]
Hey Zach, I haven't tried this out yet but it seems like within the new scoped storage you can still get URIs to external files. From that, you could call uri.getPath() to create the File object. Does this answer your question?

**Comment by zach-snell** [comment]
@TrekSoft 
I would not call myself an Expert so feel free to correct me.

However, as I understand it, you can not use this from a MediaStore Content URI which is the only real way to access files in Android 10.
The recommended way I found would be to get the data object from MediaStore. However, they are removing that in Android 10 as well.

Thanks for looking at this!

Zach

**Comment by TrekSoft** [comment]
Hey, yeah so I tried this example they give in the documentation there of how to use the storage access framework and then called uri.getPath() in addition to the getString method they show in the example and it worked great for returning the path of the file: https://developer.android.com/guide/topics/providers/document-provider#results

**Comment by zach-snell** [comment]
@TrekSoft  I agree with you that StorageAccessFramework will more than likely work.

I guess I was wanting to find a way to follow the recommended method for accessing media type files for Android. 

If storage access framework is the way to go then I will just have to deal with that but know that it causes a degraded user experience.

Basically I want to offer them to upload any media file on their device. In order to do this with SAF I will just have to tell a user to grant the root that contains all of their media. For non-tech savy people this will be an odd experience.

**Comment by TrekSoft** [comment]
Ah gotcha - yeah I don't think there's a way around getting user permissions for external storage.

**Comment by zach-snell** [comment]
@TrekSoft 
We can keep this closed for now but just to be clear, MediaStore/ContentResolver already requires external file permission.

SAF with Android 10 will just require a user to use the "Picker" to select your access.

I am fine with granting permissions. It just sucks when you require user input and they can fail to grant the correct location etc. Very error prone.

Thanks anyways!

Perhaps consider reviewing a method with InputStream for an enhancement if you want to create some improved user experience.

I have not dug into this yet and uploading may not be a major feature for me so I might ignore it for now.

**Comment by TrekSoft** [comment]
Yeah feel free to reopen this issue if you end up having a specific use case code sample you can post here where our existing functionality limits the usability of your app.
