### ISSUE TITLE
How can I streaming video & audio at the same time using Kinesis Video on Android APP ?

### ISSUE THREAD

**Issue by Ranchee** [aws-amplify/aws-sdk-android#1166]
**State your question**
I want to stream video & audio at the same time  on Android App，the offical demo(aws-sdk-android-samples) is only support video，Can you provder a demo ？

**Which AWS Services are you utilizing?**
Kinesis Video

**Environment(please complete the following information):**
Kinesis Video 2.15+，Android plaform.

**Comment by Ranchee** [comment]
@garishsood  @desokroshan  I‘ve read the amazon-kinesis-video-streams-producer-sdk-java. My Question is： How can I produce an "Audio frame" just like 1549577161733573000-audio-false-frame in the resources/data/audio-video-frames/ folder?

**Comment by kalpeshwadekar** [comment]
@Ranchee, have you achieved this? I am trying for a couple of hours now and not getting any lead to stream audio-video both using Kinesis video stream SDK for Android.

**Comment by AlexKnyazyuk** [comment]
Any updates @Ranchee? I also need to stream both audio and video, why you don't provide realisation for it?

**Comment by eeatonaws** [comment]
Please see the following GitHub repo for an example of streaming audio and video using KVS: https://github.com/awslabs/aws-sdk-android-samples/tree/main/AmazonKinesisVideoDemoApp

**Comment by Ranchee** [comment]
Here is the solution for stream both audio and video,you can have a try:
https://github.com/zhiyua-git/aws-sdk-android/tree/audiovideo
