### ISSUE TITLE
Invalidate or refresh access token manually

### ISSUE THREAD

**Issue by mregnauld** [aws-amplify/aws-sdk-android#1171]
**Which AWS Services is the feature request for?**

Cognito

**Is your feature request related to a problem? Please describe.**

In my project, I have users in different Cognito user pool groups with different IAM roles. For example, one group contains the users that use my Android app for free, and another group contains the users who pay for advanced features. Those features are APIs in API Gateway, that can only be call by users who pay for it. When a user just paid to get access to those advanced features, he goes from the "free" group to the "paid" group.

In that situation, I need that change to take effect as soon as the user paid, and not being obligated to wait for the access token to expire before the user can call the APIs. This is a big limitation and the only workaround is to disconnect and reconnect the user, which is definitely not a good user experience.

**Describe the solution you'd like**

Since the `AWSMobileClient.signOut()` function invalidates all tokens, I need something equivalent that only invalidates the access token, so my user can get the right IAM roles as soon as he goes from one group to another, without having to disconnect then reconnect.

**Comment by cmbaykal** [comment]
Any updates yet ?

**Comment by angitha-das** [comment]
Any updates on this?

**Comment by div5yesh** [comment]
Please use this workaround: https://github.com/aws-amplify/aws-sdk-android/issues/696#issuecomment-1101894554 and let us know if it fits your use case.

**Comment by tjleing** [comment]
If the workaround does not work, please comment on this issue or open a new one.
