### ISSUE TITLE
Crashes while using TransferService in Oreo & Above

### ISSUE THREAD

**Issue by deepakrokz** [aws-amplify/aws-sdk-android#1173]
**Describe the bug**
Getting this crash log:
```
Fatal Exception: android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3a7b7c6 u0 com.canlah/com.amazonaws.mobileconnectors.s3.transferutility.TransferService}
       at android.app.ActivityThread$H.handleMessage + 1752(ActivityThread.java:1752)
       at android.os.Handler.dispatchMessage + 107(Handler.java:107)
       at android.os.Looper.loop + 198(Looper.java:198)
       at android.app.ActivityThread.main + 6729(ActivityThread.java:6729)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run + 493(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main + 858(ZygoteInit.java:858)
```

**To Reproduce**
A code sample or steps:
```
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
Intent tsIntent = new Intent(mInstance.getApplicationContext(), TransferService.class);
                    NotificationChannel channel = new NotificationChannel(CHANNEL_MESSAGE,
                            "Channel human readable title",
                            NotificationManager.IMPORTANCE_NONE);

                    notificationManager =
                            (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
                    notificationManager.createNotificationChannel(channel);

                    Notification notification = new NotificationCompat.Builder(this, CHANNEL_MESSAGE)
                            .setContentTitle("")
                            .setContentText("").build();

                    tsIntent.putExtra(TransferService.INTENT_KEY_NOTIFICATION, notification);
                    tsIntent.putExtra(TransferService.INTENT_KEY_NOTIFICATION_ID, NOTIFICATION_ID_3);
                    tsIntent.putExtra(TransferService.INTENT_KEY_REMOVE_NOTIFICATION, true);
                    mInstance.getApplicationContext().startForegroundService(tsIntent);
} else {
                if (!Utils.isMyServiceRunning(TransferService.class, mInstance)) {
                    Intent tsIntent = new Intent(mInstance.getApplicationContext(), TransferService.class);
                    mInstance.getApplicationContext().startService(tsIntent);
                }
            }
```

**Which AWS service(s) are affected?**
S3 upload
**Expected behavior**
As per discussion in this thread [https://github.com/aws-amplify/aws-sdk-android/issues/1110#issuecomment-525806163](url), I implemented above code in my application class and calling the same from different for some devices it's working fine but for some users are facing so much crashes not able to use application. Losing hope in our, please help us in resolving such problems.

**Screenshots**

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [2.14.2]
 - Device: [Nokia 5, HMD Global, Moto G5, G5S Plus and others]
 - Android Version: [Oreo & Above]
 - Specific to simulators: [No]

**Additional context**
Please help us in resolving this quickly.

Thanks

**Comment by deepakrokz** [comment]
Can somebody help me with this problem? I am expecting a solution to this.

**Comment by TrekSoft** [comment]
Hi @deepakrokz,

Just wanted to give you a quick update that KV will be back on Monday so I'll let him know you're looking for an update on this.

**Comment by raphkim** [comment]
Hi @deepakrokz 

I see that you are starting foreground service for Oreo & above android versions, which is the correct approach. Would you be able to check that you have provided the app with foreground service permission by including `<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />` in your `AndroidManifest.xml` file?

**Comment by deepakrokz** [comment]
Yes, I have already. I have mentioned this thing in earlier issues threads

**Comment by deepakrokz** [comment]
Hi @raphkim,

I am facing one more issue in some of devices like Karbon and Nokia devices:

> Fatal Exception: java.lang.RuntimeException: Unable to create service com.canlah.services.KaraokeUploadService: java.lang.IllegalStateException: Error in initializing the CognitoCachingCredentialsProvider. 
       at android.app.ActivityThread.handleCreateService + 3081(ActivityThread.java:3081)
       at android.app.ActivityThread.-wrap4(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage + 1575(ActivityThread.java:1575)
       at android.os.Handler.dispatchMessage + 111(Handler.java:111)
       at android.os.Looper.loop + 207(Looper.java:207)
       at android.app.ActivityThread.main + 5737(ActivityThread.java:5737)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 789(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main + 679(ZygoteInit.java:679)

Shall I initiate another issue thread?
Please help us out cause we are losing thousands of users. I hope you are getting our problem.

**Comment by raphkim** [comment]
Hi @deepakrokz 

Thank you for the update. I believe the keystore issue was already addressed in the other thread.

Regarding running TransferService in the foreground, we will further investigate the issue to identify the cause of inconsistency between devices.

**Comment by raphkim** [comment]
@deepakrokz 

Hi, would you be able to provide us with the logs from TransferService so that we may better assess the situation? Also, can you confirm that the notification ID you are passing is not already being used or reserved by the device?
