### ISSUE TITLE
Make the logs in the SDK can be disabled

### ISSUE THREAD

**Issue by snowswinginthewind** [aws-amplify/aws-sdk-android#1175]
**Which AWS Services is the feature request for?**
aws-android-sdk-core:2.13.+, 2.14.+, 2.15+

**Is your feature request related to a problem? Please describe.**
I tried to disable logs in SDK with below method, it doesn't work:
https://aws.amazon.com/cn/blogs/mobile/logging-with-the-aws-sdk-for-android/
Some SDK logs may let users get AWS account info, it's insecurity.

**Describe the solution you'd like**
Could you please give some api to disable below logs in the sdk?
line 129:logger.info("Using keyAlias = " + keyAlias);

line 1236:logger.info("Using keyAlias = " + keyAlias);

line 153：logger.info("Creating the AWSKeyValueStore with key for " +
                        "sharedPreferences = " + sharedPreferencesName);

**Comment by royjit** [comment]
Closing this as duplicate for issue #1174
