### ISSUE TITLE
UnsupportedOperationException when try to use CognitoUserPool with awsconfiguration file without AppClientSecret property

### ISSUE THREAD

**Issue by adrianolc** [aws-amplify/aws-sdk-android#1191]
I'm trying to create CognitoUserPool using the awsconfiguration.json file passing the instance of AWSConfiguration instead of creating CognitoUserPool passing all ids on the constructor.

With this constructor
/** * Constructs a user-pool with default {@link ClientConfiguration}. * * @param context REQUIRED: Android application context. * @param awsConfiguration REQUIRED: Holds the configuration read from awsconfiguration.json */ public CognitoUserPool(Context context, AWSConfiguration awsConfiguration)

Our pool doesn't have the AppClientSecret so we don't pass it on the awsconfiguration file, but this constructor will try to read the property and add an empty string case it not found the property.

`this.clientSecret = userPoolConfiguration.optString("AppClientSecret");`

Then when we go to the initiateCustomAuthRequest it throws an exception when trying to add a null secret hash

Exception stacktrace

![Screenshot 2019-09-12 at 15 54 20](https://user-images.githubusercontent.com/4654098/64791580-372d0580-d578-11e9-8177-d3802449fe47.jpg)

````
W/System.err: java.lang.UnsupportedOperationException
W/System.err:     at java.util.AbstractMap.put(AbstractMap.java:209)
W/System.err:     at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.initiateCustomAuthRequest(CognitoUser.java:2927)
W/System.err:     at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.access$2800(CognitoUser.java:132)
W/System.err:     at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$25.run(CognitoUser.java:2521)
W/System.err:     at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$7$1.run(CognitoUser.java:882)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
```

**Comment by adrianolc** [comment]
Exactly it's not because is NULL it's because is EMPTY. 

But yep, I gonna share with you what did you ask

**Comment by adrianolc** [comment]
So this is our CognitoUserPool on awsconfiguration.json

```
"CognitoUserPool": {
    "Default": {
      "PoolId": "XXXXXXXX",
      "AppClientId": "XXXXXXXX",
      "Region": "eu-west-1"
    }
}
```

**Comment by adrianolc** [comment]
And this is our AuthenticationHandler, we wrapped it on CustonHandler to fit better in our architecture. 

```
/**
 * performs a login with a custom user challenge
 * uses a temporary user pool followed by a federatedSignIn on the AWSMobileClient
 */
class CustomAuthHandler(
    val context: Context,
    private val pool: CognitoUserPool
) : AuthenticationHandler {

    private var userName: String? = null
    private var callback: Callback<SignInResult>? = null
    private var authenticationContinuation: ChallengeContinuation? = null

    fun signIn(userName: String, callback: Callback<SignInResult>) {
        this.userName = userName
        this.callback = callback
        authenticationContinuation = null
        pool.getUser(userName).getSessionInBackground(this)
    }

    fun sendCode(code: String, callback: Callback<SignInResult>) {
        this.callback = callback
        authenticationContinuation?.setChallengeResponse(
            CognitoServiceConstants.CHLG_RESP_ANSWER,
            code
        )
        authenticationContinuation?.continueTask()
    }

    override fun onSuccess(userSession: CognitoUserSession, newDevice: CognitoDevice?) {
        AWSMobileClient.getInstance().let { awsClient ->
            val awsConfig = awsClient.configuration
            val providerKey =
                "cognito-idp.${awsConfig.cognitoRegion.getName()}.amazonaws.com/${awsConfig.cognitoPoolId}"

            awsClient.federatedSignIn(
                providerKey,
                userSession.idToken.jwtToken,
                object : Callback<UserStateDetails> {
                    override fun onResult(result: UserStateDetails?) {
                        callback?.onResult(SignInResult.DONE)
                    }

                    override fun onError(e: Exception?) {
                        callback?.onError(e)
                    }
                }
            )
        }
    }

    override fun onFailure(e: Exception?) {
        callback?.onError(e)
    }

    override fun getAuthenticationDetails(
        authenticationContinuation: AuthenticationContinuation,
        userId: String?
    ) {
        // Add parameters will force cognito to use the custom pool and response with the challenge
        val authParams = mapOf(CognitoServiceConstants.AUTH_PARAM_USERNAME to userName)
        val authDetails = AuthenticationDetails(userName, authParams, null)

        authenticationContinuation.setAuthenticationDetails(authDetails)
        authenticationContinuation.continueTask()
    }

    override fun authenticationChallenge(continuation: ChallengeContinuation?) {
        authenticationContinuation = continuation
        callback?.onResult(SignInResult(SignInState.CUSTOM_CHALLENGE, mapOf<String, String>()))
    }

    override fun getMFACode(continuation: MultiFactorAuthenticationContinuation?) {
    }
}
```

We are using this constructor here and it is working fine, but we've like to use the one we just pass the AWSConfiguration to make it simple

`CognitoUserPool(context, config.cognitoPoolId, config.cognitoAppClientId, null, config.cognitoRegion)`

**Comment by desokroshan** [comment]
> Exactly it's not because is NULL it's because is EMPTY.

I am sorry, I meant empty but typed out null instinctively. I have edited the comment.

**Comment by desokroshan** [comment]
Can you try using `AuthenticationDetails(username, password, authParameters, null);` with an empty mapOf<String, String>() along with a dummy password for creating authentication details. 
Also if you want to use `AuthenticationDetails(userName, authParams, null)`, cam you make sure that the type of authParams map is explicitly set to <String, String>. From a quick research online it looks like type mismatch can cause UnsupportedOperationException.

**Comment by adrianolc** [comment]
@desokroshan found the problem, we can't use `mapOf` but `mutableMapOf`.
So the error was that the SDK tries to add this null ` secretHash` on the  `authenticationParameters` and it does not accept a new value because it's not mutable

Thanks for the help

PS: more and more people are using kotlin nowadays, you guys should keep it in mind when writing documentation, this case was 0 clear and toke lot of debug inside your SDK to try to understand better how it works and I could see lot of fails possibilities.

**Comment by desokroshan** [comment]
@adrianolc I was expecting it to have something to do with the way map was declared since your error was not from the service. Good to hear that its working and thanks for your feedback.
Btw, we suggest using AWSMobileClient for all authentication use cases in your app. Is there a reason you are using CognitoIdentityProvider SDK instead of AWSMobileClient? We are working on custom auth support in AWSMobileClient and that will be out in next release. Let me know if there are additional use cases that you need and are not supported in AWSMobileClient.

**Comment by adrianolc** [comment]
We're using because of the custom auth, when you release it on the AWSMobileClient then we can try and stop to use directly on cognito

**Comment by desokroshan** [comment]
@adrianolc We have released support for custom auth in AWSMobileClient in the latest release 2.16.0. Please refer to the documentation here https://aws-amplify.github.io/docs/android/authentication for more details. Let me know if you have questions.
