### ISSUE TITLE
Long response time in  confirmSignUp, signIn

### ISSUE THREAD

**Issue by CezaryGoralski** [aws-amplify/aws-sdk-android#1194]
**State your question**
Hello currently Im using AWSMobileClient to authenticate my users in my application and I have observed that the response time is ussaly quite long  for those 2 requests ( confirmSignUp, signIn). For the confirmSignUp is ussualy around 11-14s, sometimes it's about 3-4s (rarely).
![image](https://user-images.githubusercontent.com/11683322/64882063-97957300-d65c-11e9-96c5-0e457c5098c8.png)
For signIn it's usually around 7-9s and sometimes it's around 2s. 

I don't think that it's network issue, because other request (like facebook and google federated sigIn, forgotPassowrd) are going smoothly with 2-3s time. 

1. It's possible that I'm doing something wrong ?
2. If yes do you have any ideas how to reduce this time ?

**Which AWS Services are you utilizing?**
- amplify
- cognito

**Provide code snippets (if applicable)**
`  AWSMobileClient.getInstance().confirmSignUp(email, code, new Callback<SignUpResult>()
 AWSMobileClient.getInstance().signIn(email, password, null, new Callback<SignInResult>()
`

**Environment(please complete the following information):**
 - android-sdk-mobile-client: 2.15.2

**Device Information (please complete the following information):**
 - Device: Samsugn Galaxy s8+
 - Android Version: 9
If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by vishveshpandya** [comment]
Yes, I am also facing the same issue. It is taking way longer to get API response.

**Comment by desokroshan** [comment]
@CezaryGoralski Thanks for reaching out. Is this spike in the time take a recent phenomenon or has it always been there? Did you upgrade the SDK version recently which caused this increase in the API calls? Can you share more information around this?

**Comment by CezaryGoralski** [comment]
@desokroshan Thank you for response. I have started developing by using AWS amplify around 1 month ago so for me it was there from the beginning. I didn’t increase the lib version so probably it’s not the case and it’s strange that other requests like forgotPassword, resendSignUp, federatedSingIn via facebook and google are taking much less time than confirmSignUp and signIn. If you have any idea what may cause this or you have any question i will be grateful

**Comment by kvasukib** [comment]
@CezaryGoralski Thank you for the response. 

How are you measuring the time for `confirmSignUp` and `signIn` operations? 
Does the measurement only include the network request or any other interactions in the app? 
Can you demonstrate how your signIn operation works? 
How many challenges are included as part of signIn?
