### ISSUE TITLE
Manual setup instead of amplify add auth

### ISSUE THREAD

**Issue by Mehdi-android** [aws-amplify/aws-sdk-android#1203]
**State your question**
I want to do manual setup for amplify add auth, as I want to allow users to authenticate using cognito.

**Which AWS Services are you utilizing?**
AWS Amplify

**Environment(please complete the following information):**
- implementation 'com.amazonaws:aws-android-sdk-core:2.15.2'
- implementation ('com.amazonaws:aws-android-sdk-mobile-client:2.13.+@aar') { transitive = true }

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]

I tried with amplify configure, but its not working for me due to some reason, So can you help me with manual setting up the awsconfiguration.json to authenticate user. Also if possible let me know if after setting up in awsConfiguration.json do I need to add any further code like below.

cognitoUser.getSessionInBackground(new AuthenticationHandler() {
	@Override
	public void onSuccess(CognitoUserSession session) {
		String idToken = session.getIdToken().getJWTToken();

		Map<String, String> logins = new HashMap<String, String>();
		logins.put("cognito-idp.<region>.amazonaws.com/<YOUR_USER_POOL_ID>", session.getIdToken().getJWTToken());
		credentialsProvider.setLogins(logins);
	}

});

Thanks.

**Comment by desokroshan** [comment]
@Mehdi-android Thanks for reaching out. We recommend using CLI for backend configuration rather than manual configuration. You mentioned that you ran into some issues while configuring via amplify add auth. Can you share more details about the problem you ran into?

**Comment by Mehdi-android** [comment]
Somehow after installing CLI when I try to run command amplify configure, it says command not found. 
Node version - v11.15.0
NPM version - 6.7.0. 

Tried uninstalling & installing node but nothing helped.

`Successfully installed the Amplify CLI
----------------------------------------
Javascript Getting Started - https://aws-amplify.github.io/docs/js/start


Android Getting Started - https://aws-amplify.github.io/docs/android/start


iOS Getting Started - https://aws-amplify.github.io/docs/ios/start


npm WARN @conduitvc/mosca@2.8.3 requires a peer of leveldown@~1.4.3 but none is installed. You must install peer dependencies yourself.
npm WARN @conduitvc/mosca@2.8.3 requires a peer of ioredis@^1.15.1 but none is installed. You must install peer dependencies yourself.
npm WARN @conduitvc/mosca@2.8.3 requires a peer of mongodb@~2.1.4 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/@aws-amplify/cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/@aws-amplify/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: snappy@5.0.5 (node_modules/@aws-amplify/cli/node_modules/snappy):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: snappy@5.0.5 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: zmq@2.15.3 (node_modules/@aws-amplify/cli/node_modules/zmq):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: zmq@2.15.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ @aws-amplify/cli@3.9.0
updated 44 packages in 175.914s
user@user-Lenovo-ideapad-300:~$ amplify configure
amplify: command not found
`

**Comment by desokroshan** [comment]
@Mehdi-android Thanks for sharing the details. It looks like this an open issue with ampli cli https://github.com/aws-amplify/amplify-cli/issues/778. You can follow the thread for updates on that issue. 
But to unblock you, if you need to manually configure the awsconfiguration json please make sure you are using [AWSMobileClient](https://github.com/aws-amplify/aws-sdk-android/tree/master/aws-android-sdk-mobile-client) and not the [CognitoIdentityProvider SDK](https://github.com/aws-amplify/aws-sdk-android/tree/master/aws-android-sdk-cognitoidentityprovider). To manually configure, create user pool from the AWS console with default settings, create an identity pool with default settings and set user pool as identity provider for the identity pool you just created. Then fill-up the details in awsconfiguration.json template shown below : 

```
{
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "XX-XXXX-X:XXXXXXXX-XXXX-1234-abcd-1234567890ab",
                "Region": "XX-XXXX-X"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "XX-XXXX-X_abcd1234",
            "AppClientId": "XXXXXXXX",
            "AppClientSecret": "XXXXXXXXX",
            "Region": "XX-XXXX-X"
        }
    }
}
```

Please let me know if you need details for any of the steps listed above. Hope it helps!

**Comment by Mehdi-android** [comment]
Thanks. But please solve that CLI issue as lot of developers are facing this CLI issue.
