### ISSUE TITLE
Please provide refreshSession() method in AWSMobileClient for getting latest access token

### ISSUE THREAD

**Issue by cjeremylin** [aws-amplify/aws-sdk-android#1204]
**Which AWS Services is the feature request for?**
Cognito Auth

**Is your feature request related to a problem? Please describe.**
At this moment, there is no public method to exchange the latest access tokens with refresh token in AWSMobileClient. This use case is similar with #1171 . According to official documentation says "ou don’t need to refresh Amazon Cognito tokens manually" [1], but in some scenario we need a method to get latest access token indeed. For instance, when we assign a user into different group in Cognito User Pool in Backend Server with Cognito API to override customer's access scope or 'cognito:groups' in access token.  We would like to let client to get latest access token by exchanging refresh token. 

**Describe the solution you'd like**
AWSMobileClient can perform refreshSession() as the same method in Amplify JS SDK [2] to force revoke access token with non expired refresh token. 

Thanks for any advice. 

[1] https://aws-amplify.github.io/docs/android/authentication#managing-security-tokens
[2]https://github.com/aws-amplify/amplify-js/blob/45b79f24371de398e36be2770a35aad128ba6ca3/packages/amazon-cognito-identity-js/src/CognitoUser.js#L1212

**Comment by zubairzahoor** [comment]
If you call getTokens() from a separate thread or async, it will fetch you the new tokens (access, id and refresh)

**Comment by ganeshbahirat** [comment]
@zubairzahoor In Android,  post initialisation again after some time I'm calling AWSMobileClient.getInstance().getTokens(); in worker thread but its returning same AccessToken. Can anyone please explain me how its behaves?

**Comment by zubairzahoor** [comment]
@ganeshbahirat Use it like this: 

   ```
    AWSMobileClient.getInstance().getTokens(new Callback<Tokens>() {
            @Override
            public void onResult(Tokens result) {
                String AccessToken = result.getAccessToken().getTokenString();
                //Use AccessToken Here
            }

            @Override
            public void onError(Exception e) {
                Log.e("Err", e.getMessage());
            }
        });
```

**Comment by mangeshsambare** [comment]
@zubairzahoor I tried above solution, but client application don't get new token. It return previous one. I face same problem as @ganeshbahirat commented

**Comment by taranabhangoo** [comment]
I have same problem. I am using amplify and I still don't see any method to force fetch the tokens.

**Comment by SomnathS09** [comment]
>@zubairzahoor : If you call getTokens() from a separate thread or async, it will fetch you the new tokens (access, id and refresh)

And what happens if there is no network connectivity? can refresh token generate new access token without network?

The problem I'm facing is :
I'm using Amplify.currentUser? to see if user is logged in or not;
If Internet is off then above line returns random results after expiration of access token time,
sometimes it finds the user and sometimes it doesn't

**Comment by div5yesh** [comment]
Please use the following as a workaround until we find a proper solution:

Set the refresh threshold higher than current expiration of idToken or accessToken to force a refresh. During the subsequent getTokens calls, the library will fetch new tokens as long as refreshToken is not expired.

`CognitoIdentityProviderClientConfig.setRefreshThreshold(thresholdInMS);` where **thresholdInMS** is the refresh threshold in milliseconds and if it is greater than the token expiration forces a token refresh request.

```java
new Thread(() -> {
    try {
    CognitoIdentityProviderClientConfig.setRefreshThreshold(100000);
    AWSMobileClient.getInstance().getTokens();
    } catch (Exception e) {
        e.printStackTrace();
    }
}).start();
```

**Comment by tjleing** [comment]
If the workaround does not work, please comment on this issue or open a new one.
