### ISSUE TITLE
refreshToken is invalid after signed in 

### ISSUE THREAD

**Issue by truongnguyen-agilityio** [aws-amplify/aws-sdk-android#1208]
**Describe the bug**
After I signed in my app successfully. I get refreshToken but it's invalid

Get refreshToken success
```
tokens.getRefreshToken().getTokenString()
```

Get refreshToken expiration fail
```
tokens.getRefreshToken().getExpiration()
```

Error
```
CognitoParameterInvalidException: invalid token

Failed to get claim from token
```

**Comment by kvasukib** [comment]
@truongnguyen-agilityio Sorry for the inconvenience caused.

What SDK are you using? `AWSMobileClient` (`aws-android-sdk-mobile-client`) or `CognitoUserPools` (`aws-android-sdk-cognitoidentityprovider`)?

Can you post a code snippet where you initialize the SDK objects and the code which performs the signIn?

Do you wait until the signIn operation completes before checking for the refresh token? 

In addition to this, can you fill in the [template](https://github.com/aws-amplify/aws-sdk-android/issues/new?template=bug_report.md) for a new bug with the required information which will be helpful to debug the issue?

**Comment by truongnguyen-agilityio** [comment]
I am using `com.amazonaws:aws-android-sdk-mobile-client` version 2.16.0

this is my codes:
```
return AWSAppSyncClient.builder()
                .context(application)
                .awsConfiguration(awsConfiguration)
                .okHttpClient(okHttpClient)
                .cognitoUserPoolsAuthProvider(() -> {
                    try {
                        return AWSMobileClient.getInstance().getTokens().getIdToken().getTokenString();
                    } catch (Exception e) {
                        Log.e("AWSMobileClient", e.getLocalizedMessage());
                        return e.getLocalizedMessage();
                    }
                }).build();
```

**Comment by kvasukib** [comment]
@truongnguyen-agilityio Thank you for the response. Have you successfully initialized AWSMobileClient and is the user signed in successfully before the IdToken can be accessed by the `cognitoUserPoolsAuthProvider`? You can refer to `AWSMobileClient` initialization here: https://aws-amplify.github.io/docs/android/authentication#initialization

Also, I don't see in your code snippet where you are retrieving the refresh token string. Can you post a complete code snippet where you initialize `AWSMobileClient`, signIn, using it in `AWSAppSyncClient` and also retrieving the refresh token?

You can read more about refresh here: https://aws-amplify.github.io/docs/android/authentication#token-fetch-and-refresh
