### ISSUE TITLE
Custom Authorization

### ISSUE THREAD

**Issue by cmbaykal** [aws-amplify/aws-sdk-android#1212]
Hi in the AWS Amplify IOS SKD has pubsub custom authorization but android sdk hasn't.
I resarch many contents. Custom authorization can be added android but not legally.

**Comment by desokroshan** [comment]
@cmbaykal Thanks for reaching out. This issue is already being tracked in https://github.com/aws-amplify/aws-sdk-android/issues/429. Please follow that thread for updates. Closing this as duplicate.
