### ISSUE TITLE
User session is not valid after session onSuccess

### ISSUE THREAD

**Issue by DmitryDoneIT** [aws-amplify/aws-sdk-android#1217]
**State your question**
My application uses cognito authentication and recently, on some devices, a problem started that after a successful session, this session is not valid, based on  firebase crashlytics, this happens only with Redmi Note 6 Pro, MI 9 and some other devices, also users of these devices reported that they cleaned the application cache and it didn’t help
also these users were checked on other devices where authorization was successful
on other devices, authorization works correctly

**Which AWS Services are you utilizing?**
com.amazonaws:aws-android-sdk-cognito:2.15.+  

**Provide code snippets (if applicable)**
```
`private fun session(user: String, password: String) {
    val awsUser = CognitoUserPool(context, USER_POOL_ID, CLIENT_ID, CLIENT_SECRET, USER_POOL_REGION).getUser(user)
    awsUser.getSession(object : AuthenticationHandler {
        override fun onSuccess(userSession: CognitoUserSession, newDevice: CognitoDevice?) {
            userSession.isValid // false
        }
        override fun onFailure(exception: java.lang.Exception) {
        }

        override fun getAuthenticationDetails(authenticationContinuation: AuthenticationContinuation, userId: String?) {
            authenticationContinuation.setAuthenticationDetails(AuthenticationDetails(user, password, null))
            authenticationContinuation.continueTask()
        }

        override fun authenticationChallenge(continuation: ChallengeContinuation?) {
        }

        override fun getMFACode(continuation: MultiFactorAuthenticationContinuation?) {
        }
    })
}`
```

**Device Information:**
 - Device: [Redmi Note 6 Pro , MI 9]

**Comment by desokroshan** [comment]
@DmitryDoneIT Thanks for reaching out. Given that you are experiencing this issue on selected devices, a bug in the primary code path is unlikely. From the implementation of isValid() https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUserSession.java#L113 method it looks like current time stamp is compared against the expiration of id token and access token. Can you check if the device clock is accurate and up-to-date. Also do you see any clock skew messages in the the SDK logs. Also are you able to make subsequent calls to AWS services once getSession gets a success callback? This is just to verify that the tokens are actually invalid.

**Comment by DmitryDoneIT** [comment]
@desokroshan  I checked on user devices where authorization did not work, and yes, based on data on device, the token expired for 1 hour, most likely this is due to wrong time zone or the set time manually.
also my application used CognitoUser.getDetails which throw a CognitoNotAuthorizedException in this case, but a direct call with GetUserRequest and AmazonCognitoIdentityProviderClient solved my problem

**Comment by desokroshan** [comment]
@DmitryDoneIT I would expect `CognitoUser.getDetails` to work just fine. Can you share the stack trace and repro steps for `CognitoNotAuthorizedException` ?

**Comment by mark-tussock** [comment]
I also have users experiencing this issue, although I have not been able to reproduce yet and do no have access to any logs. Will look at adding in some logging with crashlytics but would appreciate any extra details from your findings. Thanks
