### ISSUE TITLE
Set engine in Polly Presigned URL requests

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/aws-sdk-android#1256]
(Android version of iOS feature request https://github.com/aws-amplify/aws-sdk-ios/issues/1973)

**Which AWS Services is the feature request for?**

Amazon Polly

**Describe the solution you'd like**

The Amazon Polly service allows setting the `engine` ("standard" or "neural") used to generate speech from text. https://docs.aws.amazon.com/polly/latest/dg/API_SynthesizeSpeech.html#polly-SynthesizeSpeech-request-Engine

The auto-generated SDK allows customers to specify this via the "start speech" operation, but the presigned URL builder, as a hand-generated part of the SDK, does not allow engine to be specified.

**Comment by kvasukib** [comment]
Released in 2.16.2.
