### ISSUE TITLE
Publish status success but message not received on cloud

### ISSUE THREAD

**Issue by anandsuthar2018** [aws-amplify/aws-sdk-android#1265]
**Describe the bug**
Sometimes(randomly) publish message does not appear on the cloud. Android app receives publish status success in publish callback though registered clients and AWS cloud does not receive published message. 

**To Reproduce**
Random issue but reproduces frequently.

Your code
```java
//**Configuration:**
AWSIotMqttManager awsIotMqttManager = new AWSIotMqttManager(UUID.randomUUID().toString(), endpoint);
awsIotMqttManager.setReconnectRetryLimits(2, 4);
awsIotMqttManager.setMaxAutoReconnectAttempts(-1);
awsIotMqttManager.setAutoReconnect(true);
awsIotMqttManager.setAutoResubscribe(false);
awsIotMqttManager.setKeepAlive(60);

//**MQTT Connect code:**
awsIotMqttManager.connect(AWSMobileClient.getInstance(), (status, throwable) {
});

//**Publish message code:**
awsIotMqttManager.publishString(msg, topic, AWSIotMqttQos.QOS1, (status, userData) -> {
                String publishStrStatus;
                if (status == AWSIotMqttMessageDeliveryCallback.MessageDeliveryStatus.Success) {
                    publishStrStatus = "Success";
                } else {
                    publishStrStatus = "Failure";
                }
                Log.i("MQTT Publish",
                        "*\n*********\nTopic: " + topic
                                + "\nConnection: " + isMqttConnected()
                                + "\nPublish msg: " + msg
                                + "\nPublish Status: " + publishStrStatus + "\n*********");
            }, null);
```

**Publish Result:** 
    *********
    Topic: <Topic>
    Connection: true
    Publish msg: <Message>
    Publish Status: Success
    *********

**Which AWS service(s) are affected?**
1) aws-android-sdk-iot
2) aws-android-sdk-mobile-client

**Expected behavior**
Published message should be received on the cloud and other subscribed clients as well.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.16.0 (as 2.16.1 crashes on Android 6.0.1)
 - Device: Samsung Galaxy S10
 - Android Version: Android 9 Pie
 - Specific to simulators: No

**Additional context**
- When the issue reproduces, a test message published from AWS client does not received on the android mobile even when the MQTT is connected.
- On every publish, MQTT connection is checked from the application. If not connected to MQTT, publish will not be performed.
- Even connecting/reconnecting multiple times the problem persists.

**Comment by kvasukib** [comment]
@anandsuthar2018 Thank you for reporting to us. I have few clarifying questions to ask before I can proceed with further debugging.

"A device A uses AWS IoT SDK for Android to publish a message on a topic. Your expectation is there are certain other devices B, C, D, etc. that uses AWS IoT SDK for Android that are subscribers. These subscribers initiated a MQTT connection and subscribed to the **same** topic."

Is my understanding of the scenario you have correct?

Now, the problem you are encountering is: "device A published the message and device A got a callback saying that publish is successful. However devices B, C and D have not received the subscription messages even though there are subscribed?"

In addition to subscribers, are you also saying that "AWS IoT service does not seem to have received the message being published by your device A?" If so, how have you configured your IoT endpoint? How did you check that the IoT service did not receive the message? Can you describe the configuration of your backend?

When this problem occurs, have you checked if the network connection is stable and available? Do you have any information on the stability of the network connectivity?

**Comment by anandsuthar2018** [comment]
@kvasukib find inline answers to your questions below.

**Q1:** Is my understanding of the scenario you have correct?
**Ans:** Yes, you understood my scenario correctly and other devices are subscribed to the same topic.

**Q2:** However devices B, C, and D have not received the subscription messages even though there are subscribed?
**Ans:** Yes, devices B, C, and D have not received the message on the same topic published by device A.

**Q3:** In addition to subscribers, are you also saying that "AWS IoT service does not seem to have received the message being published by your device A?"
**Ans:** Yes, AWS IoT service does not receive the message being published by device A.

**Q4:** If so, how have you configured your IoT endpoint?
**Ans:** In android mobile app, IoT endpoint is configured as below:
```
AWSIotMqttManager awsIotMqttManager = new AWSIotMqttManager(UUID.randomUUID().toString(), **endpoint**);
awsIotMqttManager.setReconnectRetryLimits(2, 4);
awsIotMqttManager.setMaxAutoReconnectAttempts(-1);
awsIotMqttManager.setAutoReconnect(true);
awsIotMqttManager.setAutoResubscribe(false);
awsIotMqttManager.setKeepAlive(60);
```

**Q5:** How did you check that the IoT service did not receive the message?
**Ans:** We have verified the issue using AWS IoT Test Console by subscribing to the same topic. We are not getting the messages published by device A.

**Q6:** Can you describe the configuration of your backend?
**Ans:** What specific configurations you require from us? As per our understanding, Aws IoT MQTT broker is pre-configured. We have not changed any configuration for the MQTT broker.

**Q7:** When this problem occurs, have you checked if the network connection is stable and available?
**Ans:** Yes, I have verified that the network connection is stable and available.

**Q8:** Do you have any information on the stability of the network connectivity?
**Ans:** Yes. At the same time, all the RESTful service calls work correctly in the same application. When the issue occurs, we have verified other applications on the same device which are working correctly. Along with that tried multiple WiFi networks, but still, the problem persists. So, it seems there is no network stability issue.

**Other observations:**
- When the problem occurs, the application stays in the same (MQTT communication blocked) state forever. Killing the android app (Within 10 seconds of killing the app, app's background service enforces MQTT disconnect using disconnect method) and re-opening app (On successful login, the app connects MQTT using connect method) doesn't solve the problem.
- Re-installing the app resolves the problem.

Let me know in case you need further details.

**Comment by anandsuthar2018** [comment]
Hi @kvasukib,

Have you found anything related to this issue?

**Comment by anandsuthar2018** [comment]
Hi @kvasukib,

Is there any update?

**Comment by anandsuthar2018** [comment]
Hi @kvasukib,

Is there any update?

This is a blocker situation for us. Hoping to get a response soon.

**Comment by desokroshan** [comment]
@anandsuthar2018 Sorry about the delay in response. Unfortunately, I am not able to reproduce this issue on my end. Would it be possible for you to reproduce it in the [AWS IoT sample apps](https://github.com/awslabs/aws-sdk-android-samples/tree/master/AndroidPubSub)?

**Comment by anandsuthar2018** [comment]
@desokroshan as I mentioned before, this issue is random and it is not consistent. But it seems that the issue reproduces when the user tries to switch cloud environment (reinitializing the instance of AWSIotMqttManager using a different "AWS IoT endpoint").

**Comment by eeatonaws** [comment]
Hi, I apologize this was not looked into again sooner. Since this is an old issue, before we investigate further, could you please let us know if you are still facing the issue with the latest version of the SDK?

**Comment by poojamat** [comment]
Closing the issue due to lack of response, please reopen it if its still an issue.
