### ISSUE TITLE
Errors with adding modules

### ISSUE THREAD

**Issue by np161** [aws-amplify/aws-sdk-android#1270]
I have added the s3 module along with the core and kms modules but the core module seems to be giving errors

![errors](https://user-images.githubusercontent.com/6806188/67502214-74a7a700-f67d-11e9-9b0c-11c961b7f6c2.PNG)

I have set the ANDROID_HOME and ANDROID_PLATFORM variables 
![vars](https://user-images.githubusercontent.com/6806188/67502344-a587dc00-f67d-11e9-91f0-41b629d2ef7c.PNG)

I also have SDK 18 and 23 installed through SDK manager

I dont know if there is something I am missing

**Comment by kvasukib** [comment]
@np161 Thank you for reporting to us.

Can you try setting it to `23` instead of `26`? The reason is `KeyPairGeneratorSpec` is being used in API levels `18-22` and is deprecated and removed after `23`. So `26` will not be able to compile the code. 

Is there a reason why you are building from source? You can consume the artifacts for `s3` and `kms` through maven.

```
dependencies {
    implementation 'com.amazonaws:aws-android-sdk-s3:2.16.+'
}
```

**Comment by np161** [comment]
Thanks for the reply.

Changing to 23 doesnt seem to have fixed it

The reason I am using the code is because I am having an issue others mentioned with the TransferService. Context.startForegroundService() did not then call Service.startForeground()
error.

This is the code

    Notification notification = new Notification.Builder(getApplicationContext(), "1")
                        .setContentTitle("")
                        .setContentText("")
                        .setSmallIcon(R.mipmap.ic_launcher)
                        .build();

                Intent tsIntent = new Intent(getApplicationContext(), TransferService.class);
                tsIntent.putExtra(TransferService.INTENT_KEY_NOTIFICATION, notification);
                tsIntent.putExtra(TransferService.INTENT_KEY_NOTIFICATION_ID, 1);
                tsIntent.putExtra(TransferService.INTENT_KEY_REMOVE_NOTIFICATION, true);
                getApplicationContext().startForegroundService(tsIntent);

Some solutions say to startForegroud() in the onCreate of the service and wanted to try adding this in the onCreate of the TransferService to see if it made a difference

    @Override
    public void onCreate() {
        super.onCreate();

        LOGGER.info("Starting Transfer Service to listen for network connectivity changes.");

        transferNetworkLossHandler = TransferNetworkLossHandler.getInstance(getApplicationContext());

        if (Build.VERSION.SDK_INT >= ANDROID_OREO) {
            try {
                synchronized (this) {
                    // Put the service in foreground state
                    LOGGER.info("Putting the service in Foreground state.");
                    startForeground(ongoingNotificationId, new Notification());
                }
            } catch (Exception ex) {
                LOGGER.error("Error in moving the service to foreground state: " + ex);
            }
        }

        synchronized (this) {
            if (isReceiverNotRegistered) {
                try {
                    LOGGER.info("Registering the network receiver");
                    this.registerReceiver(this.transferNetworkLossHandler,
                            new IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION));
                    isReceiverNotRegistered = false;
                } catch (final IllegalArgumentException iae) {
                    LOGGER.warn("Ignoring the exception trying to register the receiver for connectivity change.");
                } catch (final IllegalStateException ise) {
                    LOGGER.warn("Ignoring the leak in registering the receiver.");
                }
            }
        }
    }


I think its been working until today when I changed our app to 28 instead of 26 and now this error keeps appearing

**Comment by kvasukib** [comment]
@np161 Sorry for the inconvenience caused. I hear your concern now.

Did you try `export ANDROID_PLATFORM=28` or `export ANDROID_PLATFORM="28"`? 
Can you navigate to `build.gradle` of the `aws-android-sdk-core` module and run `getApi23` task and see if the getApi23 task succeeds?

**Comment by np161** [comment]
Ah I meant chaning the compile and targetSDK version from 26 to 28

**Comment by np161** [comment]
so it seems with targeting sdk 28 you need to the FOREGROUND_SERVICE permission and also add notification channels

    NotificationManager mNotificationManager = (NotificationManager) this.getSystemService(Context.NOTIFICATION_SERVICE);

                String name = "transferer";
                int importance = NotificationManager.IMPORTANCE_LOW;

                NotificationChannel mChannel = new NotificationChannel("transferchannel", name, importance);

                mChannel.enableLights(true);
                mChannel.setLightColor(Color.BLUE);
                if (mNotificationManager != null) {
                    mNotificationManager.createNotificationChannel(mChannel);
                }

                Notification notification = new NotificationCompat.Builder(getApplicationContext(), "transferchannel")
                        .setContentTitle("")
                        .setContentText("")
                        .setSmallIcon(R.mipmap.ic_launcher)
                        .build();

                Intent tsIntent = new Intent(getApplicationContext(), TransferService.class);
                tsIntent.putExtra(TransferService.INTENT_KEY_NOTIFICATION, notification);
                tsIntent.putExtra(TransferService.INTENT_KEY_NOTIFICATION_ID, 1);
                tsIntent.putExtra(TransferService.INTENT_KEY_REMOVE_NOTIFICATION, true);
                getApplicationContext().startForegroundService(tsIntent);



This hasnt fully solved the isssue as i still having some Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification issues

**Comment by np161** [comment]
@kvasukib Im not sure if the notification channel needs to be added to the actual TransferService instead of outside when trying to start the service

**Comment by np161** [comment]
@kvasukib I was wondering if there is any news about this. I have tried all i can but cannot get the notification channels to work. and like I mentioned previously have a feeling that the channel needs to be added inside the service. If it doesn't can it be created outside the service like the code example above. 

This causes the service to not work on any android 9 devices.

**Comment by kvasukib** [comment]
@np161 The Notification Channel needs to be created in the app before the notification is constructed. As Android Oreo (26) imposes this requirement strictly, the app needs to create it. The `TransferService` only has the responsibility of displaying the notification by passing it through the `startForeground` method.

**Comment by np161** [comment]
ah thanks for reply it seems that there were other points in the app creating notifications that I was mistaking for being the transfer service one. I added channel to all other notifications and everything seems fine now.
