### ISSUE TITLE
Corrupted uploaded files in S3

### ISSUE THREAD

**Issue by agalfioni** [aws-amplify/aws-sdk-android#1273]
**Describe the bug**
Videos uploaded with TransferUtility upload method in S3 are corrupted (size of videos in S3 are lesser than original videos located in device).

**To Reproduce**
Multipart upload with TransferUtility

```
TransferObserver transferObserver;
// Set Metadata
ObjectMetadata objectMetadata = new ObjectMetadata();
objectMetadata.setContentDisposition("attachment;"+"filename="+fileName);
// Upload file with custom Metadata
transferObserver = transferUtility.upload("uploadFolder/fileName.mp4", fileToUpload, objectMetadata);
transferObserver.setTransferListener(new UploadListener(this));

```

**Which AWS service(s) are affected?**
S3

**Expected behavior**
I expect that videos are in S3 only if upload is successful.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [2.13.7]
 - Android Version: [ > 6.0 ]
 - Specific to simulators: [No]

**Additional context**
I try to reproduce bug stopping upload before ends but in that case the video file is not present in S3 bucket like is expected.

**Comment by kvasukib** [comment]
@agalfioni Thank you for reporting to us. Sorry for the inconvenience caused.

Have you tried without setting the content disposition to see if it interferes with the data transfer and integrity?

Does this happen for all files? for all .mp4 files? 

Is this problem specific to a device configuration?

Is this problem specific to an Android API Level Version?

**Comment by agalfioni** [comment]
Hi @kvasukib ,

about the questions, i only upload to S3 .mp4 files, the error persist in the problem detected device (Samsung S7, Android 8.0.0). I try to reproduce the error with same app version in other devices with Android 7.0.0, 8.1.0, 9.0.0 but no problem was detected.

I can try don't set content disposition, but it seems that the problem is not about this configuration...

**Comment by kvasukib** [comment]
@agalfioni Does this error happen for all .mp4 files in (Samsung S7, Android 8.0.0) device?
Have you enabled Server-Side Encryption (SSE) on your bucket? Is there any other special configuration you have enabled for your bucket?

Can you paste the code snippet for creating AmazonS3Client and TransferUtility?

**Comment by agalfioni** [comment]
I don't enable any encryption in the bucket, i only set as Metadata the keys Content-Disposition and Content-Type as video/mp4.

Here the code:

**Create AmazonS3Client:**
```
// Initialize the AWS Cognito credentials provider
CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
    mContext,
    COGNITO_POOL_ID,
    MY_REGION
));

if (sS3Client == null) {

    TransferNetworkLossHandler.getInstance(context);

    ClientConfiguration clientConfiguration = new ClientConfiguration();
    clientConfiguration.setSocketTimeout(60000);
    clientConfiguration.setMaxErrorRetry(5);

    Region bucketRegion = Region.getRegion(Regions.fromName(BUCKET_REGION));
    sS3Client = new AmazonS3Client(credentialsProvider, bucketRegion, clientConfiguration);
}
``````
**Create TransferUtility:**

```
if (sTransferUtility == null) {
    sTransferUtility = TransferUtility.builder()
                    .context(context.getApplicationContext())
                    .s3Client(sS3Client))
                    .defaultBucket(BUCKET_NAME)
                    .build();
        }

```
I detect that the error occurs when i try to upload consecutively more than one video (only the first upload is successful, the other videos are corrupted). To repeat the upload proccess i call the same code with different video file after TransferListener gets TransferState.COMPLETED state.

**Comment by agalfioni** [comment]
It's seems that the problem isn't device specific. The same behaviour detected in Motorola Moto G4 when upload consecutively video files to S3.
The corrupted files' size in S3 are minor than original videos in the device. The expected behaviour is the files in S3 are in it only if the upload was successful right? Or it's possible that part of files are present in S3 when upload fails?

**Comment by raphkim** [comment]
HI @agalfioni ,

I have attempted to reproduce the issue in question, but was unsuccessful. I will close the ticket for now, but please feel free to reopen it if you are still experiencing this issue with our [latest version of SDK](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.16.11).
