### ISSUE TITLE
Handling AWS Push Notifications on Android 

### ISSUE THREAD

**Issue by chikason** [aws-amplify/aws-sdk-android#1276]
I have been trying to implement push notifications on my android project. I tried using the the tutorial on amplify page but am not getting something right.

1. **Push Notifications**
 https://aws-amplify.github.io/docs/android/push-notifications

2. **Handling FCM/GCM Push Notifications**
https://aws-amplify.github.io/docs/android/push-notifications-handle-fcm

**Does this tutorial or implementation on the second part dependent on the first part. 
The first part which has some listener implementation on the MainActivity.

Or can i just follow the guild on the second part(handling fcm/gcm push notifications) after adding notifications on my project using amplify cli. As bellow**

<receiver
    android:name=”com.amazonaws.mobileconnectors.pinpoint.targeting.notification.PinpointNotificationReceiver” android:exported=”false” >
    <intent-filter>
        <action android:name=”com.amazonaws.intent.fcm.NOTIFICATION_OPEN” />
    </intent-filter>
</receiver>

<activity
    android:name=".DeepLinkActivity"
    android:label="A deeplink!" >
    <intent-filter android:label="inAppReceiver">
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        
        <data android:scheme="pinpoint"
              android:host="deeplink" />
    </intent-filter>
</activity>

**
1.Please do I suppose to change the scheme value > android:scheme="pinpoint"
to the value of my project pinpoint id?
2. The host value which was set to deeplink, I hope I could change it? 
**

public class DeeplinkActivity extends Activity {
 
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
 
        if (getIntent().getAction() == Intent.ACTION_VIEW) {
            Uri data = getIntent().getData();
 
            if (data != null) {
 
                // show an alert with the "custom" param
                new AlertDialog.Builder(this)
                        .setTitle("An example of a Deeplink")
                        .setMessage("Found custom param: " +data.getQueryParameter("custom"))
                        .setPositiveButton(android.R.string.yes, new DialogInterface.OnClickListener() {
                            public void onClick(DialogInterface dialog, int which) {
                                dialog.dismiss();
                            }
                        })
                        .setIcon(android.R.drawable.ic_dialog_alert)
                        .show();
            }
        }
    }
}

**Comment by richardmcclellan** [comment]
The tutorial mentioned in this issue has been relocated.  Here is the current documentation for implementing push notifications: https://docs.amplify.aws/sdk/push-notifications/setup-push-service/q/platform/android#open-a-deep-link

> 1.Please do I suppose to change the scheme value > android:scheme="pinpoint" to the value of my project pinpoint id?

No, this is not meant to be your pinpoint ID.  This can be whatever you want.  It is common to use your application package name here (e.g. `com.myCompany.myApp`)

> 2. The host value which was set to deeplink, I hope I could change it?

Yes, you may set this to whatever you wish as well.  Typically this is related to the content or type of push notification you are sending, and can be inspected by calling `getIntent().getData()` from your `DeeplinkActivity`.
