### ISSUE TITLE
Android 10 Dark Theme breaks AWSMobileClient SignIn screen

### ISSUE THREAD

**Issue by BillBunting** [aws-amplify/aws-sdk-android#1281]
**Describe the bug**
The AWSMobileClient showSignIn UX does not support Android 10 Dark Theme. The username and password text field background color is white and the foreground text color is also white, username and password fields are thus not visible. The background of the text box should be dark in the dark theme. The white lower background should also be dark. The UX should match the iOS version. (https://github.com/aws-amplify/aws-sdk-ios version 2.12.1)

**Which AWS service(s) are affected?**
AWSMobileClient

**Expected behavior**
The UX should support Android 10 Dark Theme mode.

**Screenshots**
![Screen Shot 2019-10-28 at 2 21 18 PM](https://user-images.githubusercontent.com/5861783/67705975-5f3cc080-f98e-11e9-914e-44ed0a7e71ae.png)

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.16.1 (and want for 2.13.3 too)
 - Device: Any 
 - Android Version: 10
 - Specific to simulators: No

**Additional context**
Similar to iOS issue which was recently fixed:  https://github.com/aws-amplify/aws-sdk-ios/issues/1953

**Comment by BillBunting** [comment]
Any update?  Users who have Android 10 and use Dark Theme can not sign in. This is more of a bug than a feature request at this point.

**Comment by BillBunting** [comment]
@TrekSoft   Any update? My app is already in production a with Dark Theme capability, but the sign-in with AWSMobileClient does not work because users can not see the fields. Can you give me an estimate on when Dark Theme will be supported here?

**Comment by BillBunting** [comment]
Any update? Users with Dark Theme are unable to sign-up or sign-in to any app using the MobileClient sign-in screens.

**Comment by BillBunting** [comment]
@TrekSoft Please change this to a bug. This is not a feature request, it is a bug. Users are unable to login. Any update on a fix?

**Comment by BillBunting** [comment]
@TrekSoft Any update or ETA on support for Dark Theme for AWSMobileClient showSignIn ?

**Comment by TrekSoft** [comment]
Sorry for the miss on this @BillBunting - updating now and will bring it up in our bug bash today.

**Comment by TrekSoft** [comment]
My apologies again for the delay on this @BillBunting - fix is merged and will go out with the next release.

**Comment by BillBunting** [comment]
@TrekSoft - thank you.
