### ISSUE TITLE
SNS stop sending notification, Android 5 Java 8

### ISSUE THREAD

**Issue by kelpAid** [aws-amplify/aws-sdk-android#1283]
**Describe the bug**
The code used to work without the region needed to be specified.
We would like to know if the SDK changed and if so where.

**To Reproduce**
When using the code without the region line it wont send notificactions through SNS.
By adding the line it now sends the notificaction.
```
this.phone = params[0].toString();
this.message = paramsll].toStringj);

// access key

String ak = getAkO;
String sak = getSak();

AWSCredentials awsCredentials = new BasicAWSCredentials(ak, sak);
final AmazonSNSClient snsClient = new AmazonSNSClient(awsCredentials);

//this new line fixed it
snsClient.setRegion.getRegion(Regions.DEFAULT_REGION));

String phoneNumber = phone;
Map<String, MessageAttributeValue> smsAttributes = new HashMap<>;

PublishResult result = snsClient.publish(new PublishRequest().withMessage(message).withPhoneNumber(phoneNumber).withMessageAttributes(smsAttributes));
```

**Which AWS service(s) are affected?**
SNS

**Expected behavior**
The code should send notifications with SNS without the region specified

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.16.1
 - Android Version: Android 5.1
 - Specific to simulators: No

**Additional context**
The bug appeared on Oct 25.

**Comment by richardmcclellan** [comment]
This issue is fairly old, so I don't have the context to answer the question of "when" region became required, but it doesn't sound like there are any blocking issues here since you have been able to resolve your issue by specifying the region.  Please open a new issue if you have further concerns.
