### ISSUE TITLE
How are you generating the code for services? 

### ISSUE THREAD

**Issue by jakejscott** [aws-amplify/aws-sdk-android#1290]
How are you generating the code for services? 

I'm looking to port this sdk to Dart/Flutter and I'm wondering how your doing the codegen?

**Comment by undefobj** [comment]
Code generation is done with a manual build tool that isn't public. However we're looking at Flutter support for the future. If you have interest please respond on this issue with your use case: https://github.com/aws-amplify/amplify-js/issues/1852
