### ISSUE TITLE
AWS Amplify & MFA Verification

### ISSUE THREAD

**Issue by perryhoekstra** [aws-amplify/aws-sdk-android#1296]
**State your question**

I am using the AWS Amplify framework to interact with a Cognito User Pool. I can successfully authenticate a user using the AWSMobileClient class. However, every time a user logs in, an SMS MFA is sent to their phone for secondary authentication. However, I have been unable to determine how to validate through the AWSMobileClient the MFA code sent to the user's phone and what they entered into a dialog box. If I look at: https://aws-amplify.github.io/docs/android/authentication, it has everything but MFA authentication. If I look at the **SignIn** code section in the documentation, and more specifically, the _case SMS_MFA_, the example states _Please confirm sign-in with SMS_ but I can find no mechanism to actually do that. Is there no facility within the AWSMobileClient to confirm the validity of a given MFA code entered by the user?

**Which AWS Services are you utilizing?**

AWS Amplify (Android), Cognito User Pools

**Provide code snippets (if applicable)**

```android
AWSMobileClient.getInstance().signIn(username, password, null, new Callback<SignInResult>() {
    @Override
    public void onResult(final SignInResult signInResult) {
        runOnUiThread(new Runnable() {
            @Override
            public void run() {
                Log.d(TAG, "Sign-in callback state: " + signInResult.getSignInState());
                switch (signInResult.getSignInState()) {
                    case DONE:
                        makeToast("Sign-in done.");
                        break;
                    case SMS_MFA:
                        makeToast("Please confirm sign-in with SMS.");
                        break;
                    case NEW_PASSWORD_REQUIRED:
                        makeToast("Please confirm sign-in with new password.");
                        break;
                    default:
                        makeToast("Unsupported sign-in confirmation: " + signInResult.getSignInState());
                        break;
                }
            }
        });
    }

    @Override
    public void onError(Exception e) {
        Log.e(TAG, "Sign-in error", e);
    }
});
```

**Environment(please complete the following information):**
 
com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.15.2
com.amazonaws:aws-android-sdk-mobile-client:2.15.+

**Device Information (please complete the following information):**
 - Device: [Essential, Simulator]
 - Android Version: API 28

**Comment by TrekSoft** [comment]
This should do the trick for you: https://aws-amplify.github.io/docs/android/authentication#confirm-signin
