### ISSUE TITLE
Resend Verfication Code for Forgot Password

### ISSUE THREAD

**Issue by anees17861** [aws-amplify/aws-sdk-android#1297]
**State your question**
How to resend code for Cognito Forgot password flow.
The normal steps for resetting your password using otp via sms works fine but if the user does not receive an otp then there should be a way to resend otp.

I tried calling ` resendConfirmationCode` which gives error "user already confirmed". This is expected since as per the docs it's to be used for only registration of a user.

I've tried going through the docs but can't find anything regarding this use case.

**Which AWS Services are you utilizing?**
Cognito User Pools

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - Gradle setup:
```
    implementation('com.amazonaws:aws-android-sdk-mobile-client:2.8.+@aar') { transitive = true }
    implementation('com.amazonaws:aws-android-sdk-auth-userpools:2.8.+@aar') { transitive = true }

    implementation 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.8.5'
    implementation 'com.amazonaws:aws-android-sdk-sns:2.7.6'
```

**Device Information (please complete the following information):**
 - Device: Not specific to device

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by raphkim** [comment]
Hi @anees17861 ,

At the moment, there is no way to resend the same OTP to the user. The recommended action if the user did not receive it the first time is to repeat the process to send a new OTP.

Please note that there is a limit to how many times a new OTP can be generated for a user per hour to prevent security risks.

**Comment by anees17861** [comment]
It doesn't have to be the same otp. Take the case if sign up. If the user doesn't receive a otp he calls resend confirmation code to get a new otp. But it doesn't invalidate the previous otp. If for some reason the user receives the first otp after clicking resend, that otp will still work. We don't have to restart the process of sign up.

In case of forgot password though if I restart the process then the first otp gets invalidated which will be annoying to the end user if he receives it

**Comment by raphkim** [comment]
In such scenario, it would make sense to invalidate the previously generated OTP because otherwise there would be two or more passwords mapped to the same user account, which should never happen.

**Comment by anees17861** [comment]
Tell me if this flow makes sense. The user starts a session by calling forgot password. In the same session he can call resend otp which generates new otp for that session. Once the user sets up the new password for that session with any one of the otp, the password will be changed and the entire session is over. Since the session is over the rest of the otps will be invalidated

**Comment by anees17861** [comment]
I agree that if a new session is generated the previous one should be invalidated to avoid multiple passwords.

**Comment by anees17861** [comment]
Maintaining sessions can also help in dividing the forgot password flow into two parts, verify otp first and then enter the new password which I believe is a popular feature request

**Comment by nihp** [comment]
Can I able to know if the user received code or not?

I need to know if the user has received the code or not successfully. Any methods to know this?

I am using aws-amplify-react-native

**Comment by gruckionvit** [comment]
Just trigger `Auth.resendSignUp(email);` again, store the email address and re-use it.

**Comment by c0deWookiee** [comment]
> Just trigger the equivalent of `Auth.resendSignUp(email);` again, store the email address and re-use it.

This does not work for me, I get an error back saying that he user is already confirmed

**Comment by gpanshu** [comment]
I am closing this issue as the way to resend the OTP is to do a forgotPassword api call again. The details of how the code was sent is sent in the response of the forgot password api call. From the docs: 

`Forgot password is a 2 step process. You need to first call forgotPassword() method which would send a confirmation code to user via email or phone number. The details of how the code was sent are included in the response of forgotPassword(). Once the code is given by the user, you need to call confirmForgotPassword() with the confirmation code to confirm the change of password.`
