### ISSUE TITLE
Is it possible to use two versions of the AWS SDK?

### ISSUE THREAD

**Issue by theemathas** [aws-amplify/aws-sdk-android#1304]
**State your question**
I am building an Android library (which would compile into an AAR file). Our library uses the AWS SDK, although this is not exposed in its public classes. I have found a problem when an Android app wants to use the AWS SDK on its own, and this app also wants to use our library.

If the app wants to use the same version of AWS SDK as our library, then there's no problem. However, if the app wants to use a different version of AWS SDK, then we're in trouble, since Java seems to refuse to load two different classes with the same name at the same time. (i.e., it can't load an AmazonS3Client from one version and also load an AmazonS3Client from another version.) This results in either a compile time error, or runtime error (with code in the AWS SDK throwing a NoClassDefFoundError).

Do you have any advise on how to resolve this?

**Which AWS Services are you utilizing?**
Cognito, S3, DynamoDB

**Environment(please complete the following information):**
 - SDK Version: 2.16.1 (for our library), 2.7.7 (for the app)

**Device Information (please complete the following information):**
 - Device: (tested on simulator) Pixel 2
 - Android Version: (tested on simulator) Android 10
 - Specific to simulators: Probably not.

**Comment by kvasukib** [comment]
@theemathas Gradle build system (and any build system in general) will enforce using one version of a library artifact in a project. You can recommend the consumer of your library to exclude the version of the AWS SDKs that your library is depending on and they can manually import a version of AWS SDK in their build.gradle that will be compatible for their app as well as your library. See [gradle exclude](https://discuss.gradle.org/t/how-do-i-exclude-specific-transitive-dependencies-of-something-i-depend-on/17991/2) for reference.

**Comment by theemathas** [comment]
So... it's impossible to have more than one version of the SDK in one app, and the best I can do is specify which version I want?

**Comment by desokroshan** [comment]
That's correct
