### ISSUE TITLE
Passwordless Custom Auth Flow in awsmobileclient

### ISSUE THREAD

**Issue by poora-best** [aws-amplify/aws-sdk-android#1347]
Hi All,

I'm having an issue when attempting sign in doing a custom auth flow for passwordless sign in.
I followed the docs here: https://aws-amplify.github.io/docs/android/authentication#custom-authentication-in-amplify

I got a awsconfiguration.json like the one there, with those two sections including the custom part.

I am facing two issues with this which are:

1. I have written a Lambda pre-authentication trigger to validate if the user is already existing in the database (RDS) or not. But when I try to sign in, this lambda method does not invoke.

2. Second is when I sign in using the CustomAuthFlow calling method **AWSMobileClient.getInstance().confirmSignIn()** the first time, it allows me to sign in without any issue. Thereafter when I sign out and try to sign in again, it trigger the lambda service Define auth challenge and Create auth challenge twice.

Thanks in advance for the help!

**Comment by desokroshan** [comment]
@poora-best Thanks for reaching out. Amazon Cognito invokes pre-authentication trigger when a user attempts to sign in, allowing custom validation to accept or deny the authentication request. Pre-authentication lambda not being triggered is likely an issue with service and I would encourage you to post ask about in [AWS Cognito Forum](pre-authentication) with more details. 

> Second is when I sign in using the CustomAuthFlow calling method AWSMobileClient.getInstance().confirmSignIn() the first time, it allows me to sign in without any issue. Thereafter when I sign out and try to sign in again, it trigger the lambda service Define auth challenge and Create auth challenge twice.

This might possibly be an SDK issue and it looks like for some reason client is making two trips to service for a single call to confirmSignIn. It seems unlikely; Can you share relevant code snippet that I can use to reproduce this issue?
