### ISSUE TITLE
Client disconnects when it tries to subscribe to a non existing topic

### ISSUE THREAD

**Issue by bsafwen** [aws-amplify/aws-sdk-android#1383]
**Describe the bug**
Client disconnects when it tries to subscribe to a non existing topic. The client gets an IOException on the socket.

**To Reproduce**
Subscribe to a non existing topic

**Which AWS service(s) are affected?**
iot

**Expected behavior**
Broker should not close the socket if the client tries to subscribe to a non existing topic.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.4 -> 2.9

I know this is not a sdk issue but i don't where else to post this.

**Comment by desokroshan** [comment]
@bsafwen Thanks for reaching out. Can you please provide some relevant code snippets. I am unable to reproduce the issue on my end. I connected to IoT and tried publishing and subscribing to  topics with random name but was never disconnected by the broker. Would it be possible for you to reproduce it in the following sample app : 
https://github.com/awslabs/aws-sdk-android-samples/tree/master/AndroidPubSubWebSocket
Also can you use the latest version of the SDK 2.16.5?

**Comment by bsafwen** [comment]
Thank you for the quick response. I used that last SDK 2.16.5 and I still have the problem. I am using just in time provisioning with a standard Mqtt client, I mean not using a websocket. I will reuse https://github.com/awslabs/aws-sdk-android-samples/blob/master/AndroidPubSub and I will report back.

**Comment by bsafwen** [comment]
So I copied pasted the subscribe function in my application and I still have the issue.

> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.subscribeToTopic(AWSIotMqttManager.java:1266)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.subscribeToTopic(AWSIotMqttManager.java:1219)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at com.irdeto.appwatch.mqtt.MyMqttManager.subscribeClick(MyMqttManager.java:436)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at com.irdeto.appwatch.mqtt.MyMqttManager.topicsSubscription(MyMqttManager.java:426)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at com.irdeto.appwatch.mqtt.MyMqttManager.access$400(MyMqttManager.java:113)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at com.irdeto.appwatch.mqtt.MyMqttManager$2.onStatusChanged(MyMqttManager.java:502)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.userConnectionCallback(AWSIotMqttManager.java:1597)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.userConnectionCallback(AWSIotMqttManager.java:1585)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager$2.onSuccess(AWSIotMqttManager.java:987)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at org.eclipse.paho.client.mqttv3.internal.ConnectActionListener.onSuccess(ConnectActionListener.java:99)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at org.eclipse.paho.client.mqttv3.internal.CommsCallback.fireActionEvent(CommsCallback.java:333)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleActionComplete(CommsCallback.java:272)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at org.eclipse.paho.client.mqttv3.internal.CommsCallback.asyncOperationComplete(CommsCallback.java:460)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at org.eclipse.paho.client.mqttv3.internal.ClientComms.shutdownConnection(ClientComms.java:434)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:190)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at java.lang.Thread.run(Thread.java:764)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager: Caused by: Client is not connected (32104)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:31)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at org.eclipse.paho.client.mqttv3.internal.ClientComms.sendNoWait(ClientComms.java:203)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribeBase(MqttAsyncClient.java:964)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:937)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at org.eclipse.paho.client.mqttv3.MqttAsyncClient.subscribe(MqttAsyncClient.java:903)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager.subscribeToTopic(AWSIotMqttManager.java:1260)
> 12-19 12:21:49.071  2919  5684 E MyMqttManager:   ... 15 more
> 12-19 12:21:49.071  2919  5684 W AWSIotMqttManager: connection is Lost

**Comment by desokroshan** [comment]
@bsafwen Thanks for the details. I guess I was initially confused by the "non-existing topics". This is the expected behavior. Server will close the connection if client attempts to subscribe to an unauthorized topic.

**Comment by bsafwen** [comment]
I re-read the standard and you are right :pensive: . Closing the issue. Thank you for your time.
