### ISSUE TITLE
S3 library - Building for SDK level 28+

### ISSUE THREAD

**Issue by codeproof-dev** [aws-amplify/aws-sdk-android#1384]
There are two issues related to S3 library.

(1) What is the library that we need on Android SDK 28+. I am using following library and i can't compile the code. It used to compile fine before, not anymore in SDK level 28.

 ` implementation 'com.amazonaws:aws-android-sdk-s3:2.+'`

(2) Our existing code uses TransferUtility to upload. Is this still supported as it uses background service? See below code snippet. 

```
<service android:name="com.amazonaws.mobileconnectors.s3.transferutility.TransferService" android:enabled="true" />

TransferObserver transferObserver = transferUtility.upload(
		    		bucketName,     /* The bucket to upload to */
		    		keyName, 	  /* The key for the uploaded object */
		            file,       /* The file where the data to upload exists */
		            CannedAccessControlList.PublicRead
		    );


```

**Comment by codeproof-dev** [comment]
(1) First one is resolved.

(2) Looking for an official response from the SDK team.

**Comment by TrekSoft** [comment]
Hey, your question is just whether we still support TransferUtility with the background TransferService? 

If so, the answer is yes.

**Comment by codeproof-dev** [comment]
Thank you.
