### ISSUE TITLE
How to send required user attributes when calling confirmSignIn.

### ISSUE THREAD

**Issue by zubairzahoor** [aws-amplify/aws-sdk-android#1403]
On gettting the NEW_PASSWORD_REQUIRED challange, when confirmSignIn is called with new password it shows 'Invalid attributes given, name is missing'.
'name' here is a required user attribute.
Is there a way to pass the name (or other attributes) while submitting the new password?
In js there is a way. What about Android?

com.amazonaws.services.cognitoidentityprovider.model.InvalidParameterException: Invalid attributes given, name is missing (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: a2afe9e6-6382-44cd-ae53-2c4c7c25a8e6) at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730) at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405) at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212) at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6292) at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.respondToAuthChallenge(AmazonCognitoIdentityProviderClient.java:4953) at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.respondToChallenge(CognitoUser.java:2408) at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.ChallengeContinuation.continueTask(ChallengeContinuation.java:165) at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.NewPasswordContinuation.continueTask(NewPasswordContinuation.java:147) at com.amazonaws.mobile.client.AWSMobileClient$7.run(AWSMobileClient.java:1274) at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101) at java.lang.Thread.run(Thread.java:764)

**Comment by raphkim** [comment]
Hi @zubairzahoor 
Would it be possible for you to provide the code snippet where you are encountering the issue? 
The cognito identity provider should automatically update its internal username upon initiating auth and use that as the username in required parameter.

**Comment by zubairzahoor** [comment]
`AWSMobileClient.getInstance().confirmSignIn(password, new Callback<SignInResult>() {
            @Override
            public void onResult(SignInResult signInResult) {
                Log.d("", "Sign-in callback state: " + signInResult.getSignInState());
                switch (signInResult.getSignInState()) {
                    case DONE:
                        //makeToast("Please confirm sign-in with SMS.");
                        break;
                    case SMS_MFA:
                        //makeToast("Please confirm sign-in with SMS.");
                        break;
                    default:
                        // makeToast("Unsupported sign-in confirmation: " + signInResult.getSignInState());
                        break;
                }
            }

            @Override
            public void onError(Exception e) {
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        Log.e("Reset", "forgot password error", e);
                    
                    }
                });
            }
        });`
This does not work after getting the NEW_PASSWORD_REQUIRED obviously because I am not providing the username attribute anywhere which is a required attribute in cognito.
PS: In JS there is a way to send username(or any other attribute) with confirmSignIn as an additional parameter but not in this sdk.

**Comment by desokroshan** [comment]
Following is an overloaded version of confirmSignIn where you can pass challenge response as Map of strings. You can use this to pass all the required attributes. 
https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L1322 
Please give it a try and let me know if you see any issues.

**Comment by zubairzahoor** [comment]
@desokroshan As I said, you cannot use this overloaded version when you are completing the NEW_PASSWORD_REQUIRED challenge.
Shows the exception: ````
"Please use confirmSignIn(String, Callback) " +
                                        "for SMS_MFA and NEW_PASSWORD_REQUIRED challenges"
````
You can check in it's implementation that it only supports custom challenges as of now.

**Comment by zubairzahoor** [comment]
@desokroshan As I said, you cannot use this overloaded version when you are completing the NEW_PASSWORD_REQUIRED challenge.
Shows the exception:

```
"Please use confirmSignIn(String, Callback) " +
"for SMS_MFA and NEW_PASSWORD_REQUIRED challenges"
```

You can check in it's implementation that it only supports custom challenges as of now.

**Comment by desokroshan** [comment]
@zubairzahoor Thanks for bringing this up. I see that we do not support the use case for passing multiple required attributes along with sign in challenge response for NEW_PASSWORD_REQUIRED case. The underlying continuation provides the facility to pass along a [bunch of user attributes](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/continuations/NewPasswordContinuation.java#L115) but the feature is not supported at AWSMobileClient layer. While we work on this, can you share your user pool settings that enforces "name" to be a required attribute while submitting the password?

**Comment by zubairzahoor** [comment]
@desokroshan I have created a userpool in AWS Cognito and simply put 'Name' as required attribute. We can create a user with just the email having UserStatus = 'UNCONFIRMED' from our backend. The user then has to complete the 'NEW_PASSWORD_CHALLENGE' and he is not able to do that from the app as it shows  'Invalid attributes given, name is missing'. 
From our react.js app, he is able to login as it supports passing name or any other attribute with the challenge.
