### ISSUE TITLE
Uploading and Downloading File Synchrounsly

### ISSUE THREAD

**Issue by asif-ashraf** [aws-amplify/aws-sdk-android#1442]
I am using Amazon s3 storage for uploading and Downloading file .But it native android client is using asynchnouly call to upload and download files i want to upload file using synchrous call because i am working on intent service that maintain its own Thread

**Comment by raphkim** [comment]
Hi @asif-ashraf ,

Invoking methods directly via low level [AmazonS3 client](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3.java) would allow synchronous call to put and get objects from S3.

However, it is generally recommended to download and upload objects via S3 asynchronously using [TransferUtility](https://aws-amplify.github.io/docs/android/storage). Please feel free to ask if you have any more questions. Thanks!
