### ISSUE TITLE
cognitoauth: AuthNavigationException: user cancelled

### ISSUE THREAD

**Issue by SaMumcu** [aws-amplify/aws-sdk-android#1443]
**User cannot able to signin in first try. I tried it both the last version 2.16.6 and 2.16.0. Result is the same.**

Steps to reproduce:
    I signed in app and then i sign out with AWSMobileClient.getInstance().signOut(SignOutOptions.builder().invalidateTokens(true).build(), new Callback<Void>() {...}
    I press sign in google button (signed in google account). It call back with "com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthNavigationException: user cancelled" error. But when i press the button again the result of call back is "signed in succeeded".
```

cognito and cognitoauth affected.

User must be able to signin on the first try.

**Environment Information**
 - AWS Android SDK Version: [2.16.6]
 - Device: [Z30]
 - Android Version: [8.1.0]

**Comment by raphkim** [comment]
#1083 #871 

Linking duplicate issues to have them all in one place.

**Comment by raphkim** [comment]
Closing in favor of #871
