### ISSUE TITLE
Potential bug with Cognito w/ FORCE_CHANGE_PASSWORD flow

### ISSUE THREAD

**Issue by wooj2** [aws-amplify/aws-sdk-android#1452]
Hi,

We recently fixed a bug on iOS where in the FORCE_CHANGE_PASSWORD flow within Cognito was broken because we were sending the service an email_verified ==true as part of the request when attempting to update a user's password.  We suspect that this bug also exists on Android, and we opening this issue for someone on the team to triage/investigate (and fix if necessary)

**Repro steps:**
1.  Create an account in the cognito console in a state where the email address has been verified, and they need to change update their password on the next login
2.  Create an app w/ cognito and log in with these credentials to allow the "change password" flow to appear
3.  Attempt to change the password

**Issue Observed on iOS:**
When attempting to change the password, we received an error from the cognito service saying: "Cannot modify the non-mutable attribute email_verified".  (We suspect we'd see the same behavior on android -- can someone verify?).

**Original bug filed here (against iOS):**
https://github.com/aws-amplify/aws-sdk-ios/issues/2203

**Client-side PR merged for iOS here:**
https://github.com/aws-amplify/aws-sdk-ios/pull/2240

**Comment by wooj2** [comment]
The PR listed in the original request is out of date, we ended up removing all userAttributes being sent back to the service.  The follow on change is located here:
https://github.com/aws-amplify/aws-sdk-ios/commit/7865fe4b448ea7d2a5425b9ab027ace544217b00

**Comment by rjuliano** [comment]
I think we're handling this appropriately on the android side. `FORCE_CHANGE_PASSWORD` gets handled by [NewPasswordContinuation](https://github.com/aws-amplify/aws-sdk-android/blob/0958a37b4757c41cac40597b973ff417e0b758c4/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/continuations/NewPasswordContinuation.java#L44)

If a user is created via the AWS console or via the `AdminCreateUser` API, that user status will be set to `FORCE_CHANGE_PASSWORD`. One caveat is that any standard attributes marked as required (other than email and username) will have to be populated as part of the challenge response when he/she first logs in. ([See cognito documentation on this](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_RespondToAuthChallenge.html#CognitoUserPools-RespondToAuthChallenge-request-ChallengeResponses))

We currently have validation in the [continueTask](https://github.com/aws-amplify/aws-sdk-android/blob/0958a37b4757c41cac40597b973ff417e0b758c4/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/continuations/NewPasswordContinuation.java#L134) method that ensures that all the necessary parameters are passed in

**Comment by TrekSoft** [comment]
Related to: https://github.com/aws-amplify/aws-sdk-android/issues/1403

**Comment by rjuliano** [comment]
As stated in the related issue, the behavior of this API for android is a bit different than what is currently in the iOS[1] and JS[2] SDKs. In android, we currently [prevent callers from invoking the overload](https://github.com/rjuliano/aws-sdk-android/blob/ca7632f7025f60c9a1bb4b3830e298fdfb4b923d/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L1358) where they're able to pass the required attributes.

[1] [iOS Behavior](https://aws-amplify.github.io/docs/sdk/ios/authentication#force-change-password)
[2] [JS Behavior](https://aws-amplify.github.io/docs/js/authentication#complete-new-password)
