### ISSUE TITLE
GetToken() return java.lang.Exception: getTokens does not support retrieving tokens for federated sign-in

### ISSUE THREAD

**Issue by adkhatri** [aws-amplify/aws-sdk-android#1465]
**Description**
When App request for accessToken, AWSMobileClient.getInstance().getTokens() method throw execption "java.lang.Exception: getTokens does not support retrieving tokens for federated sign-in".
Also for an invalid token, Library sent SIGNED_OUT_FEDERATED_TOKENS_INVALID instead of SIGNED_OUT_USER_POOLS_TOKENS_INVALID.
App has used AWSMobileClient.getInstance().signIn() method for login. No use of  federatedSignIn() method for login still getting above execption.
Library version use for AWSMobileClient is **2.13.2**

**To Reproduce**
1. Perform Login using AWSMobileClient.getInstance().signIn() with normal username and password. 
2. Put the app in idle mode for 2-3 days
3. After 2-3 day, resume App and perform getToken() for accessToken.

```
 public void signIn(User user, LoginCompletionCallback loginCompletionCallback) {
        currentUser.loggedInState = null;
        AWSMobileClient.getInstance().signIn(user.email, user.password, null,
                new Callback<SignInResult>() {
                    @Override
                    public void onResult(final SignInResult signInResult) {
                        switch (signInResult.getSignInState()) {
                            case DONE:
                               getTokens((data, error) -> {
                                    if (error != null) {
                                        // FIXME Should we block user from here?
                                    }
                                    if (loginCompletionCallback != null) {
                                        runOnUiThread(() -> loginCompletionCallback.completion(null));
                                    }
                                });
                                break;
                            // Below sign in states are not supported/implemented in app/cloud now
                            // So they are not handled for now
                            case SMS_MFA:                      
                                break;
                            case NEW_PASSWORD_REQUIRED:
                                break;
                            default:
                                break;
                        }

                    }

                    @Override
                    public void onError(Exception e) {
                    }
                });
    }



  private void getTokens(CompletionHandlerCallback completionHandlerCallback) {
        AWSMobileClient.getInstance().getTokens(new Callback<Tokens>() {
            @Override
            public void onResult(Tokens result) {
                Token accessToken = result.getAccessToken();
                /*Token refreshToken = result.getRefreshToken();     
            }

            @Override
            public void onError(Exception e) {
            }
        });
    }


```
**Affected AWS service**
   com.amazonaws:aws-android-sdk-lambda:2.13.2
   com.amazonaws:aws-android-sdk-mobile-client:2.13.2
   com.amazonaws:aws-android-sdk-auth-userpools:2.13.2
   com.amazonaws:aws-android-sdk-cognitoauth:2.13.2
 
**Expected behavior**
The library should send SIGNED_OUT_USER_POOLS_TOKENS_INVALID instead of SIGNED_OUT_FEDERATED_TOKENS_INVALID for normal login with username and password.

**Environment Information**
 - AWS verison 2.13.2

**Comment by TrekSoft** [comment]
Hey, looking in the code it appears this error could occur if you call the getTokens command before you complete AWSMobileClient initialization. Please make sure initialization completes before calling it.

**Comment by atomicalsoftwares** [comment]
I'm having this exact same issue.
