### ISSUE TITLE
login token expired within few seconds after getting new accessToken.

### ISSUE THREAD

**Issue by adkhatri** [aws-amplify/aws-sdk-android#1471]
**Description**
In my application, App request for **accessToken** at **Wed Jan 29 15:32:55 CST 2020** and received 
accessToken and idToken successfully with token expire date  **Wed Jan 29 16:21:44 CST 2020**.
Please below log 
```
AwsMobileClient: Received accessToken - Token expire date : Wed Jan 29 16:21:44 CST 2020
 - eyJraWQiOiJOUzBKcFlXUUJTNFQwdSsrOGg2bWYzcmwrUDBkdFZKRU9pNk8weHVnTEM0PSIsImFsZyI6IlJTMjU2In0.eyJzdWIiOiJkNzM4NDBhMS01MzBjLTQ3YWMtYTY0Zi1mMmMxNzkzMjhjOWQiLCJldmVudF9pZCI6IjNhZDljNDFkLTAwMzItNDcyZC1hOGJjLTg4ZmRmMGMzYTEzOCIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE1ODAyMjkzMDEsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTEuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0xX1ppMGRZVzFmQyIsImV4cCI6MTU4MDMzNjUwNCwiaWF0IjoxNTgwMzMyOTA0LCJqdGkiOiJjNjNhMGQwZC05NDdiLTQ5NmUtYjVhYy05ZTdjYTFjMjdjNmMiLCJjbGllbnRfaWQiOiI1MXBqM2hjNmlwYW9lNGpkNTZoMHVybTBybyIsInVzZXJuYW1lIjoiYzg5ZWY1MmQtM2JkNi00MzU1LWJhYjMtNjQ2YTdjZmZlODQ0In0.bPrdZpNQwkHdC_xyhNCW5EN59_wSN3f9dWJ6POaOawN6CnyR2VMBiDxhh2x4izENlUzF0qWiC7WpE_scZBTHesmxWjBoSbd68n9-TIri3aPiiUhyrgT6wQuWjpsgCB9eRsFt-5nrZ_UUz3wktJTX4ZRDCkEssRuaewsWC1318uT017elwmgGacwXVz9rtM_Q4aeWe0o-TSev2m2WjhXqrWLh7IrIw6QDxwCuHg2C7SEPIbI7HuPL8_yYRQLnVF91GIq6b9touPfkPKYHVJZqpf_f68FcqqRthkFnDfdUL5tpvDuxVqdy9L2oDNmGkQ4-nS3u9ONwl-BlhRy-WsCsBw
```
After this  when App send request to AWS at **Wed Jan 29 15:33:02 CST 2020** it throws exception **Caused by: com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Invalid login token. Token expired: 1580337161 >= 1580336504 (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 99a63c8b-5fd6-4857-90cf-d39b3d7a7a61)**

So the question is why accessToken expired earlier than its expired time?
Also, AWSMobileClient sends notification user state SIGNED_IN instead of SIGNED_OUT_USER_POOLS_TOKENS_INVALID for invalid token. See below log

`[Wed Jan 29 15:44:11 CST 2020] ONELINK-LOG: AwsMobileClient: User state changed to SIGNED_IN`

**Expected behavior**
AwsMobileClient should not send Token expired: 1580337161 >= 1580336504 if received new token within 1 hr.

- Device: Android
- OS: 9.0

**Comment by TrekSoft** [comment]
Hey, could you post some code snippets of the code you're calling to get the access token and then send the request to AWS which is leading to the exception?
