### ISSUE TITLE
Always get wrong orientation

### ISSUE THREAD

**Issue by KunNiu** [aws-amplify/aws-sdk-android#1472]
**State your question**
When I tried the AWSKinesisVideoDemoApp, the streaming video in Kinesis Video Stream Console shows with wrong orientation. I tried to set many different values in method "withCameraOrientation()", but seems it doesn't work. 

**Which AWS Services are you utilizing?**
KinesisVideo
**Provide code snippets (if applicable)**
```
private AndroidCameraMediaSourceConfiguration getCurrentConfiguration() {
        return new AndroidCameraMediaSourceConfiguration(
                AndroidCameraMediaSourceConfiguration.builder()
                        .withCameraId(mCamerasDropdown.getSelectedItem().getCameraId())
                        .withEncodingMimeType(mMimeTypeDropdown.getSelectedItem().getMimeType())
                        .withHorizontalResolution(mResolutionDropdown.getSelectedItem().getWidth())
                        .withVerticalResolution(mResolutionDropdown.getSelectedItem().getHeight())
                        .withCameraFacing(mCamerasDropdown.getSelectedItem().getCameraFacing())
                        .withIsEncoderHardwareAccelerated(
                                mCamerasDropdown.getSelectedItem().isEndcoderHardwareAccelerated())
                        .withFrameRate(FRAMERATE_20)
                        .withRetentionPeriodInHours(RETENTION_PERIOD_48_HOURS)
                        .withEncodingBitRate(BITRATE_384_KBPS)
                        .withCameraOrientation(-mCamerasDropdown.getSelectedItem().getCameraOrientation())
                        .withNalAdaptationFlags(StreamInfo.NalAdaptationFlags.NAL_ADAPTATION_ANNEXB_CPD_AND_FRAME_NALS)
                        .withIsAbsoluteTimecode(false));
    }
```
**Environment(please complete the following information):**
 - SDK Version: 2.16.8

**Device Information (please complete the following information):**
 - Device: OnePlus 5T
 - Android Version: 9

Please help, thanks.

**Comment by KunNiu** [comment]
Hi team, any updates here?

**Comment by namaha-app** [comment]
We've been facing the same issue. @TrekSoft can you please help us out with this bug? 
Thanks!

**Comment by TrekSoft** [comment]
Thanks for the suggested similar bugs - we'll take a look at it as part of on call.

**Comment by kotaIwanaga** [comment]
I have been getting the same issue. Is there any workaround or updates?

**Comment by AlexKnyazyuk** [comment]
Galaxy S20, i have same issue for back and fron camera. Any updates?

**Comment by eeatonaws** [comment]
A fix for this issue was included in the PR [here](https://github.com/awslabs/aws-sdk-android-samples/pull/345).
