### ISSUE TITLE
How to start TransferService from another service?

### ISSUE THREAD

**Issue by andreydung** [aws-amplify/aws-sdk-android#1475]
**State your question**
I'm trying to start TransferService during the start of another Service. The app does not have UI, and is a system app.

I'm using `startForegroundService` as suggested, but still got the error of TransferNetworkHandler not being initialized.
```
TransferNetworkLossHandler is not created. Please call `TransferNetworkLossHandler.getInstance(Context)` to instantiate it before retrieving
TransferUtilityException: [com.amazonaws.mobileconnectors.s3.transferutility.TransferUtilityException: TransferNetworkLossHandler is not created. Please call `TransferNetworkLossHandler.getInstance(Context)` to instantiate it before retrieving]
```

**Which AWS Services are you utilizing?**
S3 Storage

**Provide code snippets (if applicable)**
```
        Intent tsIntent = new Intent(getApplicationContext(), TransferService.class);
        tsIntent.putExtra(TransferService.INTENT_KEY_NOTIFICATION, notification);
        tsIntent.putExtra(TransferService.INTENT_KEY_NOTIFICATION_ID, 1);
        tsIntent.putExtra(TransferService.INTENT_KEY_REMOVE_NOTIFICATION, true);
        getApplicationContext().startForegroundService(tsIntent);
```

**Environment(please complete the following information):**
 - SDK Version: 2.16.8

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: 9
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by raphkim** [comment]
Hi @andreydung ,

 I see that you are using an outdated version of AWS Android SDK. `TransferNetworkLossHandler` was introduced in SDK v2.11.0. I recommend that you update the SDK to latest version ([v2.16.8](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.16.8) at the time of writing). 

Please refer to the following [documentation](https://aws-amplify.github.io/docs/sdk/android/storage#supporting-transferservice-on-oreo-and-above) for more information and feel free to update this ticket if you encounter the same issue after updating the SDK.

**Comment by andreydung** [comment]
Hi @raphkim, thanks for the reply. There was a typo earlier on the aws sdk version. I updated to 2.16.8 and still having the same question.

**Comment by raphkim** [comment]
Hi @andreydung ,

I'm sorry that you are still experiencing this issue. Would you be able to verify the following information?:
- `notification` is a valid `Notification` object and was properly constructed prior to being packaged with `tsIntent`
- `TransferService` is properly enabled inside `AndroidManifest.xml` (see [documentation](https://aws-amplify.github.io/docs/sdk/android/storage#connect-to-your-backend))
- `startForegroundService(Intent)` method is indeed being called (especially before attempting to use `TransferUtility`). It just needs to be called once
- There is no conflicting notification ID
