### ISSUE TITLE
Get the right username

### ISSUE THREAD

**Issue by fxbeuvry-luna** [aws-amplify/aws-sdk-android#1476]
**State your question**
We are using AWS Mobile Client on iOS and Android. During the signup, we put in parameter for the userName a random UUID:
`AWSMobileClient.getInstance().signUp(userId, password, userIdentifierAttributes, emptyMap())`

After signup and login, on iOS, if I ask for `AWSMobileClient.getDefaultInstance().username`, the SDK returns the right UUID we put during signup. If I ask for `AWSMobileClient.getInstance().username` on Android, the SDK returns the last username used for a login (email or phonenumber).

Same SDK, 2 different behavior: maybe I miss something ? Should I parse the access token to have the right username ? I checked and it's ok in id and access token.

**Which AWS Services are you utilizing?**
com.amazonaws:aws-android-sdk-mobile-client:2.16.6

**Environment:**
 - SDK Version: 2.16.6

**Device Information:**
 - Device: OnePlus A5010
 - Android Version: 9.0.10

**Comment by raphkim** [comment]
Hi @fxbeuvry-luna 

Would you be able to clarify what is the use-case you are trying to achieve and provide a code snippet for both iOS and Android? 

The `username` returned should be the same one that was used for signup and signin in both cases. The `username` is ideally a unique identifier that is easily understandable by the user, so it is unusual that you are using UUID as one in the case of iOS (not that it isn't allowed). 

Perhaps you are confusing `username` of a signed user (the name that user uses to sign in) with `identityId` (the unique ID generated by Cognito per user)?
