### ISSUE TITLE
Pass clientMetaData to Cognito Triggers

### ISSUE THREAD

**Issue by royjit** [aws-amplify/aws-sdk-android#1493]
Add clientMetaData into the Auth apis.

Similar ticket in iOS - https://github.com/aws-amplify/aws-sdk-ios/issues/2299

**Comment by Skyfallz** [comment]
Hi @royjit,

as the iOS version seems [merged](https://github.com/aws-amplify/aws-sdk-ios/pull/2328), is it possible to get an update about the Android version ? Not passing metadata is blocking for implementing properly Custom Auth Workflows.

Thanks,

**Comment by Skyfallz** [comment]
Hi,

any update @royjit ?

The iOS version was released, and we really need this on the Android version as well.

Thanks,

**Comment by tys-bradford-zava** [comment]
+1 this is also something our team would really need soon on the Android side to match what we have on our iOS app.

**Comment by mobileappconsultant** [comment]
This feature request was put in almost a week ago.. how far are we from it being implemented?

**Comment by pedroaiwin** [comment]
Hi @royjit,

As in the previous comments, our team need to add this feature to the Android project, since it is already implemented in iOS.

We have created a new issue [#2547](https://github.com/aws-amplify/aws-sdk-ios/issues/2547) on the iOS repository in order to add the clientMetaData parameter to the [resendSignUpCode](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ResendConfirmationCode.html) call, it is possible to take it into account for the android version?

Thanks

**Comment by hama0511** [comment]
We developed the web using amplify.

However, because the clientMetadata cannot be added in the signUp call in Android, we can no longer proceed with Android app development.

I'm so angry. All code we have developed regarding user authentication should be deleted.

I can't trust aws anymore.

**Comment by jpignata** [comment]
Heya @hama0511 -- this functionality was added to our signup APIs in https://github.com/aws-amplify/aws-sdk-android/pull/1547 butthis issue wasn't properly closed out. Are you encountering an issue trying to pass metadata to this method?

**Comment by jamesonwilliams** [comment]
Hi @hama0511! Sorry you're hitting a snag. As @jpignata mentions, I think we do have support for this. We'd like to work with you to resolve your problems, if we can. Feel free to join us on our Discord server to discuss: https://discord.gg/amplify. We're in #android-help.

**Comment by hama0511** [comment]
Sorry! I found it AWSMobileClient.
But not Amplify..
should I use AWSMobileClient instead amplify?

**Comment by jamesonwilliams** [comment]
@hama0511 Yes. For right now, I recommend to use `AWSMobileClient`. You can access it via the [escape hatch of the Amplify Auth category](https://docs.amplify.aws/lib/auth/escapehatch/q/platform/android).

```kotlin
val authPlugin = Amplify.Auth.getPlugin("awsCognitoAuthPlugin")
val mobileClient = authPlugin.escapeHatch as AWSMobileClient?
```

From there, you can pass a map of client metadata to:
1. [`signUp`](https://github.com/aws-amplify/aws-sdk-android/blob/291afc5a553698e0216faec89bb19053dda03f90/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L1897-L1911)
2. [`confirmSignUp`](https://github.com/aws-amplify/aws-sdk-android/blob/291afc5a553698e0216faec89bb19053dda03f90/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L2046-L2059)
3. [`signIn`](https://github.com/aws-amplify/aws-sdk-android/blob/291afc5a553698e0216faec89bb19053dda03f90/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L1132-L1137)
4. [`confirmSignIn`](https://github.com/aws-amplify/aws-sdk-android/blob/291afc5a553698e0216faec89bb19053dda03f90/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L1277-L1280)
5. [`resendSignUp`](https://github.com/aws-amplify/aws-sdk-android/blob/291afc5a553698e0216faec89bb19053dda03f90/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L2160-L2174)
6. [`forgotUserPassword`](https://github.com/aws-amplify/aws-sdk-android/blob/291afc5a553698e0216faec89bb19053dda03f90/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L2240-L2252)
7. [`confirmForgotPassword`](https://github.com/aws-amplify/aws-sdk-android/blob/291afc5a553698e0216faec89bb19053dda03f90/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L2334-L2348)
8. [`updateUserAttributes`](https://github.com/aws-amplify/aws-sdk-android/blob/291afc5a553698e0216faec89bb19053dda03f90/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L2521-L2533)
9. [`verifyUserAttribute`](https://github.com/aws-amplify/aws-sdk-android/blob/291afc5a553698e0216faec89bb19053dda03f90/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/AWSMobileClient.java#L2628-L2638)

**Comment by jamesonwilliams** [comment]
Closing #1493. We added support for this in https://github.com/aws-amplify/aws-sdk-android/pull/1547 and https://github.com/aws-amplify/aws-sdk-android/pull/1984.
