### ISSUE TITLE
Decryption fails for default encryption mode AES/CBC/PKCS5Padding when RSA keypair is used to encrypt symmetric key

### ISSUE THREAD

**Issue by SoMCUSDev** [aws-amplify/aws-sdk-android#15]
This issue exists from ancient times and prevents us from using sdk as a library and avoid patching it (as it's done now for 1.7.\* based code).

Problem is when S3 object is encrypted using default encryption method using this symmetric key algorithm (and in case of AWS SDK for Android it's RSA):

this is the fix for that particular problem:
src/com/amazonaws/services/s3/internal/crypto/EncryptionUtils.java:

Method:
    private static SecretKey getDecryptedSymmetricKey(byte[] encryptedSymmetricKeyBytes, EncryptionMaterials materials, Provider cryptoProvider) {

```
        byte[] decryptedSymmetricKeyBytes = cipher.doFinal(encryptedSymmetricKeyBytes);
```
-            // Here is where Amazon SDK hits us with bug. If RSA algorithm is used for encryption of symmetric key,
-            // it will skip leading zero bytes (1/256 chance for first byte in the key to be zero,
-            // 1/65536 for second to be zero, etc. We should restore it or we won't be able
-            // to decrypt the key and hence the file itself
-            // http://www.bouncycastle.org/wiki/display/JA1/Frequently+Asked+Questions#FrequentlyAskedQuestions-4.WhenIencryptsomethingwithRSAIamlosingleadingzerobytesoffmydata,whyareyouguysshippingsuchabrokenimplementation?
-            int shift = 32 - decryptedSymmetricKeyBytes.length;
-            if (shift > 0) {
-                byte[] recoveredDecryptedSymmetricKeyBytes = new byte[32];
-                for (int i = shift; i < 32; i++) {
-                    recoveredDecryptedSymmetricKeyBytes[i] = decryptedSymmetricKeyBytes[i - shift];
-                }
-                decryptedSymmetricKeyBytes = recoveredDecryptedSymmetricKeyBytes;
-            }
          return new SecretKeySpec(decryptedSymmetricKeyBytes, JceEncryptionConstants.SYMMETRIC_KEY_ALGORITHM);

The same fix should be done in AWS JAVA SDK: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/crypto/EncryptionUtils.java

**Comment by AnakSultan99** [comment]
Hc 

Decryption failed, incompatible encryption method or algorithm.
