### ISSUE TITLE
DB table modified in offline is not updated locally until devices goes online.

### ISSUE THREAD

**Issue by iKrishneel** [aws-amplify/aws-sdk-android#1517]
**State your question**
I am using both online and offline capabilities. The online works flawlessly but when I try to create and update table entries offline the updates are not shown until the device is online again. In my application, each entry must have a `unique sequential id ` (the id)  but so far when the device is offline the query to obtain the updated `id` always returns the same value of the `id` which is the value obtained when the device was last online. Hence when the device goes online, all except the first offline entries are rejected due to conflicting `id`. 

Upon further investigation, I realized that the problem is that all CRUD operations offline are not recorded nor accessible until the device is online again. 

**Which AWS Services are you utilizing?**
Amplify with android frontend

**Provide code snippets (if applicable)**

```java
// first step create data
CreateItemMutation itemMutation = CreateItemMutation.builder()
                .input(itemInput)
                .build();

client.mutate(itemMutation)
                .enqueue(new GraphQLCall.Callback<CreateItemMutation.Data>() {
                    @Override
                    public void onResponse(@Nonnull com.apollographql.apollo.api.Response<CreateItemMutation.Data> response) {
                        Log.w("PLUS", "Item added: + " + response.data().toString());
                    }

                    @Override
                    public void onFailure(@Nonnull ApolloException e) {
                        Log.e("PLUS", "FAILED: " + e.getMessage());
                    }
                });


```

```java
// create query
client.query(query)
.responseFetcher(AppSyncResponseFetchers.CACHE_ONLY)
.enqueue(new GraphQLCall.Callback<ListItemQuery.Data>() {
        @Override
        public void onResponse(@Nonnull Response<ListItemQuery.Data> response) {
            runOnUiThread(() -> {
                Log.d("PLUS", "Offline Response:  " + response.data());
                try {
                    ListItemQuery.Data data = response.data();
                } catch (NullPointerException ignored) {

                }
            });
        }

        @Override
        public void onFailure(@Nonnull ApolloException e) {
            runOnUiThread(() -> {
                Log.e("PLUS", "Exception: " + e.getMessage());
            });
        }
    };);

```
1. The response is `null` until the device is online again. 
2. When I print the list of items in the local memory it only shows the items that were there when the device was last online.  

**Environment(please complete the following information):**
 - SDK Version: 28 / `Java 1.8`
**Device Information (please complete the following information):**
 - Device:  Samsung s9 device and Pixel XL Simulator
 - Android Version:  P

I have gone over the documentation but cannot make it work. Did I miss something? How to I keep the database locally up-to-date with user activity in offline?

**Comment by jamesonwilliams** [comment]
Moved to the AppSync issues. https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/267
