### ISSUE TITLE
MQTT client library for Android version 6 and below

### ISSUE THREAD

**Issue by afizboltz** [aws-amplify/aws-sdk-android#1530]
**Which AWS Services is the feature request for?**
aws-android-sdk-iot

**Is your feature request related to a problem? Please describe.**
- for android version 6 and below, the app always crash whenever start running the MQTT.
- eclipse/paho.mqtt.java library didn't support Android version 6 and below.

**Describe the solution you'd like**
- change dependency of MQTT from using eclipse/paho.mqtt.java to Pitel/paho.mqtt.java
- if you have other the solution for this issue then okay

**Additional context**
- this link will show the issue has been solved by pitel
https://github.com/Pitel/paho.mqtt.java/commit/27eebcb3b8a48c10d03f09e45eac6bd3cbf38ff2

**Comment by jpignata** [comment]
Thanks @afizboltz. We're discussing this internally and tracking via https://github.com/aws-amplify/aws-sdk-android/issues/1259.
