### ISSUE TITLE
The Android IoT SDK disconnects when a message arrives on a get/accepted topic.

### ISSUE THREAD

**Issue by jarvis32123** [aws-amplify/aws-sdk-android#1539]
This wasn't happening until recently but I get a "connection is Lost" message from mqtt after I push a "get" on a topic. It says "message arrived on topic: [my-topic]" but then the connection is lost. mqtt then reconnects. However, this keeps happening sort of in a loop. This is because I get a topic when mqtt connects. So one causes the connection lost and then it reconnects, gets again and once more connection is lost.

Has something changed here in mqtt? Maybe some backend settings?

**Comment by desokroshan** [comment]
@jarvis32123 Thanks for reaching out. I am unable to reproduce this on the latest version of the SDK. I tried the following to reproduce the issue :
 
* connect client to the broker
* subscribe to `$aws/things/<thingName>/get/accepted` and `$aws/things/<thingName>/get/rejected`
* publish an empty message to `$aws/things/<thingName>/get`

I get state information on the `$aws/things/<thingName>/get/accepted` and the device remains connected. 

<img width="391" alt="Screen Shot 2020-04-24 at 12 46 02 AM" src="https://user-images.githubusercontent.com/4340938/80187749-06f51d00-85c5-11ea-8818-25390d2a897a.png">


Can you please provide the following : 

* Additional steps, if any, required to reproduce the issue
* Version of SDK that you are using. It looks like you are using an antiquated version(2.2.13) of the SDK. I would suggest updating to the latest version 2.16.11 of the SDK and check if the issue persists
* You mentioned that you see loss of connection in `AWSIotMqttNewMessageCallback().onMessageArrived()`. Can you possiblly share the stack trace?

**Comment by RoustamManookian** [comment]
The solution is "Coroutines"
