### ISSUE TITLE
Error connecting to DynamoDb Table from Android app

### ISSUE THREAD

**Issue by abhidaa1233** [aws-amplify/aws-sdk-android#1549]
Cannot connect to DynamoDb Table, I have set admin access in the policy, set the correct region, checked lot of time Table name exists. I am using Android Sdk 2.0 and could not find any latest docs specifically for dynamoDb for Android. So somehow took some ideas from Java sdk, some from unknown old blogs and some from old mobile hub. 

I am relatively new in Aws, please do correct me if I'm doin anything wrong and it would be helpful if any Latest link of documentation for performing CRUD operations programmatically for Android for DynamoDb is shared.
I'm using Document for inserting and reading. The line it gives error is where 

            databaseTable = Table.loadTable(databaseClient, "tableName");
           
 
gives error:
 com.amazonaws.services.dynamodbv2.model.ResourceNotFoundException: Requested resource not found: Table: tableName not found (Service: AmazonDynamoDB; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: ........)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:5257)
        at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.describeTable(AmazonDynamoDBClient.java:1613)
        at com.amazonaws.mobileconnectors.dynamodbv2.document.Table.loadTableDescription(Table.java:124)
        at com.amazonaws.mobileconnectors.dynamodbv2.document.Table.loadTable(Table.java:110)
        at com.example.myawsapp.MyActivity$2.run(MyActivity.java:197)
        at java.lang.Thread.run(Thread.java:764)

Before the Line that gives error:
` dbClient = new AmazonDynamoDBClient(AWSMobileClient.getInstance());`

In place of the above AWSMobileClient.getInstance argument I have tried  giving credentialsProvider which I initialized by:

 ```
// Initialize the Amazon Cognito credentials provider
            CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
                    getApplicationContext(),
                    "My identity pool", // Identity pool ID
                    Regions.AP_SOUTH_1 // Region
            );
```
giving same results

**Comment by jpignata** [comment]
Feel free to reply to my email if you need additional help.

**Comment by abhidaa1233** [comment]
Sorry to bother u again Sir,  I have one query that in user pool I have
added a custom attribute but I have tried everything but cannot add or get
to it, I have aslo set the proper read and write access, By using the below
code I am able to get the main attributes like email, emial_verified etc, I
am also using proper "custom:name" prefix to check for the key., using
Android sdk 2.0
  Map<String, String> map =AWSMobileClient.getInstance
().getUserAttributes();
for (Map.Entry<String, String> entry : map.entrySet()) {
    key = entry.getKey();
    value = entry.getValue();
}
Any help would be great

**Comment by abhidaa1233** [comment]
Thanx a lot @jpignata
