### ISSUE TITLE
MqttException (0) - java.io.IOException: Already connected

### ISSUE THREAD

**Issue by cmbaykal** [aws-amplify/aws-sdk-android#1550]
**Describe the bug**
I'am using android sdk. When I want to make a custom authorization with mqtt it says you are "Already connected". And I can see the connection in the logs but after 1 second it kicks me out. And there is no proper sample app for custom authorization.

**To Reproduce**
A code sample or steps:
I am using the Amplify pubsub tutorials code

**Which AWS service(s) are affected?**

**Expected behavior**
In iOS there is no connection error in same method but when we try in the Android platform it says already connected.

**Screenshots**
`https://imgur.com/G29NjHR`

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [e.g. 2.6.25]
 - Device: Samsung S10E , Nexus 5
 - Android Version: Android 10 , Android 7.1
 - Specific to simulators: No

**Comment by jpignata** [comment]
Thanks, @cmbaykal. Can you share the same code you've written so we can look at this?

**Comment by cmbaykal** [comment]
try {
            String clientId = MqttAsyncClient.generateClientId();

            AWSIotMqttManager manager = new AWSIotMqttManager(clientId, Region.getRegion(Regions.US_EAST_1), "a3p843671svo75-ats");

            manager.setCleanSession(true);
            manager.setAutoReconnect(true);
            manager.setKeepAlive(60);

            AccessTokenHelper helper = new AccessTokenHelper(TokenHelper.accessToken);

            String tokenKeyName = "token-name";
            String token = "token-access";
            String tokenSignature = "signature";
            String customAuthorizerName = "token-authorizer";

            manager.connect(
                    tokenKeyName,
                    token,
                    tokenSignature,
                    customAuthorizerName,
                    (status, throwable) -> {
                        Log.d("AWSTest", "Status = " + status);
                        activity.runOnUiThread(() -> {
                            if (throwable != null) {
                                Log.e("AWSTest", "Connection error.", throwable);
                            }
                        });
                    });
        } catch (final Exception e) {
            Log.e("AWSTest", "Connection error.", e);
        }

**Comment by jpignata** [comment]
Using the example code you provided, I'm able to reproduce this.

**Comment by jpignata** [comment]
It looks like Paho returns "Already connected" on a connection error due to authorization under WebSockets (see https://github.com/eclipse/paho.mqtt.java/issues/481). If you don't have a Policy Document that allows your connection to subscribe to topics, that's the result you get. I was able to get this working with the following (much-too-wide, not-following-the-principle-of-least-privilege) Policy Document:

```console
$ aws iot test-invoke-authorizer --authorizer-name [AuthorizerName] --token [TokenName] --token-signature [Signature]
```
```json
{
    "isAuthenticated": true,
    "principalId": "user",
    "policyDocuments": [
        "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Action\":\"iot:*\",\"Effect\":\"Allow\",\"Resource\":\"arn:aws:iot:us-east-1:012345678912:*\"}]}"
    ],
    "refreshAfterInSeconds": 300,
    "disconnectAfterInSeconds": 86400
}
```

Let me know if this resolves your issue. I'll provide some feedback on the IoT docs around this, and we'll work with the Paho project to see if we can help resolve that ubg.

**Comment by cmbaykal** [comment]
Sorry for the late reply. I tried the aws command to test my connection informations. It response my informations is okay. But when I try to connect on android mobile sdk it says "Already connected".  And I can see the login attempt and given permissions in the dashboard.

**Comment by AngelHadzhiev** [comment]
@jpignata hey, I have the same issue with AWS and Android but I do have policies attached. I wonder if you know how this can be solved?

**Comment by kartic-techindustan** [comment]
@cmbaykal @jpignata 

```
String tokenKeyName = "token-name";
String token = "token-access";
String tokenSignature = "signature";
String customAuthorizerName = "token-authorizer";
```
I have all except "token". How do i get this ?

**Comment by ShankarKakumani** [comment]
@kartic-techindustan, I also have same issue, 

did you found any solution?
