### ISSUE TITLE
Cannot get custom attributes from user pools

### ISSUE THREAD

**Issue by abhidaa1233** [aws-amplify/aws-sdk-android#1563]
In user pool I have added a custom attribute but I have tried everything but cannot add or get to it, I have aslo set the proper read and write access needed, I am also using proper "custom:name" prefix to check for the key., using Android sdk 2.0. By using the below code I am able to get the main attributes like email, emial_verified etc,
```
  Map<String, String> map = AWSMobileClient.getInstance().getUserAttributes(); 
  
  for (Map.Entry<String, String> entry : map.entrySet()) { 
      key = entry.getKey();
      value = entry.getValue();
     }
```
Any help would be great

**Comment by jpignata** [comment]
Have you verified the user has a custom attribute set to be returned in the above call?

**Comment by abhidaa1233** [comment]
Initially when the user logs in for the first time its not set, but the user sets it so that next time it can be retrieved but I cannot see anything, I am using hosted UI, below to put into custom attribute:
```
 final Map<String, String> attributes = new HashMap<>();
 attributes.put("custom:Name", editText.getText().toString());
```

**Comment by alanlee-gn** [comment]
I'm also trying to get existing custom attributes from Congnito User Pool but I do not see it using `AWSMobileClient.getInstance().getUserAttributes()`.

**Comment by alanlee-gn** [comment]
FYI. I just had a similar problem but just realized that the attribute read permission was not set for the app I was using. Modifying the permission fixed the issue for me.

**Comment by abhidaa1233** [comment]
@alanlee-gn bro how did u update the attributes after puttin them? 
My code didn't work:

                    try {
                            AWSMobileClient.getInstance().updateUserAttributes(attributes);
                        } catch (Exception e) {
                            e.printStackTrace();
                        }

**Comment by alanleedev** [comment]
@abhidaa1233 Sorry. I'm only reading from my mobile app so haven't tried updating.

**Comment by alanlee-gn** [comment]
@abhidaa1233 Sorry. I have a different use case. I'm only reading the custom attribute from the mobile app and have no need to update.

**Comment by eeatonaws** [comment]
Hi. It has been quite some time since this issue was last updated. @abhidaa1233 could you please let us know if you are still facing the issue with the latest version of the SDK?

**Comment by poojamat** [comment]
Closing the issue due to lack of response, please reopen it if its still an issue.
