### ISSUE TITLE
federatedSignIn is unacceptably slow

### ISSUE THREAD

**Issue by maxflores** [aws-amplify/aws-sdk-android#1566]
**Describe the bug**
A successful call to federatedSignIn regularly takes anywhere from 1500 to 2000 ms (this is not an internet problem other network calls e.g. to my server hosted on ec2 take 200ms).

**To Reproduce**
A code sample or steps:
```
// I used the Facebook version shown here:
// https://aws-amplify.github.io/docs/sdk/android/authentication#federated-sign-in
```

**Which AWS service(s) are affected?**
AwsMobileClient with Cognito

**Expected behavior**
A successful call should take a few hundred ms tops.

**Screenshots**

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.16.11
 - Device: OnePlus 5T
 - Android Version: OxygenOS 9.0.11
 - Specific to simulators: No

**Additional context**

**Comment by jpignata** [comment]
Heya @maxflores! Thanks for the report. Can you tell me a little more? What is your use-case and how is  this infrequent action's response time causing an issue for you? Why do you think it should take a few hundred milliseconds, and what is the impact of the action taking longer?

**Comment by maxflores** [comment]
Hi @jpignata! Thanks for a quick reply. My use-case is a mobile app sign in screen which I would like the app to be snappy. With the FB login (400ms) + federatedSignIn (2000ms) + my server login api (300ms) the total time for sign in is approximately 3 seconds after clicking the button. This is not a good impression each time the app is opened reducing confidence in the technology, especially as a developer knowing that login could happen much more quickly.

I understand the federatedSignIn has to make a few calls internally but I would expect all of these to be colocated and on the order of 10s of ms each.

**Comment by jpignata** [comment]
Thanks. We can certainly inquire with the service team, but my hunch is that this is in the ballpark of the expected latency of that endpoint and there's not much we'll be able to do on the SDK side to help.

**Comment by jpignata** [comment]
Under the hood, this method is calling `CognitoCachingCredentialsProvider`, which uses the [basic authentication flow](https://docs.aws.amazon.com/cognito/latest/developerguide/authentication-flow.html) to return temporary credentials from AWS Security Token Service (STS). Several of the calls are external.

**Comment by maxflores** [comment]
@jpignata, I tried using CognitoCachingCredentialsProvider directly and found it to be a bit snappier than AwsMobileClient especially when calling getCredentials after the first time (i.e. when the previous credentials are still valid).

I'm not sure if AwsMobileClient is providing additional functionality. I prefer the cleaner interface, syntax, and paradigm of AwsMobileClient but it seems to spend on the order of hundreds of milliseconds extra for various calls (both network and non network calls).

Since the basic authentication flow will take a decent amount of time, I plan to use the CognitoCachingCredentialsProvider directly.

**Comment by jpignata** [comment]
Gotcha. That makes sense. It's unlikely we'll spend time here right now, but stay tuned for our Amplify Library Auth category. Thanks!
