### ISSUE TITLE
Please update Bouncy Castle

### ISSUE THREAD

**Issue by Neustradamus** [aws-amplify/aws-sdk-android#1568]
Please update Bouncy Castle
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by raphkim** [comment]
Hi @Neustradamus ,

Thank you for taking your time to reach out to us. [Client-side encryption in S3](https://aws-amplify.github.io/aws-sdk-android/docs/reference/) that originally relied on bouncy castle was deprecated in favor of server-side encryption, and our SDK should not expose any of the mentioned vulnerabilities. 

If you have further concerns, please feel free to re-open this ticket, or submit a new one.

**Comment by Neustradamus** [comment]
@raphkim: What is it?
- https://github.com/aws-amplify/aws-sdk-android/search?q=bouncycastle&unscoped_q=bouncycastle

**Comment by raphkim** [comment]
That dependency is scoped to tests, and therefore will be only available for test compilation/execution.

**Comment by Neustradamus** [comment]
@raphkim: Strange...
I do not understand why it is for test, it is one file not all.

**Comment by Neustradamus** [comment]
@raphkim: Can you update Bouncy Castle?

**Comment by jpignata** [comment]
@Neustradamus Thanks for raising! Can you explain the concern you have or what problem an older version of this dependency is causing for you?

**Comment by Neustradamus** [comment]
@jpignata: Better to be up-to-date, it is a security and important lib...

**Comment by jpignata** [comment]
Hm, I'm not sure this effectively makes a difference as this dependency isn't used on this project. We'll just remove it. See https://github.com/aws-amplify/aws-sdk-android/pull/1606.

**Comment by Neustradamus** [comment]
@jpignata: Thanks but please remove all!
- https://github.com/aws-amplify/aws-sdk-android/issues/1568#issuecomment-613589270
