### ISSUE TITLE
Verify ability to update demographic data for pinpoint analytics client

### ISSUE THREAD

**Issue by wooj2** [aws-amplify/aws-sdk-android#1593]
We talked to the pinpoint team and it was discussed that we should not block customers from having custom pinpoint demographic data.

We have updated the iOS SDK framework to support this use case and we should verify that we have parity with android:

Related iOS tickets are here
https://github.com/aws-amplify/aws-sdk-ios/issues/2380
https://github.com/aws-amplify/aws-sdk-ios/pull/2410

**Comment by richardmcclellan** [comment]
Customizing the demographic data is supported by the Android SDK.  Here is some sample code to accomplish this:
```
PinpointConfiguration pinpointConfig = new PinpointConfiguration(
    applicationContext,
    AWSMobileClient.getInstance(),
    awsConfig);
pinpointManager = new PinpointManager(pinpointConfig);
EndpointProfileDemographic demographic = new EndpointProfileDemographic(pinpointManager.getPinpointContext());
demographic.setAppVersion("1.2.3.4.5.6");
demographic.setPlatform("MyCustomPlatform");
demographic.setModel("MyCustomDeviceModel");
EndpointProfile profile = new EndpointProfile(pinpointManager.getPinpointContext());
profile.setDemographic(demographic);
pinpointManager.getTargetingClient().updateEndpointProfile(profile);
```
