### ISSUE TITLE
Can't login with Facebook on Android if account was created on iOS 

### ISSUE THREAD

**Issue by igorka48** [aws-amplify/aws-sdk-android#1656]
**Describe the bug**
Can't login with Facebook on Android if account was created on iOS 

**To Reproduce**
We have two identical native clients for Android and iOS. 
if user make fist login on iOS device, it will not be able to login on Android.
Only account manual deleting from User Pool helps.
It reproduces in 90% on Android. And in 30% on iOS. 

```
 val hostedUIOptions = HostedUIOptions.builder()
                .identityProvider("Facebook")
                .build()

val signInUIOptions = SignInUIOptions.builder()
                .hostedUIOptions(hostedUIOptions)
                .build()

awsClient.showSignIn(
                    (context as MyApplication).currentActivity,
                    signInUIOptions
                )

```
logcat:

_com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthInvalidGrantException: invalid_grant
        at com.amazonaws.mobileconnectors.cognitoauth.util.AuthHttpResponseParser.parseHttpResponse(AuthHttpResponseParser.java:67)
        at com.amazonaws.mobileconnectors.cognitoauth.AuthClient$1.run(AuthClient.java:323)
        at java.lang.Thread.run(Thread.java:919)_

**Which AWS service(s) are affected?**
Cognito

**Expected behavior**
Android users must have ability to log into accounts created with iOS SDK. 

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.16.11 - 2.16.12
 - Device: Pixel 3, Pixel 3XL, Sumsungs, Emulators
 - Android Version: all from 7.1 to 10
 - Specific to simulators: No

**Comment by royjit** [comment]
Hi @igorka48 

I could not reproduce the issue, I setup two native apps for both platforms and tried to login in iOS first and then in android. I was able to login in both cases. As per this [doc](https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html) : 
```
invalid_grant
Refresh token has been revoked.

Authorization code has been consumed already or does not exist.
```
How is your userpool setup? Does iOS and Android has the same app client ids?
Also, is your redirect uri in iOS and Android awsconfiguration.json same?
