### ISSUE TITLE
How to do Fb login with disableFederation(false)?

### ISSUE THREAD

**Issue by igorka48** [aws-amplify/aws-sdk-android#1657]
**State your question**
How to do Login with Facebook with disableFederation(false) option?

**Which AWS Services are you utilizing?**
Cognito

**Provide code snippets (if applicable)**
```
 // For Facebook
            val hostedUIOptions = HostedUIOptions.builder()
                .identityProvider("Facebook")
                .disableFederation(false)
                .build()

            val signInUIOptions = SignInUIOptions.builder()
                .hostedUIOptions(hostedUIOptions)
                .build()

 awsClient.addUserStateListener(userStateListener)

val  userStateDetails = awsClient.showSignIn(
                    (context as MyApplication).currentActivity,
                    signInUIOptions
                )
```

With my code userStateDetails has state SIGNED_OUT
and userStateListener newer fires

Without disableFederation(false) option everything works almost good

**Comment by gpanshu** [comment]
Hi @igorka48 what is it that you are trying to accomplish here? Can you elaborate please?
