### ISSUE TITLE
AWS XR (AR/VR) with Android 

### ISSUE THREAD

**Issue by p3420a1** [aws-amplify/aws-sdk-android#1666]
Any pointers on how to implement AR/VR category in Android Application

AWS Amplify XR

 - SDK Version: [e.g. 2.6.25]

Device Information
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Pie 9]

**Comment by jamesonwilliams** [comment]
Closing as dupe of https://github.com/aws-amplify/amplify-android/issues/410 ; keeping Amplify Android version which contains the "category" metaphor.
