### ISSUE TITLE
UnsupportedOperationException while creating Lamda service 

### ISSUE THREAD

**Issue by ksivaji** [aws-amplify/aws-sdk-android#1667]
**Describe the bug**
`UnsupportedOperationException` been thrown while creating Lamda service . The complete exception messgae is `Method threw 'java.lang.UnsupportedOperationException' exception. Cannot evaluate $Proxy2.toString()`

**To Reproduce**
A code sample or steps:
```
interface AwsLambdaService {

 @LambdaFunction(functionName = "get_devices")
    fun getDevices(request: String) : JsonObject
  
}


// Create an instance of CognitoCachingCredentialsProvider
       val credentialsProvider = CognitoCachingCredentialsProvider(
                      application.applicationContext,
                     "XXXXXXXXX", // this is our project identityPoolId
                     Regions.US_EAST_1
                    )

// Create a LambdaInvokerFactory, to be used to instantiate the Lambda proxy

                    val factory = LambdaInvokerFactory.builder()
                        .credentialsProvider(credentialsProvider)
                        .context(application.applicationContext)
                        .region(Regions.US_EAST_1)
                        .build()!!

          val service = factory.build(AwsLambdaService::class.java)
The above build() method throws the exception with message `Method threw 'java.lang.UnsupportedOperationException' exception. Cannot evaluate $Proxy2.toString()`
```

**Which AWS service(s) are affected?**
`Aws Lambda serice`
**Expected behavior**
 The service object should be created with out any exception

**Screenshots**

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.6.12
 - Device:  Simulator
 - Android Version: Android 10
 - Specific to simulators: No

**Additional context**

**Comment by ksivaji** [comment]
@desokroshan , please let me know if it is reproducible at your end and also let me know if  any more info needed from me

**Comment by ksivaji** [comment]
@desokroshan Please let me know if there is any update on this issue.

**Comment by eeatonaws** [comment]
Using the code you provided, I only observe the error when debugging the app but not when running the app. Are you seeing the error when running the app or only when debugging the app? If you are using Android Studio, you can fix the error when debugging the app by right clicking on the service variable in the debugger and selecting “View as” and then “Object”. This will display the variable in the debugger as an object rather than trying to use its `toString()` method, which in this case isn’t supported.
