### ISSUE TITLE
Unable to retrieve status of sessionPersisted for MQTT connections

### ISSUE THREAD

**Issue by ldetmer** [aws-amplify/aws-sdk-android#1686]
**Which AWS Services is the feature request for?**
IoT

**Is your feature request related to a problem? Please describe.**
Right now it looks like the SDK MQTT is ignoring the `cleanSession` attribute. (If I set it to false it seems like it's still creating a new session. but I can't prove/deny this without seeing if the session is new in the connect response.)

**Describe the solution you'd like**
I would like to update the `AWSIotMqttManager` to include `getSessionPersisted()` which would return default value false and the value would get updated on a successful connection to the value of 
`IMqttToken.getSessionPersisted()`.

**Describe alternatives you've considered**
I considered trying to figure out other ways to debug this issue, but in the end I still need to understand whether or not the session is persisted. If it's not persisted I need to publish on certain topics to retrieve messages that I may have missed while offline.

**Additional Context**
Specifics for MQTT persisted sessions: https://docs.aws.amazon.com/iot/latest/developerguide/mqtt-persistent-sessions.html

**Comment by jpignata** [comment]
Heya @ldetmer! Just to clarify: is the issue here that persistent session support isn't working for you, or are you requesting an attribute exposed to detect whether or not you're resuming a session?

**Comment by jpignata** [comment]
This was addressed in 2.19.3. Let us know how this works for you!
