### ISSUE TITLE
Change User Pool in Android Application

### ISSUE THREAD

**Issue by AnasMirza8630** [aws-amplify/aws-sdk-android#1739]
I used amplify Cognito to login and register the in android application. I created some user pools on the Aws console and now I want to change the user pool. I tried  to configure awsconfiguration.json file to change the key-values  like this:

`    "CognitoUserPool": {
        "Default": {
            "PoolId": "XXXXXXXXXXXXXwhRT",
            "AppClientId": "XXXXXXXXXXXXXXXXXXXXXXXX",
            "AppClientSecret": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
            "Region": "eu-XXXX-1"
        }
    },`

but after changing I am able to log in and register the new user pool but I am not getting the logging status true after logged in.
` AWSMobileClient.getInstance().isSignedIn()`
and when I run the command **amplify pull** all key has been changed automatically on the previous default user pool values.
So Is there any way to change the user pool in the android application,

**Amplify CLI Version**
4.18.1

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Node Version.12.16.3

Any help would be appreciated, 
Thanks

**Comment by FazalHussain** [comment]
Any update??

**Comment by desokroshan** [comment]
@AnasMirza8630 you can use `amplify update auth` to update the user pool configuration in the android application without having to update the configuration file manually.

**Comment by AnasMirza8630** [comment]
@desokroshan Thanks for your answer but this command is not working. In my case, they update the configuration of the same user pool. Could you please explain the process of update the user pool using this command?

**Comment by richardmcclellan** [comment]
> Could you please explain the process of update the user pool using this command?

The short answer is, use `amplify import auth`.   See this documentation for more details on how to [Use an existing Cognito User Pool and Identity Pool](https://docs.amplify.aws/cli/auth/import).
