### ISSUE TITLE
How to check if cognito user is confirmed?

### ISSUE THREAD

**Issue by markorakita** [aws-amplify/aws-sdk-android#1740]
**State your question**
As I've stated in #713, when you call AWSMobileClient.getInstance().forgotPassword() with username of unconfirmed user, it will throw InvalidParameterException instead of UserNotConfirmedException.

However, if you call AWSMobileClient.getInstance().forgotPassword() with username of confirmed user, who has changed her email but has not yet verified it, it will throw the same InvalidParameterException as in the case of unconfirmed user.

How can we differentiate between those two cases? In other words, how to know if user is confirmed? When AWSMobileClient.getInstance().forgotPassword() is called, user is not signed in, so we can't get user attributes.

My current hacky solution is to try to call AWSMobileClient.getInstance().signIn() with that username and some dummy password, and then figure it out depending on exception being thrown. In case of unconfirmed user it will throw UserNotConfirmedException (currently different because of bug #1721), and in case of confirmed user with unverified email it will throw NotAuthorizedException.

But this seems pretty hacky and unnecessary, it would be nice if there was some easier way to distinct between those two cases.

**Which AWS Services are you utilizing?**
Cognito

**SDK Version:**
2.16.9

**Comment by poojamat** [comment]
Here is a response from cognito team, which might help you: https://github.com/aws/aws-aspnet-cognito-identity-provider/issues/179#issuecomment-871051383
