### ISSUE TITLE
Cognito SAML Sign Out Failure

### ISSUE THREAD

**Issue by doc-rj-celltrak** [aws-amplify/aws-sdk-android#1746]
**Describe the bug**

After signing in successfully to a SAML IdP through showSignIn() with hosted UI... When trying to signOut() with the IdP sign out flow, the sign out completes successfully, but we get a failure in the custom browser tab for the hosted UI, and the redirect doesn't complete so the user is then stuck in the browser.

It looks like there are a couple of http 400 errors. The screenshots are below and HAR trace is attached here: 
[celltrakmobiletest2.auth.us-east-1.amazoncognito.com.har.zip](https://github.com/aws-amplify/aws-sdk-android/files/4637377/celltrakmobiletest2.auth.us-east-1.amazoncognito.com.har.zip)

The problem may not be in the mobile SDK, but this is the place to start as we're initiating the sign out through the SDK.

**To Reproduce**

Sign in:

```
   val hostedUIOptions: HostedUIOptions = if (providerName.isEmpty()) HostedUIOptions.builder().build() else
      HostedUIOptions.builder().identityProvider(providerName).build()
    val signInUIOptions: SignInUIOptions = SignInUIOptions.builder().hostedUIOptions(hostedUIOptions).build()

    AWSMobileClient.getInstance().showSignIn(this.activity, signInUIOptions, object : Callback<UserStateDetails> { ...
```

Sign out:

isInvalidateTokens = true and isSignOutGlobally = false...

```
    val signOutOptions: SignOutOptions = SignOutOptions.builder()
            .invalidateTokens(isInvalidateTokens)
            .signOutGlobally(isSignOutGlobally)
            .build()

    AWSMobileClient.getInstance().signOut(signOutOptions, object : Callback<Void> { ...
```

**Which AWS service(s) are affected?**

Cognito

**Expected behavior**

The browser page error should not happen, and the user should be redirected back from the custom browser tab to the app.

**Screenshots**

![Screenshot_1589560893](https://user-images.githubusercontent.com/55109813/82101896-67aedb80-96d3-11ea-9995-4c894320e7bc.png)

![Screen Shot 2020-05-15 at 11 40 51 AM](https://user-images.githubusercontent.com/55109813/82101935-87460400-96d3-11ea-94e8-e03a61bd3b3d.png)

<img width="517" alt="Screen Shot 2020-05-15 at 5 36 20 PM" src="https://user-images.githubusercontent.com/55109813/82101937-8ad98b00-96d3-11ea-982a-b347d4564e81.png">

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.16.8
    implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.16.8'
    implementation 'com.amazonaws:aws-android-sdk-cognitoauth:2.16.8'
 - Device: Pixel 3a hardware, also Pixel 3 emulator
 - Android Version: 10
 - Specific to simulators: No

**Additional context**

IdP sign out flow is enabled in the Cognito SAML IdP options.

SAML IdP metadata here: https://consumerdirectb2ctest.b2clogin.com/consumerdirectb2ctest.onmicrosoft.com/B2C_1A_signup_signin_saml/Samlp/metadata

**Comment by janmiderback** [comment]
@doc-rj-celltrak Facing a similar problem now in our Android app, using the Amplify libraries.
Did you have any success with this?
Cheers

**Comment by doc-rj-celltrak** [comment]
Hi @janmiderback, yes we were able to get past this issue. The problem was a basic SAML incompatibility between AWS and Microsoft defaults. We had to create and host our own SAML SP metadata file in order to signal the correct bindings. Here is an explanation I wrote to our AWS support person:

"I have some good news for this issue. I think the problem was an incompatibility between AWS and Microsoft Azure B2C regarding the SAML protocol and the logout endpoint.

The AWS logout endpoint uses HTTP Post binding. However, HTTP Redirect (not Post) is the binding that Microsoft assumes for the logout endpoint. MS docs here: https://docs.microsoft.com/en-us/azure/active-directory-b2c/connect-with-saml-service-providers#4-setup-application-in-the-azure-ad-b2c-directory 

AWS doesn't provide SAML SP metadata for us (as it probably should), so there is no place to specify that HTTP Post binding should be used by Microsoft for the logout endpoint.

However, we decided to provide SAML SP metadata for ourselves, because it is needed for this and also for full security with encrypted messages. Our SP metadata is hosted in an S3 bucket: https://public-cognito-saml-sp.s3.amazonaws.com/saml_sp_metadata_us-east-1_Vu6ccYQri 

Now that we specify HTTP Post binding in the SP metadata for the logout endpoint, the logout seems to be working well as expected."

===

In order to create the SAML SP metadata XML, we started with this tool: https://www.samltool.com/sp_metadata.php

**Comment by janmiderback** [comment]
Thank you very much @doc-rj-celltrak!
We will check this and try out.

**Comment by janmiderback** [comment]
Hello @doc-rj-celltrak. Still facing some problems with this.

If understand this correctly, you are using your own SAML SP metadata (the one in the S3 bucket) and use that one to configure the app in Azure AD.

I have done the same thing in our Azure AD that comes with our Office 365 subscription and it seems as if I can upload the metadata and the logout endpoint looks correct, but the POST does not become effective and I cannot find a way to really tell if the configuration is correct. I still see the error page from Cognito Hosted UI.

I fully understand if you cannot spend time answering this, but if you have any further hints it would be great.

**Comment by rjuliano** [comment]
Possibly related to https://github.com/aws-amplify/amplify-android/issues/1432, which is being investigated by the service team

**Comment by div5yesh** [comment]
The logout url is missing the required query params which is the reason in HAR its response is 400. This shouldn't happen if the logout url was not overridden either in code or in config. 

Regarding SAML metadata, since the SP does not have enough information about IdP endpoints and attribute mappings, please use the metadata provided by the IdP instead of generating one manually.

@janmiderback To test if the config is correct, launch the hostedUI from cognito console and test out the signin and signout flows. Please refer to this [post](https://aws.amazon.com/blogs/security/how-to-set-up-amazon-cognito-for-federated-authentication-using-azure-ad/), to setup Azure AD with Cognito correctly.

Note: The steps in above post uses `aws cli` but cognito console can also be used.

**Comment by div5yesh** [comment]
Closing this issue since the original question was answered and this issue has been inactive for some time. Please create a new issue if you have additional questions.
