### ISSUE TITLE
Federated sign-in: getUserAttributes requires aws.cognito.signin.user.admin scope

### ISSUE THREAD

**Issue by RandomEngy** [aws-amplify/aws-sdk-android#1747]
When you are using Federated sign in (in my case with Google), calling getUserAttributes throws a NotAuthorizedException.

**To Reproduce**
1) Create a user pool with Google enabled for federated sign in.
2) Initialize options:

```
val hostedUIOptions: HostedUIOptions = HostedUIOptions.builder()
    .scopes("openid", "email", "profile")
    .build()
val signInUIOptions: SignInUIOptions = SignInUIOptions.builder()
    .hostedUIOptions(hostedUIOptions)
    .build()
```

3) Call showSignIn() with options
4) Call `AWSMobileClient.getInstance().userAttributes` (Kotlin)

**Expected result**:
We get user attributes.

**Actual result**:
NotAuthorizedException is thrown.

I need to add the "aws.cognito.signin.user.admin" scope to get these. But according to [the docs](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-idp-settings.html), this scope shouldn't be needed to access that information. This is giving admin permissions to the user pool, which includes modifying attributes. It says "The profile scope grants access to all user attributes that are readable by the client." So that seems like that should be sufficient.

**Which AWS service(s) are affected?**
Cognito

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.16.12
 - Device: Nexus 6
 - Android Version: 7.1.1
 - Specific to simulators: No

**Comment by TrekSoft** [comment]
Closing in favor of your other ticket

**Comment by TrekSoft** [comment]
The specific question here of why can't openid + profile scopes give read only access to attributes is unique so reopening this. If other users are also having this issue, please +1 so we can prioritize appropriately.

**Comment by RandomEngy** [comment]
In my app I'm planning on doing auth through federation and I'm not going to have spots to edit your name, email, etc. I thought it would be good to follow the [Principle of Least Privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege) here. If someone got their hands on some access tokens there's less damage they can do.

**Comment by TrekSoft** [comment]
Got it - I'll leave the ticket open here for others to comment/+1 and will prioritize it accordingly in our backlog.

**Comment by RandomEngy** [comment]
Cool. Should probably update the labels on the issue, then?

**Comment by satishnalla** [comment]
+1, we also are having similar issue for social federated login ...we require solution considering security point of view

**Comment by eeatonaws** [comment]
`AWSMobileClient.getInstance().getUserAttributes()` calls the Cognito GetUser API, which requires an access token. The `aws.cognito.signin.user.admin` scope grants access to Cognito APIs requiring access tokens, including GetUser (please see [Cognito documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-app-idp-settings.html)). The `email`, `openid`, and `profile` scopes are not enough to be able to call Cognito’s GetUser API, thus resulting in a NotAuthorizedException without the `aws.cognito.signin.user.admin` scope. Besides adding the `aws.cognito.signin.user.admin` scope to the HostedUIOptions scopes, an alternative way to get the user attributes, if you added the `profile` scope, is to retrieve them from the ID token after the user has signed in. An example in Java is below:
```
Tokens userTokens = AWSMobileClient.getInstance().getTokens();
Token idToken = userTokens.getIdToken();
// Check for name attribute
boolean nameAttributeSet = CognitoJWTParser.hasClaim(idToken.getTokenString(), “name”);
if (nameAttributeSet) {
    // Get name attribute
    String nameAttribute = idToken.getClaim(“name”);
}
```

**Comment by RandomEngy** [comment]
This did the trick, thank you!
