### ISSUE TITLE
How can I use pagination in Android using AWS Amplify

### ISSUE THREAD

**Issue by sagarkhurana00786** [aws-amplify/aws-sdk-android#1755]
I want to use Pagination in with AWS amplify in android
How can I use that any guide or doc related to that
please help 
Thanks

**Comment by desokroshan** [comment]
@sagarkhurana00786 Can you provide the following information to enable to us to help you better:

**State your question**

**Which AWS Services are you utilizing?**

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).
