### ISSUE TITLE
Multiple user pools on android. How can I combine two sign in flows: username+password with one user pool and hostedUI login with another?

### ISSUE THREAD

**Issue by Zeliret** [aws-amplify/aws-sdk-android#1771]
Hello,

Thank you for this library, but I have a question here:
I have two user pools configured on the aws side. 
1st user pool used for a basic username+password login.
2nd user pool used for a hosted ui sign in through a 3rd-party provider. 

If I use it like this: 
```kotlin
AWSMobileClient.getInstance()
            .showSignIn(
                this,
                SignInUIOptions.builder()
                    .hostedUIOptions(
                        HostedUIOptions.builder()
                            .idpIdentifier("my-saml-provider")
                            .scopes("openid", "email")
                            // Disable federation
                            .disableFederation(false) // There is a issue in library with a reversed boolean value  
                            .build()
                    )
                    .build(),
                object : Callback<UserStateDetails> {
                    override fun onResult(result: UserStateDetails) {
                        Timber.d("SSO Result: ${result}")
                    }

                    override fun onError(e: Exception) {
                        Timber.e(e)
                    }
                })
```

I can debug and see that I get tokens successfully but it are not saved to the store because it can be saved only in case of federation enabled. 
So I have a semi-working flow. I can launch my hosted ui, login here and get all tokens I need after redirect. But I can't use UserStateDetails because it is always SIGNED_OUT (because the library didn't put tokens to the store).

So what options do I have?

**Comment by gpanshu** [comment]
Hello, is this still a problem? If yes we can do a deep dive. Please also try using the latest SDK to ensure you have the latest code when debugging.

**Comment by Inshaki** [comment]
I have the same issue now. Do you have an idea how this can be fixed? 
When I log it with a hosted UI using socials the state is always SIGNED_OUT even though I have the tokens.
