### ISSUE TITLE
How to send required parameter in NEW_PASSWORD_CHALLENGE 

### ISSUE THREAD

**Issue by FazalHussain** [aws-amplify/aws-sdk-android#1783]
I have `NEW_PASSWORD_CHALLENGE` but how can i create `NewPasswordContinuation` response to send required attribute and new password?

**Which AWS Services are you utilizing?**

AWS Cognito via AWS Amplify

**Sign In Callback**

```kotlin
fun fetchAuthenticationCallBack(): Callback<SignInResult> {
    return object : Callback<SignInResult> {
        override fun onResult(result: SignInResult?) {
            when (result?.signInState) {
                SignInState.DONE -> {
                    //AWSMobileClient.getInstance().confirmSignIn()
                    Log.d(TAG, "LOGIN SUCCESS ${AWSMobileClient.getInstance().tokens.accessToken}")
                }

                SignInState.NEW_PASSWORD_REQUIRED -> {
                    Log.d(TAG, "NEW PASSWORD CHALLENGE")
                }

                else -> {
                    //Unsupported sign-in confirmation:
                }
            }
        }

        override fun onError(e: java.lang.Exception?) {
            TODO("Not yet implemented")
        }
    }
}
```

Related: https://github.com/aws-amplify/aws-sdk-android/issues/1452

I have read all your documentation and it seems to be that you are more focused on hosted UI. There is no clear explanation of custom UI sign-in flow. Moreover, I have checked the issues that is explaining cast your continuation response in `NewPasswordContinuation` and send the new password and required attributes. However, in `SignInResult` there is no continuation response like `cognitoUser.getSession()` is providing.

**Comment by jhuamanchumo** [comment]
any update on this issue?, I have users created by an admin, and the user state is FORCE_CHANGE_PASSWORD, then the SDK does not provide a builtin function to change the password as same as js (Auth.completeNewPassword api).

**Comment by ansuman-CP** [comment]
No update yet? Has anyone found any solutions/workaround?

**Comment by jhuamanchumo** [comment]
Currently I found a way to make it work, but I dont know if its the right way,

```
Amplify.Auth.signIn(
                    username,
                    password,
                    result -> {
                        if (result.getNextStep().getSignInStep().toString().equals("CONFIRM_SIGN_IN_WITH_NEW_PASSWORD")) {
                            Intent intent = new Intent(LoginActivity.this, CreatePasswordActivity.class);
                            startActivity(intent);
                        } else {
                            if (result.isSignInComplete()) {
                                Log.w("AuthQuickstart", "loginApp: is success login" + result.toString());
                                isInitSesion();
                            } else {
                                hideAlertDialog();
                                Log.w("AuthQuickstart", "loginApp: error in login");
                            }
                        }
                    },
                    error -> {
                        hideAlertDialog();
                        showModalErrorLogin();
                    }
            );
```

**Comment by rjuliano** [comment]
You should be able to use the 'confirmSignIn` API of the mobile client.

https://docs.amplify.aws/sdk/auth/working-with-api/q/platform/android/#force-change-password
