### ISSUE TITLE
AWSMobileClient, OAuth2Client Redirect step failed because of chrome tabs.

### ISSUE THREAD

**Issue by Zeliret** [aws-amplify/aws-sdk-android#1791]
AWSMobileClient Oauth flow if not possible when you are using custom redirect uri (custom scheme). 

This code clears callback when chrome tabs closes just BEFORE I can get my intent with a code and state and handle a redirect. 
```java
mCustomTabsCallback = new CustomTabsCallback() {
            @Override
            public void onNavigationEvent(int navigationEvent, Bundle extras) {
                super.onNavigationEvent(navigationEvent, extras);

                if (navigationEvent == TAB_HIDDEN && !mAuthorizeOrSignOutRedirectReceived) {
                    if (mSignOutCallback != null) {
                        mSignOutCallback.onError(new Exception("User cancelled flow or flow interrupted."));
                        mSignOutCallback = null;
                    } else if (mAuthorizeCallback != null) {
                        mAuthorizeCallback.onError(new Exception("User cancelled flow or flow interrupted."));
                        mAuthorizeCallback = null;
                    }
                }
            }
        };
```

When I get an intent here the callback is null already, so the flow is considered by the library as canceled. 
```kotlin
override fun onNewIntent(intent: Intent?) {
        super.onNewIntent(intent)
        intent?.let {
            AWSMobileClient.getInstance().handleAuthResponse(it)
        }
    }

```

**Comment by doc-rj-celltrak** [comment]
@Zeliret What version of the Chrome app was installed?  I experienced this problem with my emulator's stock version of Chrome (58.0.3029.125), but when I upgraded to a newer version (84.0.4147.125) the problem went away.

**Comment by Zeliret** [comment]
@doc-rj-celltrak I was definitely the latest version, because It was tested on my pixel 3 fully updated.

**Comment by doc-rj-celltrak** [comment]
@Zeliret Android 10 or what OS version?

**Comment by Zeliret** [comment]
@doc-rj-celltrak yes, it is version 10.

**Comment by div5yesh** [comment]
It looks like `onNavigationEvent` is causing the problem here. With hostedUI we don't handle `onNavigationEvent` and everything works fine but need to check if we can handle this for OAuthClient without the navigation event and find a better way to handle user interruption/cancelled exceptions.

**Comment by sktimalsina** [comment]
@Zeliret Apologies for getting back to you this late. Considering many things, changed in course of time, I wanted to check if you are still facing this issue.

**Comment by sktimalsina** [comment]
Understandable :) and thank you for prompt comment! 
Closing this issue for now. Anyone interested or affected by this issue, please feel free to reopen this ticket or link this to the new one if needed.
