### ISSUE TITLE
CognitoCachingCredentialsProvider failes with KeyNotFoundException exception

### ISSUE THREAD

**Issue by ravik2d** [aws-amplify/aws-sdk-android#1794]
Hi All,

I am creating a very simple App which on a click of a Button gets credentials from AWS Cognito and then gets access to DynamoDB table. But my program fails as CognitoCachingCredentialsProvider dosen't get any Credential. I have created the AWS Identity Pool and also assigned Role to it.

**To Reproduce**
CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
                     getApplicationContext(), // Context
                     COGNITO_IDENTITY_POOL_ID, // Identity Pool ID
                     COGNITO_IDENTITY_POOL_REGION );// Region

This code fails with 

**_E/AWSKeyValueStore: com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
Deleting the encryption key identified by the keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = eu-central-1:ABCDEFGHIJ.identityId_**

Your code
MainActivity.java
package demo.example.studentappdemo;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Context;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.EditText;

import com.amazonaws.AmazonClientException;
import com.amazonaws.AmazonServiceException;
import com.amazonaws.auth.CognitoCachingCredentialsProvider;
import com.amazonaws.mobileconnectors.dynamodbv2.document.Table;
import com.amazonaws.mobileconnectors.dynamodbv2.document.datatype.Document;
import com.amazonaws.regions.Region;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient;
import java.util.Map;

public class MainActivity extends AppCompatActivity {

      String message = "Default";
    private final String COGNITO_IDENTITY_POOL_ID = "eu-central-1:ABCDEFGHIJ" ; ---- As per AWS
    private final Regions COGNITO_IDENTITY_POOL_REGION = Regions.EU_CENTRAL_1 ;
    private final String DYNAMODB_TABLE = "XX_STUDENT_TABLE" ;
    private Context context ;
    private CognitoCachingCredentialsProvider credentialsProvider ;
    private AmazonDynamoDBClient dbClient ;
    private Table dbTable ;
    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
    }
    /** Called when the user touches the button */
    public void findStudent(View view)
    {
        // Do something in response to button click
         EditText editText = (EditText) findViewById(R.id.StudNameTxt);

             CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
                     getApplicationContext(), // Context
                     COGNITO_IDENTITY_POOL_ID, // Identity Pool ID
                     COGNITO_IDENTITY_POOL_REGION );// Region

             AmazonDynamoDBClient dbClient = new AmazonDynamoDBClient(credentialsProvider);
             dbClient.setRegion(Region.getRegion(Regions.EU_CENTRAL_1));
             dbTable = Table.loadTable(dbClient, DYNAMODB_TABLE);

    }
}

**Which AWS service(s) are affected?**
CognitoCachingCredentialsProvider  --- This is supposed to work
**Expected behavior**
To get access to DynamoDB handler

**Screenshots**

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: Pkg.Revision=26.1.1
 - Device: Simulator - Pixel2-API 26
 - Android Version: [e.g. Android8.0

Any help will be Appreciated, I am completely stuck.

Regards
Ravi

**Comment by desokroshan** [comment]
@ravik2d In my experience error logs from `E/AWSKeyValueStore` are mostly innocuous and do not provide a lot of information for debugging. Does you application crash with the above code? Can you share your entire stack trace if possible?

**Comment by RKBL4ZE** [comment]
Can you show us your configuration file?

**Comment by ravik2d** [comment]
I just did some debug and found that my Application crashes only at line 
dbTable = Table.loadTable(dbClient, DYNAMODB_TABLE_NEW);

Even though the Table exists and I have also set Unauthenticated role in AWS IAM and below is the JSON
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "mobileanalytics:PutEvents",
                "cognito-sync:*",
                "dynamodb:GetItem",
                "dynamodb:PutItem",
                "dynamodb:Query"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}`

Is there something wrong with the permission of the table or Role Policy in IAM

**Comment by ravik2d** [comment]
But if its failing at the Table initialization or because dbClient itself was not initialized properly is something I am not getting.

**Comment by RKBL4ZE** [comment]
Try to set the configuration via Configuration File

`{
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "us-east-1:52XXXXXX75-4cXXXXXX07XXXX29d",
                "Region": "us-east-1"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "AppClientId": "472XXXXXXXXb26arXXXXX4vc1",
            "PoolId": "us-east-1_XXXXXXXXX",
            "Region": "us-east-1"
        }
    },
    "Auth": {
        "Default": {
            "authenticationFlowType": "USER_SRP_AUTH"
        }
    }
}`

Put the file in app/src/main/res/draw and name the file awsconfiguration.json

AWS SDK will automatically pickup all the necessary information from that file

**Comment by eeatonaws** [comment]
Hi. It has been quite some time since this issue was last updated. Before we investigate further, could you please let us know if you are still facing the issue with the latest version of the SDK?

**Comment by poojamat** [comment]
Closing the issue due to lack of response, please reopen it if its still an issue.
