### ISSUE TITLE
Hosted UI says "Login option is not available"

### ISSUE THREAD

**Issue by devxpy** [aws-amplify/aws-sdk-android#1808]
Hello, I've successfully integrated the Hosted UI in a [flutter plugin](https://github.com/scientifichackers/flutter_cognito_plugin).

But it shows the following error message "Login option is not available. Please try another one" -

<image height=400 src="https://user-images.githubusercontent.com/19492893/83503993-90134400-a4e1-11ea-925e-e319a1a3f65e.png" /> 

Both google sign in and username+password sign in seem to work fine, so users might get tripped up from seeing that error.

---

Am I doing something wrong here?

```kotlin
val hostedUIOptions = HostedUIOptions.builder()
    .scopes("email", "openid")
    .identityProvider("google")
    .build()
val signInUIOptions = SignInUIOptions.builder()
    .hostedUIOptions(hostedUIOptions)
    .build()

AWSMobileClient.getInstance().showSignIn(
    activity,
    signInUIOptions,
    object : Callback<UserStateDetails> {
        override fun onResult(details: UserStateDetails) {
            Log.d("TAG", "onResult: " + details.getUserState());
        }

        override fun onError(e: Exception) {
            Log.e("TAG", "onError: ", e);
        }
    }
)
```

---

Links to code on Github -

1. Invoke [showSignIn()](https://github.com/scientifichackers/flutter_cognito_plugin/blob/9f69c3a04687faa197dfcdb680b7a0aa7264b4d3/android/src/main/kotlin/com/pycampers/flutter_cognito_plugin/Cognito.kt#L214)

2. Override [onNewIntent](https://github.com/scientifichackers/flutter_cognito_plugin/blob/9f69c3a04687faa197dfcdb680b7a0aa7264b4d3/android/src/main/kotlin/com/pycampers/flutter_cognito_plugin/FlutterCognitoPlugin.kt#L17)

3. The [intent filter](https://github.com/scientifichackers/flutter_cognito_plugin/blob/9f69c3a04687faa197dfcdb680b7a0aa7264b4d3/example/android/app/src/main/AndroidManifest.xml#L25)  in `AndroidManifest.xml`

5. The [list of dependencies](https://github.com/scientifichackers/flutter_cognito_plugin/blob/9f69c3a04687faa197dfcdb680b7a0aa7264b4d3/android/build.gradle#L42) -

```
    implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.16.12'
    implementation 'com.amazonaws:aws-android-sdk-cognitoauth:2.16.12'
```

---

Hope this information is sufficient in helping me debug this issue.

**Comment by devxpy** [comment]
My `awsconfiguration.json` -

```json
{
  "UserAgent": "aws-amplify-cli/0.1.0",
  "Version": "1.0",
  "IdentityManager": {
    "Default": {}
  },
  "CredentialsProvider": {
    "CognitoIdentity": {
      "Default": {
        "PoolId": "ap-south-1:XXXX-XXX",
        "Region": "ap-south-1"
      }
    }
  },
  "CognitoUserPool": {
    "Default": {
      "PoolId": "ap-south-1_XXXX",
      "AppClientId": "XXXX",
      "Region": "ap-south-1"
    }
  },
  "Auth": {
    "Default": {
      "OAuth": {
        "WebDomain": "XXXX.auth.ap-south-1.amazoncognito.com",
        "AppClientId": "XXXX",
        "SignInRedirectURI": "myapp://callback",
        "SignOutRedirectURI": "myapp://signout",
        "Scopes": ["email", "openid"]
      }
    }
  }
}
```

**Comment by An0r4k** [comment]
I'm having the same issue when using the Hosted UI in a react native app. Were you able to figure out the reason why it is showing up the error?

**Comment by TrekSoft** [comment]
Hey, yeah in Android Amplify [we actually do have enums for those values](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android#add-response-handler). Although this is very interesting that the lowercase throws that error since I see we currently have our enums set to the lowercase values (although the old AWSMobileClient documentation shows the values capitalized) so I'll double check this on our end.

**Comment by TrekSoft** [comment]
Ah, yeah I checked into this and I see we have a converter where we convert the Amplify local constants to the AWS Cognito specific values and they are capitalized there. So I'll go ahead and close this. Thanks again for your response An0r4k.
