### ISSUE TITLE
[Hosted UI] Can't use getUserAttributes() without the aws.cognito.signin.user.admin scope

### ISSUE THREAD

**Issue by devxpy** [aws-amplify/aws-sdk-android#1813]
Using the following code during sign-in,

```kotlin
val hostedUIOptions = HostedUIOptions.builder()
    .scopes("email", "opened", "profile")
    .identityProvider("google")
    .build()
val signInUIOptions = SignInUIOptions.builder()
    .hostedUIOptions(hostedUIOptions)
    .build()

AWSMobileClient.getInstance().showSignIn(
    activity,
    signInUIOptions,
    object : Callback<UserStateDetails> {
        override fun onResult(details: UserStateDetails) {
            Log.d("TAG", "onResult: " + details.getUserState());
        }

        override fun onError(e: Exception) {
            Log.e("TAG", "onError: ", e);
        }
    }
)
```

Calling `getUserAttributes` returns with an error -

```kotlin
AWSMobileClient.getInstance().getUserAttributes(object : Callback<Map<String, String>> {
    override fun onResult(attrs: Map<String, String>?) { ... }
    override fun onError(e: Exception) { ... }
})
```

```
Unhandled Exception: NotAuthorizedException: Access Token does not have required scopes (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: e3943497-10d0-43a7-a0fa-5ad2d1747ee8)
com.amazonaws.services.cognitoidentityprovider.model.NotAuthorizedException: Access Token does not have required scopes (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: e3943497-10d0-43a7-a0fa-5ad2d1747ee8)
 at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:730)
 at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
 at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
 at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke(AmazonCognitoIdentityProviderClient.java:6319)
 at com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.getUser(AmazonCognitoIdentityProviderClient.java:4045)
 at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getUserDetailsInternal(CognitoUser.java:1166)
 at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getDetails(CognitoUser.java:1149)
 at com.amazonaws.mobile.client.AWSMobileClient$19.run(AWSMobileClient.java:2215)
 at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
 at java.lang.Thread.run(Thread.java:919)
```

When I include the `"aws.cognito.signin.user.admin"` scope, then `getUserAttributes` works fine. Why is this required? Shouldn't user attributes be accessible under the `"profile"` scope? Isn't it potentially dangerous to give every user admin access?

**Comment by RandomEngy** [comment]
Also asked about in https://github.com/aws-amplify/aws-sdk-android/issues/1747

**Comment by TrekSoft** [comment]
In short, no it's not dangerous. The admin scope is misleadingly named but only gives users access to their own attributes from what I've asked about internally. The naming and behavior of these scopes is outside our control on the AWSMobileClient side and is controlled by the Cognito team. 

Also, it's confusing that you didn't have this scope enabled by default because I believe the CLI sets it up by default - unless you set something up manually or perhaps in an older version.

**Comment by RandomEngy** [comment]
@TrekSoft It also allows [changing that user's attributes](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserAttributes.html). Which is beyond what's really needed for sign-in, right?

**Comment by TrekSoft** [comment]
Yeah you're right - I'm not sure why `profile` is not working for read-only access of the attributes. This would be a good question for the Cognito team.

**Comment by RandomEngy** [comment]
Not sure how I would phrase that question or where I would report the bug. What Cognito API are you calling that's failing here?

**Comment by TrekSoft** [comment]
After looking into it some more, it does look like that issue may be worth investigating on our end so I'll reopen your previous ticket so other users can react to it and we can prioritize it in our backlog.

**Comment by Gheotic** [comment]
I believe this is still a problem. At least I haven't been able to get user info without including the `aws.cognito.signin.user.admin` scope.

**Comment by charlie-psyomics** [comment]
For anyone coming to this thread: Decoding the id token will give you the data for claims in a scope - so cognito user attributes can be found there.

@TrekSoft Are you able to give confirmation 2 years later whether the admin scope only allows users to modify their own attributes? I haven't found any more information on this in the docs, but this is good to know (important info!)
