### ISSUE TITLE
How to get user token in android.

### ISSUE THREAD

**Issue by maheshlalu** [aws-amplify/aws-sdk-android#1828]
**Describe the bug**

**To Reproduce**
A code sample or steps:
```
Your code
```

**Which AWS service(s) are affected?**

**Expected behavior**

**Screenshots**

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [e.g. 2.6.25]
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators: [e.g. Yes/No]

**Additional context**

**Comment by richardmcclellan** [comment]
Amplify libraries should be used for all new applications.  For existing applications, we recommend you evaluate migration to the Amplify libraries. The AWS Mobile SDK will continue be maintained with bug fixes and security updates.

If you are using the SDK, see the [Token fetch and refresh section on the Authentication Overview](https://docs.amplify.aws/sdk/auth/how-it-works/q/platform/android#token-fetch-and-refresh) for how to get the user token.

If you are using Amplify, see the guide for [Accessing Credentials](https://docs.amplify.aws/lib/auth/access_credentials/q/platform/android)
