### ISSUE TITLE
How can I pass graph ql autogenerated model through intent ?

### ISSUE THREAD

**Issue by sagarkhurana00786** [aws-amplify/aws-sdk-android#1838]
I want to pass the GraphQL Model class to another activity 
as is it good to modify that autogenerated class?

**Comment by richardmcclellan** [comment]
(Paraphrased from @jamesonwilliams's answer in Discord):

The framework doesn’t have any built in solution for this, right now.

Currently the best solution is probably to serialize / deserialize using [gson](https://github.com/google/gson), which is used internally for serialization as well.

In the future, we may codegen either `Parcelable` or `Serializable` for our Models.

**Comment by danielmbutler** [comment]
Hi guys was there ever a solution made for this or are we still using json ?

**Comment by jamesonwilliams** [comment]
The Android SDK doesn't have any GraphQL models, so I suspect this ticket was meant for Amplify Android.

In that case, this is a duplicate of https://github.com/aws-amplify/amplify-android/issues/815. Please follow along there for feature updates.
