### ISSUE TITLE
AWSMobileClient.getTokens() takes 12 seconds to return on Android 5.0.1

### ISSUE THREAD

**Issue by sergei** [aws-amplify/aws-sdk-android#1844]
**Describe the bug**
If I call AWSMobileClient.getInstance().getTokens() it takes about 12 seconds to return on  device running Android 5.0.1. Don't see this problem on newer version of Android.

While it's being executed I see the following logcat output
<pre>
06-09 17:58:30.107 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:30.372 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:30.647 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:30.902 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:31.152 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:31.472 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:31.757 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:32.007 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:32.277 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:32.542 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:32.832 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:33.117 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:33.387 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:33.677 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:33.947 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:34.222 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:34.507 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:34.772 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:35.147 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:36.037 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:37.337 D/AWSMobileClient(28872): hasFederatedToken: false provider: cognito-idp.us-east-1.amazonaws.com/us-east-XXXXXXX
06-09 17:58:37.657 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:38.317 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:38.987 D/AWSMobileClient(28872): hasFederatedToken: false provider: cognito-idp.us-east-1.amazonaws.com/us-east-XXXXXXX
06-09 17:58:38.992 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:39.332 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:39.642 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:39.997 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:40.687 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:41.702 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias
06-09 17:58:42.397 W/keystore( 2575): Could not read CACERT_com.amazonaws.mobile.client.rsaKeyStoreAlias

</pre>

**To Reproduce**
A code sample or steps:
```
Tokens tokens = AWSMobileClient.getInstance().getTokens();
                    tokenString = tokens.getIdToken().getTokenString();
```

**Which AWS service(s) are affected?**
Cognito
**Expected behavior**
I expect it should be faster than one second on WiFi network and then being cached till expired.

**Screenshots**

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.16.4
 - Device: Samsung GT-I9500
 - Android Version: 5.0.1
 - Specific to simulators: No

**Comment by Dachmian** [comment]
I am also experiencing this issue. On Huawei P20 with android 9.1.0 and Galaxy S9 with android 10

**Comment by tyjaon** [comment]
I am also experiencing this issue. And others from previously ignored thread also [#1722]https://github.com/aws-amplify/aws-sdk-android/issues/1722l)

**Comment by CezaryGoralski** [comment]
I have also similar problem. On my galaxy s8+ and others phones.

**Comment by maciejbial** [comment]
I have the same exact problem on my Samsung Galaxy S10.

**Comment by reku47** [comment]
i'm facing exactly the same problem on my one plus 7t pro

**Comment by TrekSoft** [comment]
Closing in favor of #1722
