### ISSUE TITLE
Progress callback does not work after resuming a paused download task in TransferUtility

### ISSUE THREAD

**Issue by skyler1grey** [aws-amplify/aws-sdk-android#1865]
**Describe the bug**

Every time I resume a paused task, the progress callback does not work.  This
is especially true when more than half of the task completed before the pausing
point. However, when the task is about to finish, there is only one last
progress call and the state changes to complete.

As a first attempt to workaround the problem, I cleared the old progress
callback attached to the Observer when I start the task, and create a new one
when I resume the task. But, it still does not work.

**To Reproduce**
```java
@Override
public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
    mTotalBytesTransferred = bytesCurrent;
    mTotalBytes = bytesTotal;
    Log.d("TestTimer","origin bytesCurrent " + String.valueOf(bytesCurrent));
}
```

**Which AWS service(s) are affected?**
S3

**Expected behavior**
After I resume the task, the callback should be called normally as usual
instead of only the last call when it is about to complete. 

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: newest 2.17.x
 - Device: huawei mate8
 - Android Version: android 8.0
 - Specific to simulators: no

**Additional context**
After I look through the code, and I find the problem happens at Line 378 in
`TransferStatusTpdater.java`, the callback is not called when
`bytesTransferredSoFar < bytesCurrent`:

![image](https://user-images.githubusercontent.com/25931890/84455230-5daad900-ac8f-11ea-8175-d0953c979806.png)

And line 110 in `DownloadTask.java` indicates that it will report progress
decided by the existing file size before resuming the task:
![image](https://user-images.githubusercontent.com/25931890/84455509-18d37200-ac90-11ea-97a3-10ff86e50e86.png)

For instance, let's say there is a 10MB file to download. At first, I pause the
task when half (5MB), is completed. Then the task is resumed,
the `bytesTransferredSoFar` would start counting from 0. However, because of line
378 in `TransferStatusTpdater.java`, these progress reports are not able to call
the progress callback. This is because progress right now is less than 5MB,
which means I could not receive the progress correctly until the resumed
progress accumulated reaches 5MB( **this 5MB**+**5MB before paused**=10MB, end
of the file).

After I delete this check, the problem is fixed:
```java
if (bytesTransferredSoFar < transfer.bytesCurrent) {
```

I do not know whether there is something wrong with me directly deleting line
378 in `TransferStatusTpdater.java`.

**Comment by rbarbish** [comment]
Also noticing the progress being incorrect after network resume / re-enable, seems to get worse the more often you turn off/on network connectivity. Uploads will sometimes complete at 60, 70, 80% if you had toggled Wifi 2-3 times during an upload.

**Comment by jamesonwilliams** [comment]
Oops, sorry @rbarbish, didn't mean to delete your comment:
> Also noticing the progress being incorrect after network resume / re-enable, seems to get worse the more often you turn off/on network connectivity. Uploads will sometimes complete at 60, 70, 80% if you had toggled Wifi 2-3 times during an upload.

**Comment by rbarbish** [comment]
Also noticing the progress being incorrect after network resume / re-enable, seems to get worse the more often you turn off/on network connectivity. Uploads will sometimes complete at 60, 70, 80% if you had toggled Wifi 2-3 times during an upload.

**Comment by qq296216078** [comment]
I had the same problem

**Comment by sdhuka** [comment]
duplicate #2601

**Comment by skyler1grey** [comment]
您的邮件已收悉，谢谢！
