### ISSUE TITLE
READ_PHONE_STATE added to the Manifest

### ISSUE THREAD

**Issue by alejouribesanchez** [aws-amplify/aws-sdk-android#1914]
**Describe the bug**
After update to the last version I got this manifiest warning
// Amazon SDK
    implementation 'com.amazonaws:aws-android-sdk-s3:2.16.12'
    implementation 'com.amazonaws:aws-android-sdk-core:2.16.12'
    api ('com.amazonaws:aws-android-sdk-mobile-client:2.16.12@aar') 

**To Reproduce**  Just update the android project to last version 2.16.12
// Amazon SDK
    implementation 'com.amazonaws:aws-android-sdk-s3:2.16.12'
    implementation 'com.amazonaws:aws-android-sdk-core:2.16.12'
    api ('com.amazonaws:aws-android-sdk-mobile-client:2.16.12@aar') 

Your code
```
// Amazon SDK
    implementation 'com.amazonaws:aws-android-sdk-s3:2.16.12'
    implementation 'com.amazonaws:aws-android-sdk-core:2.16.12'
    api ('com.amazonaws:aws-android-sdk-mobile-client:2.16.12@aar') 
```

**Which AWS service(s) are affected?**

**Expected behavior**
Why it requires now READ_PHONE_STATE?

**Screenshots**
<img width="1037" alt="Screen Shot 2020-06-19 at 9 54 25 PM" src="https://user-images.githubusercontent.com/3950665/85189967-6c8a2080-b279-11ea-8586-4caaada8019c.png">

**Environment Information (please complete the following information):**
// Amazon SDK
    implementation 'com.amazonaws:aws-android-sdk-s3:2.16.12'
    implementation 'com.amazonaws:aws-android-sdk-core:2.16.12'
    api ('com.amazonaws:aws-android-sdk-mobile-client:2.16.12@aar') 

**Additional context**
reason: com.amazonaws.mobile.client has a targetSdkVersion < 4

**Comment by sktimalsina** [comment]
Apologies for responding so late. The READ_PHONE_STATE is required by an underlying package. Specifically: `aws-android-sdk-cognitoidentityprovider-asf`. 
We are working on making this optional. Although it has been long, please let us know if you are still facing the issue and reopen the ticket.
