### ISSUE TITLE
Adding email to an endpoint in Pinpoint

### ISSUE THREAD

**Issue by baole** [aws-amplify/aws-sdk-android#1927]
I would like to add an email associated with a user in Pinpoint which can be sent email campaign later (https://docs.aws.amazon.com/pinpoint/latest/userguide/channels-email.html). As the document I found suggest to use "Amplify" integration (https://docs.amplify.aws/lib/analytics/identifyuser/q/platform/android). However, our integration doesn't use "Amplify" (i.e. using com.amazonaws:aws-android-sdk-pinpoint:{version} library). Any sample code would be appreciated?

**Comment by jpignata** [comment]
Hi @baole! Does [this documentation](https://docs.amplify.aws/sdk/analytics/getting-started/q/platform/android) help? It covers the SDK you are referring to.

**Comment by baole** [comment]
Thanks @jpignata  for the references. I couldn't see any way to attach an email to an user/session/target. Could you elaborate a bit?

**Comment by jpignata** [comment]
Hmm, we use this in Amplify, so here's an example: https://github.com/aws-amplify/amplify-android/blob/78208fb4f58181eadf5b516e94f39a93b3e49581/aws-analytics-pinpoint/src/main/java/com/amplifyframework/analytics/pinpoint/AWSPinpointAnalyticsPlugin.java#L142

**Comment by baole** [comment]
That's really helpful. Thanks @jpignata
