### ISSUE TITLE
AWSMobileClient USER_SRP_AUTH flow signIn() how to pass clientMetadata

### ISSUE THREAD

**Issue by natIv13** [aws-amplify/aws-sdk-android#1949]
I'm trying to find a way to send clientMetadata during signIn process (USER_SRP_AUTH flow).
Using AWSMobileClient.getInstance().signIn(username, password, clientDataMap, object : Callback<SignInResult>
and passing clientMetadata in validationData field as stated https://github.com/aws-amplify/aws-sdk-ios/issues/2435 
but it doesn't seems to work. 
Can you please let me know what will be the best way to send clientMetadata during signIn process.

 - SDK Version: 2.16.10

**Comment by raphkim** [comment]
This feature will be included in 2.16.13, which will be released shortly. Hang on tight!

**Comment by natIv13** [comment]
Unfortunately, I don't see it working on 2.16.13 as well.  
In the Profiler Network flow there is no clientMetadata in any of the USER_SRP_AUTH flow messages, and in RespondToAuthChallengeResult respondToAuthChallenge response = invoke(request, responseHandler, executionContext); request -> clientMetadata is always null

**Comment by raphkim** [comment]
Hi @natIv13,
I apologize for the misinformation. The necessary changes were made to address this in #1984. This will be included in the version 2.16.14, and be released as soon as possible.

**Comment by natIv13** [comment]
Hi Raphael, is there any other way to send clientMetadata during sign In process? Or an example how to inject clientMetadata to a  respondToAuthChallenge() function?

**Comment by raphkim** [comment]
Once the PR is merged in, you can clone the repo and build the SDK yourself following [these steps](https://github.com/aws-amplify/aws-sdk-android#building-the-sdk).

**Comment by anhaya** [comment]
Hi, is there any alternative for this? Didn`t find in 2.16.13. When will be release 2.16.14?

**Comment by raphkim** [comment]
@anhaya Hang on tight! The new release will be coming soon!

**Comment by div5yesh** [comment]
The feature is available post version 2.16.14.

For more info on Auth Lambda Tiggers refer: https://github.com/aws-amplify/aws-sdk-ios/issues/2435#issuecomment-619986883
