### ISSUE TITLE
.doesObjectExist(..) result unpredictable, returns false even if object exist

### ISSUE THREAD

**Issue by abhidaa1233** [aws-amplify/aws-sdk-android#1973]
**Describe the bug**
I am using s3Client.doesObjectExist(bucketName, objectName) for my android application which has been working fine till now. The problem appeared when one of our team member uploaded in s3 from linux command line, and there is no such policy modification that he applied. Whenever I am trying to detect those objects or folder/files its showing false but in console its existing and has read write policy, other folder those I created in console or created by me in android code are working fine 
Update- when I programatically listed out all objects  I found those objects created from linux cmd line were missing folder objects. eg: In Aws console suppose in public folder I have a s900 named folder which should list as public/s900/ but this thing was missing in those created from linux and only images or file stored were listed like public/s900/f3/image.bmp were returned.
Any help would be great
  
**Environment Information:**
 - Device: [Lg]
 - Android Version: [oreo]

**Comment by gpanshu** [comment]
Hello and I apologize that this was not looked into till now. As this is a very old issue before we investigate I would like to know if you are still facing the issue?
