### ISSUE TITLE
Federate Google sign-in using Cognito user pool 

### ISSUE THREAD

**Issue by WassimErriha** [aws-amplify/aws-sdk-android#1976]
I am working on adding Google One Tap Sign-in to my project to overlay the AWS "drop-in" UI. the Amplify Docs only show how to  integrate federated identities through the Amplify CLI and there does't seem to be any examples out there of how Google sign in can be added without the CLI. The reason I am not Using the CLI is because I was unable to use an existing Cognito user pool without having to modify CloudFormation template. this is already tracked by #779.
My attempt was to pass the Google token to ` federatedSignIn()
`
```
AWSMobileClient.getInstance().federatedSignIn(IdentityProvider.GOOGLE.toString(), "GOOGLE_TOKEN", new Callback<UserStateDetails>() {
    @Override
    public void onResult(final UserStateDetails userStateDetails) {
        //Handle the result
    }

    @Override
    public void onError(Exception e) {
        Log.e(TAG, "sign-in error", e);
    } 
});
```

I get the following error : 

```
D/ AWSMobileClient: hasFederatedToken: false provider: accounts.google.com
E/ java.lang.RuntimeException: Error in federating the token.
```

Is this a supported use case. if not, Please point me to some example that I can use to add Google sign to my project.

**Comment by WassimErriha** [comment]
Any comments about this ?

**Comment by WassimErriha** [comment]
I can provide more information if the question seems vague ...

**Comment by WassimErriha** [comment]
@jamesonwilliams  @richardmcclellan 
Any feedback would help.
Thank you.

**Comment by TrekSoft** [comment]
Hey sorry for the delay on this - to add normal Google sign in (not sure about the one tap) follow the steps here up to the CLI ones: https://docs.amplify.aws/sdk/auth/federated-identities/q/platform/android#set-up-google

Since you want to avoid using the CLI, I believe it will be enough for you to then just manually add Google as an Authentication provider by opening up your identity pool in the AWS Console, editing it, and then adding your Google information underneath the Authentication Providers section:

<img width="1150" alt="Screen Shot 2020-08-25 at 10 27 29 AM" src="https://user-images.githubusercontent.com/5085574/91186997-ac2c1900-e6bd-11ea-859f-684aa697240c.png">

**Comment by WassimErriha** [comment]
Hi @TrekSoft 
Thank you for your help.
The issue I meant to link to is [aws-amplify/amplify-cli/issues/779](https://github.com/aws-amplify/amplify-cli/issues/779)
I am able to sign in and out now using Google UI.

Is it true that I have to manually parse and create the user in my user pool after they are federated ? or am I missing some steps ? the documentation doesn't mention how to proceed.

**Comment by TrekSoft** [comment]
Great! And yes it's true if you're using federated sign in you'll need to manually create them in the user pool as well. Currently the only way to have that happen automatically is to use HostedUI.

**Comment by WassimErriha** [comment]
@TrekSoft
Is  #1434 tracking support for this ? 

> Cognito currently doesn't support this but we are in touch with them about adding this functionality so will update as we find out more.

> The original issue asked about here is on our roadmap for this year ...

If this is something that the team is currently working on supporting for this year, I think it would make sense for me to just wait ...
Can you please provide some status on this.
Thank you !

**Comment by WassimErriha** [comment]
I think #622 is also marked as a feature request for this.

**Comment by TrekSoft** [comment]
Yeah last I heard this is not being actively worked on by Cognito although it's definitely been discussed internally as something they should add - I'll update if I hear otherwise.

**Comment by Jun711** [comment]
@WassimErriha 
Hi, did you figure out a way to do this?

@TrekSoft 
Hi, have you got any update for this?
