### ISSUE TITLE
CognitoUserPool.getSession() always going to success on re auth

### ISSUE THREAD

**Issue by Baaaaatz** [aws-amplify/aws-sdk-android#2019]
Is there another method for signing in when user is on re auth? Meaning user re opened the app and called signIn for the 2nd time. I already tried clearing the `CognitoCachingCredentialsProvider` on every initialisation still the same. I want to happen is everytime a user calls CognitoUserPool.getSession() it will always go to `getAuthenticationDetails`

com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.16.13

 - SDK Version: 2.16.13

 - Device: [e.g. Oneplus 7]
 - Android Version: Android 10

**Comment by jamesonwilliams** [comment]
Hi @Baaaaatz I understand that you're asking a question about calling `signIn` when a user is already signed-in. Can you clarify the behavior you expect, versus the behavior you are observing? Are you trying to detect if the user is already signed in?
