### ISSUE TITLE
InternalErrorException: Internal server error

### ISSUE THREAD

**Issue by ryancrunchi** [aws-amplify/aws-sdk-android#2022]
**Describe the bug**
I am using AWSMobileClient to sign in user with custom auth flow following this guide https://docs.amplify.aws/sdk/auth/custom-auth-flow/q/platform/android
When calling `AWSMobileClient.getInstance().signIn(...)` I get `com.amazonaws.services.cognitoidentityprovider.model.InternalErrorException: Internal server error. (Service: AmazonCognitoIdentityProvider; Status Code: 500; Error Code: InternalErrorException; Request ID: 2a21db14-0608-4546-bf7d-a3d77b3a9885`

**To Reproduce**
awsconfiguration.json
```json
{
  "IdentityManager": {
    "Default": {}
  },
  "CredentialsProvider": {
    "CognitoIdentity": {
      "Default": {
        "PoolId": "eu-west-1:...",
        "Region": "eu-west-1"
      }
    }
  },
  "CognitoUserPool": {
    "Default": {
      "PoolId": "eu-west-1_...",
      "AppClientId": "...",
      "Region": "eu-west-1"
    }
  },
  "Auth": {
    "Default": {
      "authenticationFlowType": "CUSTOM_AUTH"
    }
  },
  "S3TransferUtility": {
    "Default": {
      "Bucket": "...",
      "Region": "eu-west-1"
    }
  }
}
```

```kotlin
AWSMobileClient.getInstance().signIn(username, "", null, object: Callback<SignInResult> {
    override fun onError(e: java.lang.Exception?) {
        error { e }
    }

    override fun onResult(result: SignInResult?) {
        when (result?.signInState) {
            SignInState.CUSTOM_CHALLENGE -> {

            }
        }
    }
})
```

**Which AWS service(s) are affected?**
Cognito

**Expected behavior**
Another response

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.16.+
 - Device: Samsung Galaxy S9
 - Android Version: 10

**Comment by jamesonwilliams** [comment]
Thanks for the report, @ryancrunchi. A 500 failure indicates a problem within the Cognito service. You can file issues to the Cognito service team via the "Feedback" tab in the bottom of the AWS console, or by visiting https://console.aws.amazon.com/support/home.
