### ISSUE TITLE
voice along with video stream KVS android producer library

### ISSUE THREAD

**Issue by NitulPatelSavaliya** [aws-amplify/aws-sdk-android#2026]
I am using KVS video streaming in which we can record audio with video. For this I am following below github link.

https://github.com/awslabs/aws-sdk-android-samples/tree/effae8c8d20287098e71db2b669d379264391c0d/AmazonKinesisVideoDemoApp
But I am not able to find one of the class in it named "AndroidAudioVideoMediaSourceConfiguration".

com.amazonaws.mobileconnectors.kinesisvideo.mediasource.android.AndroidAudioVideoMediaSourceConfiguration

So anyone have idea on that ?

**Comment by jamesonwilliams** [comment]
@NitulPatelSavaliya That file does not exist in the AWS SDK for Android, and I can't find any references to it on the public Internet. I'm guessing one of our developers made changes to the sample repository before contributing a feature back to the SDK.
