### ISSUE TITLE
2.17.0 Auth Core failed to publish to maven

### ISSUE THREAD

**Issue by pedronveloso** [aws-amplify/aws-sdk-android#2045]
The newest update , `2.17.0` failed to publish all the artifacts to maven. Namely:

https://repo1.maven.org/maven2/com/amazonaws/aws-android-sdk-auth-core/2.17.0/

**Comment by raphkim** [comment]
Hi @pedronveloso , Thank you for pointing this out! We will address it as soon as possible.

**Comment by jamesonwilliams** [comment]
Thanks again for catching this @pedronveloso.

`aws-android-sdk-auth-core` has now been uploaded, and I verified that all other modules were present.

https://repo1.maven.org/maven2/com/amazonaws/aws-android-sdk-auth-core/2.17.0/

**Comment by pedronveloso** [comment]
No worries. Looks good now, thanks for working on the fix!
