### ISSUE TITLE
Getting UnsupportedOperationException when passing metadata in signIn

### ISSUE THREAD

**Issue by osugikoji** [aws-amplify/aws-sdk-android#2048]
**Describe the bug**
Hi guys. In the latest release the metada parameter is available in signIn method. When I try to use it, the following exception is thrown:

![image](https://user-images.githubusercontent.com/40952615/89251147-ad04ea00-d5ec-11ea-9340-3bc999bb1da4.png)

**To Reproduce**
`val metadata = mapOf(Pair("key", "value")`
`AwsClient.instance().signIn("username", "password", null, metada, callback)`

**Which AWS service(s) are affected?**
sdk-client

**Expected behavior**
exception shouldn't be thrown

**Screenshots**
NA

**Environment Information (please complete the following information):**
 - com.amazonaws:aws-android-sdk-mobile-client:2.17.0
 - Device: All
 - Android Version: Api 29 and Api 23
 - Specific to simulators: No

**Additional context**
NA

**Comment by jamesonwilliams** [comment]
Hi @osugikoji thanks for the report. I am able to reproduce this. I'll provide a fix.

**Comment by osugikoji** [comment]
Thank you so much! Do you know when this fix could be released?

**Comment by osugikoji** [comment]
Sorry for be impatiente, but I have a important release to do in the end of this month and a really depend on this feature. Do you guys know any alternative way to trigger the post authentication lamba in sign-in method?

**Comment by osugikoji** [comment]
Sorry for being impatient, but I have an important release to do at the end of this month and I really depend on this feature. Do you guys know any alternative way to trigger the post-authentication lamba in the sign-in method?

**Comment by jamesonwilliams** [comment]
This fix will go in 2.17.1. ETA 3-7 days.
