### ISSUE TITLE
WebSocket usage

### ISSUE THREAD

**Issue by alexei-frolo** [aws-amplify/aws-sdk-android#2072]
Is that possible to make requests to a WebSocket API (send messages and subscribe to inbox) through the SDK?

We created a WebSocket API in the AWS console, but I could not find any docs on how to use it on the client side (Android).

Thank you in advance.

**Comment by iamarjun** [comment]
Even I'm in search of this for android

**Comment by iamarjun** [comment]
@alexei-frolo did you find anything or you went with a 3rd party lib, can you help me?

**Comment by jamesonwilliams** [comment]
There is no explicit support for this in the SDK right now. Regarding [Amazon API Gateway's support for WebSocket APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api.html), I'd  suggest to use [OkHttp's WebSocket client](https://developer.squareup.com/blog/web-sockets-now-shipping-in-okhttp-3-5/).

**Comment by iamarjun** [comment]
> There is no explicit support for this in the SDK right now. Regarding [Amazon API Gateway's support for WebSocket APIs](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-websocket-api.html), I'd suggest to use [OkHttp's WebSocket client](https://developer.squareup.com/blog/web-sockets-now-shipping-in-okhttp-3-5/).

Thanks, I was evaluating Okhttp only
