### ISSUE TITLE
Amazon image upload issue: AmazonClientException

### ISSUE THREAD

**Issue by pari1992** [aws-amplify/aws-sdk-android#2093]
**State your question**
while trying to upload multiple images to s3 with proper network speed its working fine. But in some device in between the upload if network is inconsistent or weak then the below error issue is coming. Please help me to resolve the error

com.amazonaws.AmazonClientException: Unable to execute HTTP request: Unable to resolve host "s3.eu-west-1.amazonaws.com": No address associated with hostname
      at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
      at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
      at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4659)
      at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1752)
      at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.uploadSinglePartAndWaitForCompletion(UploadTask.java:219)
      at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:93)
      at com.amazonaws.mobileconnectors.s3.transferutility.UploadTask.call(UploadTask.java:49)
      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
      at java.lang.Thread.run(Thread.java:764)

**Which AWS Services are you utilizing?**
Used transfer utility to upload images 

**Provide code snippets (if applicable)**
 ```
val uploadObserver = transferUtility.upload(bucketname, toRemoteKey, aLocalFile, md, CannedAccessControlList.PublicRead)
            uploadObserver.setTransferListener(object : TransferListener {
                override fun onStateChanged(
                        id: Int,
                        state: TransferState
                ) {
                    if (TransferState.FAILED == state) {  } 
              else if (TransferState.COMPLETED == state) {
         }
                }

                override fun onProgressChanged(
                        id: Int,
                        bytesCurrent: Long,
                        bytesTotal: Long
                ) {
                  
                }

                override fun onError(id: Int, exception: Exception) {

                }
            })
```

**Environment(please complete the following information):**
    implementation('com.amazonaws:aws-android-sdk-mobile-client:2.13.2@aar') { transitive = true }
    implementation 'com.amazonaws:aws-android-sdk-s3:2.6.31'

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by pari1992** [comment]
I made it now the 
```
 val configuration = ClientConfiguration()
        configuration.maxErrorRetry = 10
        configuration.maxConnections = 100
        configuration.connectionTimeout = 0
        configuration.socketTimeout = 0
```

So its uploading all of the images but issue is now, it's taking long time to upload all of the images(uploading 100 images)

**Comment by raphkim** [comment]
Hey @pari1992 ,
`TransferUtility` is currently unequipped to handle inconsistent connection while transferring files.

However, you should be able to resume any cancelled transfer (caused by bad connection), and the transfer will continue from where it left off.
