### ISSUE TITLE
AWS IoT prints to log every second: [CDS]EAGAIN in Recvfrom

### ISSUE THREAD

**Issue by beersheba** [aws-amplify/aws-sdk-android#2096]
**Describe the bug**
I updated AWS IoT 2.15.0 > 2.18.0
Now these lines are printed to log every second

```
09-02 09:02:28.136 I: [CDS]EAGAIN in Recvfrom
09-02 09:02:28.136 I: [CDS]read byte is 0
09-02 09:02:29.136 I: [CDS]EAGAIN in Recvfrom
09-02 09:02:29.136 I: [CDS]read byte is 0
09-02 09:02:30.136 I: [CDS]EAGAIN in Recvfrom
09-02 09:02:30.136 I: [CDS]read byte is 0
```

What does it mean?
Is there a way to stop it?

**To Reproduce**
```
    implementation 'com.amazonaws:aws-android-sdk-iot:2.18.0'
```

**Which AWS service(s) are affected?**
AWS IoT

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.18.0
 - Android Version: Android 5.1

**Additional context**
Seems like it's related to [Paho 1.2.5](https://github.com/eclipse/paho.mqtt.java/issues/705) used under the hood.

**Comment by raphkim** [comment]
Hi @beersheba ,
I understand that you are annoyed that Paho is logging in a rather chatty manner. 

However, can I confirm that the unnecessarily verbose log is the only issue that you are experiencing with our SDK? If so, I would consider this to be a low priority bug and wait for the Paho team to address it on their end first.

**Comment by beersheba** [comment]
I'm actively using logs in my project. All this Paho noise is making the log much less readable. This issue is stopping me from using AWS IoT 2.18.0, I can't accept it and should revert back to 2.15.0.

Another issue I had w/ 2.18.0 is lacking advanced profiling support for Android Studio 4 
(Run > Edit Configuration > Profiling). When it's enabled, the app can't run.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithProfilers-transformForDebug'.
> java.lang.IllegalArgumentException (no error message)
```

**Comment by richardmcclellan** [comment]
Closing in favor of https://github.com/eclipse/paho.mqtt.java/issues/705
