### ISSUE TITLE
How Would i know that user is existing user or new user from email id

### ISSUE THREAD

**Issue by ravisaini1990** [aws-amplify/aws-sdk-android#2099]
Have 2 basic questions about it -
1. How Would I know that user is an existing user or new user from email id 
2. Also, How would I know via which social platform user have logged in whether its Google, Facebook, Apple Id etc

**Comment by rjuliano** [comment]
1 - If you want to trigger some code to run in response to a user signing up, you could leverage [lambda triggers in Cognito](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html). On the client side, I can't think of a way to do that.

2 - Determining the source provider can be done by inspecting the sub claim of the user pool. It will be prefixed with the provider name + a unique id. For example, Google will have `google_<unique id>`
