### ISSUE TITLE
Do kinesis-sdk support two kinesisStreamName in one app?

### ISSUE THREAD

**Issue by t-kabaya** [aws-amplify/aws-sdk-android#2106]
**State your question**

When I use two two kinesis stream names, I see the error below.

> Received error response: com.amazonaws.AmazonServiceException: User: arn:aws:sts::xxxxxxxx:assumed-role/Cognito_xxxxx_Unauth_Role/CognitoIdentityCredentials is not authorized to perform: kinesis:PutRecords on resource: arn:aws:kinesis:ap-northeast-1:xxxxxxxx:stream/stg-xxxx-stream (Service: null; Status Code: 400; Error Code: AccessDeniedException; Request ID: xxxxx)

I just add new `poolId` of Cognito, and Kinesis stream name. Then, new `poolId` uses old `userId` of Cognito!

Expected is:
```
[new userId]:stream/[new stream name]
```
But actual is:
```
[old userId]:stream/[new stream name]
```

Is the kinesis client a singleton class? 

**Which AWS Services are you utilizing?**
- Kinesis
- Cognito

**Environment(please complete the following information):**
```gradle
 com.amazonaws:aws-android-sdk-kinesis:2.15.2
```

**Comment by jpignata** [comment]
Heya. Can you provide some kind of code sample?
