### ISSUE TITLE
Hide Cognito App Client Id and secret.

### ISSUE THREAD

**Issue by kuabhish** [aws-amplify/aws-sdk-android#2119]
I am building an Android application in Java and using the **Cognito User Pool** [(using this demo)](https://github.com/awslabs/aws-sdk-android-samples/tree/main/AmazonCognitoYourUserPoolsDemo) to generate **User Session Tokens** to authenticate the Rest Api calls.

In the  [sample repo](https://github.com/awslabs/aws-sdk-android-samples/tree/main/AmazonCognitoYourUserPoolsDemo) the client secret is written in the the AppHelper class. 

So, my question is : Is it safe to keep the client Id and Client Secret in the open.
If not , what is the best way to do it.?

Please, give me suggesstions.
Thank you

**Comment by TrekSoft** [comment]
Hey, a similar issue was filed here and is being discussed internally - I'll close this issue in favor of that one and you can expect a response on it shortly: https://github.com/aws-amplify/docs/issues/2021
