### ISSUE TITLE
AWS IOT connecting Issue with SocketTimeout  Exception

### ISSUE THREAD

**Issue by hardik-vt352** [aws-amplify/aws-sdk-android#2121]
**Describe the bug**
While our app is trying to connect AWS MQTT, it can not connect, and is
receiving a `SocketTimeoutException` from the AWS IoT SDK. Note that the user
has stable Internet connectivity when this occurs.

**To Reproduce**
To establish the MQTT connection, we are using the version of the
`connect(...)` method which takes a KeyStore:

```java
awsIotMqttManager.connect(clientKeyStore, new AWSIotMqttClientStatusCallback() {
    @Override
    public void onStatusChanged(AWSIotMqttClientStatus status, Throwable throwable) {
        switch (status) {
            case Connecting:
                break;
            case Reconnecting:
                break;
            case Connected:
                break;
            case ConnectionLost:
                break;
            default:
                break;
        }
    }
});
```

**ADB Exception Logs**
```console
07-30 10:36:36.490 19574  1029 W AWSIotMqttManager: Reconnect failed 
07-30 10:36:36.490 19574  1029 W AWSIotMqttManager: MqttException (0) - java.net.SocketTimeoutException: connect timed out
07-30 10:36:36.490 19574  1029 W AWSIotMqttManager: 	at k.b.a.a.a.q.a$a.run(ClientComms.java:57)
07-30 10:36:36.490 19574  1029 W AWSIotMqttManager: 	at java.lang.Thread.run(Thread.java:761)
07-30 10:36:36.490 19574  1029 W AWSIotMqttManager: Caused by: java.net.SocketTimeoutException: connect timed out
07-30 10:36:36.490 19574  1029 W AWSIotMqttManager: 	at java.net.PlainSocketImpl.socketConnect(Native Method)
07-30 10:36:36.490 19574  1029 W AWSIotMqttManager: 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
07-30 10:36:36.490 19574  1029 W AWSIotMqttManager: 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
07-30 10:36:36.490 19574  1029 W AWSIotMqttManager: 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
07-30 10:36:36.490 19574  1029 W AWSIotMqttManager: 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
07-30 10:36:36.490 19574  1029 W AWSIotMqttManager: 	at java.net.Socket.connect(Socket.java:605)
07-30 10:36:36.490 19574  1029 W AWSIotMqttManager: 	at com.android.org.conscrypt.OpenSSLSocketImpl.connect(OpenSSLSocketImpl.java:265)
07-30 10:36:36.490 19574  1029 W AWSIotMqttManager: 	at k.b.a.a.a.q.m.start(TCPNetworkModule.java:4)
07-30 10:36:36.490 19574  1029 W AWSIotMqttManager: 	at k.b.a.a.a.q.l.start(SSLNetworkModule.java:1)
```

**Expected behavior**
AWS MQTT should connect without any error.

**Environment Information :**
- AWS Android SDK Version: 2.13.2
- Device: ZTE Z899VL
- Android Version: Nougat 7.1.1
- Specific to simulators: NO

**Comment by lellisls** [comment]
I'm also facing this same issue. For some reason, the app is not able to connect over Wifi, but works over LTE.
I think it has something to do with the ISP firewall, but I don't think it should happen.

**Comment by TrekSoft** [comment]
We have had an issue before with MQTT not working over a firewall. The solution in that case was to explore using an HTTPS connection instead: https://docs.aws.amazon.com/iot/latest/developerguide/http.html

**Comment by jamesonwilliams** [comment]
Looks to be duplicated in https://github.com/aws-amplify/aws-sdk-android/issues/2185. Possibly related to https://github.com/aws-amplify/aws-sdk-android/issues/2105. @hardik-vt352 & @lellisls can you please try [this debugging step](https://github.com/aws-amplify/aws-sdk-android/issues/2185#issuecomment-712608738) and reply back on #2185?
