### ISSUE TITLE
 java.security.cert.CertPathValidatorException

### ISSUE THREAD

**Issue by heqiankun** [aws-amplify/aws-sdk-android#2130]
Unable to execute HTTP request: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

**Comment by TrekSoft** [comment]
We need a lot more info here to troubleshoot this. What API were you calling? What version? Code snippets? etc.

**Comment by jamesonwilliams** [comment]
Hi @heqiankun, we'll reopen if you are able to provide more details.
