### ISSUE TITLE
AWS cognito giving different response for Andriod and iOS

### ISSUE THREAD

**Issue by ravikanthvob** [aws-amplify/aws-sdk-android#2131]
**Describe the bug**
Guys, your help is appreciated. I have the below code for Android, which I am
using to:
1. Filter out confirmed AWS Cognito users,
2. Capture the remaining unconfirmed users,
3. Re-send them a one-time-password

When I trigger an OTP resend for CONFIRMED users on iOS, Cognito does respond
with error and OTP regeneration is rejected. But on Android, it sends a new
code.

Need your suggestions. How can I identify CONFIRMED & UNCONFIRMED users on
Android?

**To Reproduce**
```java
AWSMobileClient.getInstance().resendSignUp(mobile, new Callback() {
    @Override
    public void onResult(SignUpResult result) {
        Log.d(TAG, "resendConfirmationCode :: onResult: " + result.toString());
        signupStateLD.postValue(AuthVM.SignupFlowState.SIGN_UP_CONFIRMATION_CODE_RESENTED);
    }
    @Override
    public void onError(Exception e) {
        Log.e(TAG, "resendConfirmationCode onError: " + e.getMessage());
        signupStateLD.postValue(AuthVM.SignupFlowState.SIGN_UP_CONFIRMATION_CODE_RESENT_FAIL);
    }
});
```

**Which AWS service(s) are affected?**
AWS Cognito

**Expected behavior**
For an confirmed user, once the resend OTP is triggered on an Android, it
should fail the resending of OTP and error out.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version:  2.15+
 - Android Version: 7 and above
 - Specific to simulators: [No]

**Comment by Tatsato3** [comment]
Even I am getting the same response
if the user already confirmed then "resendSignUp" api is returning "onResult" method it should call "onError" with Exception.

**Comment by ravikanthvob** [comment]
Any solution is appreciated.

**Comment by ravikanthvob** [comment]
dear @raphkim is this identified as bug by AWS, if yes, is there an alternate solution currently

**Comment by ravikanthvob** [comment]
@raphkim @awsmobilesdk is this prioritized and time of release pls

**Comment by raphkim** [comment]
Hi @ravikanthvob,

I apologize for the delay! I will bring this up with the team to find out what the expected behavior is and update the ticket with the appropriate action required.

**Comment by raphkim** [comment]
Would you be able to provide some details on the error message you are getting on the iOS side? Both platforms are directly calling the same API from Cognito service, which means they should behave the same. 

As for determining whether a user is confirmed or not, you can do the following:
 * calling `resendSignUpCode()` method on the user you would like to confirm, and inspect `AuthSignUpStep` property by calling `authSignUpResult.getNextStep().getSignUpStep()`. If it is `CONFIRM_SIGN_UP_STEP`, then the user is not yet confirmed; `DONE` means the user is already confirmed.
 * you can also check the Cognito User Pools console directly to manually check if a user is confirmed or not

**Comment by TrekSoft** [comment]
Hey, your use case of checking whether other users are confirmed or not is an admin task. We specifically don't want to allow users to see whether other users are confirmed or not. AWSMobileClient is a client facing SDK with no Admin functionalities like that so you'd have to look through other Cognito APIs to see if one of them provides an admin function to do that.

Otherwise, as an admin, you can simply visually look through your list of users in the console and see who are confirmed or not.

**Comment by Tatsato3** [comment]
Hi @TrekSoft @raphkim,

The application is not checking whether the user is in a confirmed state or unconfirmed state.

The application has required the SDK "**resendSignUp**" method should return an error method "**onError**" with appropriate exceptions like you guys are giving in IOS SDK.

In IOS SDK application method is returning as an **error** but in Android, we are getting always a success "**onResult**" if the user is already confirmed state it should return an error in android SDK as well.

**Comment by raphkim** [comment]
@Tatsato3 It appears that Cognito does in fact send an error when attempting to resend confirmation code to an already confirmed user. I will look into Android Mobile Client to check its current behavior and apply a fix as necessary. Thank you.

**Comment by ravikanthvob** [comment]
@raphkim is there any deviation observed in code? can you confirm the behavior?

**Comment by raphkim** [comment]
Hey @ravikanthvob ,

Sorry for the delay, but I finally had some time to look into this last week. I confirmed by inspecting the direct response from Cognito that the service behavior is to return `InvalidParameterException` upon attempting to call the `ResendConfirmationCode` API on an already confirmed user. However, it also appears that both iOS and Android platforms implement `AWSMobileClient` to reflect this behavior accurately and trigger an error callback. I was able to confirm this on a sample app myself.

Are you able to share the code snippet that is causing you to experience this deviation? Can you also confirm that the user is actually already `CONFIRMED` from the console?
