### ISSUE TITLE
AWS mobile client showSignIn crash with Facebook in HostedUiOptions

### ISSUE THREAD

**Issue by jugos654** [aws-amplify/aws-sdk-android#2145]
**Describe the bug**
Started implementation of Facebook login with HosteUI and I hit a AWS SDK bug "user cancelled" exception -  described here: https://github.com/aws-amplify/aws-sdk-android/issues/871

I updated the aws android sdk version from 2.16 to 2.18 as instructed at the closing of that bug's docs guide, 
changed the handler and now from the moment of upgrade to 2.18 I started getting crash on call of  AWSMobileClient.getInstance().showSignIn 

Here is the exception:
No virtual method getSession()V in class Lcom/amazonaws/mobileconnectors/cognitoauth/Auth; or its super classes (declaration of 'com.amazonaws.mobileconnectors.cognitoauth.Auth'

I added the awsmobileclient source code and I got better exception, here it is:
```
/com.myApp.development E/AndroidRuntime: FATAL EXCEPTION: Thread-6
    Process: com.myApp.development, PID: 2250
    java.lang.NoSuchMethodError: No virtual method getSession()V in class Lcom/amazonaws/mobileconnectors/cognitoauth/Auth; or its super classes (declaration of 'com.amazonaws.mobileconnectors.cognitoauth.Auth' appears in /data/app/com.myApp.development-XXRS4kFMzQ2dM9urGYRjAw==/base.apk!classes4.dex)
        at com.amazonaws.mobile.client.AWSMobileClient$25.run(AWSMobileClient.java:2969)
        at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
        at java.lang.Thread.run(Thread.java:919)
```

**To Reproduce**
A code sample or steps:

I am using aws sdk 2.18.0 and 2.19.0 with android sdk 29

The gradle config:
implementation "com.amazonaws:aws-android-sdk-core:2.18.0"
implementation "com.amazonaws:aws-android-sdk-mobile-client:2.18.0"
implementation "com.amazonaws:aws-android-sdk-cognitoauth:2.18.0"

Here is the used aws configuration
```
 "Auth": {
        "Default": {
            "OAuth": {
                "WebDomain": "XXXXXXXXXXX.auth.eu-central-1.amazoncognito.com",
                "AppClientId": "xxxxxxxxxxxxxx",
                "SignInRedirectURI": "myapp://callback",
                "SignOutRedirectURI": "myapp://signout",
                "Scopes": ["openid", "email", "profile", "aws.cognito.signin.user.admin"]
            }
        }
    }
```
and the button action
```
val hostedUIOptions = HostedUIOptions.builder()
                .scopes("openid", "email", "profile", "aws.cognito.signin.user.admin")
                .identityProvider("Facebook")
                .build()
            val signInUIOptions = SignInUIOptions.builder()
                .hostedUIOptions(hostedUIOptions)
                .build()
// requireActivity() refers to the current active Activity
            AWSMobileClient.getInstance()
                .showSignIn(
                    requireActivity(),
                    signInUIOptions,
                    object : Callback<UserStateDetails?> {

                        override fun onResult(result: UserStateDetails?) {
                            println("result with hosted: ${result?.userState}")
                        }

                        override fun onError(e: Exception?) {
                            println("error with hosted: ${e?.cause}")
                        }
                    })
```
The activity for the callback handler
```
<activity
    android:name="com.amazonaws.mobileconnectors.cognitoauth.activities.CustomTabsRedirectActivity">
    <intent-filter>
        <action android:name="android.intent.action.VIEW" />
        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />
        <data android:host="callback" android:scheme="myapp" />
    </intent-filter>
</activity>
```

**Which AWS service(s) are affected?**

AWSMobileClient Auth

**Expected behavior**
Expected not to crash - the HostedUI should show as on previous versions of AWS SDK showSignIn method.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [2.18.0]
 - Device: [ Pixel2 Simulator]
 - Android Version: [Android 10, Pie 9]
 - Specific to simulators: [No]

**Additional context**
Have to mention that I used native login till now, social login is the addition in the project.
Also I do not doubt the aws cognito configuration  as the same works on my iOS app - implemented the same way using same methods. Everything works as expected there.

**Comment by jugos654** [comment]
Updated gradle version to 6.1.1 and everything magically worked. I cannot believe it!

**Comment by TrekSoft** [comment]
Thanks for posting all that and the resolution as well!
