### ISSUE TITLE
GetClip API is not there in SDK for Android i.e.aws-android-sdk-kinesisvideo-archivedmedia

### ISSUE THREAD

**Issue by shishir87** [aws-amplify/aws-sdk-android#2148]
I am using `aws-android-sdk-kinesisvideo-archivedmedia` to show a video saved in the cloud. In my Android app, I want the user to be able to _download_ the video, as well. To implement this download clip functionality I am looking for the `GetClip` API which is already present in the SDK for Java. But, I don't see it in the Android SDK.

**Comment by shishir87** [comment]
Sorry I have put the issue in wrong place

**Comment by eeatonaws** [comment]
The GetClip API was added in version 2.22.6 of the AWS SDK for Android.
