### ISSUE TITLE
Missing required parameter REFRESH_TOKEN in latest Android version only

### ISSUE THREAD

**Issue by shwetachauhan-simform** [aws-amplify/aws-sdk-android#2187]
When trying to authenticate with one of our test accounts, I receive:

> com.amazonaws.services.cognitoidentityprovider.model.InvalidParameterException: Missing required parameter REFRESH_TOKEN (Service: AmazonCognitoIdentityProvider; Status Code: 400; Error Code: InvalidParameterException; Request ID: e7e69fbb-ceed-432a-ba1c-4b58bbd498f2)

`getClass()` on the exception:
> class com.amazonaws.mobileconnectors.cognitoidentityprovider.exceptions.CognitoInternalErrorException

`getMessage()` on the exception:
> Failed to authenticate user

The authentication works on other Android devices. Clearing cache and
reinstalling app doesn't seem to fix the issue.

Here's my code:
```java
AWSMobileClient.getInstance().signIn(email, password, null, new Callback<SignInResult>() {
    @Override
    public void onResult(final SignInResult signInResult) {            
        Log.d(TAG, "Sign-in callback state: " + signInResult.getSignInState());
    }

    @Override
    public void onError(Exception e) {        
        Log.e(TAG, "Sign-in error", e);
        e.printStackTrace();            
    }
});
```

```gradle
implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.12.4'
```

**Expected behavior**
Able to login in all device.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [2.12.4]
 - Device: [oneplus7pro]
 - Android Version: [Oxygen OS 10.3.3]
 - Specific to simulators: [No]

**Additional context**
- On another device it's working properly.

**Comment by TrekSoft** [comment]
Hey, that's actually a pretty old version of the SDK - could you try running it with the latest version, 2.19.1?

**Comment by rjuliano** [comment]
Please attempt to use the latest version of the SDK and let us know if this is still a problem

**Comment by changxu0306** [comment]
I'll close this issue since we didn't hear from the customer for a while. Please feel free to reopen the issue if the problem still exists.
