### ISSUE TITLE
I can't use Kinesis Video Stream with Cognito Guest user

### ISSUE THREAD

**Issue by adxcorp** [aws-amplify/aws-sdk-android#2201]
**Describe the bug**
I want to integrate Cognito guest session and Kinesis Video, but I can't get a
successful response from AWS.

**To Reproduce**
Source code:
```java
CognitoCachingCredentialsProvider credentialsProvider =
    new CognitoCachingCredentialsProvider(
        getApplicationContext(),
        "ap-northeast-2:6d06e042-1cae-48ed-953b-3722efb83039", // Identity pool ID
        Regions.AP_NORTHEAST_2 // Region
    );

final AWSKinesisVideoClient awsKinesisVideoClient =
    new AWSKinesisVideoClient(credentialsProvider);
awsKinesisVideoClient.setRegion(Region.getRegion("ap-northeast-2"));
awsKinesisVideoClient.setSignerRegionOverride("ap-northeast-2");
awsKinesisVideoClient.setServiceNameIntern("kinesisvideo");

try {
    DescribeSignalingChannelResult describeSignalingChannelResult =
        awsKinesisVideoClient.describeSignalingChannel(
            new DescribeSignalingChannelRequest().withChannelName("channelName"));
} catch (Exception e) {
    e.printStackTrace();
}
```

IAM Policy:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "mobileanalytics:PutEvents",
                "cognito-sync:*",
                "kinesisvideo:*"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

Error Log:
```console
com.amazonaws.services.kinesisvideo.model.AccessDeniedException: User: arn:aws:sts::796181577313:assumed-role/Cognito_WebRTCTestUnauth_Role/CognitoIdentityCredentials is not authorized to perform: kinesisvideo:DescribeSignalingChannel on resource: channelName (Service: AWSKinesisVideo; Status Code: 403; Error Code: AccessDeniedException; Request ID: 3ea3ec8a-a615-4ea1-a788-a233c36bc1b4)
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:731)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:405)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:212)
    at com.amazonaws.services.kinesisvideo.AWSKinesisVideoClient.invoke(AWSKinesisVideoClient.java:1551)
    at com.amazonaws.services.kinesisvideo.AWSKinesisVideoClient.describeSignalingChannel(AWSKinesisVideoClient.java:653)
```

**Which AWS service(s) are affected?**
Kinesis Video, Cognito

**Expected behavior**
Work well

**Screenshots**
Policy simulator successfully checks the permissions, but I can't get success response:
![image](https://user-images.githubusercontent.com/24836078/97535316-cefce580-19fe-11eb-8172-3e63ed67868e.png)

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.19.1
 - Device: Galaxy Note 10
 - Android Version: 10
 - Specific to simulators: No

**Comment by jamesonwilliams** [comment]
Do you have the role above correctly attached to the identity pool, and is that identity pool setup for your guest access?

**Comment by behrooziAWS** [comment]
I believe the issue is Cognito applies a scopedown policy that doesn't include Kinesis Video Streams to unauthenticated users:

https://docs.aws.amazon.com/cognito/latest/developerguide/iam-roles.html#access-policies

**Comment by jamesonwilliams** [comment]
Offline, @behrooziAWS suggested a workaround to use basic auth instead of the enhanced auth. [See a discussion on the two auth flows](https://docs.aws.amazon.com/cognito/latest/developerguide/authentication-flow.html). The `CognitoCachingCredentialsProvider` will work with basic auth, depending on how you construct it. For example, [this version](https://aws-amplify.github.io/aws-sdk-android/docs/reference/com/amazonaws/auth/CognitoCachingCredentialsProvider.html#CognitoCachingCredentialsProvider-android.content.Context-com.amazonaws.auth.AWSCognitoIdentityProvider-java.lang.String-java.lang.String-) will use the basic auth flow.

**Comment by adxcorp** [comment]
Thanks. I'll try basic auth.
