### ISSUE TITLE
User state "SIGNED_OUT_USER_POOLS_TOKENS_INVALID" right after signed in.

### ISSUE THREAD

**Issue by rideflag-yankai-tian** [aws-amplify/aws-sdk-android#2209]
**Describe the bug**
After signing in with the code below:
```kotlin
AWSMobileClient.getInstance()
    .signIn(user_id, password, validationData, callback)
```
I got `SignInState.DONE` in the callback.

Then I check the user state by using:

```kotlin
AWSMobileClient.getInstance()
	.currentUserState(callback2)
```

It gives me `SIGNED_OUT_USER_POOLS_TOKENS_INVALID` in `callback2`.

**To Reproduce**
```kotlin
AWSMobileClient.getInstance().signIn(userId, password, null, object : Callback<SignInResult> {
    override fun onResult(result: SignInResult?) {
        if (result?.signInState == SignInState.DONE) {
            AWSMobileClient.getInstance().currentUserState(object : Callback<UserStateDetails> {
                override fun onResult(result: UserStateDetails?) {
                    // in 'result' the user status is "SIGNED_OUT_USER_POOLS_TOKENS_INVALID"
                }
                override fun onError(e: java.lang.Exception?) {
                    // ...
                }
            })
        }
        else {
            // ...
        }
    }
    override fun onError(e: Exception?) {
        // ...
    }
})
```

**Which AWS service(s) are affected?**
`AWSMobileClient`

**Expected behavior**
After signing in with user ID and password there should be a `SIGNED_IN`
status. If I keep this account in `SIGNED_OUT_USER_POOLS_TOKENS_INVALID` and
try the `getToken(callback)` method, it will return a "No cached session"
Exception

I am not using AWSMobileClient integrated UI.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.19.1
 - Device: Simulator, Samsung S5, Sony Xperia XZ2
 - Android Version: Android 6, Android 9
 - Specific to simulators: No

**Additional context**
I also tried using:

```kotlin
AWSMobileClient.getInstance()
    .signIn(user_id, password, validationData, callback)
```

After `SIGNED_OUT_USER_POOLS_TOKENS_INVALID` status,
it still gives me `SignInState.DONE` and `SIGNED_OUT_USER_POOLS_TOKENS_INVALID`
when I retrieve user state afterwards.

**Comment by eeatonaws** [comment]
Hi @rideflag-yankai-tian. Using the code you provided, I'm seeing a status of `SIGNED_IN` for the user state and did not observe a `SIGNED_OUT_USER_POOLS_TOKENS_INVALID` status. The `SIGNED_OUT_USER_POOLS_TOKENS_INVALID` status occurs when the refresh tokens are invalid. When this happens, the user needs to sign in again. However, if the device is offline and the refresh tokens are invalid, you would need to wait for the device to come online (at which point the tokens will be refreshed) before signing in again. Please see the [Android SDK documentation](https://docs.amplify.aws/sdk/auth/how-it-works/q/platform/android/#token-fetch-and-refresh) for more information. Is the device online when you call sign in? If the device is online, could you try signing the user in again when encountering the `SIGNED_OUT_USER_POOLS_TOKENS_INVALID` status?
