### ISSUE TITLE
Expected change in TransferState from IN_PROGRESS to WAITING_FOR_NETWORK

### ISSUE THREAD

**Issue by vivekgabadiya** [aws-amplify/aws-sdk-android#2210]
**Describe the bug**
Expected change in TransferState from IN_PROGRESS to WAITING_FOR_NETWORK if we are connected using wifi with no data connection. 

**To Reproduce**
Using S3TransferUtilitySample app and in-between the upload of the video file disconnect the data connection of the WIFI network connected to the phone. (hotspot without data or unplug the data from WIFI router).

**Expected behavior**
TransferService should change state from IN_PROGRESS to WAITING_FOR_NETWORK

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [2.19.0]
 - Device: [Pixel 2XL]
 - Android Version: [android 11]
 - Specific to simulators: [No]

**Comment by aleksnied** [comment]
I have reproduced a very similar issue to this (probably the same). I set up an upload in TransferUtility and connected the phone via Charles proxy using throttling. 
- At first I had normal 3g-like speeds: the upload state changed to IN_PROGRESS and progressed smoothly
- Then I reduced to 30kbps: the upload state remained unchanged and upload still trickled along
- Then further to 3kbps: the upload halted, no state change to WAITING_FOR_NETWORK
- I waited 5 minutes. No state change, no upload progress.
- I then increased speed back up to full WIFI speed: the upload remained stuck with no progress and state still IN_PROGRESS

Let me know if you need more details of my set up. I essentially have:

TransferNetworkLossHandler.getInstance(context)
val awsMobileClient = AWSMobileClient.getInstance()
val clientConfig = ClientConfiguration()
clientConfig.connectionTimeout = 15 * 1000
clientConfig.socketTimeout = 30 * 1000
val amazonS3Client = AmazonS3Client(awsMobileClient, s3Config.region, clientConfig)
TransferUtility.builder()
            .context(context)
            .awsConfiguration(awsMobileClient.configuration)
            .s3Client(amazonS3Client)
            .build()

**Comment by raphkim** [comment]
Hi, 
Currently, the `WAITING_FOR_NETWORK` status is reserved for a specific case when the phone's WIFI/Data (whichever one was being used when the transfer was started) is turned off explicitly.

I will tag this issue as a feature request for improved network management for `TransferUtility` and discuss further action with my team. Thank you.

**Comment by raphkim** [comment]
@aleksnied , thank you for the repro steps. It appears that your issue differs slightly from the original post and I do see a certain behavior that concerns me in your description:
> I then increased speed back up to full WIFI speed: the upload remained stuck with no progress and state still IN_PROGRESS

It should have either recovered gracefully or failed with callback, but it appears that neither was true in your case. Would you be able to open up a separate issue for us to track? Thanks.

**Comment by aleksnied** [comment]
sure thing

**Comment by aleksnied** [comment]
https://github.com/aws-amplify/aws-sdk-android/issues/2236

**Comment by vivekgabadiya** [comment]
Hi @raphkim ,
 Thanks for your reply. I am also looking forward for the solution of problem given by @aleksnied .
