### ISSUE TITLE
Video upload failed after uploading 100%

### ISSUE THREAD

**Issue by vivekgabadiya** [aws-amplify/aws-sdk-android#2217]
**Describe the bug**
I am trying to upload a video of size 70-90 Mb with internet upload speed of 30
Mbps. I observe my upload failed most of the time between 90 - 100% sometimes
it's getting failure after uploading 100% also.

AWS configuration is as follows:
```java
clientConfiguration.withMaxErrorRetry(3); // 3 retries
clientConfiguration.withConnectionTimeout(120000); // 120,000 ms
clientConfiguration.withSocketTimeout(120000); // 120,000 ms
```

Getting the below exception 
> E/UploadPartTask: Encountered error uploading part 
>     com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout

One more question I would like to ask, Is `HTTPS request: timeout` also
dependends on the bucket reagion? I am trying to upload from India and my
bucket region is us-east-1. Please suggest.

**To Reproduce**
Using TransferUtility sample app to upload 4K video files. You will get upload
failure on the first try or subsequent tries.

**Expected behavior**
The upload should work fine if we are having good bandwidth.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [2.19.0]
 - Device: [Samsung S20+]
 - Android Version: [Android 11]
 - Specific to simulators: [No]

**Comment by raphkim** [comment]
Hi @vivekgabadiya ,
`TransferUtility` has built-in mechanism for recovering from loss of internet connection, but not from unstable connectivity. 
May I suggest that you add a retry logic in your app to resume your transfer after it has failed due to network-related issues?
Transferred data is not deleted, so a transfer that failed due to slow connectivity should be recoverable by simply resuming it.

**Comment by vivekgabadiya** [comment]
Hi @raphkim,
 Thanks for your reply and sorry delay in response. I have already implemented to retry 10 times once getting timeout exception but it keeps failing with the same exception for every retry. Do you think it is because of bucket region because I am trying to upload from India and my bucket region is us-east-1.

**Comment by raphkim** [comment]
There has been a change in `TransferUtility` to make large file uploads to be more reliable. Please try updating the SDK to v2.22.7 for improved experience.
