### ISSUE TITLE
Typo: getSessionCredentitalsExpiration

### ISSUE THREAD

**Issue by mojodna** [aws-amplify/aws-sdk-android#2218]
[`CognitoCredentialsProvider.getSessionCredentitalsExpiration()`](https://github.com/aws-amplify/aws-sdk-android/blob/8018b729f6508944507eab9a097a50615c4576ba/aws-android-sdk-core/src/main/java/com/amazonaws/auth/CognitoCredentialsProvider.java#L443) is misspelled (should be `CognitoCredentialsProvider.getSessionCredentialsExpiration()`). Perhaps a fix for the next major version (and/or the addition of an alias in the next minor version)?

**Comment by changxu0306** [comment]
Thank you for pointing out this! We will fix it asap.

**Comment by changxu0306** [comment]
We have already fix this issue. It will be released in next version. I'll close this issue for now.
