### ISSUE TITLE
S3TransferUtility hanging without recovery or failure after network outage

### ISSUE THREAD

**Issue by aleksnied** [aws-amplify/aws-sdk-android#2236]
**Describe the bug**
Transfer utility hangs after network slows down, doesn't fail or resume upload.

**To Reproduce**
I set up an upload to S3 using TransferUtility and connected the phone via Charles proxy using throttling. 
- At first I had normal 3g-like speeds: the upload state changed to IN_PROGRESS and progressed smoothly
- Then I reduced to 30kbps: the upload state remained unchanged and upload still trickled along
- Then further to 3kbps: the upload halted, no state change to WAITING_FOR_NETWORK or any other state
- I waited 5 minutes. No state change, no upload progress. Changed to 0kbps, no failing out, no waiting for network, no resumption
- I then increased speed back up to full WIFI speed: the upload remained stuck with no progress and state still IN_PROGRESS
- After another 5 minutes, I switched on airplane mode. This caused the upload to finally FAILED (onError was called). Otherwise it hanged

Let me know if you need more details of my set up. I essentially have:

```
TransferNetworkLossHandler.getInstance(context)
val awsMobileClient = AWSMobileClient.getInstance()
val clientConfig = ClientConfiguration()
clientConfig.connectionTimeout = 15 * 1000
clientConfig.socketTimeout = 30 * 1000
val amazonS3Client = AmazonS3Client(awsMobileClient, s3Config.region, clientConfig)
TransferUtility.builder()
            .context(context)
            .awsConfiguration(awsMobileClient.configuration)
            .s3Client(amazonS3Client)
            .build()
```

**Which AWS service(s) are affected?**
Android S3TransferUtility

**Expected behavior**
I expected either the error callback to be called or the upload to resume and complete after connection speed increased back up.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.19.1
 - Device: Motorola G7
 - Android Version: 10
 - Specific to simulators: No

**Comment by aleksnied** [comment]
hey guys, Happy New Year :) Any update on this? thanks

**Comment by aleksnied** [comment]
Hey guys, have looked around your codebase. Maybe this can help:

I think the crux is that you rely on Android’s ConnectivityManager to pause/resume uploads via the TransferNetworkLossHandler. This gives very coarse-grained connectivity updates. You could be on a functioning 3g connection that then progresses to be functionally dead and ConnectivityManager will not tell you anything changed.

The only real way to know whether a network you are on has gone functionally dead is pinging.

Since you are streaming an upload and getting periodic progress updates that you feed to the SDK's listener, you could maybe implement a timing mechanism whereby if there are no updates for a very long period of time you 'switch' the TransferNetworkLossHandler to isConnected false, making the same network loss process you have in place kick in:
the emission of WAITING_FOR_NETWORK, and pausing all pending uploads, then resuming them later.

In terms of resuming the uploads, you also shouldn't just depend on ConnectivityManager. What happens if my 3g goes functionally dead, then comes back again? Not a peep from ConnectivityManager in this case. I would suggest implementing a mechanism where TransferNetworkLossHandler attempts to ping the network with exponential backoff whenever it's set to offline.

Something like the above would allow you to react to connectivity in real time and transition in and out of pausing uploads. It will make the SDK much more robust in variable networks.

Since all of the above is based on progress updates, this can actually be implemented as a wrap-around mechanism around the SDK. I'm going to attempt to do so when I have some time :)

**Comment by sdhuka** [comment]
@aleksnied thanks for the suggestions. We have addressed this concerns in the [dev-preview](https://github.com/aws-amplify/amplify-android/tree/dev-preview/aws-storage-s3/src/main/java/com/amplifyframework/storage/s3/transfer/worker) of [Amplify 2.0](https://github.com/aws-amplify/amplify-android/tree/dev-preview). I recommend you to either try Amplify 2.0 or open a PR with the fix here if you have already worked on it.
