### ISSUE TITLE
Cognito: SIGNED_IN status returned by "currentUserState()" even though the refresh token has expired

### ISSUE THREAD

**Issue by basikon** [aws-amplify/aws-sdk-android#2240]
I uses Cognito UserPool.
I think "currentUserState()" will return the SIGNED_OUT_USER_POOLS_TOKENS_INVALID after the refresh token is expired.
But I can get SIGN_IN status...

I made proguard-rules by referring to the settings in the below link.
But I'm worried that some settings are missing.
Please let me know if my rules are missing.

[consumer-proguard-rules.pro](https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-core/consumer-proguard-rules.pro)

Source code:
```
AWSMobileClient.getInstance().currentUserState(new Callback<UserStateDetails>() {
    @Override
    public void onResult(UserStateDetails result) {

        switch (result.getUserState()) {
            case SIGNED_IN:
                // Actually, SIGNED_IN status is returned after refresh token is expired.
                break;
            case SIGNED_OUT_USER_POOLS_TOKENS_INVALID:
                // I expected this status will return.
                break;
            default:
                break;
        }
    }

    @Override
    public void onError(Exception ex) {

    }
});
```
  
My proguard-rules:

```
########-------AWS--------#########
-keepnames class com.amazonaws.**
-keepnames class com.amazon.**
-keepnames class com.amazonaws.mobile.**
-keepnames class com.amazonaws.mobile.config.**
# Request handlers defined in request.handlers
-keep class com.amazonaws.services.**.*Handler
# The following are referenced but aren't required to run
-dontwarn com.fasterxml.jackson.**
-dontwarn org.apache.commons.logging.**
# Android 6.0 release removes support for the Apache HTTP client
-dontwarn org.apache.http.**
# The SDK has several references of Apache HTTP client
-dontwarn com.amazonaws.http.**
-dontwarn com.amazonaws.metrics.**
-dontwarn com.amazonaws.mobileconnectors.**
```

**Which AWS Services are you utilizing?**
Cognito

**Environment(please complete the following information):**
- 'com.amazonaws:aws-android-sdk-mobile-client:2.16.13'
- "com.amazonaws:aws-android-sdk-auth-userpools:2.16.12"

**Device Information (please complete the following information):**
 - Android Version: 8,9,10

**Comment by TrekSoft** [comment]
Hey, we're tracking this issue here #1827
