### ISSUE TITLE
not getting new token after expiration

### ISSUE THREAD

**Issue by mangeshsambare** [aws-amplify/aws-sdk-android#2241]
**Describe the bug**
I am using One Plus 2 & Samsung Galaxy A50 Android phones for testing. In my project I initialize `AWSMobileClient` and use its sign-in functionality. After successfully logging in, I get tokens from the `AWSMobileClient.getInstance().getTokens(callback)` function. But after the expiration time, this token is invalid. And after this case my app calling `AWSMobileClient.getInstance().getTokens(callback)` function for new token. This functionality is working fine for Samsung Galaxy A50 version. But for the One Plus 2, it is not working. It returns old expired token.

**To Reproduce**
Using following dependencies:

```gradle
implementation com.amazonaws:aws-android-sdk-mobile-client:2.19.1
implementation com.amazonaws:aws-android-sdk-cognitoauth:2.19.1
implementation com.amazonaws:aws-android-sdk-lambda:2.19.1
```

Steps:

1. Wait 1h until token expire or clear data or set time 5 minute time for expire token. Please do use One Plus 2 phone & Android version 6.0.1.
2. `AWSMobileClient.getInstance().initialize()`
3. `AWSMobileClient.getInstance().getTokens()`

**Expected behavior**
New token should be obtained, not older one. Maybe it is because of not updating shared preferences data for One Plus 2 phone, or version 6.0.1.

**Environment Information (please complete the following information):**
AWS Android SDK Version: 2.19.1
Device: One Plus 2
Android Version: Android 6.0.1
Specific to simulators: No

**Additional context**
Please do check shared preferences data. I debugged application. For Samsung or One Plus 7 Pro phones, it clears caches session after token expired. But for One Plus 2 device it is unable to create cached session. This may the reason. Hope it helps you.

**Comment by gpanshu** [comment]
If I understand correctly you are unable to clear the cache on the one plus 2 device? 

Are you doing a specific value removal from sharedPreference or are you clearing out your entire sharedpreferences data ?
