### ISSUE TITLE
Mqtt connection issue

### ISSUE THREAD

**Issue by sharad2970** [aws-amplify/aws-sdk-android#2246]
Hello,
trying to connect to IoT with Authenticated user but not connecting to Mqtt.
plz find the error message

```
com.amazonaws.services.cognitoidentity.model.ResourceNotFoundException: IdentityPool 'us-east-2:1d25e******' not found. (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 0a52b7)*
```

also while attaching policy, getting exception as **No policy found**
```
 try {
    AWSMobileClient.getInstance().identityId
    val attachPolicyReq = AttachPolicyRequest()
    attachPolicyReq.policyName = AWSConstant.ATTACH_POLICY
    attachPolicyReq.target = AWSMobileClient.getInstance().identityId
    val mIotAndroidClient = AWSIotClient(AWSMobileClient.getInstance())
    mIotAndroidClient.setRegion(Region.getRegion(Regions.US_EAST_2)) // tried us_east_1 as well
    mIotAndroidClient.attachPolicy(attachPolicyReq)
} catch (e: java.lang.Exception) {
    e.printStackTrace()
    Log.d(TAG, " attachPrincipal policy exception =  $e")
}
```

this is causing for authenticated user only, it works for an unauthenticated user

iot region = us_east_1
rest all in region =  us_east_2

Compiled sdk version 29
Device OnePlus Nord 
Android version 10
Thank you

**Comment by jpignata** [comment]
`setRegion` just sets the endpoint for the MQTT connection. Are you setting the region passed to `AWSMobileClient` to `us-east-1` ?

**Comment by sharad2970** [comment]
Resolved. Thank you

**Comment by jpignata** [comment]
Ah, okay! Let us know if we can help.

**Comment by sharad2970** [comment]
sure
