### ISSUE TITLE
what are the push notifications related metrics collected automatically by amplify lib ?

### ISSUE THREAD

**Issue by gvnavin** [aws-amplify/aws-sdk-android#2247]
**State your question**
What are the push notifications related metrics collected automatically by amplify lib ? What are those can be viewable in pinpoint console ? We are facing issues in notification delivery, there seems to be huge drop in notification delivery. 
So we would like to understand the automatic/default metrics emitted by amplify lib to understand the delivery stats better.

**Which AWS Services are you utilizing?**
AWS Pinpoint

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]
"aws-amplify": "1.1.23",
"aws-amplify-react-native": "0.2.5",

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators:

**Comment by rjuliano** [comment]
Push notification events get reported as `opened_notification`, `received_foreground`, `received_background` in the Pinpoint console. The attributes sent with those events depend on how the message is triggered and what options you have set on the client, but at a basic level it sends device information, campaign info (if applicable) and depending on whether you're using the [updateEndpointProfile](https://docs.amplify.aws/sdk/analytics/endpoints/q/platform/android#assigning-user-ids-to-endpoints) in your app, it will send some user info as well.
