### ISSUE TITLE
AmazonClientException: Unable to unmarshall error response: Response Code: 504

### ISSUE THREAD

**Issue by beczesz** [aws-amplify/aws-sdk-android#2266]
Both Cognito and AwsLambda calls are failing now with the error

> com.amazonaws.AmazonClientException: Unable to unmarshall error response (Unable to parse JSON String.). Response Code: 504, Response Text: Gateway Time-out, Response Headers: {X-Android-Selected-Protocol=http/1.1, Server=awselb/2.0, Connection=keep-alive, X-Android-Response-Source=NETWORK 504, X-Android-Sent-Millis=1606314513478, Content-Length=132, X-Android-Received-Millis=1606314523710, Date=Wed, 25 Nov 2020 14:28:43 GMT, Content-Type=text/html}

It happens on multiple devices so it is not something local on my side. Has anybody seen this? I started to see this an hour ago.

Regards, 
Szabolcs

**Comment by jesusdanielx15** [comment]
same problem here, my implementation is:

implementation 'com.amazonaws:aws-android-sdk-core:2.7.7'
    implementation 'com.amazonaws:aws-android-sdk-s3:2.7.2'
    implementation('com.amazonaws:aws-android-sdk-mobile-client:2.7.+@aar') { transitive = true }
    implementation('com.amazonaws:aws-android-sdk-auth-userpools:2.7.+@aar') { transitive = true }
    implementation 'com.amazonaws:aws-android-sdk-cognito:2.7.+'

**Comment by jamesonwilliams** [comment]
AWS is experiencing a Large Scale Event (LSE). Please follow the [AWS Service Health Dashboard](https://status.aws.amazon.com/).

> Increased Error Rates
>
> 8:05 AM PST: Kinesis is experiencing increased API errors in the US-EAST-1 Region. This is also causing issues with ACM, Amplify Console, API Gateway, AppStream2, AppSync, Athena, Cloudformation, Cloudtrail, CloudWatch, Cognito, Connect, DynamoDB, EventBridge, IoT Services, Lambda, LEX, Managed Blockchain, Resource Groups, SageMaker, Support Console, and Workspaces. This issue has also affected our ability to post updates to the Service Health Dashboard.
