### ISSUE TITLE
NullPointerException in AWSMobileClient.signOut

### ISSUE THREAD

**Issue by imetodieva** [aws-amplify/aws-sdk-android#2268]
I'm getting NullPointer from AWSMobileClient.signOut function 

**To Reproduce**
Call to AWSMobileClient.getInstance().signOut()

**Which AWS service(s) are affected?**
AWSMobileClient

**Expected behavior**
No crash happening.

**Environment Information :**
 - com.amazonaws:aws-android-sdk-mobile-client:2.18.0
 - Devices: [Huawei Mate 20 RS , Samsung Galaxy S10,Samsung Galaxy Note8,Huawei HUAWEI P smart+ 2019,Samsung Galaxy A51 etc.]
 - Android Version: [Android 9 Pie, Android 10, Android 11]
 - Specific to simulators: [No]

**Additional context**
Not happening on emulators.
App min version is 21.
I can only share part of the stacktrace :

Caused by: java.lang.NullPointerException: 
  at com.amazonaws.mobile.client.AWSMobileClient.signOut (AWSMobileClient.java:1467)

**Comment by shikhar-91s** [comment]
Was this working fine previously? If this was working fine previously and you are getting this now all of a sudden, then it might be related to recent Aws Outage. For more info: https://www.theverge.com/2020/11/25/21719396/amazon-web-services-aws-outage-down-internet.

**Comment by shikhar-91s** [comment]
As you have only shown part of the stack trace it seems to me its a Null Pointer Exception on reference returned by getInstance(). Just check whether AwsMobileClient.getInstance() (probably a singleton) is null or not using debugger. You might be lazily initialising it somewhere in code but you called sign out first without initialising it properly.

**Comment by imetodieva** [comment]
I haven't seen this problem before. From the stacktrace I see that the problem lies within **mStore** field of the AWSMobileClient.java being null . If the singleton wasn't initialized other earlier calls to the library would be problematic but they aren't. And for the part with the outage - I don't think that is it because it's not making the global signout of all sessions, the code doesn't seem to make any other thing than to clear out local data. If it were something other than that **mStore** field wouldn't that mean that the **mFederatedLoginsMap.clear()** would also fail with nullpointer? This is assumption made by examining the method from the library that is invoked:

/**
     * Clears local tokens so that the client is in a signed-out state.
     */
    @AnyThread
    public void signOut() {
        mCognitoUserSession = null;
        if (userpool != null) {
            userpool.getCurrentUser().signOut();
            userpool.getUser().signOut();
        }
        if (cognitoIdentity != null) {
            cognitoIdentity.clear();
        }
        if (IdentityManager.getDefaultIdentityManager() != null) {
            IdentityManager.getDefaultIdentityManager().signOut();
        }
        mFederatedLoginsMap.clear();
        mStore.clear(); //**the crash happens on this line**
        String hostedUIJSON = null;
        if (awsConfiguration.optJsonObject(AUTH_KEY) != null && awsConfiguration.optJsonObject(AUTH_KEY).has("OAuth")) {
            try {
                hostedUIJSON = awsConfiguration.optJsonObject(AUTH_KEY).getJSONObject("OAuth").toString();
            } catch (JSONException e) {
                e.printStackTrace();
            }
            if (hostedUI != null) {
                hostedUI.signOut(true);
            }
            if (mOAuth2Client != null) {
                mOAuth2Client.signOut();
            }
        }
        mStore.set(HOSTED_UI_KEY, hostedUIJSON);
        setUserState(getUserStateDetails(false));
        releaseSignInWait();
    }

**Comment by imetodieva** [comment]
The issue persists in com.amazonaws:aws-android-sdk-mobile-client:2.22.2 version. Any updates ?

**Comment by raphkim** [comment]
Hi @imetodieva , we will close #2380 in favor of this and investigate the root cause.
