### ISSUE TITLE
App goes in background after calling the method showSignIn()

### ISSUE THREAD

**Issue by shishir87** [aws-amplify/aws-sdk-android#2279]
**Describe the bug**
We are facing a problem with latest AWS android SDK v2.19.3 for social login. The issue is, as soon as we call the method named “showSignIn()” for google login, the app goes in background.

This issue is observed only with latest android SDK v2.19.3.
There is no such issue occurred when we were using older SDK v2.16.3

**To Reproduce**
A code sample or steps:
```
In my app there are two Social Sign In options i.e. Facebook and Google

To enable social sign in, I am using below code Snippet.
==================
val hostedUIFb = HostedUIOptions.builder()
                .scopes("openid", "email")
                .identityProvider("Google") // or Facebook
                .build()
val signInUIOptions = SignInUIOptions.builder()
            .hostedUIOptions(hostedUi)
            .build()
        AWSMobileClient.getInstance()
            .showSignIn(requireActivity(), signInUIOptions, object : Callback<UserStateDetails> {      // [1]
                override fun onResult(details: UserStateDetails) {

                }

                override fun onError(e: Exception) {
                    Log.e(TAG, "onError: ", e)
                }
            })
==================
```

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.19.3.
 - Android Version: Android 10 (Q)

**Comment by raphkim** [comment]
Your issue appears to be similar to #2145. Have you tried updating your gradle version?

**Comment by raphkim** [comment]
Hi @shishir87,
It looks like there have been some breaking changes from 2.17.x to 2.18.0 for Hosted UI setup. Please [follow this guide](https://docs.amplify.aws/sdk/auth/hosted-ui/q/platform/android#setup-amazon-cognito-hosted-ui-in-android-app) to correctly adjust `AndroidManifest.xml` file as necessary.

**Comment by shishir87** [comment]
@raphkim Thank you so much!!. After referring the guide and doing the necessary changes, the app in not going into background. Its working fine
