### ISSUE TITLE
Hosted UI - Cognito - Google - Sign out does not clear the user from device

### ISSUE THREAD

**Issue by sdhwani13** [aws-amplify/aws-sdk-android#2291]
After signing out from Hosted UI of google identity, the sdk signs out. But signing in again signs in the previous user automatically without asking for credential.

Following the documentation for Hosted UI:
https://docs.amplify.aws/sdk/auth/hosted-ui/q/platform/android#setup-amazon-cognito-hosted-ui-in-android-app
Sign In call:

    HostedUIOptions hostedUIOptions = HostedUIOptions.builder()
            .scopes("openid", "email")
            .build();
    SignInUIOptions signInUIOptions = SignInUIOptions.builder()
            .hostedUIOptions(hostedUIOptions)
            .build();
    AWSMobileClient.getInstance().showSignIn(this, signInUIOptions, new Callback<UserStateDetails>() {
        @Override
        public void onResult(UserStateDetails details) {
            Log.d(TAG, "onResult: " + details.getUserState());
        }

        @Override
        public void onError(Exception e) {
            Log.e(TAG, "onError: ", e);
        }
    });

Sign Out flow: 

    AWSMobileClient.getInstance().signOut(SignOutOptions.builder().invalidateTokens(true).build(), new Callback<Void>() {
        @Override
        public void onResult(Void result) {
            Log.d(TAG, "onResult: ");
        }

        @Override
        public void onError(Exception e) {
            Log.e(TAG, "onError: ", e);
        }
    });

The same works for Apple sign in and sign out, the next sign in asks for apple user info. 
Is the google sign out different? Are any calls needed other than the sdk call to sign out the user?

 - AWS Android SDK Version: 2.19.0
 - Device: Samsung Galaxy M21
 - Android Version: 10
 - Specific to simulators: No

The account logged in automatically is not the same as the google account the android device is configured with.

**Comment by raphkim** [comment]
This issue is now resolved with [v2.24.0](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.24.0). Please follow the [updated documentation](https://docs.amplify.aws/sdk/auth/hosted-ui/q/platform/android#setup-amazon-cognito-hosted-ui-in-android-app) to apply this fix :)
