### ISSUE TITLE
A video clip downloaded from AWS cloud storage is not getting shared on WhatsApp

### ISSUE THREAD

**Issue by shishir87** [aws-amplify/aws-sdk-android#2309]
Hi,

I am developing an Android app which has the feature of storing live streaming video clips on cloud and then user can playback those videos as well as user can download them and share on social media.

I am able to download the video clip successfully in phone's local storage and then downloaded clips are getting played in other video players like VLC player. But when I try to send the video file over whatsapp its not happening. I get the error prompt in WhatsApp saying "Can't send this video. Choose a different video and try again".

I am attaching two video files here. One is sample video and other one is the actual video which was created via live streaming

https://user-images.githubusercontent.com/12554967/102882554-87319200-4474-11eb-83d1-c06aee0171e3.mp4

https://user-images.githubusercontent.com/12554967/102882572-8f89cd00-4474-11eb-86ef-83fd18eaefc2.mp4

**Comment by richardmcclellan** [comment]
Here are a few things to check to see why your video is not shareable via WhatsApp: https://www.technipages.com/fix-whatsapp-error-this-video-could-not-be-sent

Closing this issue as it is not related to AWS or the SDK, but rather with What's App.
