### ISSUE TITLE
Textract not found in the new version 2.20.1

### ISSUE THREAD

**Issue by dwitiyabhatt** [aws-amplify/aws-sdk-android#2313]
**Describe the bug**
It has been written in the md files that textract module is available. However, If I put this gradle 

**To Reproduce**
A code sample or steps:
```
implementation 'com.amazonaws:aws-android-sdk-SERVICE:2.20.1'
```

**It is not showing me any Textract class to import**

For Eg.
AmazonTextract client = AmazonTextractClientBuilder.defaultClient();
 This line is showing error of class not found.

**Expected behavior**
Actually, It should give me Textract class so I can code further

**Screenshots**

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [e.g. 2.20.1]
**Additional context**

**Comment by jamesonwilliams** [comment]
Hi @dwitiyabhatt! 

Firstly, I'd suggest looking at the Predictions category of the Amplify Android Library. It is a higher level interface that will allow you to do things like extracting text from an image.

See here: https://docs.amplify.aws/lib/predictions/identify-text/q/platform/android

---------------

As to your actual inquiry:

Version 2.20.1 of the Textract SDK for Android is [available from Maven, as seen here](https://repo1.maven.org/maven2/com/amazonaws/aws-android-sdk-textract/2.20.1/aws-android-sdk-textract-2.20.1.aar).

To include it, add this to the `dependencies` block in your app's `build.gradle`:
```gradle
implementation 'com.amazonaws:aws-android-sdk-textract:2.20.1'
```
To use it, you'll call the [`AmazonTextractClient(AWSCredentialsProvider)`](https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-textract/src/main/java/com/amazonaws/services/textract/AmazonTextractClient.java#L173-L206) constructor. For example:
```kotlin
// Build a client: suggest to use AWSMobileClient as the credentials provider
// but for simple testing, this example shows some use of IAM user credentials.
val iamUserCredentials = BasicAWSCredentials(accessKey, secretKey)
val credentialsProvider = StaticCredentialsProvider(iamUserCredentials)
val textract = AmazonTextractClient(credentialsProvider)

// Use textact client to detect text in an image you're storing in S3.
val document = Document().withS3Object("s3://yourbucket/yourkey.jpg")
val request = DetectDocumentRequest().withDocument(document)
val result = textract.detectDocumentText(request)
```

Let me know if you have any more questions!

**Comment by dwitiyabhatt** [comment]
Thank you very much!
