### ISSUE TITLE
why cannot set custom endpoint

### ISSUE THREAD

**Issue by yang5155324** [aws-amplify/aws-sdk-android#2314]
We set the endpoint as below, but it doesn't work. How can I set a custom endpoint, using my own domain?

```java
s3client.setEndpoint("http://upload.acceleratingdomain.com");
```

The infrastructure being used is as below:
```console
china user---(upload)----Wangsu CDN accelerating domain-----(original host will be set S3 endpoint)---S3
```
If we can change the upload domain, it will work well. Because we tested that with the AWS CLI.

**Comment by rjuliano** [comment]
Try to also set the client options passing in an object that with pathStyleAccess set to true. Without that, I believe it will always try to add the bucket name to the host name, which may be causing the failure in your case.

```java
S3ClientOptions options = S3ClientOptions.builder().setPathStyleAccess(true).build();
AmazonS3Client s3client = new AmazonS3Client(new BasicSessionCredentials(...);
s3client.setS3ClientOptions(options);
s3client.setEndpoint("https://<your domain name>");
PutObjectResult result = s3client.putObject(bucket, key, "This is a test");
```

**Comment by changxu0306** [comment]
Please try the above solution. I'll close this issue for now. You could reopen it anytime if you have further questions.
