### ISSUE TITLE
How to extract data from PDF

### ISSUE THREAD

**Issue by dwitiyabhatt** [aws-amplify/aws-sdk-android#2317]
**I was able to fetch data from the image but my requirements is to perform textract process on the PDF document. Is it possible? If yes, how? If no, any other alternative?**

**I am using following **
implementation 'com.amazonaws:aws-android-sdk-textract:2.20.1'
implementation 'com.amazonaws:aws-android-sdk-sqs:2.20.1'
implementation 'com.amazonaws:aws-android-sdk-sns:2.20.1'

**I am performing coding from following link**
https://docs.aws.amazon.com/textract/latest/dg/async-analyzing-with-sqs.html

It shows error in this line :
    sns = AmazonSNSClientBuilder.defaultClient();
   sqs= AmazonSQSClientBuilder.defaultClient();

It shows AmazonSNSClientBuilder is not found. 

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.20.1]

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel 3A, One Plus 3T]
 - Android Version: [e.g. Oreo+]
 - Specific to simulators:

**Comment by jamesonwilliams** [comment]
Hey @dwitiyabhatt! If you're trying to do text extraction on Android, please use [Amplify Android's Predictions category](https://docs.amplify.aws/lib/predictions/identify-text/q/platform/android).

-----------

The guide you've referenced is using the [V1 Java SDK](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/welcome.html).

The _Android SDK_ does happen to have support for SNS and SQS, as well. If you'd like to try and follow the guide, anyway, please use the [`AmazonSQLClient`](https://github.com/aws-amplify/aws-sdk-android/blob/1383637ca37ce686e7a82ea7ef23acf71fb2b62b/aws-android-sdk-sqs/src/main/java/com/amazonaws/services/sqs/AmazonSQSClient.java#L264-L297) and [`AmazonSNSClient`](https://github.com/aws-amplify/aws-sdk-android/blob/1383637ca37ce686e7a82ea7ef23acf71fb2b62b/aws-android-sdk-sns/src/main/java/com/amazonaws/services/sns/AmazonSNSClient.java#L191-L224) constructors.

```java
AmazonSNSClient sns = new AmazonSNSClient(credentialsProvider);
AmazonSQSClient sqs = new AmazonSQSClient(credentialsProvider);
```

If you don't already have a way to provide credentials, look at the [AWSMobileClient](https://docs.amplify.aws/sdk/auth/how-it-works/q/platform/android).
