### ISSUE TITLE
AWSMobileClient internal thread occasionally throwing uncatchable UnknownHostException

### ISSUE THREAD

**Issue by jprofit** [aws-amplify/aws-sdk-android#2319]
**Describe the bug**
Occasionally, when coming out of standby my app crashes due to an uncaught exception (UnknownHostException) coming from an internal AWSMobileClient thread. Since the exception comes from an internal AWS thread, I don't have a way of catching it to avoid the crash. Here is the stack trace:
```console
Caused by java.net.UnknownHostException:
com.amazonaws.http.UrlHttpClient.writeContentToConnection (UrlHttpClient.java:162)
com.amazonaws.http.UrlHttpClient.execute (UrlHttpClient.java:75)
com.amazonaws.http.AmazonHttpClient.executeHelper (AmazonHttpClient.java:371)
com.amazonaws.http.AmazonHttpClient.execute (AmazonHttpClient.java:212)
com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.invoke (AmazonCognitoIdentityProviderClient.java:6319)
com.amazonaws.services.cognitoidentityprovider.AmazonCognitoIdentityProviderClient.initiateAuth (AmazonCognitoIdentityProviderClient.java:4283)
com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.refreshSession (CognitoUser.java:2378)
com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getCachedSession (CognitoUser.java:976)
com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession (CognitoUser.java:771)
com.amazonaws.mobile.client.AWSMobileClient$11.run (AWSMobileClient.java:1763)
com.amazonaws.mobile.client.internal.InternalCallback$1.run (InternalCallback.java:101)
java.lang.Thread.run (Thread.java:919)
```
**To Reproduce**
Reproducing this issue is not easy. It happens about 1 out of every 10-20 phone wakes using the power button.

**Which AWS service(s) are affected?**
AWSMobileClient

**Expected behavior**
The app should not crash in the event of a failed AWSMobileClient operation.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.20.0
 - Device: Samsung S10
 - Android Version: 10
 - Specific to simulators: No

**Comment by changxu0306** [comment]
Hello, thanks for reporting the issue! Could you please attach your code snippet?

**Comment by jprofit** [comment]
Hi,
I'm not really sure what code to attach since my app only uses Amplify for access to cognito. 

Here is the initialization code:
class MyApp: Application() {
...
override fun onCreate() {
        super.onCreate()
        try {
            Amplify.addPlugin(AWSApiPlugin())
            Amplify.addPlugin(AWSCognitoAuthPlugin())
            awsConfiguration = AWSConfiguration(applicationContext)
            awsConfiguration.configuration = "Default"
            Amplify.configure(applicationContext)
        } catch (e: AmplifyException) {
            Log.e("Soovu", "Could not initialize Amplify", e)
        }
    }
```
Here is my (edited) amplifyconfiguration.json:
{
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify-cli/0.1.0",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {
                            "PoolId": "XXX",
                            "Region": "us-west-2"
                        }
                    }
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "xxx",
                        "AppClientId": "xxx",
                        "AppClientSecret": "xxx",
                        "Region": "us-west-2"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}
```

I'm happy to share other code but not sure what would be helpful since the crash is not the direct result of any API call that I make (see stack trace).

**Comment by jprofit** [comment]
Can I get an update on this issue? It's 6 months old and still occuring.

**Comment by sktimalsina** [comment]
@jprofit Apologies for getting back to you this late. 
The given stack trace can occur when the app is trying to fetch the token from Cognito. And, if somehow the host or IP used for connecting cannot be resolved, maybe because of DNS latency etc, the error is thrown in HttpClient implementation level. All of these is done in a separate thread as you can see. 
Interestingly, I found catch block for all the code segments where these are accessed and am not able to pinpoint the exact code block. 
Unfortunately, for some reason, the line numbers in your stack trace doesn't seem to match the source code line number. If you are still facing the issue, would you be able to try the latest version of the SDK and share the stack trace again? And ideally bit more logs surrounding it as I wanted to understand the context where the error is taking place at.
