### ISSUE TITLE
Not able to assign S3Object

### ISSUE THREAD

**Issue by dwitiyabhatt** [aws-amplify/aws-sdk-android#2322]
**I have integrated code as per amlify and used those libraries but I have an issue when passing S3object**

**Following services are being used by me**
```gradle
implementation 'com.amazonaws:aws-android-sdk-textract:2.20.1'
implementation 'com.amazonaws:aws-android-sdk-sqs:2.20.1'
implementation 'com.amazonaws:aws-android-sdk-sns:2.20.1'
```

**Provide code snippets (if applicable)**
```java
     StartDocumentAnalysisRequest req = new StartDocumentAnalysisRequest()
                .withFeatureTypes("TABLES","FORMS")
                .withDocumentLocation(new DocumentLocation()
                    .withS3Object(new S3Object()
                        .withBucket(bucket)
                        .withName(document)))
                .withJobTag("AnalyzingText")
                .withNotificationChannel(channel);
```
This is how I am passing S3object in  making analysis request.

I am getting error at this line :
```java
 StartDocumentAnalysisResult startDocumentAnalysisResult = textract.startDocumentAnalysis(req);
```

Error is :
> com.amazonaws.services.textract.model.InvalidParameterException: Request has invalid parameters (Service: AmazonTextract; Status Code: 400; Error Code: InvalidParameterException; Request ID: a010e356-9563-425b-a0c6-c1b7019f0463)

When investigated this error. I came to know that It comes when S3object is not passed in the request.
Ref link : https://docs.aws.amazon.com/textract/latest/dg/API_StartDocumentTextDetection.html. 
(See InvalidParameterException) 

Please note :
- S3object name and bucket name is perfect
- Region of the service is perfect(US East (N. Virginia) us-east-1)
- Both bucket and S3object uploaded on console is public which can be accessed by anyone.

So Is there anything I'm Still missing?

**Environment(please complete the following information):**
 - SDK Version: [2.20.1]

**Device Information (please complete the following information):**
 - Device: [One Plus 3T]
 - Android Version: [Oreo]

**Comment by dwitiyabhatt** [comment]
Side note,
I also investigated this issue with aws support person and he used cloud trail to check whether the S3object on console was okay or not with the following command :
aws textract start-document-text-detection \--document-location 'S3Object={Bucket=<bucketname>,Name=<filename.pdf>}'

It ran perfectly in cloudtrail and he said there is no issue with the S3object but issue maybe in the code of StartDocumentAnalysisRequest.

**Comment by jamesonwilliams** [comment]
First off, please checkout [Amplify Predictions](https://docs.amplify.aws/lib/predictions/identify-text/q/platform/android).

It uses the [`AnalyzeDocument`](https://docs.aws.amazon.com/textract/latest/dg/API_AnalyzeDocument.html) API, internally:

https://github.com/aws-amplify/amplify-android/blob/08ce7f581ee68deabd094d2aadb314b26d4df2ca/aws-predictions/src/main/java/com/amplifyframework/predictions/aws/service/AWSTextractService.java#L114-L122

**Comment by dwitiyabhatt** [comment]
I am not extracting any image. I want to extract pdf document. which has to be on s3 console.

**Comment by jamesonwilliams** [comment]
> which has to be on s3 console

The console uses the same public APIs that are available from the various SDKs.

**Comment by sktimalsina** [comment]
Please confirm if you are not prepending "s3://" to your bucket name and have proper extension to the file name when creating the S3Object as in 
```
String bucket = "bucketName";
String document = "fileName.pdf;"

S3Object s3obj = new S3Object()
                        .withBucket(bucket)
                        .withName(document);
```
