### ISSUE TITLE
How to get UserMFASettingList value?

### ISSUE THREAD

**Issue by andrecardoso** [aws-amplify/aws-sdk-android#2336]
**State your question**

I'm trying to implement the MFA setup flow in the android app I'm working on. I'm trying to read the value of UserMFASettingList from the [getUser response](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_GetUser.html) using the [`CognitoUser#getDetails` method](https://github.com/aws-amplify/aws-sdk-android/blob/bd75e6ad568549a11bb5b5635faa631c93a647ca/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser.java#L1464) but the value is not included in the result object:

```kotlin
         userPool.currentUser.getDetails(object : GetDetailsHandler {
            override fun onSuccess(cognitoUserDetails: CognitoUserDetails) {
                val settings = cognitoUserDetails.settings.settings["UserMFASettingList"]
                continuation.resume(settings?.contains("SOFTWARE_TOKEN_MFA") == true)
            }

            override fun onFailure(exception: Exception) {
                continuation.resumeWithException(exception)
            }
        })
```

The `cognitoUserDetails.settings.settings` map always return empty, even when the backend responds with some value.

By looking at the SDK code I suspect the problem happens because `getDetails` uses [`GetUserResult#getMFAOptions()`](https://github.com/aws-amplify/aws-sdk-android/blob/bd75e6ad568549a11bb5b5635faa631c93a647ca/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/mobileconnectors/cognitoidentityprovider/CognitoUser.java#L1490) instead of `getUserMFASettingList` and it seems that `MFAOptions` param [is no longer supported](https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/services/cognitoidentityprovider/model/GetUserResult.java#L243).

Is there another way to read the "UserMFASettingList" value?

**Which AWS Services are you utilizing?**

Amazon Cognito

**Environment(please complete the following information):**
 - SDK Version: 2.19.3

**Device Information (please complete the following information):**
 - Device: Nexus 5X
 - Android Version: 8

**Comment by rjuliano** [comment]
You would probably need to use the [adminGetUser](https://github.com/aws-amplify/aws-sdk-android/blob/e37db7ee5cc166736bcf6db00635b1f2b63d141c/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/services/cognitoidentityprovider/AmazonCognitoIdentityProviderClient.java) API from the low-level provider
