### ISSUE TITLE
How to gather the Amazon S3 request ID in log ?

### ISSUE THREAD

**Issue by shiv71** [aws-amplify/aws-sdk-android#2344]
**State your question**
How do I gather the Amazon S3 request ID values requested by AWS Support in AWS Android SDK?

**Which AWS Services are you utilizing?**
AWS Android SDK (AWSTransferUtility)
```gradle
implementation('com.amazonaws:aws-android-sdk-mobile-client:2.20.+@aar') { transitive = true }
implementation 'com.amazonaws:aws-android-sdk-s3:2.20.+'
```
**Environment(please complete the following information):**
 - SDK Version: [2.20]

**Device Information (please complete the following information):**
 - Device: [Samsung]
 - Android Version: [10]

We've tried to get the  2 Amazon S3 request ID values (x-amz-request-id,x-amz-id-2) through verbose logging in Android Studio but we're unable to get these 2 Id's. Here is the log we've got

```
2021-01-28 20:05:59.612 16013-17504/com.xxxx.XXXXX D/S3MetadataResponseHandl: Server is ignored.
2021-01-28 20:05:59.613 16013-17504/com.xxxx.XXXX D/S3MetadataResponseHandl: x-amz-request-id is ignored.
2021-01-28 20:05:59.613 16013-17504/com.xxxx.XXXX D/S3MetadataResponseHandl: x-amz-id-2 is ignored.
2021-01-28 20:05:59.613 16013-17504/com.xxxx.XXXX D/S3MetadataResponseHandl: Date is ignored.

```

We can see that we got ignored in the log messages. Is there any configuration we need to set on our android client S3 SDK?

**Comment by rjuliano** [comment]
If you're working with a debug build, you can try using the `curlLogging` option in the `ClientConfiguration` passed in to the S3 client. 

https://docs.aws.amazon.com/AWSAndroidSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#setCurlLogging-boolean-

Or you can try adding your own request handlers as resources in your app. 

https://github.com/aws-amplify/aws-sdk-android/blob/ce23da181fc925f33d40b685301930db98e2870a/aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L634

https://github.com/aws-amplify/aws-sdk-android/blob/ce23da181fc925f33d40b685301930db98e2870a/aws-android-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L634
