### ISSUE TITLE
Transfer Utility fails to upload large videos parallel 

### ISSUE THREAD

**Issue by shiv71** [aws-amplify/aws-sdk-android#2345]
**Describe the bug**
We tested our code with multiple videos parallel and we found that if videos are small then upload runs parallel but if videos are large in size then upload doesn't run parallel. We've tested on Samsung galaxy S9 you can find full tech specs here [https://www.gsmarena.com/samsung_galaxy_s9-8966.php](TechSpecs)

We have tested 2 55MB videos upload using a single transfer utility object and both uploaded parallel.
We have tested 2 178MB videos upload using a single transfer utility object and the second video started after the first one almost uploaded like 99%.

This is the issue we are facing. Is there any flag or configuration we need to set in our code? 

We're creating 2 different transfer utilities for each type of upload e.g one for post and one for comment. Is this right approach or should we use a single transfer utility instance? I assume 2 transfer utility instances will upload 2 or more videos parallel. Correct me If I'm wrong.

**To Reproduce**
Created a single instance of Transfer Utility and uploaded 2 large videos and observe the behaviour.
Created 2 instances of Transfer Utility and uploaded 2 large videos one video with each instance and observe the behaviour.

**Which AWS service(s) are affected?**
AWSTransferUtility

**Expected behavior**
Large size videos should upload parallel 

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [2.20+]
 - Device: [Samsung]
 - Android Version: 10]

**Additional context**

**Comment by jamesonwilliams** [comment]
There's a bug with large file uploads right now. This is likely a duplicate of https://github.com/aws-amplify/aws-sdk-android/issues/1947.

**Comment by jamesonwilliams** [comment]
Oh, I see @shiv71. Your point is about sequencing of successful downloads.

**Comment by shiv71** [comment]
@jamesonwilliams my point is about parallel uploads.

**Comment by jamesonwilliams** [comment]
@shiv71 You should include some code, so that we can see what you're doing.

**Comment by alokipandey-qa** [comment]
hey there, I am also facing same issue while uploading large(1GB..3GB) videos to s3 from android application. I am using transfer TransferUtility w/o any custom options.
It starts uploading goes for about 20..25% then I get callback in onStateChanged() with state=TransferState.FAILED.
is there any way to debug it further? I am kind of stuck here, any workaround/suggestions might help.
I am putting some code below:

//codeGoesHere

**val transferUtility = TransferUtility.builder()
                .context(context.applicationContext)
                .s3Client(s3Client)
                .build()

val transferObserver = transferUtility?.upload(BUCKET_NAME, fileKey, file, CannedAccessControlList.PublicRead)
transferObserver.setTransferListener(awsTransferListener)**

**Comment by alokipandey** [comment]
I also had this issue and I resolved it while going through multiple stackoverflow /github /aws doc pages. leaving a link to my documentation below for whomsoever may need it.
https://alokipandey.medium.com/upload-to-aws-s3-from-android-s3-in

**Comment by raphkim** [comment]
There has been a change in `TransferUtility` to make large file uploads to be more reliable. Please try updating the SDK to v2.22.7 for improved experience.
