### ISSUE TITLE
Analyzing a video stored in an Amazon S3 bucket with Android

### ISSUE THREAD

**Issue by 24Lathiya** [aws-amplify/aws-sdk-android#2354]
**How to detecting inappropriate(Explicit Nudity) stored videos in S3 bucket?*
I don't know how to use Amazon Rekognition  in android to analyse videos.
I have go through [this](https://docs.aws.amazon.com/rekognition/latest/dg/video-analyzing-with-sqs.html)  but get error in below code.
 

```
sns = AmazonSNSClientBuilder.defaultClient();
        sqs= AmazonSQSClientBuilder.defaultClient();
        rek = AmazonRekognitionClientBuilder.defaultClient();
```

Example will be more appreciable.
@jamesonwilliams

**Comment by rjuliano** [comment]
That example is for the Java SDK which has different syntax for than the Android SDK. The javadoc for the Rekognition client can be found [here](https://aws-amplify.github.io/aws-sdk-android/docs/reference/com/amazonaws/services/rekognition/AmazonRekognitionClient.html). You might also want to take a look at the [predictions category in Amplify](https://docs.amplify.aws/lib/predictions/getting-started/q/platform/android)

**Comment by 24Lathiya** [comment]
Is predictions able to identify Explicit Nudity stored videos in S3 bucket?
If Yes please let me know how ?
Example will be more appreciable @rjuliano @jamesonwilliams

**Comment by jamesonwilliams** [comment]
> Is predictions able to identify Explicit Nudity stored videos in S3 bucket with Android?
> If Yes please let me know how ?
> Example will be more appreciable @rjuliano @jamesonwilliams

Amplify Predictions does not currently support the [content moderation APIs](https://docs.aws.amazon.com/rekognition/latest/dg/moderation.html#moderation-api), no.

You can use the `AmazonRekognitionClient` directly, though. Just follow along with the service documentation and call upon the corresponding APIs in the Android client. (See [`detectModerationLabels`](https://github.com/aws-amplify/aws-sdk-android/blob/7155b35577d3120b3c6a2cca5984bd0c44ebac5a/aws-android-sdk-rekognition/src/main/java/com/amazonaws/services/rekognition/AmazonRekognitionClient.java#L1673).
