### ISSUE TITLE
Connect to GameLift using Amplify

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [aws-amplify/aws-sdk-android#2371]
Hi,  
I'm trying to communicate with GameLift by invoking lambdas, however every time I try to connect to the lambda, I got rejected...  
So what I thought is to use an API Gateway connected to the lambdas, and then use Amplify to communicate with GamLift... However GameLift doesn't allow communication through HTTP afaik... now I'm new to GameLift so I thought that maybe you can help me figure out how to use Amplify to communicate with the GameLift fleet

**Comment by gpanshu** [comment]
Hello @AlbertoSinigaglia can you please post specific examples what you are trying to do, which api is failing and what the error response is ?

**Comment by poojamat** [comment]
Closing the issue due to lack of response, please reopen it if its still as issue.
