### ISSUE TITLE
NPE in com.amazonaws.mobile.client.AWSMobileClient._signIn (AWSMobileClient.java:1168)

### ISSUE THREAD

**Issue by imetodieva** [aws-amplify/aws-sdk-android#2380]
NPE trying to login 

**Steps:** 
1. AWSMobileClient is initialized successfully 
2. AWSMobileClient.getInstance().signOut() wrapped in try catch because of unresolved https://github.com/aws-amplify/aws-sdk-android/issues/2268
2. Execute signIn function
3. NPE

**Expected behavior**
No crash

**Environment Information :**
 - com.amazonaws:aws-android-sdk-mobile-client:2.22.2
 - Device: Galaxy A50
 - Android Version: Android 10, API 29

**Stack trace**
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.amazonaws.mobile.client.AWSMobileClientStore.d(java.lang.String, java.lang.String)' on a null object reference
       at com.amazonaws.mobile.client.AWSMobileClient._signIn(AWSMobileClient.java:1168)
       at com.amazonaws.mobile.client.AWSMobileClient.signIn(AWSMobileClient.java:1140)
       at com.amazonaws.mobile.client.AWSMobileClient.signIn(AWSMobileClient.java:1129)

**Something to be noted**
There is connection with https://github.com/aws-amplify/aws-sdk-android/issues/2268 because again it's problem with the **mStore** field being null.

**Comment by raphkim** [comment]
Closing in favor of #2268
