### ISSUE TITLE
AWSMobileClient.getInstance() return null

### ISSUE THREAD

**Issue by paramjot-prepladder** [aws-amplify/aws-sdk-android#2384]
**Describe the bug**
AWSMobileClient.getInstance() returns null on some devices. i need token to call api, but this is returning null and i didn't get any method to re-instance the AWSMobileClient.

**To Reproduce**
After 2-3 hour of login AWSMobileClient.getInstance() got null and i am unable to get the token. I didnt called the signout method
```
Your code
to get token
 token = AWSMobileClient.getInstance().tokens.accessToken.tokenString


**Expected behavior**
 AWSMobileClient.getInstance() should return instanse or how can i re init the AWSMobileClient without login again



**Environment Information (please complete the following information):**
 - AWS Android SDK Version: com.amazonaws:aws-android-sdk-mobile-client:2.22.2
 - Device: Mi A1
 - Android Version: version 9

Thanks in advance

**Comment by raphkim** [comment]
@paramjot-prepladder ,

Hi, I am having trouble reproducing this issue. Would it be possible to provide some relevant code snippets and log details?

**Comment by paramjot-prepladder** [comment]
AWSMobileClient.getInstance().initialize(applicationContext, object : Callback<UserStateDetails?> {
                override fun onResult(userStateDetails: UserStateDetails?) {
                 }
              })
              
              I have initialize the sdk in the Application class like this.
              
 AWSMobileClient.getInstance().signIn()
 And for login i have used this method.
 
 After successful login we have to open the app after the interval of 3-4 hours. Then the SDK starts returning Null. It will happen in second or third attempt. 
 
Hope these thing will help you

**Comment by raphkim** [comment]
`AWSMobileClient.getInstance()` will guarantee that you get a non-null instance of `AWSMobileClient`. It would be helpful to provide a detailed log of your crash from NPE so that we can better identify what may be happening.

**Comment by paramjot-prepladder** [comment]
Caused by java.lang.Exception: You must be signed-in with Cognito Userpools to be able to use getTokens
       at com.amazonaws.mobile.client.AWSMobileClient$11.run(AWSMobileClient.java:79)
       at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:24)
       at com.amazonaws.mobile.client.AWSMobileClient.getTokens(AWSMobileClient.java:10)
       at com.prepladder.oneprep.activity.qbank.QBankActivity.callServer(QBankActivity.java:43)
       at com.prepladder.oneprep.activity.qbank.QBankActivity.onLayoutCreated(QBankActivity.java:141)
       
       i get this exception
       I got this log from the Firebase Analytics
       
       Device  Galaxy Tab A (8.0", 2019) 
       Android Version 10
       DateMar 23, 2021, 2:37:35 PM 

This issue is faced by our tester and he is also not able to reproduce it again. But randomly SDK return null

**Comment by paramjot-prepladder** [comment]
@raphkim Are you able to reproduce this issue?

**Comment by paramjot-prepladder** [comment]
@raphkim Any update?

**Comment by eeatonaws** [comment]
Hi @paramjot-prepladder, I apologize for the delayed response. The error you are getting indicates that the tokens have expired and the user needs to sign in again, so trying to retrieve the tokens using `AWSMobileClient.getInstance().tokens` fails. Please see the documentation [here](https://docs.amplify.aws/sdk/auth/how-it-works/q/platform/android/#token-fetch-and-refresh) for more information, including how to add a user state listener to listen for when the user has been signed out because of their tokens expiring.
