### ISSUE TITLE
Too long sign up with AWSMobileClient

### ISSUE THREAD

**Issue by PineapplePie** [aws-amplify/aws-sdk-android#2392]
Hello! I've been struggling with the long sign up process for the majority of our production users (>5 seconds only for pure callback), so it's not like a network issue.

**My dependecies**

awsSDK = 'com.amazonaws:aws-android-sdk-mobile-client:2.22.2'
awsAuthSDK = 'com.amazonaws:aws-android-sdk-cognitoauth:2.22.2'

**Device**
Samsung s10e, Android 29.

**Snippet**
```
   logger().i("Start cognito sign up with region")
    awsMobileClient.signUp(
            email,
            password,
            parameters,
            null,
            object : Callback<SignUpResult> {
                override fun onResult(signUpResult: SignUpResult) {
                    logger().i("Cognito sign up successful")
                }

                override fun onError(e: Exception) {
                    logger().i("Cognito sign up failed")
                }
            })
```
            
This is the result for this function:
```
2021-03-24 11:20:54.971 3117-6520 I/cognito: Start cognito sign up with region
2021-03-24 11:20:59.827 3117-7722 I/cognito: Cognito sign up successful
```
As you can see, it gives about 5 seconds only for sign up and, actually, it's a good result, because I've faced worse and in analytics it's the smallest amount of time. After that I need to make sign in and refresh tokens which takes approximately 1.5-2 seconds. So the whole sign up process is really slow and long. Can we somehow make it faster? What's the reason of this long processing?

**Comment by eeatonaws** [comment]
Hi @PineapplePie. I'm seeing the sign up code you provided consistently run in 700 to 800 ms. Are you using any lambda triggers (executed on sign up) or other modules from the AWS SDK for Android?
