### ISSUE TITLE
Getting java.net.protocolexception unexpected end of stream in GetClip API response

### ISSUE THREAD

**Issue by shishir87** [aws-amplify/aws-sdk-android#2394]
Hi,

I am developing an Android app which have the functionality of downloading a 5 minutes Clip from KVS.
I am using GetClip API to download by following this documentation. 
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_reader_GetClip.html

But I am facing the error "java.net.protocolexception unexpected end of stream" frequently when I am trying to read the input stream received in response at this line --->inputStream.read(buffer)

I am facing this while running the app on actual phone and not using emulator.

Entire code is given below
==========================
          try{
                val dataClient = frontEndClient!!.getDataEndpoint(GetDataEndpointRequest().withStreamName(mChannelName)
                    .withAPIName("GET_CLIP")).dataEndpoint
                val requestBody = "{\"ClipFragmentSelector\":{\"FragmentSelectorType\":\"$fragmentSelectorType\",\"TimestampRange\":{\"EndTimestamp\":${endTimeForDownload/1000},\"StartTimestamp\":${startTimeForDownload/1000}}},\"StreamName\":\"$mChannelName\"}".toRequestBody("application/json; charset=utf-8".toMediaTypeOrNull())

                val request = Request.Builder()
                    .url("${dataClient.trim()}/getClip")
                    .method("POST",requestBody)
                    .addHeader("X-Amz-Security-Token",sessionToken!!)
                    .addHeader("Host","${dataClient.trim().replace("https://","",true)}")
                    .addHeader("x-amz-date",DateFormatUtil.getAmzDate())
                    .addHeader("Connection","close")
                    .build()

                val signer = OkHttpAwsV4Signer(mRegion, "kinesisvideo")

                val newRequest = signer.sign(request, accessKeyId, secretAccessKey)
                val okhttpClient = OkHttpClient.Builder()
                    .connectTimeout(120, TimeUnit.SECONDS)
                    .retryOnConnectionFailure(true)
                    .readTimeout(300, TimeUnit.SECONDS)
                    .build()

                okhttpClient.newCall(newRequest).enqueue(object: Callback{
                    override fun onFailure(call: Call, e: IOException) {
                        e.printStackTrace()
                        emitter.onError(e)
                    }

                    override fun onResponse(call: Call, response: Response) {
                        Log.d("DownloadURL",response.body.toString())
                        val inputStream: InputStream = response.body!!.byteStream()

                        val buff = ByteArray(1024)
                        var downloaded: Long = 0

                        val fileName = "recording_${Date().time}"
                        var output: OutputStream? = null
                        var fileUri: Uri? = null
                        if (Build.VERSION.SDK_INT >= 29) {
                            val resolver = context!!.contentResolver
                            val contentValues = ContentValues().apply {
                                put(MediaStore.MediaColumns.DISPLAY_NAME, fileName)
                                put(MediaStore.MediaColumns.MIME_TYPE, "video/mp4")
                                put(MediaStore.MediaColumns.RELATIVE_PATH, "${Environment.DIRECTORY_MOVIES}/${Constants.RECORDING_FOLDER}/")
                            }
                            val collection = MediaStore.Video.Media.getContentUri(MediaStore.VOLUME_EXTERNAL_PRIMARY)
                            fileUri = resolver.insert(collection, contentValues)
                            output = resolver.openOutputStream(fileUri!!)
                        } else {
                            val savedVideoFile =  provideFileForRecording(fileName)
                            output = FileOutputStream(savedVideoFile)
                            fileUri = Uri.fromFile(savedVideoFile)
                        }

                        while (true) {
                            try{
                                val readed: Int = inputStream.read(buff)
                                if (readed == -1) {
                                    break
                                }
                                output!!.write(buff, 0, readed)
                                //write buff
                                downloaded += readed.toLong()
                            }catch (e:Exception){
                                e.printStackTrace()
                                emitter.onError(e)
                                break
                            }
                        }
                        output!!.flush()
                        output!!.close()
                        inputStream.close()
                        if (fileUri != null){
                            emitter.onSuccess(fileUri)
                        }else{
                            emitter.onError(Exception("Cloud not find file uri"))
                        }
                    }
                })
            }catch (e: Exception){
                e.printStackTrace()
                emitter.onError(e)
            }
=============================================

I am attaching the screenshot from Android studio Logcat
![MicrosoftTeams-image (10)](https://user-images.githubusercontent.com/12554967/112467475-1b213b80-8d8d-11eb-97af-d7b595b3c274.png)

Using below versions of AWS SDK
1. com.amazonaws:aws-android-sdk-kinesisvideo-archivedmedia:2.22.2@aar
2. com.amazonaws:aws-android-sdk-kinesisvideo:2.22.2@aar
3. com.amazonaws:aws-android-sdk-mobile-client:2.22.3@aar 

- Android Version: 10
- Not using any Simulator

**Comment by hassanctech** [comment]
@shishir87 It looks like for some reason the GetClip API didn't get added to the kinesis video archived media client.  We are working to add that.  Once that's added please use that instead of attempting to construct the request on your own.

**Comment by shishir87** [comment]
@hassanctech Thank you for reply. Is it possible for you to give a timeline for adding GetClip API in Kinesis video archived media client?. It will be very helpful.

**Comment by hassanctech** [comment]
I can't provide a guarantee right now but I'm hoping it will be there before Friday.

**Comment by hassanctech** [comment]
@shishir87 It is live now:  https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.22.6

**Comment by shishir87** [comment]
@hassanctech Thanks for the update. I tried to download a 5minutes Clip using the latest SDK v2.22.6 which has GetClip API in Kinesis video archived media client. But I am still facing the same issue. Below is the code snipppet.

                val timeRange = ClipTimestampRange()
                timeRange.startTimestamp =  Date(startTimeForDownload)
                timeRange.endTimestamp = Date(endTimeForDownload)

                val clipFragmentSelector = ClipFragmentSelector()
                clipFragmentSelector.fragmentSelectorType = fragmentSelectorType
                clipFragmentSelector.timestampRange = timeRange

                val clipRequest = GetClipRequest()
                clipRequest.streamName = mChannelName
                clipRequest.clipFragmentSelector = clipFragmentSelector

                val achClient = AWSKinesisVideoArchivedMediaClient(object : AWSSessionCredentials {
                    override fun getSessionToken(): String {
                        return this@CloudPlaybackViewModel.sessionToken!!
                    }

                    override fun getAWSAccessKeyId(): String {
                        return this@CloudPlaybackViewModel.accessKeyId!!
                    }

                    override fun getAWSSecretKey(): String {
                        return this@CloudPlaybackViewModel.secretAccessKey!!
                    }

                })

                val dataClient = frontEndClient?.getDataEndpoint(GetDataEndpointRequest().withStreamName(mChannelName)
                    .withAPIName("GET_CLIP"))?.dataEndpoint
                achClient.endpoint = dataClient

                val clipResult = achClient.getClip(clipRequest)
                val inputStream = clipResult.payload

                val buff = ByteArray(1024 * 4)

                val fileName = "recording_${Date().time}"
                var output: OutputStream? = null
                var fileUri: Uri? = null
                if (Build.VERSION.SDK_INT >= 29) {
                    val resolver = context!!.contentResolver
                    val contentValues = ContentValues().apply {
                        put(MediaStore.MediaColumns.DISPLAY_NAME, fileName)
                        put(MediaStore.MediaColumns.MIME_TYPE, "video/mp4")
                        put(MediaStore.MediaColumns.RELATIVE_PATH, "${Environment.DIRECTORY_MOVIES}/${Constants.RECORDING_FOLDER}/")
                    }
                    val collection = MediaStore.Video.Media.getContentUri(MediaStore.VOLUME_EXTERNAL_PRIMARY)
                    fileUri = resolver.insert(collection, contentValues)
                    output = resolver.openOutputStream(fileUri!!)
                } else {
                    val savedVideoFile =  provideFileForRecording(fileName)
                    output = FileOutputStream(savedVideoFile)
                    fileUri = Uri.fromFile(savedVideoFile)
                }

                while (true) {
                    try{
                        val readed: Int = inputStream.read(buff)
                        if (readed == -1) {
                            break
                        }
                        output!!.write(buff, 0, readed)
                        //write buff
                    }catch (e:Exception){
                        e.printStackTrace()
                        emitter.onError(e)
                        break
                    }
                }
                output!!.flush()
                output!!.close()
                inputStream.close()
                if (fileUri != null){
                    emitter.onSuccess(fileUri)
                }else{
                    emitter.onError(Exception("Cloud not find file uri"))
                }

**Comment by shishir87** [comment]
@hassanctech Below is the screenshot from Android studio Logcat
![Screenshot 2021-04-09 at 9 32 12 PM](https://user-images.githubusercontent.com/12554967/114208414-122e8d80-997b-11eb-84f7-b0566194dd39.png)

**Comment by gpanshu** [comment]
Please confirm if this has been fixed in the latest release as marked by the linked issue. Thank you. If not then feel free to reopen this issue.
