### ISSUE TITLE
How to stop TransferUtility and TransferThreadPool 

### ISSUE THREAD

**Issue by lon9man** [aws-amplify/aws-sdk-android#2460]
@richardmcclellan 

### **State your question**
i am using `TransferUtility` in background service, which can be started/stopped dynamically.

1. how to stop gracefully `TransferThreadPool`, which is used in the core of `TransferUtility`? i see exists method `closeThreadPool`, but i am unable to call it it due to package-private nature visibility:
[TransferThreadPool.closeThreadPool](https://github.com/aws-amplify/aws-sdk-android/blob/e31564c594212c825c53a3272ca6d9120d69d096/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferThreadPool.java#L58-L67)
2. what is the correct and best way to **COMPLETELY** and **IMMEDIATE** stop `TransferUtility`:
... 
a) Stop background thread (if exists)
b) Cancel all currently active uploads
c) Stop `TransferThreadPool` (in some way(
... 
maybe else or completely other steps/order ?

### **Which AWS Services are you utilizing?**
S3 TransferUtility
### **Provide code snippets (if applicable)**
simplified example:
```
class MyThread extends Thread
{   
    @Override
    public void run()
    {
        ** logic to determine what to upload **

        for (MyFile file : files) {
            if (Thread.isInterrupted()) {
                break;
            }

            ** long upload **
            transferUtility.upload(...);
        }
    }
}
```

```
public class MediaScannerService extends Service {
    MyThread thread;
    TransferUtility transferUtility;

    public int onStartCommand(Intent intent, int flags, int startId) 
    {
        if (intent.getAction().equals("START")) {
            start();
        } else if (intent.getAction().equals("STOP")) {
            stop();
        }
    } 

    public void start()
    {
        transferUtility = new TransferUtility(...);

        thread = new MyThread();
        thread.start();
    }

    public void stop()
    {
        thread.interrupt();
        transferUtility.cancelAllWithType(TransferType.UPLOAD);

        ** how to stop here TransferUtility's TransferThreadPool ??  **
    }
}

```
```
// simplified logic to run

context.startService(startIntent);          
** HERE background thread - started, FIRST TransferThreadPool - started **

sleep(10000);

context.startService(stopIntent);          
** HERE background thread - stopped. FIRST TransferThreadPool - alive **

context.startService(startIntent);          
** HERE background thread - started, SECOND TransferThreadPool - started **

context.startService(stopIntent);          
** HERE background thread - stopped. FIRST/SECOND TransferThreadPool - alive **

...

context.startService(startIntent);          
** HERE background thread - stopped, FIRST/SECOND/THIRD/.../... TransferThreadPool - alive **
```

am i correctly understand that after multiple restarts we will have multiple instances of `TransferThreadPool`?

_P.S. i understand that we can instantiate `TransferUtility` in `onCreate`-method to prevent issue, but in result we will have at least 1 instance, which we potentially in some time point don't need anymore_

### **Environment(please complete the following information):**
 - SDK Version: [e.g. 2.22.+]

### **Device Information (please complete the following information):**
 - Device: API 30 emulator
 - Android Version: [Android 11]

**Comment by gpanshu** [comment]
I am not sure I understand the problem here @lon9man. Can you please elaborate and we can look into it?

**Comment by lon9man** [comment]
@gpanshu hello, i described all in details in the 1st post. you can reread it slowly one more time...

fast flow:
1. when you call `transferUtility.upload(...);` internally logic instantiates `TransferThreadPool`-instance
2. i make upload using background service, which can be ON or OFF

so i want to clean already instantiated `TransferThreadPool`-instance before stop my background service to cleanup used resources. to do it (AFAIU) i should call method [closeThreadPool] (https://github.com/aws-amplify/aws-sdk-android/blob/e31564c594212c825c53a3272ca6d9120d69d096/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferThreadPool.java#L58-L67), BUT i can't do it, due to package-private visibility (`TransferThreadPool` is private package, so methods from it can be called ONLY from classes of the same namespace. BUT i want to call it from the class outside core namespace)

questions: 
1. how to call `closeThreadPool`-method to close thread pool outside core namespace:
`package com.amazonaws.mobileconnectors.s3.transferutility;`
?
2. or am i missing something?

thanks!

**Comment by sdhuka** [comment]
@lon9man `cancel` API not only updates the state in the DB but also [cancels](https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferRecord.java#L258) the tasks from the threadPool.

We don't think it is right behavior to expose the closeThreadPool publicly, because calling it directly without updating the database will leave the existing transferTasks in limbo, which will result in unexpected behavior.

Ideally, you should have one instance of transferUtility (unless you are dealing with multiple buckets) and use it across the app.

**Comment by lon9man** [comment]
@sdhuka any thoughts about [previous post](https://github.com/aws-amplify/aws-sdk-android/issues/2460#issuecomment-1043133296)?

**Comment by sdhuka** [comment]
@lon9man There is no need to clear threadPool instance if there are no pending tasks waiting execution. My guess is closeThreadPool() was primarily implemented for testing purpose.
For your usecase as I previously recommended have a single instance of TransferUtility for the app and use cancel api for stopping any tasks.

**Comment by lon9man** [comment]
@sdhuka thanks. 
can you give some advice for https://github.com/aws-amplify/aws-sdk-android/issues/1382 ?
