### ISSUE TITLE
AWS Recognition

### ISSUE THREAD

**Issue by donpaul120** [aws-amplify/aws-sdk-android#2468]
Is the AWS Rekognition available in the amplify version? I want to be able to detect certain facial gestures, e.g smiling, look left, look right etc.

**Comment by rjuliano** [comment]
Checkout the [predictions category](https://docs.amplify.aws/lib/predictions/getting-started/q/platform/android) for Amplify instead and see if it suits your needs.

If your use case requires use of the low level Rekognition client, you can also use that in Amplify [via the escape hatch](https://docs.amplify.aws/lib/predictions/escapehatch/q/platform/android).

**Comment by donpaul120** [comment]
@rjuliano , Thanks very much! I actually just read about the escape hatch before seeing your comment.
I'm Already using the amplify on Android however i just realize that i'm unable to retrieve properties like Brightness and sharpness and i can't find anywhere in the documentation on how to go about that.

**Comment by raphkim** [comment]
Amplify Predictions category exposes some but not all of the properties from the low level clients. It seems that the property in question (`ImageQuality`) is not one of the available parameters in Amplify. The workaround would be to follow the escape hatch documentation to use `AmazonRekognitionClient` directly.
