### ISSUE TITLE
How to use custom endpoint in s3?

### ISSUE THREAD

**Issue by shaoguanglin** [aws-amplify/aws-sdk-android#2474]
**State your question**
We want to use a custom endpoint in S3. 
The following errors will be reported when uploading or viewing the bucket information (except that the download is successful)
With the same endpoint, our server can successfully upload it by using the Java 2.x version of the SDK; I want to know what else mobile needs to do to make it work?
**Which AWS Services are you utilizing?**
aws-android-sdk-s3

**Provide code snippets (if applicable)**
   
       StaticCredentialsProvider provider=new StaticCredentialsProvider(new BasicAWSCredentials(accessKey,secretKey));
        S3ClientOptions options = S3ClientOptions.builder().setPathStyleAccess(true).build();
        AmazonS3Client s3Client=new AmazonS3Client(provider, Region.getRegion(US_EAST_1));
        s3Client.setS3ClientOptions(options);
        s3Client.setEndpoint(endpoint);

        com.amazonaws.request: Received error response: com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied ( 
        Service: null; Status Code: 403; Error Code: AccessDenied; Request ID: 8374312f-e533-43e4-82de-a5777f2cf6ce), S3 
        Extended Request ID: ZmlsZWJhc2UtNTc5NTc0OTY2Ni1sbm1xOA==
        2021-05-12 09:29:39.095 11825-12434/com.test  W/System.err: 
        com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: 
        AccessDenied; Request ID: 8374312f-e533-43e4-82de-a5777f2cf6ce), S3 Extended Request ID: 
        ZmlsZWJhc2UtNTc5NTc0OTY2Ni1sbm1xOA==
        2021-05-12 09:29:39.095 11825-12434/com.test  W/System.err:     at 
        com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
        2021-05-12 09:29:39.096 11825-12434/com.test  W/System.err:     at 
        com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
        2021-05-12 09:29:39.096 11825-12434/com.test  W/System.err:     at 
        com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
        2021-05-12 09:29:39.096 11825-12434/com.test W/System.err:     at 
        com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4829)
        2021-05-12 09:29:39.096 11825-12434/com.test  W/System.err:     at 
        com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1912)

**Environment(please complete the following information):**
 - SDK Version: [2.23.0]

**Device Information (please complete the following information):**
 - Device: [Huawei v20]
 - Android Version: [android 10]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by shaoguanglin** [comment]
here is my upload code:
 PutObjectRequest objectRequest=new PutObjectRequest(bucketName,"Lynn.jpg",file);
 PutObjectResult result= s3Client.putObject(objectRequest);

**Comment by raphkim** [comment]
Hi @shaoguanglin, are you able to perform other requests besides upload successfully with the above setup?

**Comment by shaoguanglin** [comment]
@raphkim I can only download it successfully, but nothing else.

**Comment by gpanshu** [comment]
Hello @shaoguanglin I have tried creating a sample project and tried to upload and download using s3 and I had no issues. Can you please try creating a new project based on our docs with the latest SDK and see if you are still experiencing it. That may help narrow down the issue.

**Comment by poojamat** [comment]
Closing the issue due to lack of response, please reopen it if its still an issue.
