### ISSUE TITLE
[question] new develop

### ISSUE THREAD

**Issue by matiasechaharria** [aws-amplify/aws-sdk-android#2478]
Hello, I am about to start a new development on a proprietary hardware that runs an android oreo and I wonder which sdk is the appropriate one for it.
Will this sdk continue to be supported? Will new functionalities be implemented?
We are mainly interested in kinesis video streams and kinesis video streams on webrtc.
On the one hand to be able to make a video call with webrtc between 2 an android and an ios or android. On the other, unsar kinesis video stream to send audio and video to later be consumed on demand by a mobile device (android or ios)

**Comment by gpanshu** [comment]
Hi, that is quite a broad question. I would recommend reading our docs to understand what we have in our different categories and what suites your situation. You will likely also need Auth and datastore other than Kinesis. I would recommend taking a look at it [here](https://docs.amplify.aws/lib/auth/getting-started/q/platform/android)
