### ISSUE TITLE
Error: The request signature we calculated does not match the signature you provided!! | LEXSAMPLE

### ISSUE THREAD

**Issue by HaemanthSP** [aws-amplify/aws-sdk-android#2485]
*LexSample*: I am facing the signature mis-match error after upgrading to aws version: 2.23.0 or (2.22.6 +) as indicated in #2385. 

**To Reproduce**
Upgrade to AWS version: 2.22.6 or later

Which requires androidx migration: After migration dependencies looks like this
```
dependencies {
    def android_libs_version = "28.0.0"
    implementation 'androidx.multidex:multidex:2.0.0'
    implementation 'androidx.appcompat:appcompat:1.0.0'
    implementation 'com.google.android.material:material:1.0.0'

    def aws_version = '2.23.0'
    implementation ("com.amazonaws:aws-android-sdk-lex:$aws_version@aar") { transitive=true }
    implementation ("com.amazonaws:aws-android-sdk-mobile-client:$aws_version@aar") { transitive=true }
}
```
**Which AWS service(s) are affected?**

AmazonLexRuntimeClient

**Expected behavior**

During the start of the conversation, encountered following error

```
E/TextActivity: Interaction error
    com.amazonaws.AmazonServiceException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details. (Service: AmazonLexRuntime; Status Code: 403; Error Code: InvalidSignatureException; Request ID:...
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
        at com.amazonaws.services.lexrts.AmazonLexRuntimeClient.invoke(AmazonLexRuntimeClient.java:885)
        at com.amazonaws.services.lexrts.AmazonLexRuntimeClient.postContent(AmazonLexRuntimeClient.java:623)
        at com.amazonaws.mobileconnectors.lex.interactionkit.InteractionClient$3.run(InteractionClient.java:452)
        at java.lang.Thread.run(Thread.java:764)
```

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.22.6 and above
 - Device: Both in simulator and actual device
 - Android Version: Android 8.0
 - Specific to simulators: No

**Additional context**
While trying to access the bot through postman, reproduced the same error with *PostContent*
![Screenshot from 2021-05-19 14-02-36](https://user-images.githubusercontent.com/15871764/118809624-25524880-b8ab-11eb-8170-2056dbbbd703.png)

Which is rectified with PostText, received appropriate response from the bot
![Screenshot from 2021-05-19 14-03-03](https://user-images.githubusercontent.com/15871764/118809701-3e5af980-b8ab-11eb-98e4-e2301e148105.png)

is there any way to choose postText in interactionClient instead of postContent? or how to overcome this issue?

We are struck with this issue for couple of weeks!! Kindly help us to fix the issue
Thanks.

**Comment by raphkim** [comment]
Hi @HaemanthSP , would you be able to share a redacted version of your `awsconfiguration.json`?

**Comment by HaemanthSP** [comment]
Hi @raphkim,

awsconfiguration.json
```
{
    "UserAgent": "aws-amplify-cli/0.1.0",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": <PoolId>,
                "Region": "eu-central-1"
            }
        }
    },
    "Auth": {
        "Default": {
            "authenticationFlowType": "USER_SRP_AUTH"
        }
    },
    "Lex": {
        "OrderFlowers_dev": {
            "Name": "OrderFlowers_dev",
            "Alias": "beta",
            "Region": "eu-central-1"
        }
    }
}
```

**Comment by raphkim** [comment]
@HaemanthSP 

Thank you for providing details! I was able to locate the source of error to be specific to certain regions including `eu-central-1`. I have opened a PR to address this issue and we will soon have the fix ready. Thank you for your patience.
