### ISSUE TITLE
Create `TransferNetworkLossHandler` substitution that would not use `ConnectivityManager.CONNECTIVITY_ACTION` 

### ISSUE THREAD

**Issue by dariuszseweryn** [aws-amplify/aws-sdk-android#2489]
**Which AWS Services is the feature request for?**
`aws-android-sdk-s3`

**Is your feature request related to a problem? Please describe.**
As of version `2.23.0` [`TransferNetworkLossHandler` is expecting `ConnectivityManager.CONNECTIVITY_ACTION` intent](https://github.com/aws-amplify/aws-sdk-android/blob/8a2f805179039f671e026fbfafe97d816acaf54f/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferNetworkLossHandler.java#L109) which [is deprecated since API 28](https://developer.android.com/reference/android/net/ConnectivityManager#CONNECTIVITY_ACTION)

**Describe the solution you'd like**
An alternative to `TransferNetworkLossHandler` that would be easy to integrate with an Android application and would not use deprecated functionalities.

**Describe alternatives you've considered**
Android source suggests these approaches:
>      * @deprecated apps should use the more versatile {@link #requestNetwork},
>      *             {@link #registerNetworkCallback} or {@link #registerDefaultNetworkCallback}
>      *             functions instead for faster and more detailed updates about the network
>      *             changes they care about.

**Additional context**
I have not seen any issue that would track this case. Feel free to close if this is a duplicate.

```
val transferNetworkLossHandler = TransferNetworkLossHandler.getInstance(context)
val connectivityActionIntentFilter = IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION)
context.registerReceiver(transferNetworkLossHandler, connectivityActionIntentFilter)
```
<img width="726" alt="Zrzut ekranu 2021-05-25 o 19 31 15" src="https://user-images.githubusercontent.com/1412475/119542401-cb142480-bd8f-11eb-9cfd-1ea983455e2b.png">

**Comment by sdhuka** [comment]
We recommend upgrading to [Amplify 2.0](https://docs.amplify.aws/lib/storage/getting-started/q/platform/android/) where we re-architected the storage plugin implementation to use the workmanager library which uses the latest api to manage network changes.
