### ISSUE TITLE
Support user migration via `MigrationEnabled` flag in awsconfiguration.json

### ISSUE THREAD

**Issue by patrickcapadmi** [aws-amplify/aws-sdk-android#2501]
**Which AWS Services is the feature request for?**
Cognito/ com.amazonaws:aws-android-sdk-mobile-client:2.22.2

**Is your feature request related to a problem? Please describe.**
The iOS AWS SDK supports user migration by setting a flag `"MigrationEnabled": "YES"` in the awsconfiguration.json file, as described [here](https://github.com/aws-amplify/aws-sdk-ios/issues/2398). The same functionality is not supported on Android, leading to workarounds being suggested and put into production, as described in this [closed issue](https://github.com/aws-amplify/aws-sdk-android/issues/1136).

There is a clear difference between the functionality in the SDKs for each platform:
https://github.com/aws-amplify/aws-sdk-ios/search?q=MigrationEnabled
https://github.com/aws-amplify/aws-sdk-android/search?q=MigrationEnabled

**Describe the solution you'd like**
Align the functionality in the Android and iOS SDKs in this respect.

**Describe alternatives you've considered**
We're currently making use of the workaround suggested in the closed Android issue linked above, but this is causing duplicate devices to be saved against the user's Cognito account when they sign in post migration. This is not happening with our iOS app signing into the same userpool with the `MigrationEnabled` flag set.

**Comment by abhishekImpressico** [comment]
I am also facing the same issue on Android app

**Comment by lawmicha** [comment]
Hi @patrickcapadmi, glad the workaround is atleast working for you.

> duplicate devices to be saved against the user's Cognito account when they sign in post migration

what's the impact to the customer here? Are you able to dedup and remove the old device manually from the admin side?

@abhishekImpressico were you able to follow the workaround in https://github.com/aws-amplify/aws-sdk-android/issues/1136  ?

**Comment by patrickcapadmi** [comment]
@lawmicha I think they were able to delete the duplicate devices, but this was three years ago on a project which has now been decommissioned so I can't verify that.

No idea if this feature was added in the last few years as I've not needed it or used Cognito much since then. Issue should probably be closed as stale and re-raised if someone else needs it.
