### ISSUE TITLE
HTTP Custom Headers

### ISSUE THREAD

**Issue by lolucosmin** [aws-amplify/aws-sdk-android#2502]
**State your question**
There is a way to add custom headers before call:
apiCLient.methodX .
?

**Which AWS Services are you utilizing?**
```
    implementation group: 'com.amazonaws', name: 'aws-android-sdk-apigateway-core', version: '2.24.0'
    implementation group: 'com.amazonaws', name: 'aws-android-sdk-s3', version: '2.24.0'
    implementation group: 'com.amazonaws', name: 'aws-android-sdk-sns', version: '2.24.0'
    implementation group: 'com.amazonaws', name: 'aws-android-sdk-mobile-client', version: '2.24.0'
    implementation group: 'com.amazonaws', name: 'aws-android-sdk-auth-userpools', version: '2.24.0'
    implementation group: 'com.amazonaws', name: 'aws-android-sdk-auth-ui', version: '2.24.0'
    implementation group: 'com.amazonaws', name: 'aws-android-sdk-cognitoauth', version: '2.24.0'
    implementation group: 'com.amazonaws', name: 'aws-android-sdk-auth-facebook', version: '2.24.0'
    implementation group: 'com.amazonaws', name: 'aws-android-sdk-auth-google', version: '2.24.0'
```

**Provide code snippets (if applicable)**
```
        ApiClientFactory apiClientFactory= new ApiClientFactory();
        apiClientFactory.region(AppConfig.REGION.getName());
        apiClientFactory.endpoint(AppConfig.SERVER_ENDPOINT);
        apiClientFactory.clientConfiguration(this.clientConfiguration);
        apiClientFactory.credentialsProvider(provider);
       ApiClient apiCLient=apiClientFactory.build(ApiClient .class);
```

and when I do a request I call: 
```
apiCLient.methodX
```

**Environment(please complete the following information):**
 - SDK Version: [2.24.0]

**Device Information (please complete the following information):**
 - Device: [Simulator]
 - Android Version: [Nougat 7.1.2]

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by eeatonaws** [comment]
Hi @lolucosmin, you can use custom HTTP headers by first adding them to Amazon API Gateway (please see the documentation [here](https://docs.amplify.aws/lib/restapi/authz/q/platform/android/#customizing-http-request-headers)) and then adding the header to your request, similar to the code example [here](https://docs.amplify.aws/sdk/api/rest/q/platform/android/#iam-authorization).

**Comment by lolucosmin** [comment]
@eeatonaws Thanks for the reply.
Ok lets take this:
apiClient = new ApiClientFactory()
                    .credentialsProvider(AWSMobileClient.getInstance())
                    .build(YOUR_API_CLIENT_NAME.class);

in my YOUR_API_CLIENT_NAME.class I have already this function:
@com.amazonaws.mobileconnectors.apigateway.annotation.Operation(path = "/avatars", method = "GET")
 AvatarList avatarsGet();

in code example there they create a new request:
ApiRequest localRequest =
                    new ApiRequest(apiClient.getClass().getSimpleName())
                            .withPath(path)
                            .withHttpMethod(HttpMethodName.valueOf(method))
                            .withHeaders(headers)
                            .addHeader("Content-Type", "application/json")
                            .withParameters(parameters);
So is not make sense for me to create new request when that request is already defined in my YOUR_API_CLIENT_NAME.class.
For me is not a good idea to create a new request for each function from my "YOUR_API_CLIENT_NAME.class", there are a lot of functions.

My workflow:
  this.myClient= new ApiClientFactory()
                .region(AppConfig.REGION.getName())
                .endpoint(AppConfig.SERVER_TICKETS_ENDPOINT)
                .clientConfiguration(this.clientConfiguration)
                .credentialsProvider(provider)
                .build(MyClient.class);
and on async or observer I run: myClient.avatarsGet()
