### ISSUE TITLE
Handling ApiClientException:Signature Expired for generated AWS API Gateway Client

### ISSUE THREAD

**Issue by escdev-je** [aws-amplify/aws-sdk-android#253]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS API Gateway 
* In what version of SDK are you facing the problem?
v2.3.9
* Is the issue limited to Simulators / Actual Devices?
Tested on an actual android device only
* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
Android

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

* Please include a stacktrace if applicable.
```
getProfilePost: something went wrong see cloudwatch logscom.amazonaws.mobileconnectors.apigateway.ApiClientException: {"message":"Signature expired: 20170212T175938Z is now earlier than 20170215T145534Z (20170215T150034Z - 5 min.)"}
                                                                         (Service: TimeFirstClient; Status Code: 403; Error Code: null; Request ID: 8073bbc5-f38f-11e6-a616-b9eddabf1a00)

```
If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/). 

**My Problem**
My API Client Gateway calls keeps on failing when my device time is more or less than 5 min of the AWS Server time. I don't have any problems when calling other AWS Services except for the generated API Gateway Client SDK. Do I need to handle this on my own? If so can you point me to the right direction.

I was thinking of parsing the error message to get the server time and the device time then i'll get the time offset then set that as the SDK's global time offset. Is this the right solution or is there a better way to handle the clock skew error when using the generated API Gateway Client SDK?

**Comment by mlshon** [comment]
Hi,
Thanks for reporting. We will take a look.

**Comment by escdev-je** [comment]
Hi.

Just an update. So I tried setting the global offset when the API Gateway fails by parsing the error message. After setting the global offset and calling again the API Gateway method, the method still fails.

**Comment by escdev-vikko** [comment]
Hi,

I've also tried replicating the same scenario, but this time it's using iOS with Objective C.

- What service are you using?
AWS API Gateway

- In what version of SDK are you facing the problem?
v2.4.12

- Is the issue limited to Simulators / Actual Devices?
Tested on an actual iOS device

- Can your problem be resolved if you bump to a higher version of SDK?
No

- Is this problem related to specific Android/OS version?
No

Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

Please include a stacktrace if applicable.
```
Printing description of task->_error:
Error Domain=com.amazonaws.AWSAPIGatewayErrorDomain Code=1 "(null)" UserInfo={HTTPBody=<CFBasicHash 0x15ed61c0 [0x3add9ca8]>{type = immutable dict, count = 1,
entries =>
	0 : <CFString 0x38388f88 [0x3add9ca8]>{contents = "message"} = <CFString 0x15e4ba00 [0x3add9ca8]>{contents = "Signature expired: 20170216T054905Z is now earlier than 20170217T054416Z (20170217T054916Z - 5 min.)"}
}
, HTTPHeaderFields=<CFBasicHash 0x15e5ee60 [0x3add9ca8]>{type = immutable dict, count = 9,
entries =>
	3 : Via = <CFString 0x15eba270 [0x3add9ca8]>{contents = "1.1 68c17bb482a09fbeae0b042d2b84af05.cloudfront.net (CloudFront)"}
	4 : x-amzn-ErrorType = <CFString 0x15ed0720 [0x3add9ca8]>{contents = "InvalidSignatureException"}
	5 : Content-Type = <CFString 0x15e4d700 [0x3add9ca8]>{contents = "application/json"}
	6 : x-amzn-RequestId = <CFString 0x15e39ee0 [0x3add9ca8]>{contents = "d14bd249-f4d4-11e6-830c-57375333de79"}
	7 : Content-Length = <CFString 0x15e3a500 [0x3add9ca8]>{contents = "115"}
	8 : Connection = <CFString 0x15eb2d20 [0x3add9ca8]>{contents = "keep-alive"}
	9 : Date = <CFString 0x15e633b0 [0x3add9ca8]>{contents = "Fri, 17 Feb 2017 05:49:16 GMT"}
	10 : X-Cache = <CFString 0x15e66ee0 [0x3add9ca8]>{contents = "Error from cloudfront"}
	11 : X-Amz-Cf-Id = <CFString 0x15e3d940 [0x3add9ca8]>{contents = "0o6NgaWoJaCS2ldj4pKeaiQqmCEFP5cYLXqnznyZlBA93QZwsgSy1A=="}
}

```

**Comment by giovazjim** [comment]
Hi,

I have the same problem as @escdev-vikko using iOS with Objective C just that I'm using a higher version of aws-sdk-ios which is 2.6.1

**Comment by desokroshan** [comment]
@escdev-je 
The exception indicates that the signature was not created recently and thus the signature validation failed with the error message you mentioned. A common cause of this is when the local clock on the host generating the signature is off by more than a few minutes.

Could you share the code snippet you used to set the global offset and retry the API Gateway call? Also can you try to sync the device time with server time and let me know if that fixes the issue?

@giovazjim @escdev-vikko Can you please open a separate issue in [aws-sdk-ios](https://github.com/aws-amplify/aws-sdk-ios) repo.
