### ISSUE TITLE
Top Crashes in app are pinpoint related

### ISSUE THREAD

**Issue by MKelman** [aws-amplify/aws-sdk-android#2530]
**Describe the bug**
We are seeing pinpoint being our top crashes for multiple versions now through firebase crashlytics. We have 4 crashes affecting over 5 thousand users on one of our apps.  Here are the 4 crashes in order of highest number of crashes to lowest:

1. PinpointDBBase.java line 93
com.amazonaws.mobileconnectors.pinpoint.internal.event.PinpointDBBase.insert
"Fatal Exception: java.lang.RuntimeException: Unable to create application com.adfone.cover.app.LycaApp: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY): , while compiling: PRAGMA journal_mode"

2. PinpointDatabaseHelper.java line 38
com.amazonaws.mobileconnectors.pinpoint.internal.event.PinpointDatabaseHelper.onConfigure
"Fatal Exception: java.lang.RuntimeException: Unable to create application com.adfone.cover.app.LycaApp: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)"

3. PinpointDBBase.java line 98
com.amazonaws.mobileconnectors.pinpoint.internal.event.PinpointDBBase.insert
"Fatal Exception: java.lang.RuntimeException: Unable to create application com.adfone.cover.app.LycaApp: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)"

4. PinpointDBBase.java line 219
com.amazonaws.mobileconnectors.pinpoint.internal.event.PinpointDBBase.delete
"Fatal Exception: java.lang.RuntimeException: Unable to create application com.adfone.cover.app.LycaApp: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5 SQLITE_BUSY)"

**Which AWS service(s) are affected?**
AWS pinpoint and we are on version 2.23.0 

**Expected behavior**
no crash

**Screenshots**

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: on 2.23.0 and we have upgraded a few times but issue is still occuring
 - Device: all
 - Android Version: all
 - Specific to simulators: no

**Comment by sdhuka** [comment]
@MKelman Could you please confirm whether you are still noticing these crashes?

Could you please also confirm that you are not using multiple instances of PinpointManager in your app? Because that might cause multiple instances of PinpointDatabaseHelper trying to access the database at the same time, resulting in this crash.

**Comment by MKelman** [comment]
@sdhuka looks like it is no longer an issue :)
