### ISSUE TITLE
CognitoCachingCredentials: Token is inactive error when using Kinesis

### ISSUE THREAD

**Issue by meavydev** [aws-amplify/aws-sdk-android#2539]
**Describe the bug**
This is with an updated AWS AuthToken, which is reporting an expiry time an hour away:

`07-08 14:00:19.428 18549 22126 D Utils$Companion: Updating AWS AuthToken for Kinesis with new expiry Thu Jul 08 15:00:19 GMT+01:00 2021
`

Then we see this (2 sec later), which shows the user is signed in but it gives "Token is inactive" errors in the logcat:

`07-08 14:00:21.839 18549 22113 D CognitoCachingCredentia: Clearing credentials from SharedPreferences
07-08 14:00:21.840 18549 23231 D AWSMobileClient: Inspecting user state details
07-08 14:00:21.840 18549 23231 I KinesisStream$initKinesisDataStream: [nvsdk] AWS Init onResult:  SIGNED_IN
07-08 14:00:21.841 18549 23231 I KinesisStream$initKinesisDataStream: [nvsdk] AWS user is signed in, setting up Kinesis
07-08 14:00:21.847 18549 22974 D CognitoCachingCredentia: Loading credentials from SharedPreferences
07-08 14:00:21.849 18549 22974 D KeyProvider23: AndroidKeyStore contains keyAlias com.amazonaws.android.auth.aesKeyStoreAlias
07-08 14:00:21.849 18549 22974 D KeyProvider23: Loading the encryption key from Android KeyStore.
07-08 14:00:21.851 18549 22974 D CognitoCachingCredentia: Making a network call to fetch credentials.
07-08 14:00:21.853 18549 22610 D com.amazonaws.request: Received error response: com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Token is inactive (Service: null; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 8ccc7906-9aae-46a2-8b39-a38cb7ce87c5)
07-08 14:00:21.854 18549 22610 E AbstractKinesisRecorder: DeadLetterListener onRecordsDropped has thrown an exception (user code)
07-08 14:00:21.854 18549 22610 E AbstractKinesisRecorder: java.lang.NullPointerException: Attempt to invoke interface method 'void com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.DeadLetterListener.onRecordsDropped(java.lang.String, java.util.List)' on a null object reference
07-08 14:00:21.854 18549 22610 E AbstractKinesisRecorder: 	at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.AbstractKinesisRecorder.submitAllRecords(AbstractKinesisRecorder.java:188)
07-08 14:00:21.854 18549 22610 E AbstractKinesisRecorder: 	at com.navenio.sdk.aws.kinesis.KinesisStream$sendKinesisWifiStream$1.invokeSuspend(KinesisStream.kt:253)
07-08 14:00:21.854 18549 22610 E AbstractKinesisRecorder: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07-08 14:00:21.854 18549 22610 E AbstractKinesisRecorder: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
07-08 14:00:21.854 18549 22610 E AbstractKinesisRecorder: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
07-08 14:00:21.854 18549 22610 E AbstractKinesisRecorder: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
07-08 14:00:21.854 18549 22610 E AbstractKinesisRecorder: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
07-08 14:00:21.854 18549 22610 E AbstractKinesisRecorder: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
07-08 14:00:21.858 18549 22610 E AbstractKinesisRecorder: ServiceException in submit all, the last request is presumed to be the cause and will be dropped
07-08 14:00:21.858 18549 22610 E AbstractKinesisRecorder: com.amazonaws.services.cognitoidentity.model.NotAuthorizedException: Token is inactive (Service: AmazonCognitoIdentity; Status Code: 400; Error Code: NotAuthorizedException; Request ID: 8ccc7906-9aae-46a2-8b39-a38cb7ce87c5)
07-08 14:00:21.858 18549 22610 E AbstractKinesisRecorder: 	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:742)
07-08 14:00:21.858 18549 22610 E AbstractKinesisRecorder: 	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:420)
07-08 14:00:21.858 18549 22610 E AbstractKinesisRecorder: 	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:229)
07-08 14:00:21.858 18549 22610 E AbstractKinesisRecorder: 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.invoke(AmazonCognitoIdentityClient.java:1836)
07-08 14:00:21.858 18549 22610 E AbstractKinesisRecorder: 	at com.amazonaws.services.cognitoidentity.AmazonCognitoIdentityClient.getId(AmazonCognitoIdentityClient.java:809)
07-08 14:00:21.858 18549 22610 E AbstractKinesisRecorder: 	at com.amazonaws.auth.AWSAbstractCognitoIdentityProvider.getIdentityId(AWSAbstractCognitoIdentityProvider.java:172)
07-08 14:00:21.858 18549 22610 E AbstractKinesisRecorder: 	at com.amazonaws.auth.AWSEnhancedCognitoIdentityProvider.refresh(AWSEnhancedCognitoIdentityProvider.java:76)
07-08 14:00:21.858 18549 22610 E AbstractKinesisRecorder: 	at com.amazonaws.auth.CognitoCredentialsProvider.startSession(CognitoCredentialsProvider.java:687)
07-08 14:00:21.858 18549 22610 E AbstractKinesisRecorder: 	at com.amazonaws.auth.CognitoCredentialsProvider.getCredentials(CognitoCredentialsProvider.java:474)
07-08 14:00:21.858 18549 22610 E AbstractKinesisRecorder: 	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:496)
07-08 14:00:21.858 18549 22610 E AbstractKinesisRecorder: 	at com.amazonaws.auth.CognitoCachingCredentialsProvider.getCredentials(CognitoCachingCredentialsProvider.java:78)
07-08 14:00:21.858 18549 22610 E AbstractKinesisRecorder: 	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:3331)
07-08 14:00:21.858 18549 22610 E AbstractKinesisRecorder: 	at com.amazonaws.services.kinesis.AmazonKinesisClient.putRecords(AmazonKinesisClient.java:1716)
07-08 14:00:21.858 18549 22610 E AbstractKinesisRecorder: 	at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.KinesisStreamRecordSender.sendBatch(KinesisStreamRecordSender.java:86)
07-08 14:00:21.858 18549 22610 E AbstractKinesisRecorder: 	at com.amazonaws.mobileconnectors.kinesis.kinesisrecorder.AbstractKinesisRecorder.submitAllRecords(AbstractKinesisRecorder.java:139)
`

**To Reproduce**
Seems to be random, but when it happens it repeats, interspersed with working Kinesis uploads.

**Which AWS service(s) are affected?**
Kinesis / Cognito

**Expected behavior**
No error

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.26.0
 - Device: Pixel 3A XL
 - Android Version: 10
 - Specific to simulators: No

**Comment by div5yesh** [comment]
@hassantech Please take a look at this.

**Comment by gpanshu** [comment]
HI @meavydev can you advise if this is still an issue. If it is can you advise exactly the steps you took to reproduce this?

**Comment by meavydev** [comment]
Hard to say as we coded around the problem and it was... a year ago!

**Comment by gpanshu** [comment]
If you remember what the workaround was or can dig it, please feel free to comment it out here to help others.
