### ISSUE TITLE
AWSlotMqttManager offlinePublishQueueBound not working

### ISSUE THREAD

**Issue by CapitainOats** [aws-amplify/aws-sdk-android#2558]
**Describe the bug**
The `offlinePublishQueueBound` in the `AWSlotMqttManager` fails to apply an actual message limit. In the method `putMessageInQueueAndNotify` is called `mqttMessageQueue.remove(0);` which intends to remove first item of a queue, however `ConcurentLinkedQueue.remove` accepts only an Object of given queue as a parameter. This results into the remove call never removing items.

**Which AWS service(s) are affected?**
aws-android-sdk-iot

**Comment by raphkim** [comment]
Thank you for catching this issue @CapitainOats! I have a PR to address the bug and we will close the issue once it is released.

**Comment by CapitainOats** [comment]
@raphkim Thanks for the fast response. I closed the duplicated PR #2559 created by me.
