### ISSUE TITLE
S3TransferUtilitySample, The downloaded file is changed

### ISSUE THREAD

**Issue by qq296216078** [aws-amplify/aws-sdk-android#2577]
S3TransferUtilitySample

This is how the file is downloaded in the sample:
```
        File file = new File(getExternalFilesDir(null).toString() + "/" + key);
        // Initiate the download
        TransferObserver observer = transferUtility.download(key, file);
```
I renamed the file：
```
        File file = new File(getExternalFilesDir(null).toString() + File.separator + "1.0.0.0.apk");
        // Initiate the download
        TransferObserver observer = transferUtility.download(key, file);
```
After the file is downloaded, the file size may be different, or the MD5 value of the file may be different despite the same file size.
Is it because there is a problem in downloading the SDK? I have been troubled by this problem for several days, and finally found the reason, but I still don't know why it happens.

**Comment by qq296216078** [comment]
Test multiple times, the one-time download may not be a problem, but if you first pause and then resume, the md5 value after the download may be different

**Comment by gpanshu** [comment]
Before we do a deep dive into this, can you please confirm if this is still happening as its been 6 months since this issue was opened?

**Comment by poojamat** [comment]
Closing the issue due to lack of response, please reopen it if its still as issue.
