### ISSUE TITLE
AWS Hosted UI SignIn - no browsers installed error

### ISSUE THREAD

**Issue by meavydev** [aws-amplify/aws-sdk-android#2578]
**Describe the bug**
Hosted UI failing to login (tested on Android 11 and 12 Beta 4) with:

onError: com.amazonaws.mobileconnectors.cognitoauth.exceptions.BrowserNotInstalledException: No browsers installed.

**To Reproduce**
Try to login using hosted UI and you get an onError callback saying no browser installed.
```
        val hostedUIOptions = HostedUIOptions.builder()
            .scopes("openid", "email")
            .build()

        val signInUIOptions = SignInUIOptions.builder()
            .hostedUIOptions(hostedUIOptions)
            .build()

        AWSMobileClient.getInstance().showSignIn(
            this,
            signInUIOptions,
            object : Callback<UserStateDetails> {
                override fun onResult(details: UserStateDetails) {
                    Timber.d("onResult: ${details.userState}")
                   ()
                }

                override fun onError(e: Exception) {
                    Timber.e("onError: $e")
                }
            })
```

**Which AWS service(s) are affected?**
AWS Android  Mobile Client Hosted UI Signin.
 
**Expected behavior**
Login without onError, as happened previously

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.28.0
 - Device: Pixel 3A XL, Pixel 4A
 - Android Version: 11 (3A), 12 Beta 4 (4A)
 - Specific to simulators: No

**Comment by div5yesh** [comment]
HostedUI requires a browser that support custom tabs to be installed on the device. Are you having this issue even if a browser is installed?

**Comment by meavydev** [comment]
These are stock Pixels with Chrome installed as part of GMS...
It works fine if we roll back to 2.26.0, so has been introduced since then.

**Comment by div5yesh** [comment]
I was unable to replicate the issue if you have browsers installed.

Add the following code to verify if the device has any supporting browsers installed:
```java
private Collection<String> getSupportedBrowserPackage(){
        PackageManager packageManager = context.getPackageManager();
        // Get default VIEW intent handler.
        Intent activityIntent = new Intent()
                .setAction(Intent.ACTION_VIEW)
                .addCategory(Intent.CATEGORY_BROWSABLE)
                .setData(Uri.fromParts("http", "", null));

        // Get all apps that can handle VIEW intents.
        List<ResolveInfo> resolvedActivityList = packageManager.queryIntentActivities(activityIntent, 0);
        List<String> packageNamesSupportingCustomTabs = new ArrayList<>();
        for (ResolveInfo info : resolvedActivityList) {
            Intent serviceIntent = new Intent()
                    .setAction(ACTION_CUSTOM_TABS_CONNECTION)
                    .setPackage(info.activityInfo.packageName);
            // Check if this package also resolves the Custom Tabs service.
            if(packageManager.resolveService(serviceIntent, 0) != null) {
                packageNamesSupportingCustomTabs.add(info.activityInfo.packageName);
            }
        }
        return packageNamesSupportingCustomTabs;
    }
```

**Comment by meavydev** [comment]
Have you actually tried on Android 11?
As I said this is a *stock* Google Pixel with all the latest updates which includes Chrome.
If you don't work with this scenario then you need to revert your latest changes, as they won't support the devices we use for customers!

**Comment by div5yesh** [comment]
Sorry about that. Due to Android 11's [package visibility changes](https://developer.chrome.com/docs/android/custom-tabs/integration-guide/#how-can-i-check-whether-the-android-device-has-a-browser-that-supports-custom-tab), apps targeting API level 30 or above requires adding the following `queries` section in `AndroidManifest.xml`:

```xml
<queries>
  <intent>
    <action android:name="android.intent.action.VIEW" />
    <data android:scheme="https" />
  </intent>
  <intent>
    <action android:name=
        "android.support.customtabs.action.CustomTabsService" />
  </intent>
</queries>
```

We will update the SDK and Amplify docs to include the queries section: https://github.com/aws-amplify/docs/pull/3517

**Comment by tomtaila** [comment]
> Sorry about that. Due to Android 11's [package visibility changes](https://stackoverflow.com/questions/62535856/intent-resolveactivity-returns-null-in-api-30), apps targeting API level 30 or above requires adding the following `queries` section in `AndroidManifest.xml`:
> 
> ```
> <queries>
>   <intent>
>     <action android:name="android.intent.action.VIEW" />
>     <data android:scheme="https" />
>   </intent>
>   <intent>
>     <action android:name=
>         "android.support.customtabs.action.CustomTabsService" />
>   </intent>
> </queries>
> ```
> 
> We will update the SDK and Amplify docs to include the queries section: [aws-amplify/docs#3517](https://github.com/aws-amplify/docs/pull/3517)

This fixed it for me, thank you!

**Comment by denxorz** [comment]
@div5yesh The following document still misses the intent:
https://docs.amplify.aws/lib/auth/social/q/platform/flutter/#configure-auth-category

**Comment by tylerjroach** [comment]
@denxorz, According to https://developer.chrome.com/blog/custom-tabs-android-11/#frequently-asked-questions, the https intent should not be needed as long as the CustomTabsService intent is added. Are you seeing otherwise?

**Comment by tylerjroach** [comment]
I believe the required part of the intent is:

```
<intent>
    <action android:name=
        "android.support.customtabs.action.CustomTabsService" />
  </intent>
```

The Flutter documentation does call this out here: https://docs.amplify.aws/lib/auth/social/q/platform/flutter/#android-platform-setup

If you found that you had already done that, but it didn't work until adding the addition https section, please let us know.

**Comment by denxorz** [comment]
That does not seem to be enough, please check the answers above. And the PR for the docs where the 'intent' is added is already merged (but I am not sure where to).

> Sorry about that. Due to Android 11's [package visibility changes](https://stackoverflow.com/questions/62535856/intent-resolveactivity-returns-null-in-api-30), apps targeting API level 30 or above requires adding the following `queries` section in `AndroidManifest.xml`:
> 
> ```
> <queries>
>   <intent>
>     <action android:name="android.intent.action.VIEW" />
>     <data android:scheme="https" />
>   </intent>
>   <intent>
>     <action android:name=
>         "android.support.customtabs.action.CustomTabsService" />
>   </intent>
> </queries>
> ```
> 
> We will update the SDK and Amplify docs to include the queries section: [aws-amplify/docs#3517](https://github.com/aws-amplify/docs/pull/3517)

**Comment by denxorz** [comment]
I just restarted Visual Studio Code and the app (on Android 13), and now it is indeed no longer needed.
Somehow I did get the "no browsers installed" error on the first OAuth login I did. Not sure what that was, maybe the manifest got cached somewhere down the line.

Sorry for the inconvenience!
