### ISSUE TITLE
withHibernate member function missing in StopInstanceRequest?

### ISSUE THREAD

**Issue by po-stulate** [aws-amplify/aws-sdk-android#2583]
**State your question**
As title, Android Studio keeps complaining that `withHibernate` cannot be resolved in `com.amazonaws.services.ec2.model.StopInstancesRequest`.

I am referencing the method from the doc:
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/ec2/model/StopInstancesRequest.html#withHibernate-java.lang.Boolean-

Is it an API change or am I using it wrong?
Thank you!

**Which AWS Services are you utilizing?**
```
com.amazonaws:aws-android-sdk-auth-core:2.28.0
com.amazonaws:aws-android-sdk-core:2.28.0
com.amazonaws:aws-android-sdk-ec2:2.28.0
```

**Provide code snippets (if applicable)**
```Java
new com.amazonaws.services.ec2.model.StopInstancesRequest()
    .withHibernate(true);
```
Error:
```
Cannot resolve method 'withHibernate' in 'StopInstancesRequest'
```

**Environment(please complete the following information):**
 - Android Studio
 - SDK Version: 2.28.0

**Device Information (please complete the following information):**
 - Android API level 30

**Comment by raphkim** [comment]
Thank you for opening this issue @po-stulate 

It looks like Android SDK is not quite up-to-date with the EC2 APIs. I believe this is a case of de-prioritization since EC2 use-cases for Android mobile development is quite rare. I will investigate this and update the thread after I find out why our SDK is behind the service APIs.

**Comment by raphkim** [comment]
It looks we no longer support updating "aws-sdk-android" with the latest APIs from EC2.

However, you may find the [upcoming kotlin SDK](https://docs.aws.amazon.com/sdk-for-kotlin/latest/developer-guide/home.html) useful as we continue to develop it for GA.

**Comment by sktimalsina** [comment]
Closing this issue as there is nothing actionable. Please reopen if needed.
