### ISSUE TITLE
method 'void com.amazonaws.mobile.client.Callback.a(java.lang.Exception)' on a null object reference

### ISSUE THREAD

**Issue by irfanirawansukirman** [aws-amplify/aws-sdk-android#2612]
Hello, I am using aws mobile client on android. In the past 30 days I've been getting quite a lot of errors and don't know the root cause. From the crashlytics dashboard data I only get reports like this:

`Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'void com.amazonaws.mobile.client.Callback.a(java.lang.Exception)' on a null object reference
com.amazonaws.mobile.client.internal.InternalCallback.call (InternalCallback.java:77)
com.amazonaws.mobile.client.internal.InternalCallback.access$000 (InternalCallback.java:34)
com.amazonaws.mobile.client.internal.InternalCallback$1.run (InternalCallback.java:103)`

Several times I tried to reproduce the error on the android operating system including 11, 10, 9, 8, and 5 through the emulator and the device did not experience this. Is it possible that the AWS team knows the root of the problem? 

![Screenshot from 2021-09-01 09-18-27](https://user-images.githubusercontent.com/6957297/131602197-8a4b24d4-6f42-4194-b932-db33cea5d9be.png)

 - AWS Android SDK Version: 2.27.0
 - Device: OPPO [CPH1909, F11], Realme [realme C2], Samsung [Galaxy A71], Xiaomi [Redmi Note 3]
 - Android Version: 11, 10, 9, 8, 5

**Comment by eeatonaws** [comment]
Hi @irfanirawansukirman. Thanks for reporting this issue. Could you please share your code snippets?
