### ISSUE TITLE
onProgressChanged takes too much time to update

### ISSUE THREAD

**Issue by qwaskhaled** [aws-amplify/aws-sdk-android#2629]
I noticed that onProgressChanged  gets updated every 1024KB gets transferred. Is there any way I can shorten that period? 
This is a very long period of time to have the bytes transferred updated.

Thanks

**Comment by changxu0306** [comment]
Here is the javadoc of `onProgressChanged` method:
```
void onProgressChanged(int id,
                       long bytesCurrent,
                       long bytesTotal)

Called when more bytes are transferred.

Parameters:
    id - The id of the transfer record.
    bytesCurrent - Bytes transferred currently.
    bytesTotal - The total bytes to be transferred. 
```
It's not true that the progress get updated every 1024KB. You can even use a progress bar to track the upload progress.
