### ISSUE TITLE
[s3] java.lang.NullPointerException - TransferNetworkConnectionType.isConnected

### ISSUE THREAD

**Issue by mirland** [aws-amplify/aws-sdk-android#2635]
**Describe the bug**
Some users are getting this crash:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkConnectionType.isConnected(android.net.ConnectivityManager)' on a null object reference
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferRecord.checkPreferredNetworkAvailability(TransferRecord.java:369)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferRecord.pauseIfRequiredForNetworkInterruption(TransferRecord.java:229)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.pauseAllTransfersDueToNetworkInterruption(TransferNetworkLossHandler.java:216)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler.access$100(TransferNetworkLossHandler.java:37)
       at com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler$1.run(TransferNetworkLossHandler.java:125)
       at java.lang.Thread.run(Thread.java:776)

```
It started to happen after I upgraded version 2.26.0 to 2.29.0

Crash info:
The issue happened in Android 7, Android 10, and Android 11 (I could not reproduce, I'm checking the crash reports).
Multiple brands, (Samsung, oppo, Huawei)

**Comment by changxu0306** [comment]
According to your error log, `ConnectivityManager` is null when you call `TransferNetworkConnectionType.isConnected()` method. Could you please provide the code snippet so that we can figure out what goes wrong?

**Comment by mirland** [comment]
Yes, you're right I checked the diff code between that versions and you didn't do any changes. However, that crash didn't happen to me before, so I suppose it's not related to that version itself.

> Could you please provide the code snippet so that we can figure out what goes wrong?

I don't have a code snippet for that, I mean, I'm using the SDK like in the example app.

If I have something to upload, I start the transfer service 

```
  fun startTransferServiceIfNeeded(context: Context, notificationData: NotificationData) {
    if (!isRunningTransferService(context)) {
      val transferServiceIntent = createTransferServiceIntent(context, notificationData)
      context.startService(transferServiceIntent)
      logger.d("Start s3 service")
    } else {
      logger.d("S3 service is already working")
    }
  }

  private fun isRunningTransferService(context: Context): Boolean {
    val manager = context.getSystemService(Context.ACTIVITY_SERVICE) as? ActivityManager?
    return manager?.getRunningServices(Int.MAX_VALUE)
        ?.any { service -> TransferService::class.java.name == service.service.className } == true
  }
  ```
  
  
  I'm using `startService` instead of `ContextCompat.startForegroundService(` due to [this issue](https://github.com/aws-amplify/aws-sdk-android/issues/2471). I changed that in my latest version, I think it's not related but I wanted to point it out.
  
  Then, I add the files in this way:
  
  ```
    override fun uploadFile(
      bucketId: String,
      bucketFilePath: String,
      file: File,
      listener: TransferListener
  ): TransferObserver = transferUtility.upload(bucketId, bucketFilePath, file)
      .apply { setTransferListener(listener) }
 ```

**Comment by mirland** [comment]
Hi, that is a new sdk, right? cannot I use just this sdk? I mean, is it deprecated for users? 

I think you're not proposing a solution for this issue, you're just telling me that I should use an alternative.
However that SDK is based on this SDK so, the issue could be present. 

Cannot you just check if the value is null or not?

**Comment by mirland** [comment]
Hi, thanks for your quick response! 

>  I have checked the current code in a sample app and I can upload files without getting a NPE using the current docs.

I think it's hard to reproduce it, in the latest 90 days the issue has 47 crash events affecting 15 users (just a few users). Only 15 users are affected, so it will be hard to reproduce it. 

I will try to do it, but I think the stack trace is clear

The NPE is here:
```
 if (transferUtilityOptions != null &&
            !transferUtilityOptions.getTransferNetworkConnectionType().isConnected(connManager)) {
            ```
                 
So you have two options, `transferUtilityOptions` was updated aync in another thread or `getTransferNetworkConnectionType` is null.

If you read the ex message it tells you that `TransferNetworkConnectionType.isConnected(android.net.ConnectivityManager)' on a null object reference` so it seems that `getTransferNetworkConnectionType` is null.
So if you check that variable is not null the issue should be solved. Am I wrong?
