### ISSUE TITLE
AWSIotMqttManager with keystore sample 

### ISSUE THREAD

**Issue by frestoinc** [aws-amplify/aws-sdk-android#2636]
**State your question**
Is there a working sample on how to establish mqtt connection using keystore /certificate base. I've been working on this for 2 weeks but fail to establish connection in android platform with the sdk throwing EOFException.

```
W/AWSIotMqttManager: onFailure: connection failed.
    Connection lost (32109) - java.io.EOFException
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:197)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.io.EOFException
        at java.io.DataInputStream.readByte(DataInputStream.java:270)
        at org.eclipse.paho.client.mqttv3.internal.wire.MqttInputStream.readMqttWireMessage(MqttInputStream.java:92)
        at org.eclipse.paho.client.mqttv3.internal.CommsReceiver.run(CommsReceiver.java:137)
        at java.lang.Thread.run(Thread.java:923) 
E/AwsManager: Reconnecting:Connection lost (32109) - java.io.EOFException
I/AWSIotMqttManager: schedule Reconnect attempt 0 of 10 in 4 seconds

```
Java-Iot v2 and python aws samples works when using the same set of root, public cert and private key, so i guess its not a server problem

**Which AWS Services are you utilizing?**
AWS-IOT

**Provide code snippets (if applicable)**
```
private const val SOME_ENDPOINT = "SOME_ENDPOINT"
private const val SOME_ID = "SOME_ID"
private const val SOME_KS_PATH = "SOME_KS_PATH"
private const val SOME_KS_NAME = "SOME_KS_NAME"
private const val SOME_KS_PWD = "SOME_KS_PWD"
private const val SOME_ALIAS = "SOME_ALIAS"
private const val SOME_CERT = "SOME_CERT"
private const val SOME_PRIVATE_KEY = "SOME_PRIVATE_KEY"

private val mqttManager = AWSIotMqttManager(SOME_ID, SOME_ENDPOINT)

private fun saveKeyStore() {
    if (!AWSIotKeystoreHelper.isKeystorePresent(
                SOME_KS_PATH,
                SOME_KS_NAME
            )
        ) {
            AWSIotKeystoreHelper.saveCertificateAndPrivateKey(
                SOME_ALIAS,
                SOME_CERT,
                SOME_PRIVATE_KEY,
                SOME_KS_PATH,
                SOME_KS_NAME,
                SOME_KS_PWD)
        }
}

private fun getKeyStore() = AWSIotKeystoreHelper.getIotKeystore(
        SOME_ALIAS,
        SOME_KS_PATH,
        SOME_KS_NAME,
        SOME_KS_PWD)

private fun connect() {
 mqttManager.connect(getKeyStore()) { SOME_CALLBACK}
}
```

**Environment(please complete the following information):**
 - SDK Version: com.amazonaws:aws-android-sdk-iot:2.30.0

**Device Information (please complete the following information):**
 - Device: Emulator and Samsung Note 10
 - Android Version: Android 11

 - Specific to simulators:
If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by eeatonaws** [comment]
Hi @frestoinc, have you followed all of the [setup instructions](https://docs.amplify.aws/sdk/pubsub/getting-started/q/platform/android/) for using AWS IoT? An example of connecting with AWS IoT can be found in [our documentation](https://docs.amplify.aws/sdk/pubsub/working-api/q/platform/android/#establish-connection).

**Comment by kartic-techindustan** [comment]
@frestoinc can you please explain more, how you connect to iot from android using "CredentialProviders" ?
