### ISSUE TITLE
How to reset session/refresh tokens

### ISSUE THREAD

**Issue by hamen** [aws-amplify/aws-sdk-android#2637]
Hi all, our iOS team is using the following command

```
AWSCognitoIdentityUserPool.default().currentUser()?.clearSession()
```
to invalidate the current session and force a token refresh when some BE events occur.

I have been struggling finding the equivalent for the Android SDK. I really need your help with this.

**Which AWS Services are you utilizing?**

We are using Amplify/Cognito.

**Environment(please complete the following information):**
 - SDK Version: 2.25.1

**Comment by div5yesh** [comment]
Currently there is no equivalent for Android SDK.

**Comment by hamen** [comment]
Hi and thank you for the reply.

I found a couple of similar requests as well (https://github.com/aws-amplify/aws-sdk-android/issues/696, https://github.com/aws-amplify/aws-sdk-android/issues/1073).

For our specific use case, we are integrating Cognito with RevenueCat and our BE. After certain events, the BE instructs the app to refresh the token for security reasons and to avoid dealing with stale data.

The only way we can currently achieve this on Android is signing out the user and ask for a new login. You can imagine how this is incredibly disruptive for the user experience. The iOS team was able to refresh the token with one line of code, so they were able to implement the expected navigation flow and UX pretty quickly.

I appreciate that the SDK is automagically refreshing the token when necessary, but I wonder if you could suggest an approach to force a refresh when our app domain consider it necessary as well. Would it be absurd to have feature parity with the iOS SDK?

**Comment by changxu0306** [comment]
Manually force a refresh is not currently supported, but we have an open feature request here: aws-amplify/aws-sdk-android#696. Feel free to add your +1 and describe your use case on that issue, to help prioritize it. This is not something that is being actively worked on, but it has been a feature request in the amplify native libraries as well. We do want to align with iOS, and would implement it in the future. I am going to link those issues for reference. We will continue to use this issue to track interest in manually/proactively refreshing the token.

amplify-ios: aws-amplify/amplify-ios#1179
android-sdk: [aws-amplify/aws-sdk-android#696](https://github.com/aws-amplify/aws-sdk-android/issues/696)
amplify-android: aws-amplify/amplify-android#1283
amplify-flutter: [https://github.com/aws-amplify/amplify-flutter/issues/299](https://github.com/aws-amplify/amplify-flutter/issues/299)

**Comment by frimfram** [comment]
Hello!  Here is a test that uses ```revokeTokens``` method  of CognitoUser.  Is your use case something similar?

https://github.com/aws-amplify/aws-sdk-android/blob/0681a5ca00e47d73885ba55460e27776e5493612/aws-android-sdk-mobile-client/src/androidTest/java/com/amazonaws/mobile/client/AWSMobileClientTest.java#L484
