### ISSUE TITLE
Expiration field not available in AWSMobileClient android version

### ISSUE THREAD

**Issue by ajeet-inspify** [aws-amplify/aws-sdk-android#2648]
Reference aws-amplify/docs#1034 

android - implementation 'com.amazonaws:aws-android-sdk-mobile-client:2.30.0'

ios - 'AWSMobileClient', '= 2.9.8'

I want the sessionToken expiration, in order to perform SigV4 signing for aws iot.

But the android version of this library only has the following fields -

```
public interface AWSSessionCredentials {
    String getAWSAccessKeyId();

    String getAWSSecretKey();

    String getSessionToken();
}
```

On the other hand, the iOS sdk has the expiration field as well -

```
/**
 An AWS credentials container class.
 */
@interface AWSCredentials : NSObject

/**
 Access Key component of credentials.
 */
@property (nonatomic, strong, readonly) NSString *accessKey;

/**
 Secret Access Key component of credentials.
 */
@property (nonatomic, strong, readonly) NSString *secretKey;

/**
 Session Token component of credentials.
 */
@property (nonatomic, strong, readonly, nullable) NSString *sessionKey;

/**
 Date at which these credentials will expire.
 */
@property (nonatomic, strong, readonly, nullable) NSDate *expiration;
```

**How do I get the expiration field in Android?**

**Comment by raphkim** [comment]
Hi @ajeet-inspify ,

Perhaps you can use our existing [SigV4 signer](https://github.com/aws-amplify/aws-sdk-android/blob/a1c69ba5f6371b3f9a30f0b920f915e9a0536288/aws-android-sdk-core/src/main/java/com/amazonaws/auth/AWS4Signer.java#L40) in the SDK to sign your requests?

**Comment by ajeet-inspify** [comment]
Sure. Thank you for your help. I will close it now.
