### ISSUE TITLE
UnsupportedOperationException in setAuthenticationParameter(AuthenticationDetails.java:229)

### ISSUE THREAD

**Issue by AgiMaulana** [aws-amplify/aws-sdk-android#2655]
**Describe the bug**
The `authenticationParameters` property is declared as `Map<String, String>` which is an immutable key-value pair. But, in the line of 229, there is a call to mutation process `put(String key, String value)`

**To Reproduce**
A code sample or steps:
```
val authenticationDetails = AuthenticationDetails(
    email,
    hashMapOf("USERNAME" to email),
    hashMapOf()
)
continuation.setAuthenticationDetails(authenticationDetails)
continuation.continueTask()
```

**Which AWS service(s) are affected?**
aws-android-sdk-cognitoidentityprovider v2.33.0

**Expected behavior**
The continuation could continue the task without app crash due to `UnsupportedOperationException` of `put` process

**Screenshots**

![Screen Shot 2021-10-04 at 17 28 49](https://user-images.githubusercontent.com/8645266/135837512-117d316b-f6f3-4095-93f4-babaa7f04859.png)

![Screen Shot 2021-10-04 at 17 26 59](https://user-images.githubusercontent.com/8645266/135837489-82ef3271-5628-43c2-b7e1-55968adafb38.png)
![Screen Shot 2021-10-04 at 17 28 08](https://user-images.githubusercontent.com/8645266/135837509-e6625420-d3e2-43e6-a670-1108f0b284b5.png)

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.33.0
 - Device: Emulator
 - Android Version: Android 30 x86
 - Specific to simulators: There is no different process both for real device and simulator, the issue could affect both of them.

**Additional context**

**Comment by AgiMaulana** [comment]
can I make changes to fix this @eeatonaws ?

**Comment by eeatonaws** [comment]
Hi @AgiMaulana. Thanks for reporting this. We are working on determining the cause of the issue and will keep you updated here.
