### ISSUE TITLE
Failed to start sign in with social web UI when default browser does not support Custom Chrome Tab

### ISSUE THREAD

**Issue by kyleliao321** [aws-amplify/aws-sdk-android#2660]
**Describe the bug**
With aws-sdk-android 2.26.0, user can not start social sign in with web UI when its default browser does not support Custom Chrome Tab. Even though there are other Browser installed on the device that support Custom Chrome Tab.

For example, I've installed Chrome and Opera on my testing device. If I set Chrome as my default browser, user can start the social sign in with web UI normally. Once I change my default browser to Opera, it will failed with CustomTabsNotSupportedException. But Chrome is still on my device that can be used to launch Custom Chrome Tab.

After some investigation, I think the problem is with this check which located inside **launchCustomTabs**:
```java
if(!isCustomTabSupported()) {
    userHandler.onFailure(new CustomTabsNotSupportedException("Browser with custom tabs support not found."));
    return;
}
```
Internally, **isCustomTabSupported** checks if there's any browser support Custom Chrome Tab on the device:
```java
private boolean isCustomTabSupported() {
    if (isCustomTabSupported) {
        return true;
    }
    if (getSupportedBrowserPackage().size() > 0) {
        isCustomTabSupported = true;
        return true;
    }
    return false;
}
```
But the logic of **getSupportedBrowserPackage** does not work as expected.
```java
private Collection<String> getSupportedBrowserPackage(){
    PackageManager packageManager = context.getPackageManager();
    // Get default VIEW intent handler.
    Intent activityIntent = new Intent()
            .setAction(Intent.ACTION_VIEW)
            .addCategory(Intent.CATEGORY_BROWSABLE)
            .setData(Uri.fromParts("http", "", null));

    // Get all apps that can handle VIEW intents.
    List<ResolveInfo> resolvedActivityList = packageManager.queryIntentActivities(activityIntent, 0);
    List<String> packageNamesSupportingCustomTabs = new ArrayList<>();
    for (ResolveInfo info : resolvedActivityList) {
        Intent serviceIntent = new Intent()
                .setAction(ACTION_CUSTOM_TABS_CONNECTION)
                .setPackage(info.activityInfo.packageName);
        // Check if this package also resolves the Custom Tabs service.
        if(packageManager.resolveService(serviceIntent, 0) != null) {
            packageNamesSupportingCustomTabs.add(info.activityInfo.packageName);
        }
    }
    return packageNamesSupportingCustomTabs;
}
```
Instead of get all the apps that can handle VIEW intents, **packageManager.queryIntentActivities(activityIntent, 0)** will actually only return the default browser's package. That's why I cannot start the sign in flow with Opera as default browser, even though there's Chrome that can be used to launch the browser. 

My question is that is checking the Custom Chrome Tabs service necessary in **launchCustomTabs**? I think that **startActivityForResult** will handle it by itself. If there's no browser that supports this function, we will catch ActivityNotFoundException and send it through onError callback. This way, user can still sign in with social web UI when there's at least one browser supports Custom Chrome Tab on the device. And won't be block by the default browser.

**To Reproduce**
1. Installed Chrome and Opera on the device.
2. Make Opera as default browser. 
3. Sign in with social web UI (Amplify 1.25.1 or above):
```kotlin
// Amplify 1.25.1 use aws-sdk-android 2.30.0 internally. 
// It will call showSignIn to start the web UI.
Amplify.Auth.signInWithSocialWebUI(
    AuthProvider.google(),
    this,
    {
        Log.i(TAG, "Sign-In succeeds: $it")
    },
    {
        Log.w(TAG, "Sign-In fails: $it")
        Log.e(it.cause)
    }
)
```
4. Cannot start the sign-in flow.

**Which AWS service(s) are affected?**
Cognito user pool

**Expected behavior**
I will expect that user can start sign-in flow normally when there's any browser on the device that supports Custom Chrome Tab. And user should not be blocked by its default browser.

**Screenshots**
![截圖 2021-10-06 上午10 54 34](https://user-images.githubusercontent.com/68772637/136133500-0defc2d6-6860-460f-8c80-648fcb516744.png)

**Environment Information (please complete the following information):**
 - AWS Android SDK Version:2.30.0
 - Amplify: 1.25.1
 - Device: Samsung Galaxy Note 20 Ultra 5G / Sony SOV36
 - Android Version: Android 11 / Android 8
 - Specific to simulators: No

**Comment by AndreasBoehm** [comment]
I created a pull-request to address that issue: https://github.com/aws-amplify/aws-sdk-android/pull/2721
