### ISSUE TITLE
Deprecating Facebook Login support on Android WebViews

### ISSUE THREAD

**Issue by BillBunting** [aws-amplify/aws-sdk-android#2663]
**Which AWS Services is the feature request for?**
aws-android-sdk-auth-facebook

Upgrade Facebook dependency to latest to resolve "Deprecating Facebook Login support on Android WebViews"
https://developers.facebook.com/docs/facebook-login/android/deprecating-webviews

**Is your feature request related to a problem? Please describe.**
Facebook login no longer supports WebViews and Facebook requires this upgrade. Beginning October 5, 2021, Facebook Login will no longer support using Android embedded browsers (WebViews) for logging in users.

**Describe the solution you'd like**
Upgrade to the latest FB dependencies via pull request: https://github.com/aws-amplify/aws-sdk-android/pull/2652

**Comment by eeatonaws** [comment]
Thank you for your contribution! Closing this issue as the PR was released as part of AWS SDK for Android version 2.41.0.
