### ISSUE TITLE
getSession returns Expired Token if My Android Device's Local Data & Time is in Past 

### ISSUE THREAD

**Issue by arun-ns** [aws-amplify/aws-sdk-android#2665]
**Describe the bug**
getSession returns Expired Token if Mobile's Local Data & Time is in Past. In my case, token expires in Every 60 minutes then i call getSession/getSessionInBackground to get new Access. I think cognitoidentityprovider is not checking with NTP time.

**To Reproduce**
A code sample or steps:

1. Login via  getSessionInBackground(authenticationHandler);
2. Close the App and change my mobile device time to some Past Time (2 days before)
3. Open the app after 60 minutes 
4. Check Access token return same as before i got

**Which AWS service(s) are affected?**
com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.34.0

**Expected behavior**
Need to get New token even if my local time is past time

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.34.0
 - Device: Nokia 7.2
 - Android Version: 10.0

**Comment by gpanshu** [comment]
Without calling an external API this can not be resolved. I would recommend you use fetchAuthSession instead from amplify-android which will refresh your token or make the user sign in again when the timezone changes.
