### ISSUE TITLE
Hard refresh of access token

### ISSUE THREAD

**Issue by aayoushee** [aws-amplify/aws-sdk-android#2671]
Is there any API similar to https://docs.amplify.aws/lib/auth/manageusers/q/platform/js/#retrieve-current-session auth.currentSession() in android that would issue new access and id tokens on the basis of a refresh token? My usecase is to hard refresh of access token before the defined TTL.

**Comment by poojamat** [comment]
Hi @aayoushee we don't have any api for hard refresh of tokens at this time, but the good new is we are working on it. In the mean time there is a work around by using lambda. Its discussed[ in this issue ](https://github.com/aws-amplify/amplify-android/issues/919)towards the bottom.
