### ISSUE TITLE
How to log out the users out if their usernames/passwords have been changed from other platforms (iOS/Web)?

### ISSUE THREAD

**Issue by ln206** [aws-amplify/aws-sdk-android#2703]
**State your question**
How to log out the users out if their usernames/passwords have been changed from other platforms (iOS/Web) while they are logged in on Android?

**Which AWS Services are you utilizing?**
Amazon Cognito (aws-android-sdk-mobile-client)

**Environment(please complete the following information):**
com.amazonaws:aws-android-sdk-mobile-client:2.30.0

**Comment by poojamat** [comment]
@ln206 After username/password has been updated sign out the[ user with global option](https://docs.amplify.aws/lib/auth/signOut/q/platform/android/#:~:text=Calling%20signOut%20without%20any%20options%20will%20just%20delete%20the%20local%20cache%20and%20keychain%20of%20the%20user.%20If%20you%20would%20like%20to%20sign%20out%20of%20all%20devices%2C%20invoke%20the%20signOut%20api%20with%20advanced%20options.). This will force sign out the user from all the devices.
