### ISSUE TITLE
SessionID

### ISSUE THREAD

**Issue by BhayashriPatil** [aws-amplify/aws-sdk-android#2716]
Issue related to session: <null> when we submit event that time sessionID  

"session": 
{ 
"id": "00000000-00000000", 
"startTimestamp": 0 
}

submitevent()

This needs to post with id
"session": {
"id": "2e82a88e-20211116-160842989",
"startTimestamp": 1637078922989
},

Bhagyashri Patil 
November 16, 2021, 8:21 AM
Edited

Checked this issue from android app side for session duration as I found this record time properly but for aws pinpoint calculation cant debugged.

Session Started 

pinpoint contains below json :

{
"class": "com.amazonaws.mobileconnectors.pinpoint.analytics.AnalyticsEvent",
"hashCode": "945ff25",
"event_id": "92170035-8bb3-4fe9-82de-5d616fddfdf1",
"event_type": "_session.start",
"unique_id": "e8db8202-33f5-464c-b5da-af682e82a88e",
"timestamp": 1637078990788,
"platform": "ANDROID",
"platform_version": "9",
"make": "samsung",
"model": "SM-J701F",
"locale": "en",
"carrier": "Idea",
"session": {
"id": "2e82a88e-20211116-160842989",
"startTimestamp": 1637078922989
},
"sdk_version": "2.20.1",
"sdk_name": "aws-sdk-android",
"app_version_name": "1.0.1",
"app_version_code": "35",
"app_package_name": "com.thread.TURBO",
"app_title": "APP_NAME",
"app_id": "368e98b0670348a5b5a851f2689f6cad",
"attributes": {
"STUDY_ID": "34badc6c-fd8f-46b5-9daa-0d93017951d0",
"SITE_ID": "62c72d58-f7ff-402e-af97-9b4eb10fa7de",
"CLIENT_ID": "654154"
}
}

When app goes background

When submitevent(): 

{
"class": "com.amazonaws.mobileconnectors.pinpoint.analytics.AnalyticsEvent",
"hashCode": "b0fba3e",
"event_id": "2682521d-8ba3-40be-a30c-8ae08718d0a9",
"event_type": "APP_SESSION_DURATION",
"unique_id": "e8db8202-33f5-464c-b5da-af682e82a88e",
"timestamp": 1637076789920,
"platform": "ANDROID",
"platform_version": "9",
"make": "samsung",
"model": "SM-J701F",
"locale": "en",
"carrier": "Idea",
"session": {
"id": "00000000-00000000",
"startTimestamp": 0
},
"sdk_version": "2.20.1",
"sdk_name": "aws-sdk-android",
"app_version_name": "1.0.1",
"app_version_code": "35",
"app_package_name": "com.thread.TURBO",
"app_title": "APP_NAME",
"app_id": "368e98b0670348a5b5a851f2689f6cad",
"attributes": {
"STUDY_ID": "34badc6c-fd8f-46b5-9daa-0d93017951d0",
"PARTICIPANT_ID": "626ff70b-b3e4-4494-a663-9be876712b9d",
"CLIENT_ID": "654154",
"CATEGORY": "ON_BOARDING",
"SUB_CATEGORY": "APP_SESSION_DURATION"
},
"metrics": {
"APP_SESSION_DURATION": 101007
}
}

We are recording user session start and stop submit session facing issue with cubmitevent that time posted "id": "00000000-00000000", nit actual one so How can I check

**Comment by poojamat** [comment]
@BhayashriPatil  are you using[ pinpoint custom events?](https://docs.amplify.aws/sdk/analytics/events/q/platform/android/#custom-events)
