### ISSUE TITLE
AWSIotMqttManager getConnectionState() is not public

### ISSUE THREAD

**Issue by rigroch** [aws-amplify/aws-sdk-android#2735]
How do I get a states of AWSIotMqttManager's connection status?

I think it will be public.

thank you..

**Comment by frestoinc** [comment]
> How do I get a states of AWSIotMqttManager's connection status?
> 
> I think it will be public.
> 
> thank you..

You should make use of the `AWSIotMqttClientStatusCallback` interface.

An example would be:
```
var state: AWSIotMqttClientStatusCallback.AWSIotMqttClientStatus? = null
val mqttManager = AWSIotMqttManager("someId", "someEndpoint")
mqttManager.connect(someKeyStore) { status, throwable ->
     state = status
     ...
     ...
}
```

**Comment by poojamat** [comment]
@rigroch AWSIotMqttManager has a method called
    MqttManagerConnectionState getConnectionState() {
        return connectionState;
    }
