### ISSUE TITLE
"aws-android-sdk-cognitoidentityprovider-asf" android jar is throwing a generic error on some android 11+ devices

### ISSUE THREAD

**Issue by poojamat** [aws-amplify/aws-sdk-android#2748]
**Describe the bug**
We've hit a bug in the "aws-android-sdk-cognitoidentityprovider-asf" android jar in our app. It's throwing a generic error on some android 11+ devices when asked to generate a signature. The cause of the bug probably lies in our application rather than the jar, but.. we've decompiled the jar and found it is masking the underlying cause of the error. We'd like to modify and recompile it so we can get access to the original error, and we'd rather do this using the original source code instead of working from a decompiled jar, but the source code isn't public for some reason.

Making the source code open source would be nice, but just being able to see the source or have access to it in some NDA covered way would be fine.

Here is brief overview of how we are using the jar:

We've got a customer facing mobile app written in react-native that runs on android and iOS. An AWS Cognito Pool is the authentication provider and we use a fork of the amplify-js library for handle communicating with it. We forked it because the original has no way to generate the device signatures required by Cognito's Advanced Security. We created a react-native library that is a thin wrapper around the AWS provided native libraries for each platform (https://github.com/ConnectedHomes/react-native-cognito-asf-fingerprint) and plugged that into our fork.
========

My understanding and my investigation:
This jar file is mentioned on:
 https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-viewing-advanced-security-app.html
But we seems dont have it on Github which is truly a closed source project.
https://github.com/aws-amplify/aws-sdk-android

So as it is related to advance security, there could be some security concern, so I have set the right expectation that we can't share the source code. 

But on the Cognito side, is there anything else we can suggest?

If we can share the code by signing some NDA, we can engage the TAM regarding this, this is an enterprise ### customer.

**To Reproduce**
A code sample or steps:
```
Your code
```

**Which AWS service(s) are affected?**

**Expected behavior**

**Screenshots**

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [e.g. 2.6.25]
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators: [e.g. Yes/No]

**Additional context**

**Comment by eeatonaws** [comment]
A PR with the fix for this issue has been released as part of AWS SDK for Android version 2.38.0.
