### ISSUE TITLE
Table Class does not have loadTable method.

### ISSUE THREAD

**Issue by SamnnyWong** [aws-amplify/aws-sdk-android#2753]
Table dbTable = Table.loadTable(dbClient, "TableName1") Table does not have loadTable method.

I followed this doc [AWS Dynamo doc api](https://aws.amazon.com/blogs/mobile/using-amazon-dynamodb-document-api-with-the-aws-mobile-sdk-for-android-part-2/)

I noticed that the link I provided above is not for amplify or it may be deprecated. I am trying to curd on dynamo table (several existing dynamo tables) directly from the android client app. I went through the [amplify doc](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/android/#sample-schema) but it is not what I need. 
Is there a way to set this up? I also provided the not working code below.

```
 CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
            context, AWSConstants.IDENTITY_POOL_ID, AWSConstants.Regions.AP_SOUTH_1);

    // Create a connection to DynamoDB
    AmazonDynamoDBClient dbClient = new AmazonDynamoDBClient(credentialsProvider);

    // Create a table reference
    Table dbTable = Table.loadTable(dbClient, "ShoppingLists");
    // android studio prompted "Cannot resolve method 'loadTable' in 'Table'" error.

    Document memo = new Document();
    memo.put("Apple", "apple");
    dbTable.putItem(memo);
```

Thanks in advance.

**Comment by eeatonaws** [comment]
@SamnnyWong, although that document is older, you should still be able to call `Table.loadTable`, defined [here](https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-ddb-document/src/main/java/com/amazonaws/mobileconnectors/dynamodbv2/document/Table.java#L106). Could you please verify that you have added the dependency for aws-android-sdk-ddb-document to your build.gradle file?
