### ISSUE TITLE
Allow Authentication Flow Type to be changed after configuration like the JavaScript API

### ISSUE THREAD

**Issue by ChrisSawczukMSM** [aws-amplify/aws-sdk-android#2786]
**Which AWS Services is the feature request for?**
Amplify Auth, Cognito

**Is your feature request related to a problem? Please describe.**
It's currently not possible to switch authentication flow type after you configure the SDK which means switching between USER_SRP_AUTH and CUSTOM_AUTH is not possible, and implementing SRP via CUSTOM_AUTH is massive repetition of effort.

**Describe the solution you'd like**
It would be nice to be able to configure the `AWSCognitoAuthPlugin`to allow changes to the authentication flow type after `Amplify.configure` has been called. This will bring parity between the native mobile SDK and the javascript SDK, allowing businesses to implement a similar pattern of authentication on both mobile and web.

**Describe alternatives you've considered**
An alternative would be implementing some kind of delegate AuthPlugin that would delegate to either instances of a configured AWSCognitoAuthPlugin- but this also isn't possible due to the nature of the AWSMobileClient singleton.

**Additional context**
The [JavaScript documentation for this feature](https://docs.amplify.aws/lib/auth/switch-auth/q/platform/js/)

**Comment by tjleing** [comment]
Thank you for opening this issue, @ChrisSawczukMSM -- I see the JS docs you linked, and we don't have a matching feature currently, but would you mind going into a little detail about the use case you'd like this feature for?

**Comment by eeatonaws** [comment]
AWS SDK for Android version 2.43.0 introduced an additional signIn API that takes an AuthFlowType as a parameter and Amplify Android version 1.34.0 added an AuthFlowType property to AWSCognitoAuthSignInOptions, in order to switch the auth flow type at runtime when signing in. Are there other APIs in the auth category that you are requesting to be able to change the auth flow type for?

**Comment by div5yesh** [comment]
As pointed out by @eeatonaws, signIn API takes a parameter for switching AuthFlowType for SDK 2.43.0+ and Amplify 1.34.0+. Let us know if you are having any other issues.
