### ISSUE TITLE
AWSLocationTracker access the wrong region when trying to perform: geo:BatchUpdateDevicePosition

### ISSUE THREAD

**Issue by khairunsh** [aws-amplify/aws-sdk-android#2801]
Hello, I've followed this documentation https://docs.amplify.aws/guides/location-service/setting-up-your-app/q/platform/android/. I created the Resource in the AWS console with region `ap-southeast-1`. When I tried to run the application, with this code:

```Kotlin
        AWSMobileClient.getInstance().initialize(
            applicationContext, object : Callback<UserStateDetails> {
                override fun onResult(userStateDetails: UserStateDetails) {
                    val executorService = Executors.newFixedThreadPool(4)

                    executorService.execute {
                        val client = AmazonLocationClient(AWSMobileClient.getInstance())
                        val request = SearchPlaceIndexForTextRequest()

                        request.text = "Space Needle"
                        request.indexName = "MyPlaceIndex"

                        val response = client.searchPlaceIndexForText(request)

                        for (result in response.results) {
                            Log.i("QuickStart", result.place.toString())
                        }
                    }
                }

                override fun onError(error: Exception) {
                    Log.e("QuickStart", "Initialization error: ", error)
                }
            }
        )
```

The app crashed with this log:
```
com.amazonaws.services.geo.model.AccessDeniedException: User: arn:aws:sts::599678976801:assumed-role/amplify-kubikasidriverapp-dev-211840-unauthRole/CognitoIdentityCredentials is not authorized to perform: geo:SearchPlaceIndexForText on resource: arn:aws:geo:us-east-1:599678976801:place-index/MyPlaceIndex (Service: AmazonLocation; Status Code: 403; Error Code: AccessDeniedException; Request ID: f09d8224-671d-49bf-a456-d98dafccff33)
```

You can see that the app is trying to access the wrong region resource `on resource: arn:aws:geo:us-east-1:599678976801:place-index/MyPlaceIndex`. This is should be the correct one `on resource: arn:aws:geo:ap-southeast-1:599678976801:place-index/MyPlaceIndex`.

I tried to add this code after client initialization:
```kotlin
client.setRegion(Region.getRegion("ap-southeast-1"))
```

Finally, the app is not crashed anymore. And I can see `result.place.toString()` in the Logcat.

So, when I tried to follow this documentation as well (https://docs.amplify.aws/guides/location-service/tracking-device-location/q/platform/android/.) for location tracking, I have the same problem. But, I can't find where I can set the region for the AWSLocationTracker.

The log:
```
com.amazonaws.services.geo.model.AccessDeniedException: User: arn:aws:sts::599678976801:assumed-role/amplify-kubikasidriverapp-dev-211840-unauthRole/CognitoIdentityCredentials is not authorized to perform: geo:BatchUpdateDevicePosition on resource: arn:aws:geo:us-east-1:599678976801:tracker/TimeBasedTracking (Service: AmazonLocation; Status Code: 403; Error Code: AccessDeniedException; Request ID: 1fd69240-1509-4c57-afd5-1501c6f32777)
```

**permission policies**
SearchLocation
```JSON
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "geo:SearchPlaceIndexForText",
            "Resource": "arn:aws:geo:ap-southeast-1:599678976801:place-index/MyPlaceIndex"
        }
    ]
}
```
TrackLocation
```JSON
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "geo:BatchUpdateDevicePosition",
            "Resource": "arn:aws:geo:ap-southeast-1:599678976801:tracker/TimeBasedTracking"
        }
    ]
}
```

**Which AWS service(s) are affected?**
AWS Location Service

**Expected behavior**
Accessing the resource with the correct region.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.4.0
 - Device: Samsung Galaxy A50
 - Android Version: Android 11
 - Specific to simulators: No

**Screenshots**

![Screen Shot 2022-02-16 at 10 21 02](https://user-images.githubusercontent.com/25631476/154189985-40e82812-9bac-4b4d-9004-988f22710b5f.png)

![Screen Shot 2022-02-16 at 10 20 39](https://user-images.githubusercontent.com/25631476/154189998-7af65d15-a023-43ba-945c-cf2948b820c8.png)

**Comment by sktimalsina** [comment]
@khairunsh It seems that region setting is missing in Doc. You can add region of `ap-southeast-1` in your awsconfiguration.json file. AWSClient will read this config file. Please have a look at [more detailed documentation and sample](https://github.com/aws-samples/amazon-location-samples/tree/main/tracking-android#initializing-the-sdk)

Let me know if it solves your issue.

**Comment by eeatonaws** [comment]
Closing the issue due to lack of response, please reopen if this is still an issue.
