### ISSUE TITLE
Switching of Auth flows dynamically in Android SDK

### ISSUE THREAD

**Issue by fad-aws** [aws-amplify/aws-sdk-android#2828]
**Which AWS Services is the feature request for?**
Android SDK for AWS Amplify for Cognito custom authentication

**Is your feature request related to a problem? Please describe.**
Requirement is to switch authentication flow dynamically based on end-user selections. For example,  a user initiates social login and it fails, so they want to retry with email + password OR  a user logs in with email + password, then logs out and tries to login again with OTP.
This is currently working in web version and iOS sdk (using a work-around mentioned below) but not on Android and hence blocking the release of Android app.

**Describe the solution you'd like**
In iOS sdk,  we can override the default auth flow that’s specified in the config by setting the _isCustomAuth_ property on the underlying instance of _AWSCognitoIdentityUserPool_ but Android sdk does not expose the custom auth attribute on the user pool in a mutable way. It is requested to make this attribute available and therefore similar behaviour can be replicated on both iOS and Android sdk.

**Describe alternatives you've considered**
No alternative available.

**Comment by sdhuka** [comment]
Fix is released in v1.34.0.
