### ISSUE TITLE
Is it a requirement to add "org.apache.http.legacy" in the manifest for the app with min sdk 24

### ISSUE THREAD

**Issue by arunj-kp** [aws-amplify/aws-sdk-android#2839]
**State your question**
AWS core sdk has added the following manifest attribute at this [line](https://github.com/aws-amplify/aws-sdk-android/blame/main/aws-android-sdk-core/src/main/AndroidManifest.xml)

By referring to this [page](https://developer.android.com/about/versions/pie/android-9.0-changes-28), I guess this might not need on apps with min SDK version is 24. If that is the case, removing that line may also reduce the APK size. I will check with the AWS team and confirm.
So, the question is, can I remove it as my app's min version is 24? 

Quoting the note from the above developer.android page
_Note: The android:required="false" attribute is required for apps that have a minimum SDK of 23 or lower, because on devices with API levels lower than 24, the org.apache.http.legacy library is not available. (On those devices, the Apache HTTP classes are available on the bootclasspath.)_
**Which AWS Services are you utilizing?**
S3

**Provide code snippets (if applicable)**

<uses-library android:name="org.apache.http.legacy" android:required="false" />

**Environment(please complete the following information):**
 - SDK Version: 2.42.0 (latest version)

**Device Information (please complete the following information):**
 - All Android devices

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by sktimalsina** [comment]
Thanks for pointing out the issue. 

I think I might have interpreted the documentation differently as per below line in same [page](https://developer.android.com/about/versions/pie/android-9.0-changes-28#apache-p).
To continue using the Apache HTTP client, apps that target Android 9 and above can add the following to their AndroidManifest.xml:
```<uses-library android:name="org.apache.http.legacy" android:required="false"/>```

My understanding is that above line is required for any newer Android versions. And, `android:required="false"` portion is specifically required for targeting apps with minSdk <= 23.

**Comment by arunj-kp** [comment]
we removed it from the app's manifest explicitly by adding the following code and it works fine (our min sdk version is 24)
```
        <uses-library
            android:name="org.apache.http.legacy"
            android:required="false"
            tools:node="remove" />
```

**Comment by gpanshu** [comment]
You are both correct, since we support apps lower than 24 we must have that line to support legacy http. Seeing as your workaround works I am going to close this question.
