### ISSUE TITLE
HostedUI uses cached configuration

### ISSUE THREAD

**Issue by tjleing** [aws-amplify/aws-sdk-android#2842]
**Describe the bug**
HostedUI configuration is loaded from SharedPreferences even when `awsconfiguration.json` is updated more recently.  This can manifest in a verification error on one of the initialization fields, even after changing the config file.

**To Reproduce**
1. Set up app with Hosted UI.
2. Set a breakpoint on `_showSignIn` in `AWSMobileClient.java`, run the app and note that it uses the proper configuration blob.
3. Update the `awsconfiguration.json` (and `amplifyconfiguration.json` -- you can run `grep` to make sure that there is no possible other source of backups), changing the `WebDomain`, for example.
4. Re-run the app and note that the blob has not updated.
5. Delete the virtual device and create a new one.
6. Re-run the app and note that the blob has updated.

**Which AWS service(s) are affected?**
After looking through `AWSMobileClient.java` (search for `mStore.get`), it looks like the issue is just with Hosted UI.

**Expected behavior**
Hosted UI should load the proper configuration from `awsconfiguration.json` and trust it over the SharedPreferences configuration.  I expect that this will just be a reordering of `getHostedUIJSON(awsConfig)`.

**Comment by banji180** [comment]
After following the steps above, I can see the updated change in the config used by the HostedUI.
