### ISSUE TITLE
How to use sdk to use Secure Element to connect iot on android platform

### ISSUE THREAD

**Issue by Runxing123** [aws-amplify/aws-sdk-android#2857]
**State your question**
How to use sdk to use Secure Element to connect iot on android platform? Such as Microchip ATECC608B

**Which AWS Services are you utilizing?**
aws iot

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: 
     api "com.amazonaws:aws-android-sdk-iot:2.16.1"
    api "com.amazonaws:aws-android-sdk-mobile-client:2.12.2"

**Device Information (please complete the following information):**
 - Device: 
   custom android tablet device
 - Android Version: 
  android9.0
 - Specific to simulators:
  no

**Thanks in advance for your reply, thank you.**

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by sktimalsina** [comment]
@Runxing123 can you clarify more on what you are trying to achieve? AWS IOT SDK provides MQTT and WSS protocols to connect to your AWS IoT (and in turn IoT) devices. Have you looked into [AWS IoT documentation](https://docs.aws.amazon.com/iot/latest/developerguide/what-is-aws-iot.html) on how to get started with setting up IoT infrastructure first?

**Comment by Runxing123** [comment]
@sktimalsina 

Thanks for your replies. 

Our current project is using "com.amazonaws:aws-android-sdk-iot:2.16.1"
"com.amazonaws:aws-android-sdk-mobile-client:2.12.2" is used to complete the connection of mqtt, and the function is also normal. 

Now our motherboard has an integrated TPM chip, the chip model link is this [https://devices.amazonaws.com/detail/a3G0L00000AAOCcUAP/ATECC608a-CryptoAuthentication-Secure-Element]
According to the introduction, it is necessary to use the interface of pkcs#11, but I am not sure whether the existing sdk supports the use of PKCS#11 on the android platform, so that the use of security chips to connect mqtt can be realized. 

Looking forward to your reply.

**Comment by sktimalsina** [comment]
@Runxing123 
This particular SDK is just a client application for Android and talks to the IoT endpoint as [in here](https://docs.aws.amazon.com/iot/latest/developerguide/connect-to-iot.html). And hence from SDK point of view, there supposedly should not be any difference. 

I would suggest to actually give it a try and see if you run into any issues and then either reopen this issue or create a new specific issue that you run into I don't have your exact environment. 

Closing this issue for now. Please feel free to reopen as per above suggestions.
