### ISSUE TITLE
Start/Pause/Resume a multipart file upload

### ISSUE THREAD

**Issue by arunj-kp** [aws-amplify/aws-sdk-android#2864]
**State your question**
What is the recommended way to start, pause & resume a multipart upload inside an Android Worker (androidx.work.Worker) implementation?

**Which AWS Services are you utilizing?**
S3 TransferUtility under com.amazonaws:aws-android-sdk-s3:<latest_release_version>

**Provide code snippets (if applicable)**
```
override fun doWork(){
            transferUtility?.upload(<s3_upload_key>, <file>)
}
```

**Environment(please complete the following information):**
 - SDK Version: 2.41.1 (com.amazonaws:aws-android-sdk-s3)

**Device Information (please complete the following information):**
 - Any Android device

**Description**

In the Worker class (androidx.work. Worker) with network connectivity constraint, it is easy to start an S3 file upload by calling the `upload` method in `TransferUtility`. Based on the upload file size, AWS SDK intelligently starts multipart uploads. But, when a connectivity failure happens, the Worker will stop, and it will be started (then, the doWork() will be started again) whenever the network is back. At this time, the upload starts from the beginning instead of resuming.

As I added in the above section, I use the following code snippet to upload a file inside the worker class implementation.
```
override fun doWork(){
            transferUtility?.upload(<s3_upload_key>, <file>)
}
```

**Usecase:**
Being a user, assume I started an s3 upload for a file of 22MB. The AWS SDK starts the multipart upload requests in the following sequence:
<initiate_request>
<upload_part1>
<upload_part2>
<upload_part3>
<upload_part4>
<upload_part5>
<complete_request>
Here, all first parts are 5MB each and the last one is 2MB.

Now, assume the device's internet connectivity is lost while uploading the last part. The Worker stops, and it will be started (means doWork() will be invoked) whenever the network is back. If the network is back after 20 minutes, the Worker will start then, and the transferUtility?.upload() [the code mentioned above] will be called again.

At this time, my expectation from the SDK is:
It should upload only the remaining parts & the complete request. That is, the following ones (as the network failure happened while uploading the last part):
<upload_part5>
<complete_request>

_Actual Result:
But, SDK starts the upload from the beginning:
<initiate_request>
<upload_part1>
<upload_part2>
<upload_part3>
<upload_part4>
<upload_part5>
<complete_request>_

**Comment by arunj-kp** [comment]
@sdhuka, this is a critical one. Please guide us with some sample code. We have implemented multipart upload (using aws sdk) for the resume part-upload feature, but it does not work in that way with our current implementation. So, we need your guidance to implement this feature perfectly.
I had tried `transferUtility?.resume(transferRecordId)`. But, it is not reliable because `transferRecordId` will be available only if the worker pauses the upload and it does not happen always.

**Comment by sdhuka** [comment]
@arunj-kp transferUtility [upload api](https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferUtility.java#L446) returns [TransferObserver](https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferObserver.java#L51) which contains id(transferRecordId). On first starting the upload you can persist this id along with the upload key and on restarting the worker you can use [transferUtility.resume(id)](https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferUtility.java#L866). Please also make sure you call [transferUtility.pause(id)](https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferUtility.java#L832) on worker onStop.

**Comment by arunj-kp** [comment]
@sdhuka I have done that already. calling pause() from the Worker's onStopped() and next time when the worker starts, resume if there is a paused work. But, it works only if the previous work is paused. Is there any other robust way to do this?

**Comment by sdhuka** [comment]
Unfortunately there is no better way to do this. Could you please provide some more details(including logs) on what is the issue you are facing with this approach? we can then help fixing any bugs related to resume and pause api.

**Comment by arunj-kp** [comment]
@sdhuka thanks, I have created a feature request ticket https://github.com/aws-amplify/aws-sdk-android/issues/2872. Please let me know if you have any questions (you can reply in that ticket or ping me `@kparunjyothis` in the discord app)

**Comment by sdhuka** [comment]
@arunj-kp can you please provide more details on the issue where the transfer work is not paused correctly? Trying to understand whether we still need this issue open or can we close since we have another issue open for feature request.
