### ISSUE TITLE
Social SignOut failed due to time out 

### ISSUE THREAD

**Issue by Papashkin** [aws-amplify/aws-sdk-android#2904]
**Describe the bug**
I'm using **AWS Mobile Client** for social sign-In/Sign-Up and SignOut.
I have several _Google_ accounts for tests and found that for some devices after **signOut()** I see that a user state was changed from SIGNED_IN to SIGNED_OUT (after that using the Google sign-In option in the app I will see a list of available accounts)
But for some reason on some devices I received an `AuthServiceException`:
```
com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthServiceException: Timed out while waiting for sign-out redirect response.
```
At the same timeб user state is still SIGNED_IN.
On that device I faced a problem, I also don't see the list of available Google accounts if selected Social sign-in (i.e. still can't choose a new google account). Even if I don't have Google accounts on that device at all.

**To Reproduce**
A code sample or steps:
```
val options = SignOutOptions.builder()
    .invalidateTokens(true)
    .build()

AWSMobileClient.getInstance().signOut(options, object : Callback<Void> {
        override fun onResult(result: Void) {
            onResult()
        }

        override fun onError(e: Exception) {
            Timber.wtf("Error occurred while Cognito sign Out: $e")
            onResult()
        }
    })
```

**Which AWS service(s) are affected?**
Amazon Cognito (social auth)

**Expected behavior**
The behaviors of social sign-out are same on all devices.

**Screenshots**

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.45.0
 - Device: Samsung A52s
 - Android Version: Android 12

**Additional context**
Here is my config file:
```
{
  "IdentityManager": {
    "Default": {}
  },
  "CredentialsProvider": {
    "Default": {}
  },
  "CognitoUserPool": {
    "Default": {
      "PoolId": "XXX",
      "AppClientId": "XXXX",
      "Region": "eu-central-1"
    }
  },
  "Auth": {
    "Default": {
      "authenticationFlowType": "USER_SRP_AUTH",
      "OAuth": {
        "WebDomain": "XXXX.amazoncognito.com",
        "AppClientId": "XXXX",
        "SignInRedirectURI": "<some_url>",
        "SignOutRedirectURI": "<some_url>",
        "responseType": "token",
        "state": "STATE",
        "Scopes": [
          "openid",
          "profile",
          "email"
        ]
      }
    }
  }
}
```
We don't use Identity pool (it's not set in the Amazon console)

**Comment by div5yesh** [comment]
On a successful signout, cognito tries to redirect back to the app to continue with local sigout on the device. The exception you are seeing is due to hostedUI not being able to redirect back to the app. This may be due to incorrect OAuth configuration. Please refer our documentation for [social sign-in](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android/).

**Comment by Papashkin** [comment]
@div5yesh hello!
Thank you for the answer.
AFAIK previously the callbacks should be like this:
```
"SignInRedirectURI": "<app_domain>://callback/",
"SignOutRedirectURI": "<app_domain>://signout/",
```
in the configuration JSON file.
In the documentation you shared with me I found that the redirect URL should be like that:
`<user_pool_domain>/oauth2/idpresponse`
Does this `user_pool_domain` mean the `WebDomain` from the configuration file? Or it should be something else?

**Comment by Papashkin** [comment]
Any updates?

**Comment by Papashkin** [comment]
@div5yesh The one thing I don't understand, in the documentation you shared with me the Amplify library is used. However, in my code, I'm using AWS SDK for Android:
```
const val amazonSdk = "2.45.0"

object Amazon {
    const val core = "com.amazonaws:aws-android-sdk-core:${amazonSdk}"
    const val client = "com.amazonaws:aws-android-sdk-mobile-client:${amazonSdk}"
    const val cognitoAuth = "com.amazonaws:aws-android-sdk-cognitoauth:${amazonSdk}"
} 
```
Does it mean that I have to add Amplify libraries as well?

**Comment by gpanshu** [comment]
@Papashkin is there a reason you are using AWSMobileClient vs the Amplify library ?

**Comment by gpanshu** [comment]
Can you try signout with `.globalSignOut(true)`

**Comment by gpanshu** [comment]
Hi @Inshaki I am going to setup a test app to test this feature out and report back. Please stand by.

**Comment by Papashkin** [comment]
@gpanshu  yes, we are using **AWSMobileClient** cos it's possible to invalidate tokens after signOut to keep the possibility of use another account in the same social provider. If I'm not mistaken, Amplify doesn't allow it yet.

**Comment by Papashkin** [comment]
Any update?

**Comment by Papashkin** [comment]
Any news?

**Comment by Papashkin** [comment]
@gpanshu do you need more information about environment?
For example `AndroidManifest`.

**Comment by gpanshu** [comment]
Hello @Papashkin I just finished setting up my environment and giving this use case a try following the exact steps from the Amplify documentation. 
Here are my observations: 
- I was able to setup Social sign in with Facebook successfully and was able to login through hostedUI
- I was able to logout (onResult: SIGNED_OUT)
- I was able to sign in again without hard signing in again since the browser session was still active ( I have verified this behaviour on iOS as well)

I am closing this issue to work as expected. Please reopen or create a new one if you are still facing difficulties.

**Comment by Papashkin** [comment]
@gpanshu thanks for the participation in that issue.
Seems that my set-up was incorrect. Could you please provide me a link to a documentation when I can set the app in the same way as you did?

**Comment by Papashkin** [comment]
@gpanshu Could you please explain one thing?
How do I have to set the intents in hosted UI activity?
Right now it looks like this:
```
<activity
        android:name="com.amplifyframework.auth.cognito.activities.HostedUIRedirectActivity"
        android:exported="true">
        <intent-filter android:label="Myapp">
            <action android:name="android.intent.action.VIEW" />

            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />

            <data
                android:host="callback"
                android:scheme="myapp" />
            </intent-filter>
        <intent-filter android:label="Myapp">
            <action android:name="android.intent.action.VIEW" />

            <category android:name="android.intent.category.DEFAULT" />
            <category android:name="android.intent.category.BROWSABLE" />

            <data
                android:host="signout"
                android:scheme="myapp" />
        </intent-filter>
</activity>
```
But it seems signout callback doesn't work properly: I've got the timeout issue.
I also tried to add a redirect to an Activity when the user signs in or signs out (I mean intent-filter), but it works only if I have both ways in the `AndroidManifest` (which is not good, user have to select an application in chooser).

**Comment by Papashkin** [comment]
@gpanshu Also I found the reason why it works in odd way. Seems that if you have a single instance of an activity, where you handle the Cognito's callbaks:
```
<activity
    android:name=".ui.auth.AuthenticationActivity"
    android:launchMode="singleInstance"
    ...
```
that will mess with a timeout issue.

**Comment by gpanshu** [comment]
Here is the [link](https://docs.amplify.aws/lib/auth/social_signin_web_ui/q/platform/android/) to the documentation using the AWS Mobile Client. Although I would recommend giving Amplify Android plugin a try instead. 

Please note we generally do not respond on closed issues. If your query is resolved leave this closed. If you are facing a different issue please feel free to open a new ticket. If you are facing the same issue and have tried setting up a brand new project with following the steps exactly as they are on the guide you can re-open this issue with perhaps a link to that sample project.
