### ISSUE TITLE
Disable multipart upload requests

### ISSUE THREAD

**Issue by arunj-kp** [aws-amplify/aws-sdk-android#3015]
**Which AWS Services is the feature request for?**
S3 uploads

**Is your feature request related to a problem? Please describe.**
Currently, aws-sdk-android does not provide a feature to disable multipart requests. SDK should provide a configuration attribute to disable this feature. For example, a smaller file (say, less than 20MB) works faster with a regular file upload (without breaking into 5MB chunks) if the mobile app user is on a reliable network with a decent upload speed. 
Now, SDK has some hardcoded logic which decides multipart upload if the file size > 5MB. So, please make this a customizable feature so that client app can enable/disable multipart-uploads.

**Describe the solution you'd like**
TransferUtilityOptions should have an attribute for setting the  value for MINIMUM_UPLOAD_PART_SIZE. Now, it is a package private static field.

**Describe alternatives you've considered**
No alternatives possible with the current design.

**Additional context**
AWS S3 team asked us to use Multipart upload only if the file size is >20MB if the user is on a reliable network. It is for quick file upload as multipart has additional API requests for initiation, ending, etc. But, this is not possible with this hardcoded logic in the SDK. So, this is a blocker for us to disable multipart for files less than 20MB if the user on a reliable wifi network.

**Comment by tylerjroach** [comment]
@arunj-kp The feature is now live in 2.55.0.
