### ISSUE TITLE
Customize UPLOAD_PART_SIZE

### ISSUE THREAD

**Issue by arunj-kp** [aws-amplify/aws-sdk-android#3016]
**Which AWS Services is the feature request for?**
S3 upload

**Is your feature request related to a problem? Please describe.**
aws-sdk-android always uses 5MB part size for multipart uploads, and the client app does not have any way to configure this to a higher value. AWS S3 team asked us to try larger size part size to improve performance. For example, if the file size is 500MB, try a 20MB part size instead of the 5MB part size. But, the SDK does not expose any methods for the client app to do so. 

**Describe the solution you'd like**
SDK can expose a method in TransferUtilityOptions for setting the part size.

**Describe alternatives you've considered**
No alternatives possible with the current design of SDK.

**Additional context**
Tweaking part size based on mobile network upload speed and reliability will improve upload performance. It is not possible without SDK exposing this feature. So, this is a blocker for us to try an experiment for improving upload performance.

**Comment by tylerjroach** [comment]
@arunj-kp The feature is now live in 2.55.0.
