### ISSUE TITLE
Amazon S3 - The authorization header is malformed; the region 'vpce' is wrong; expecting 'eu-central-1'

### ISSUE THREAD

**Issue by heisenbergye** [aws-amplify/aws-sdk-android#3018]
**Describe the bug**
The authorization header is malformed; the region 'vpce' is wrong; expecting 'eu-central-1'

**To Reproduce**
A code sample or steps:
![image](https://user-images.githubusercontent.com/25834939/191966407-830eed26-7f61-41ff-ba0d-91a4abc36cbd.png)

when creating a new progress listener for transfer, it got an ERROR as the following:
```
Received error response: com.amazonaws.services.s3.model.AmazonS3Exception: The authorization header is malformed; the region 'vpce' is wrong; expecting 'eu-central-1' (Service: null; Status Code: 400; Error Code: AuthorizationHeaderMalformed; Request ID: DN55*******2CRZ4), S3 Extended Request ID: RN8eBGO2ZCJGGy*******KtqO/1DwofYb6Bim2giwzG*******EiHZBliYfeNcU9*******OPblJJFQ=
```

maybe it is a bug similar as :
https://hadoop.apache.org/docs/stable/hadoop-aws/tools/hadoop-aws/troubleshooting_s3a.html
![image](https://user-images.githubusercontent.com/25834939/191967319-de20261a-85cc-485a-ba7a-3ed58150f8e5.png)

**Which AWS service(s) are affected?**
when upload picture by S3 interface endpoint in VPC, the transfer cannot be created.

**Expected behavior**
Please help to fix it that parse region code and produce url correctly. 

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.35.0, 2.53.0

**Comment by eeatonaws** [comment]
Thank you for reporting this issue. The AmazonS3Client is indeed parsing endpoints in VPC such that the region is "vpce". I am working on a fix for this issue.

**Comment by eeatonaws** [comment]
A fix for the issue has been released in AWS SDK for Android 2.54.0.

**Comment by EddyChina** [comment]
any update on AWS SDK for Java? I got same exception with flink checkpoint.

**Comment by eeatonaws** [comment]
Please create an issue in the [AWS SDK for Java GitHub repository](https://github.com/aws/aws-sdk-java/issues/new/choose).
