### ISSUE TITLE
ResourceNotFoundException: User pool client XXXX does not exist.

### ISSUE THREAD

**Issue by rajumb502** [aws-amplify/aws-sdk-android#3048]
Hello 
I am currently using "`com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.55.0`" in my Android Java project. I keep getting the ResourceNotFoundException at the below line in my code:
`InitiateAuthResult initiateAuthResult = new AmazonCognitoIdentityProviderClient(credentialsProvider).initiateAuth(authRequest);`
Response Details: 
`host:cognito-idp.us-east-1.amazonaws.com`
`x-amz-date:20221023T065045Z`
`x-amz-security-token:IQoJb3JpZ....`
`x-amz-target:AWSCognitoIdentityProviderService.InitiateAuth`
`Request ID: 70964c12-c9ad-4f44-838c-d2cfcec6b295`
 
As per documents I read on the web, I tried doing a curl command (I am using region AP-SOUTH-1 for all my services): 
`curl -d @reqbody.json  -H 'X-Amz-Target: AWSCognitoIdentityProviderService.InitiateAuth' -H 'Content-Type: application/x-amz-json-1.1' -v https://cognito-idp.ap-south-1.amazonaws.com/` 
It came back with the correct response:
`< date: Sun, 23 Oct 2022 06:29:54 GMT`
`< x-amzn-requestid: 42f8889f-cea6-4be5-b22f-4de181530a96`

However, when I changed the url to point to us-east-1:
`curl -d @reqbody.json  -H 'X-Amz-Target: AWSCognitoIdentityProviderService.InitiateAuth' -H 'Content-Type: application/x-amz-json-1.1' -v https://cognito-idp.us-east-1.amazonaws.com/`

I got the very same error that I was seeing in my java code:
`< date: Sun, 23 Oct 2022 06:16:18 GMT`
`< x-amzn-requestid: 4ac51252-ca82-475c-89b7-32a3dddb2560`
`< x-amzn-errortype: ResourceNotFoundException:`
`< x-amzn-errormessage: User pool client XXXXXX does not exist.`

I checked the `AmazonCognitoIdentityProviderClient.java` code and found this initialization:
https://github.com/aws-amplify/aws-sdk-android/blob/1731b43107d4974b4be6769dfcd8795020b4a9c9/aws-android-sdk-cognitoidentityprovider/src/main/java/com/amazonaws/services/cognitoidentityprovider/AmazonCognitoIdentityProviderClient.java#L392 

Is this changed anywhere else to respect the region we are in? If this is not the issue, can you point to where I could be going wrong in my Java code?

**Comment by rajumb502** [comment]
I worked around by doing this:
```            
AmazonCognitoIdentityProviderClient client = new AmazonCognitoIdentityProviderClient(credentialsProvider);
client.setEndpoint("cognito-idp.ap-south-1.amazonaws.com"); //by default, the region is us-east-1
InitiateAuthResult initiateAuthResult = client.initiateAuth(authRequest);
```
Now i get the correct response but not sure if we are supposed to use it this way.

**Comment by div5yesh** [comment]
@rajumb502, above usage is correct. Ideally you would use `AWSMobileClient` which reads the region from json configuration file. But if your use case requires you to instantiate `AmazonCognitoIdentityProviderClient`, then the above snippet should work.

**Comment by rajumb502** [comment]
@div5yesh , thank you for your comment. Since we are setting the region while creating credentialsProvider, I would have assumed that it automatically picks up the region from that. Is there a reason why the Region in CredentialsProvider is not used in this case?
`
        credentialsProvider = new CognitoCachingCredentialsProvider(
                appContext,
                IDENTITY_POOL_ID,
                REGION
        );
`

**Comment by div5yesh** [comment]
`AmazonCognitoIdentityProviderClient` and `AmazonCognitoIdentityClient` are low level service clients and they do not read config from the json file. `CognitoCachingCredentialsProvider` also do not read config file and it is just a wrapper around `AmazonCognitoIdentityClient` to support storing and retrieving credentials data from shared preferences. 

If you want both of the service clients to be initialized from json config files, please use high level `AWSMobileClient`.

**Comment by div5yesh** [comment]
Thanks for clarifying your question. 

`CredentialsProvider` is tied with Identity Pool while `AmazonCognitoIdentityProviderClient` is tied with User Pool. [CredentialsProvider](https://github.com/aws-amplify/aws-sdk-android/blob/main/aws-android-sdk-core/src/main/java/com/amazonaws/auth/AWSCredentialsProvider.java) is responsible for vending AWS Credentials and has 2 public APIs getCredentials and refresh. It can be used with other Service clients and supports a broad use case. So AmazonCognitoIdentityProviderClient is just another service client that uses CredentialsProvider to sign outgoing requests.

So using credentials provider's region to initialize service clients creates an unnecessary coupling.
