### ISSUE TITLE
What parts, if any, are licensed under Eclipse Public License - v 1.0?

### ISSUE THREAD

**Issue by matthewlmcclure** [aws-amplify/aws-sdk-android#3056]
The Eclipse Public License - v 1.0 (EPL 1.0) is [included in LICENSE.APACHE.txt][1], but I didn't find specified what parts of the code are licensed under the EPL 1.0.

Separately, [the NOTICE.txt file states][2] that the Eclipse Paho Java Client is licensed under the Eclipse Distribution License - v 1.0 (EDL 1.0).

The [LICENSE.txt file][3] doesn't mention any of the Eclipse Paho Java Client, the EPL, or the EDL.

What, if anything, is licensed under EPL 1.0? Should the above reference the EDL 1.0 instead of the EPL 1.0?

[1]: https://github.com/aws-amplify/aws-sdk-android/blob/8de48797ae2e5c157169a94746c768da7de61056/LICENSE.APACHE.txt#L213
[2]: https://github.com/aws-amplify/aws-sdk-android/blob/8de48797ae2e5c157169a94746c768da7de61056/NOTICE.txt#L47
[3]: https://github.com/aws-amplify/aws-sdk-android/blob/release_v2.52.1/LICENSE.txt

**Comment by lawmicha** [comment]
The license file https://github.com/aws-amplify/aws-sdk-android/blob/release_v2.52.1/LICENSE.txt is the most recent and mentions the license is under Apache 2.0 License. This is the correct reflection for most of the modules, except for the one mentioned in there about Amazon Cognito Identity Provider.

I believe https://github.com/aws-amplify/aws-sdk-android/blob/8de48797ae2e5c157169a94746c768da7de61056/LICENSE.APACHE.txt#L213 does not need EPL outline in there and can be removed. (PR here https://github.com/aws-amplify/aws-sdk-android/pull/3611)

https://github.com/aws-amplify/aws-sdk-android/blob/8de48797ae2e5c157169a94746c768da7de61056/NOTICE.txt#L47 is a reference to Third Party Component's license https://github.com/aws-amplify/aws-sdk-android/blob/8de48797ae2e5c157169a94746c768da7de61056/NOTICE.txt#L22-L24  and was added 9 years ago in this commit https://github.com/aws-amplify/aws-sdk-android/commit/ce68ab56fae0e42b7ec82a43e65a046a8b6f4bde I suspect that this was a dependency's license, and is more of a FYI than the license we are taking on. 

Let me know if that helps answers your questions.

**Comment by matthewlmcclure** [comment]
@lawmicha That helps clarify. Thank you.
