### ISSUE TITLE
KeyNotFoundException while using IdentityManager

### ISSUE THREAD

**Issue by rajumb502** [aws-amplify/aws-sdk-android#3064]
**State your question**
I keep getting a `KeyNotFoundException` while trying to initialize `CognitoCachingCredentialsProvider` in my Android app.

**Which AWS Services are you utilizing?**
Cognito

**Provide code snippets (if applicable)**
```
        IdentityManager idm = new IdentityManager(context, new AWSConfiguration(context));
        IdentityManager.setDefaultIdentityManager(idm);
        credentialsProvider = IdentityManager.getDefaultIdentityManager().getUnderlyingProvider();
```
(OR)
The same issue happens if I use the below code also:
```
        credentialsProvider = new CognitoCachingCredentialsProvider(
                appContext,
                IDENTITY_POOL_ID,
                REGION // Region
```
**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]
```
    awsSDKVersion = '2.55.0'
    implementation "com.amazonaws:aws-android-sdk-core:${awsSDKVersion}"
    implementation "com.amazonaws:aws-android-sdk-auth-core:${awsSDKVersion}"
    implementation "com.amazonaws:aws-android-sdk-cognitoidentityprovider:${awsSDKVersion}"
```

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]: `Emulator`
 - Android Version: [e.g. Nougat 7.1.2]: `API Level 30`
 - Specific to simulators: NA

I keep getting the below errors when I restart my app (refer to lines prefixed with `E`) during `IdentityManager idm = new IdentityManager(context, new AWSConfiguration(context))`:
```
I  Creating the AWSKeyValueStore with key for sharedPreferencesForData = com.amazonaws.android.auth
E  com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
I  Deleting the encryption key identified by the keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
E  Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = ap-south-1:xxxxx.identityId
D  Loading credentials from SharedPreferences
E  com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
I  Deleting the encryption key identified by the keyAlias: com.amazonaws.android.auth.aesKeyStoreAlias
E  Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = ap-south-1:xxxxx.expirationDate
```

I did a debug trace and found that in `AWSKeyValueStore.java` (package: `com.amazonaws.internal.keyvaluestore`) there is no attempt made to store the keys so in effect, even if `isPersistenceEnabled` is `true` (which it is by default), the keys are not stored and hence we get above exception.

Can you please let me know if my understanding is correct and if yes, how to go about saving the keys so I do not get this errors any more. I have already searched much on this issue but am unable to find any documentation regarding it.

**Comment by div5yesh** [comment]
`CognitoCachingCredentialsProvider` tries to migrate values stored in old preferences format to new encrypted format. These errors suggests that the keys supported by older versions of the SDK does not exists. IMO, these errors are harmless. Refer `onMigrateFromNoEncryption` method for more info.

**Comment by rajumb502** [comment]
Hello @div5yesh , this is a brand new application in development. There are no keys to be migrated. After I make code changes, whenever I start the app in the emulator/test device, i get the above errors as it is unable to read the values stored during the previous test run.

**Comment by div5yesh** [comment]
I apologize if it wasn't clear earlier. The migration of preferences data is to support apps that are already using unencrypted or memory-only preferences with an older version of SDK. So when those apps migrate to newer versions of SDK or enable persistence, we migrate the preferences data to encrypted shared preferences. Moreover, whether persistence is enabled or not, data is always stored in memory-only cache.

Also, we expect persistence to be false as the older versions did not support it, so we always try to migrate the data. And since the unencrypted or memory-only preferences is not supported anymore in the current version of SDK, implementation to store the keys has been removed.

The logs you are seeing are for cleanup of preferences data (encrypted and memory-only) which happens as part of migration as a precautionary measure, when decryption is not possible due to failure to retrieve the key.

**Comment by div5yesh** [comment]
@jox Yes, I agree since these errors are harmless we can make them `info` or `debug` logs instead of errors.

**Comment by div5yesh** [comment]
Log level changed to warning: https://github.com/aws-amplify/aws-sdk-android/pull/3134
