### ISSUE TITLE
CognitoUserSession is not valid because idToken is null.

### ISSUE THREAD

**Issue by jbsolutions2008** [aws-amplify/aws-sdk-android#3101]
Hi all, we are trying to configure the Amplify Authentication on Android 12, but when we try to sign in the result callback is called with a signInState equal to SignInState.DONE, but when we try to get the token (both sync or async), 

an Exception raises:  "CognitoUserSession is not valid because idToken is null. "

**To Reproduce**
A code sample or steps:

```
 #1 After  SignInState.DONE : 
 -------------------------
  fun finishSignIn() {
        launch(Dispatchers.IO) {
            AWSMobileClient.getInstance().getTokens(object : Callback<Tokens> {
                override fun onResult(result: Tokens?) {
                    result?.let {
                        Logger.d("token ${it.accessToken}")
                        val token = AWSMobileClient.getInstance().tokens.accessToken.tokenString
                        Logger.d("token $token")
                    }
                }
                override fun onError(e: java.lang.Exception?) {
                    e?.let {
                      Logger.d("token $e.toString()")
                    }
                }
            })
        }
    }
 
#2 Retrive token null in the result   
-------------------------------------
D/AWSMobileClient: _federatedSignIn: Putting provider and token in store
W/AWSMobileClient: Failed to federate tokens during sign-in
java.lang.Exception: Federation is not enabled, please check if you have CognitoIdentity configured.
at com.amazonaws.mobile.client.AWSMobileClient$11.run(AWSMobileClient.java:1901)
at com.amazonaws.mobile.client.internal.InternalCallback.await(InternalCallback.java:115)
at com.amazonaws.mobile.client.AWSMobileClient.federatedSignInWithoutAssigningState(AWSMobileClient.java:1854)
at com.amazonaws.mobile.client.AWSMobileClient$6$1.onSuccess(AWSMobileClient.java:1288)
at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$6.onSuccess(CognitoUser.java:1102)
 at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser$29.run(CognitoUser.java:3155)  at com.amazonaws.mobileconnectors.cognitoidentityprovider.continuations.ChallengeContinuation.continueTask(ChallengeContinuation.java:202)
at com.amazonaws.mobile.client.AWSMobileClient$7.run(AWSMobileClient.java:1486)
at com.amazonaws.mobile.client.internal.InternalCallback$1.run(InternalCallback.java:101)
 at java.lang.Thread.run(Thread.java:1012)
 W/CognitoUserSession: CognitoUserSession is not valid because idToken is null.
 W/AWSMobileClient: signalTokensNotAvailable
 W/CognitoUserSession: CognitoUserSession is not valid because idToken is null.
 W/AWSMobileClient: signalTokensNotAvailable
 
```

**Expected behavior**
Android 12 OS Version only.

**Screenshots**
![#issue](https://user-images.githubusercontent.com/7472158/204991615-9cf3844a-c3cf-410c-af5f-2be7554567f0.PNG)

![MotoG-Android12](https://user-images.githubusercontent.com/7472158/205001517-05c5ff10-eb1c-42d7-8dae-967a69a2a50c.png)

**Environment Information :**
 - AWS Android SDK Version: 
    implementation 'com.amplifyframework:core:1.37.7'
    implementation 'com.amplifyframework:aws-auth-cognito:1.37.7'
    
 - Device:  Moto G 
 - Android Version:  Android 12 
 - Specific to simulators: No

**Additional context**
In other Android os Versions. It working fine.

**Comment by mattcreaser** [comment]
Hi @jbsolutions2008, thanks for your report. We are looking into this.

**Comment by tylerjroach** [comment]
@jbsolutions2008 
Does your `awsconfiguration.json` file have a block like this?

```
{ 
  "CredentialsProvider": {
    "CognitoIdentity": {
      "Default": {
        "PoolId": "POOL-ID-HERE",
        "Region": "REGION-ID-HERE"
      }
    }
  }
}
```

**Comment by jbsolutions2008** [comment]
@tylerjroach Thank you for the update.No Our awsconfiguration.json is different from yours. We have shared our awsconfiguration.json file. Please review.

awsconfiguration.json
=============

{
  "UserAgent": "aws-amplify-cli/2.0",
  "Version": "1.0",
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {
            
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "POOL-ID-HERE",
            "AppClientId": "AppClient-ID-HERE",
            "Region": "REGION-ID-HERE"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "CUSTOM_AUTH"
          }
        }
      }
    }
  }
}

**Comment by dengdan154** [comment]
hi @jbsolutions2008, I am currently looking into your issue. Could you verify that you sent `awsconfiguration.json`? The file you sent seems to be  `amplifyconfiguration.json`. Please let me know if my assumption is incorrect.

**Comment by Felixroldan** [comment]
Hello. I'm having this issue when try to verify is the user is signed in. I'm working in flutter.

**Comment by dengdan154** [comment]
Hi @Felixroldan, if you are still facing this issue, please paste your code here as well as the `awsconfiguration.json` and any reproduction steps and we can continue looking into this issue.

**Comment by takieddine12** [comment]
I guess upon registration is successful , you need to provide a CognitoUserSession so that we can get idToken , RefreshToken and so on ..
