### ISSUE TITLE
Android SDK s3.doesObjectExist throwing huge number of false positives especially in Android 12 & 13

### ISSUE THREAD

**Issue by ftshareesh** [aws-amplify/aws-sdk-android#3163]
Ours is a Old project running for quite some time now(5 yrs) without issues. We were using the below Android SDK 
implementation 'com.amazonaws:aws-android-sdk-s3:2.10.0' and all was working fine till around new year, and then we started getting huge number of false positives for the  s3.doesObjectExist(bucketName, objectName) . The majority of the issues were reported on Android 12 & 13. We do understand we should have upgraded long ago, However we would like to know what has caused this sudden outburst of the false positives.

The below code was done to double check that the uploaded object has reached S3 after we got COMPLETED status from the 
TransferListener

`
class UploadListener implements TransferListener {

        @Override
        public void onError(int id, Exception e) {
          //handle error
        }

        @Override
        public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
          // handle progress
        }

        @SuppressWarnings("StatementWithEmptyBody")
        @Override
        public void onStateChanged(int id, TransferState newState) {
            if (newState == TransferState.COMPLETED) {
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                     
                         AmazonS3 s3 = ApplicationClass.getAmazonS3();
                     
                       
                        if (s3.doesObjectExist(BuildConfig.BUCKET_NAME, subFolder + "/" + name)) {
                             // The image uploaded really exists in s3 folder
                        } else {
                           // do a retry
                        }

                    }
                }).start();

            } else if (newState == TransferState.FAILED) {
                  // do a retry
            } else if (newState == TransferState.PAUSED || newState == TransferState.UNKNOWN) {
                  // handle state
            } else if (newState == TransferState.IN_PROGRESS) {// for future use
            } else if (newState == TransferState.CANCELED) {
               // handle state
            }
        }
    }`

**Which AWS service(s) are affected?**
   AWS S3 
**Expected behavior**
  The s3.doesObjectExist() function should return correct result instead of false positives.

**Environment Information (please complete the following information):**
 -  com.amazonaws:aws-android-sdk-s3:2.10.0
 -  Samsung Galaxy s22 ultra ,  Samsung Galaxy note 8
 - Android Version: 12 & 13 (the issue was there in Android 9 and all but very less)
 - Specific to simulators: No

**Additional context**
 Our app was recently targeted to  Android 12 as per Google play restrictions.

**Comment by sdhuka** [comment]
@ftshareesh Could you please try to upgrade to the latest version([v2.62.0](https://mvnrepository.com/artifact/com.amazonaws/aws-android-sdk-s3/2.62.0)) and then try repro it again. v2.10.0 is over 4 years old and we have made significant improvements since then. 

If you can still repro after upgrading to v2.62.0, then please share the detailed Logcat logs for us to investigate further.

**Comment by ftshareesh** [comment]
I can certainly do that and shall update here if the issues happen again.

**Comment by sdhuka** [comment]
@ftshareesh Closing this issue for now, please open a new bug report if the issue persists after upgrading to the latest sdk version.
