### ISSUE TITLE
us-gov-east-1 region missing from RegionUtils.java

### ISSUE THREAD

**Issue by dtufekcic** [aws-amplify/aws-sdk-android#3178]
**Describe the bug**
I am trying to use the us-gov-east-1 region with S3 in Android. I can use the Regions.US_GOV_EAST_1 enum, but I cannot retrieve any Region objects based on this enum.

**To Reproduce**
A code sample or steps:
```
Region r = Region.getRegion(US_GOV_EAST_1); // r is null
```

**Which AWS service(s) are affected?**
S3

**Expected behavior**
I expect to get a Region object for US_GOV_EAST_1

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.62.2
 - Device: Pixel 6 Pro
 - Android Version: 13
 - Specific to simulators: No

**Comment by eeatonaws** [comment]
Thank you for reporting this issue. We are working on a fix.

**Comment by eeatonaws** [comment]
A fix has been released in AWS SDK for Android version 2.63.0.
