### ISSUE TITLE
AwsMobileClient is not initialising automatically when i move to amplify 2.7.1

### ISSUE THREAD

**Issue by ZubairAkber** [aws-amplify/aws-sdk-android#3247]
**Describe the bug**
I was using 1.30.0 version of amplify and every thing works fine, when i move to 2.7.1 and updated the code amplify works fine i just get the data and ready state is triggered but when it tries to connect to MQTT i got the following error

MQTT broker: a3jmi0po6ccx5n-ats.iot.ap-southeast-1.amazonaws.com:443
MQTT I Connection Lost com.amazonaws.AmazonClientException: Cognito Identity not configured
System.err W com.amazonaws.AmazonClientException: Cognito Identity not configured
System.err W at com.amazonaws.mobile.client.AWSMobileClient.getCredentials(AWSMobileClient.java:391)
System.err W at com.amazonaws.mobileconnectors.iot.AWSIotMqttManager$1.run(AWSIotMqttManager.java:993)
System.err W at java.lang.Thread.run(Thread.java:1012)

What i have observed is AwsMobileClient is not initialised at the start of app when i use 2.7.1 and in case of 1.30.0 it is initialised properly at the start with the logs that its initialise is called.

I have create a bug on amplify repo as well
https://github.com/aws-amplify/amplify-android/issues/2400

**To Reproduce**
Simply update to 2.7.1 version of amplify from 1.30.0

**Screenshots**
<img width="967" alt="image" src="https://user-images.githubusercontent.com/15378288/233000677-9717c0eb-b465-43c9-b73d-b67f3e7f2a76.png">

**Comment by dengdan154** [comment]
Closing this ticket as responded on the duplicate on amplify repo
