### ISSUE TITLE
`UserNotConfirmedException` regardless of correct password being submitted

### ISSUE THREAD

**Issue by poliver** [aws-amplify/aws-sdk-android#3271]
**State your question**
If a user signs up, but fails to confirm the sign up, all subsequent attempts to sign in yield a `UserNotConfirmedException`, regardless of whether the correct password was entered or not. This appears to go against the [current documentation](https://docs.amplify.aws/lib/auth/signin_next_steps/q/platform/android/), which suggests that I should be seeing a success response with `nextStep.signInStep == AuthSignInStep.CONFIRM_SIGN_UP`. The behavior implied by the docs is preferable because it allows me to distinguish between a user that has authenticated using the correct password and one that hasn't. [Previous queries](https://github.com/aws-amplify/aws-sdk-android/issues/1688) about this have been closed with no real explanation. Is this something that is configurable, or is the documentation incorrect?

<img width="1052" alt="Screenshot 2023-05-01 at 4 34 19 PM" src="https://user-images.githubusercontent.com/3497406/235528727-17f60942-4962-4ea5-b662-7f52e0ec8e16.png">

**Which AWS Services are you utilizing?**
Cognito

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: `2.8.2`

**Device Information (please complete the following information):**
 - Device: Pixel 4 XL
If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by gpanshu** [comment]
Hello @poliver . The latest AWS SDK version is 2.67.0. I believe you are looking for Amplify-Android. If yes please close and recreate it there so that we can triage it.

**Comment by poliver** [comment]
@gpanshu Apologies for any confusion. I simply posted to the same repo as the issue I linked in my original post (which exhibits the same exception). A bit confusing, since both repos are under the Amplify Github org.

**Comment by poliver** [comment]
@gpanshu I opened a ticket in the other Android repo: https://github.com/aws-amplify/amplify-android/issues/2427

**Comment by gpanshu** [comment]
Thank you. I will respond there.
