### ISSUE TITLE
cognitoauth: Erroneous "user cancelled" AuthNavigationException Thrown by AuthClient

### ISSUE THREAD

**Issue by kyarosh** [aws-amplify/aws-sdk-android#328]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
  * Cognito

* In what version of SDK are you facing the problem?
  * 2.4.7

* Is the issue limited to Simulators / Actual Devices?
  * Occurs on both

* Can your problem be resolved if you bump to a higher version of SDK?
  * No; using highest

* Is this problem related to specific Android/OS version?
  * No

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
  1. Clone and build the [AmazonCognitoAuthDemo](https://github.com/awslabs/aws-sdk-android-samples/tree/master/AmazonCognitoAuthDemo) project from [aws-sdk-android-samples](https://github.com/awslabs/aws-sdk-android-samples)
  2. Update the values in the project's strings.xml
  3. In com.amazonaws.cognito.android.samples.authdemo.MainActivity, add logic to callback.onFailure() that logs the message and stack trace of the Exception that is passed to the method in logcat
  4. Build, run, and monitor logcat
  5. After signing in, when the custom Chrome tab closes, the error is thrown

* Please include a stacktrace if applicable.
```
com.amazonaws.mobileconnectors.cognitoauth.exceptions.AuthNavigationException: user cancelled
   at com.amazonaws.mobileconnectors.cognitoauth.AuthClient$4.onNavigationEvent(AuthClient.java:559)
   at android.support.customtabs.CustomTabsClient$2.onNavigationEvent(CustomTabsClient.java:189)
   at android.support.customtabs.ICustomTabsCallback$Stub.onTransact(ICustomTabsCallback.java:61)
   at android.os.Binder.execTransact(Binder.java:565)
```

* General description of the issue:
  * As a part of the AuthClient class, the SDK [implements the onNavigationEvent()](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/AuthClient.java#L551) to monitor the Chrome custom tab that is used to facilitate authentication. If the event received equals ClientConstants.CHROME_NAVIGATION_CANCELLED ([which is set to 6](https://github.com/aws/aws-sdk-android/blob/master/aws-android-sdk-cognitoauth/src/main/java/com/amazonaws/mobileconnectors/cognitoauth/util/ClientConstants.java#L31)), an instance of AuthNavigationException with the message "user cancelled" is passed back to the onFailure() method of the callback set for the AuthClient class.
  * However, according to [the documentation on Android's CustomTabsCallback](https://developer.android.com/reference/android/support/customtabs/CustomTabsCallback.html#TAB_HIDDEN), an event with the value of 6 is thrown on the TAB_HIDDEN event.
  * As a result, the "user cancelled" exception is not only thrown when a user closes/cancels the Chrome custom tab, but also under many other circumstances when the tab becomes hidden, including when the tab becomes hidden after successful authentication.

**Comment by mreddyg** [comment]
Thank you for reporting this bug, we are investigating it.

**Comment by erodewald** [comment]
Has anybody found a possible workaround?

**Comment by emax77** [comment]
Hello, I still have this issue with the last version of the AWS SDK. Someone found the way to solve this ?

**Comment by drxeno02** [comment]
Hello, every time the user gets redirected back to the app they will receive the error, "user canceled". Ignore this and consider it log verbosity information. This will not prevent other errors from being thrown or the success of authentication, it really only signifies that the user was redirected back into the app via the redirect link (your uri).

**Comment by Plinzen** [comment]
Hi,
is there any plan to fix this issue? It's quite difficult to distinguish between a real error or just a "log information".

**Comment by minbi** [comment]
Hi,

Please see if SDK release 2.12.5 fixes this issue for you.

You may see all changes in the [changelog](https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md#release-2125)

**Comment by tvanmanh** [comment]
Hi @minbi 
although i updated SDK to 2.12.5 or 2.12.7, error still does occur. 

Step to reproduce:
1. I signed in app and then i Sign out with AWSMobleClient.getInstance.SignOut()
2. I press sign in  google/facebook button (signed in google/facebook account). it goes to facebook/google page and call back with "user canceled" error. but when i press the button again the result of call back is "signed in succeeded". 

note: it means that if I sign out and want to sign in again. I have to press sign in button twice to sign in successfully. 
firsth: call back "user canceled"
secondth: "signed in" 


I'm waiting for your feedback.

**Comment by minbi** [comment]
Hi,

Please see if SDK release 2.13.2 fixes this issue for you. We have added the following bug fixes:

>Fixed erroneous user cancelled error when redirecting back to app.

You may see all changes in the [changelog](https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md#release-2132)

**Comment by shubhamssinghal** [comment]
I am still getting the same issue with latest AWS SDK
along with that at the time of sing out its throwing below exception 
" Access Token does not have required scopes "
If anyone got the solution kindly please help me out 
Thank You

**Comment by narindermalik2** [comment]
Hi, I am also getting this exception due to which my success block doesn't execute. I am willing to ignore this error but how i will get the session object then?

**Comment by narindermalik2** [comment]
Solved. In my case, I was not passing the deeplink after the custom scheme in the redirect url. So essentially the the redirect url in the Auth Builder should look something like "appscheme://xyz1x.app.goo.gl/abcd1efGHi2jklmN3". The string after appscheme:// should be the deep link (without the https)

**Comment by boldijar** [comment]
I've found a fix, I've commented here https://github.com/aws-amplify/aws-sdk-android/issues/871#issuecomment-608355327
