### ISSUE TITLE
screen blank

### ISSUE THREAD

**Issue by sanjivjha** [aws-amplify/aws-sdk-android#3333]
both on emulator and device screen is only showing kinesis logo . Rest of screen is white

**Comment by eeatonaws** [comment]
@sanjivjha are you experiencing this issue with the [kinesis video demo app](https://github.com/awslabs/aws-sdk-android-samples/tree/main/AmazonKinesisVideoDemoApp)? If so, please check you have followed all setup steps in the README. Please also provide the logs for the app (with any sensitive information removed) to help us investigate the issue.
