### ISSUE TITLE
ParserConfigurationException when using XpathUtils

### ISSUE THREAD

**Issue by noropoly** [aws-amplify/aws-sdk-android#3336]
**Describe the bug**
ParserConfigurationException when using XpathUtils

**To Reproduce**

1. Shift the device time by one hour.
2. Call AmazonS3Client#getObject().
3. When parsing the response body, XpathUtils is accessed and an exception is raised.

**Which AWS service(s) are affected?**
Amazon S3

**Expected behavior**
Correctly parse the response body and correctly handle "RequestTimeTooSkewed" error.

**Screenshots**

XpathUtils.java
```java:XpathUtils.java
    private static DocumentBuilderFactory getDocumentBuilderFactory() {
        try {
            DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();
            dbf.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
            dbf.setXIncludeAware(false); // Default false for java 8. Disable XML Inclusions leading to SSRF - https://portswigger.net/web-security/xxe/lab-xinclude-attack
            dbf.setExpandEntityReferences(false);
            return dbf;
        }
        catch (ParserConfigurationException exception){
            return null;
        }
    }
```

![PerserConfigurationException](https://github.com/aws-amplify/aws-sdk-android/assets/137459759/13d99c7e-9f68-4ffd-91e2-60b0a11bedc4)

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.71.0 (v2.59.1 or higher)
 - Device: Simulator
 - Android Version:  12
 - Specific to simulators: No

**Additional context**
[This modification](https://github.com/aws-amplify/aws-sdk-android/pull/3100) seems to have affected.

**Comment by tylerjroach** [comment]
@noropoly Thank you for the report. We have done further testing and confirmed a fix to revert the change.
https://github.com/aws-amplify/aws-sdk-android/pull/3353
