### ISSUE TITLE
Is it possible to upload with InputStream to S3 object instead of write all contents to a file to improve performance?

### ISSUE THREAD

**Issue by FrankieCheng** [aws-amplify/aws-sdk-android#3355]
**State your question**
We used the following code to write inputstream to S3, and is it possible to upload with InputStream to S3 object instead of write all contents to a file to improve performance?
/**
* Starts uploading the inputStream to the given bucket, using the given key.
*
* @param key           The key in the specified bucket by which to store the new object.
* @param inputStream   The input stream to upload.
* @param options       An UploadOptions which hold all of the optional parameters
*                      i.e. bucket, metadata, cannedAcl and transferListener.
* @return A TransferObserver used to track upload progress and state
*/
public TransferObserver upload(String key, InputStream inputStream, UploadOptions options) throws IOException {
    File file = writeInputStreamToFile(inputStream);
    return upload(
            options.getBucket() != null ? options.getBucket() : getDefaultBucketOrThrow(),
            key,
            file,
            options.getMetadata() != null ? options.getMetadata() : new ObjectMetadata(),
            options.getCannedAcl(),
            options.getTransferListener()
    );
}

**Which AWS Services are you utilizing?**
S3

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: 2.71.0
public TransferObserver upload(String key, InputStream inputStream, UploadOptions options) throws IOException {
    File file = writeInputStreamToFile(inputStream);

**Device Information (please complete the following information):**
 - Device: ALL
 - Android Version: ALL
 - Specific to simulators:

**Comment by ankpshah** [comment]
Hello @FrankieCheng. Currently this feature does not exist.

Amplify Android v1 is now in Maintenance Mode until May 31st, 2024.
This means that we will continue to include updates to ensure compatibility with backend services and security. No new features will be introduced in v1. More Details: https://docs.amplify.aws/lib-v1/q/platform/android/

But you can always raise a feature request in Amplify Android v2. Here is the template for raising feature request: https://github.com/aws-amplify/amplify-android/blob/main/.github/ISSUE_TEMPLATE/2.feature_report.yaml . In the feature request, it will be helpful if could you provide more details about performance issue you are facing. It might help in better understanding the issue.
