### ISSUE TITLE
[Android] Getting App crash while login and logout in aws android sdk 2.52.1

### ISSUE THREAD

**Issue by VijaySonawane5** [aws-amplify/aws-sdk-android#3391]
Logs:-

 E  com.amazonaws.internal.keyvaluestore.KeyNotFoundException: Error occurred while accessing AndroidKeyStore to retrieve the key for keyAlias: CognitoIdentityProviderCache.aesKeyStoreAlias
 I  Deleting the encryption key identified by the keyAlias: CognitoIdentityProviderCache.aesKeyStoreAlias
E  Error in retrieving the decryption key used to decrypt the data from the persistent store. Returning null for the requested dataKey = CognitoIdentityProvider.xxxxxxxxxxxxxx.LastAuthUser
I  hsifw() - flags=0, caller=android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow:1858 android.view.inputmethod.InputMethodManager.hideSoftInputFromWindow:1827
 I  hsifw() ignore mServedView == null or mServedView.getWindowToken() != windowToken, mServedView  D   onsize change changed

**To Reproduce**
Login A user
Logout a user
Again login same user 

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.52.1
 - Device: SAMSUNG M12
 - Android Version: 12
 - Specific to simulators: No

**Comment by gpanshu** [comment]
Can you share the aws configuration file (with redacted values) and build.gradle dependencies block?
Additionally there is a similar [issue](https://github.com/aws-amplify/aws-sdk-android/issues/1392) where the solution was to simply restart the device as this was happening on device farm. Is that the case here as well or this is happening with your actual users?
Also are you able to reproduce this locally?

**Comment by VijaySonawane5** [comment]
@gpanshu Our use case is connect to different aws congnito pools so I have created config json by programatically as follow.

class MyClass : Application() {

    override fun onCreate() {
        super.onCreate()
        try {
            val jsonObject = JSONObject()
            val auth = JSONObject()
            jsonObject.put("auth", auth)
            val plugins = JSONObject()
            auth.put("plugins", plugins)

            val awsCognitoAuthPlugin = JSONObject()
            plugins.put("awsCognitoAuthPlugin", awsCognitoAuthPlugin)


            val Auth = JSONObject()
            awsCognitoAuthPlugin.put("Auth", Auth)

            val CognitoUserPool = JSONObject()
            awsCognitoAuthPlugin.put("CognitoUserPool", CognitoUserPool)

            val cogUserPoolDefault = JSONObject()
            CognitoUserPool.put("Default", cogUserPoolDefault)

            cogUserPoolDefault.put("PoolId", "XXXXXXXXX")
            cogUserPoolDefault.put("AppClientId", "XXXXXXXXXXXXXXXXXXXXX")
            cogUserPoolDefault.put("Region", "XXXXXXX")

            val default = JSONObject()
            Auth.put("Default", default)

            val OAuth = JSONObject()
            default.put("OAuth", OAuth)

            default.put("authenticationFlowType","ALLOW_USER_SRP_AUTH")
         
            OAuth.put("WebDomain", "XXXXXXXX")
            OAuth.put("AppClientId", "XXXXXXXXXXXXXXXXXX")
            OAuth.put("SignInRedirectURI", "XXXXXXXXXXXXXXXXX")
            OAuth.put("SignOutRedirectURI", "XXXXXXXXXXXXXXXXXXXXXXXXX")

            val jsonArray = JSONArray()

            jsonArray.put("aws.cognito.signin.user.admin")
            jsonArray.put("openid")
            jsonArray.put("email")
            jsonArray.put("phone")
            jsonArray.put("profile")

            OAuth.putOpt("Scopes",jsonArray)

            Amplify.addPlugin(AWSCognitoAuthPlugin())
            Amplify.configure(AmplifyConfiguration.fromJson(jsonObject), this)
            Log.i("MyAmplifyApp", "Initialized Amplify")
        } catch (error: AmplifyException) {
            Log.e("MyAmplifyApp", "Could not initialize Amplify", error)
        }

In Activity:-

  Amplify.Auth.signInWithWebUI(this, { it ->
                Log.e("MyAmplifyApp", "Could not initialize Amplify")
            }, {
                Log.e("MyAmplifyApp", "Could not initialize Amplify")
            })

 Amplify.Auth.signOut {
                  Log.e("MyAmplifyApp", "Could not initialize Amplify")
            }


 override fun onNewIntent(intent: Intent?) {
        super.onNewIntent(intent)
        Log.e("MyAmplifyApp", "Could not initialize Amplify")
    }

With above hosted UI custom tab opened but getting above exception at start also not getting signin callback result.

**Comment by gpanshu** [comment]
Can you link the generated jsonObject that you create? I want to make sure your structure is good.

**Comment by VijaySonawane5** [comment]
@gpanshu , 

As we using aws sdk with hosted ui which will launch web login ui using appclientId and cognito domainurl, First login attempt works well and we get idp token as well.

But if we logout or clear application cache and try same user again the application has fatal crash.

I try to catch some steps when app gets crash as follow

In AWSKeyValueStore
public synchronized void put(final String dataKey, final String value) {
-------
}

The code_challenge and scope put success and app will get crash.

sqOQXXXXXXXXXX2nXWHacQ-ywY0mQEaUcode_challenge
sqOQtr6KXXXXXXXXXXXXnXWHacQ-ywY0mQEaUscope


In Succcessful login above code_challenage and scope will be put with sucesss as also other paramaters.

CognitoIdentityProvider.XXXXXXXXXXXX.xxxxxxxxx.08@yopmail.com.tokenType
CognitoIdentityProvider.XXXXXXXXXXXX.xxxxxxxxx.08@yopmail.com.idToken 
CognitoIdentityProvider.XXXXXXXXXXXX.xxxxxxxxx.08@yopmail.com.accessToken
CognitoIdentityProvider.XXXXXXXXXXXX.xxxxxxxxx.08@yopmail.com.refreshToken
CognitoIdentityProvider.XXXXXXXXXXXX.xxxxxxxxx.08@yopmail.com.tokenScopes 

Last code execution point where app gets crashed is 

if (activity != null) {
   //  **### Here app will get crash.**
                **activity.startActivityForResult(
                    CustomTabsManagerActivity.createStartIntent(context, mCustomTabsIntent.intent),
                    CUSTOM_TABS_ACTIVITY_CODE
                );**
            } else {
                Intent startIntent = CustomTabsManagerActivity.createStartIntent(context, mCustomTabsIntent.intent);
                startIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                context.startActivity(startIntent);
            }

One more observation, If we used version 2.13.2 then this flow works fine but when we put app in background then crome custom tab get removed, If we upgrade version above 2.13.2 then app will get crashed as per above steps.

Could you please help here as we are facing crash in productions.

**Comment by gpanshu** [comment]
@VijaySonawane5 I think you are mixing the sdk code with V2 code. If you are using V2 just simply follow how to use webUI [here](https://docs.amplify.aws/lib/auth/signin_web_ui/q/platform/android/).

**Comment by VijaySonawane5** [comment]
@gpanshu , Yes, we are trying both way sdk and v2, So query is by programatically constructing the AwsConfiguration work using json object as tried above, or awsconfigurations.json file must be part of app. As our usecase is to connect diff aws congnito pools depends on API response.

**Comment by gpanshu** [comment]
@VijaySonawane5 [Amplify's AWS SDK for Android ](https://docs.amplify.aws/sdk/q/platform/android/) and [Amplify Android V2 ](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/android/) are not compatible with each other. Please use V2 for your purposes to avoid compatibility issues.
