### ISSUE TITLE
com.amazonaws.AmazonClientException: Unable to execute HTTP request: Stream closed

### ISSUE THREAD

**Issue by miketextnow** [aws-amplify/aws-sdk-android#3438]
**Describe the bug**
When calling `AmazonCognitoIdentityClient(AnonymousAWSCredentials()).getCredentialsForIdentity(request)` we get an `AmazonClientException` thrown after updating project to jdk17 and Android Gradle Plugin 8.1.1 (previously using jdk11 and AGP version 7.1.0)

**To Reproduce**
A code sample or steps:

Make following request on Android project using jdk 17 and Android Gradle Plugin 8.1.1
```
        AmazonCognitoIdentityClient(AnonymousAWSCredentials())
                            .getCredentialsForIdentity(request)
```

**Which AWS service(s) are affected?**
aws-android-sdk-core

**Expected behavior**
Files able to be uploaded to s3 

**Screenshots**

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.73.0
 - Device: Affects all devices
 - Android Version: Affects all versions
 - Specific to simulators: No

**Additional context**

**Comment by ankpshah** [comment]
Hello @miketextnow,
   I was not able to replicate the issue and it works as expected with JDK17 and AGP 8.1.1. Could you share more specific details about your setup?
