### ISSUE TITLE
Can JDK17 Build aws-sdk-android  2.63.0 and Later?

### ISSUE THREAD

**Issue by ElisabethJing** [aws-amplify/aws-sdk-android#3453]
**State your question**
Can JDK17 Build aws-sdk-android  2.63.0 and Later?

**Comment by tylerjroach** [comment]
@ElisabethJing Are you experiencing issues in building, or is this just a question. It should work, yes.

**Comment by ElisabethJing** [comment]
Nothing, thank you.
