### ISSUE TITLE
My Device cannot get get/accepted or update/accepted, but same account in other devices is OK. 

### ISSUE THREAD

**Issue by powerzd** [aws-amplify/aws-sdk-android#3561]
**State your question**
I use same account in three different devices, two devices work fine, the another device cannot get get/accepted or update/accepted, mqtt connect success, subscribe success, but it cannot get new message, it can publish at the same time which is the strange thing. The three devices are in the same environment. If this question happens, nothing can solve the problem,  include delete app and install, clear cache. What can i do to solve the problem or how to find the way to solve the problem. This troubles me a few days, i need your help, thanks. 

**Which AWS Services are you utilizing?**
a1gf9vy3yis1r4-ats.iot.us-east-2.amazonaws.com

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: [2.42.0 / 2.75.0] 

**Device Information (please complete the following information):**
 - Device: [SAMSUNG]
 - Android Version: [Android 11 One UI Core 3.1]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by tylerjroach** [comment]
1. Are they also on the same wifi?
2. Does the problematic device have any proxies configured? To ensure nothing is set, it may be good to try and "forget" the network and reconnect.
3. Are the devices all the same? What is the make/model/os version of the working devices compared the the problematic one.
