### ISSUE TITLE
Duplicate AWS Chime SDK locations?

### ISSUE THREAD

**Issue by Orbyt** [aws-amplify/aws-sdk-android#3602]
**State your question**
Which is the correct repository of the AWS Chime Android SDK?

**Which AWS Services are you utilizing?**
Chime and Cognito

There appear to be multiple repositories related to the AWS Chime SDK. This repository contains `aws-android-sdk-chimesdkmessaging` as well as `aws-android-sdk-chimesdkidentity`. However, there's another repository: https://github.com/aws/amazon-chime-sdk-android.

I have not yet found any definitive information regarding which repository is the "correct" one, as there seems to be a fair amount of conflicting information and examples. [build-chat-applications-in-ios-and-android-with-amazon-chime-sdk-messaging](https://aws.amazon.com/blogs/business-productivity/build-chat-applications-in-ios-and-android-with-amazon-chime-sdk-messaging) references and links to a [module in this repository ](https://github.com/aws-amplify/aws-sdk-android/tree/main/aws-android-sdk-chimesdkmessaging), but then documents like [chime-sdk/latest/dg/sdk-for-android](https://docs.aws.amazon.com/chime-sdk/latest/dg/sdk-for-android.html) link to the other one (https://github.com/aws/amazon-chime-sdk-android).

I'd like to integrate the AWS Chime SDK into an Android app primarily for messaging functionality. Which repository contains the correct SDK, and why are there multiple repositories?

**Comment by tylerjroach** [comment]
Hi @Orbyt Thank you for your message. The Chime SDK in this repo is primarily code generated cleint APIs to assist in hitting the Chime service APIs.

The Chime SDK here: https://github.com/aws/amazon-chime-sdk-android is actively being developed to not only access the Chime APIs, but also help complete advanced use cases on the Android OS (ex: managing complexities of video calling on the Android OS and all that involves). I would recommend starting at that repo.

**Comment by mattcreaser** [comment]
This question has been sufficiently answered - we recommend using https://github.com/aws/amazon-chime-sdk-android - please feel free to open a new issue if anything else comes up!
