### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by licaon-kter** [aws-amplify/aws-sdk-android#3605]
Reading https://github.com/aws-amplify/aws-sdk-android/blob/main/LICENSE.txt says:
> The AWS SDK for Android is generally licensed under the Apache 2.0 License, with the Amazon Cognito Identity Provider aws-android-sdk-cognitoidentityprovider subcomponent being licensed under the Amazon Software License, and the Amazon Lex subcomponent under the path aws-android-sdk-deepsense/src/main/jni/ under the AWS Customer Agreement (https://aws.amazon.com/agreement/ ).

Which sounds fine, but looking at the maven repo, eg. https://mvnrepository.com/artifact/com.amazonaws/aws-android-sdk-auth-core/2.75.2

I see `License: Amazon`

Looking at the POM file: https://repo1.maven.org/maven2/com/amazonaws/aws-android-sdk-auth-core/2.75.2/aws-android-sdk-auth-core-2.75.2.pom we see `Amazon Software License`

Can we get some clarification?

**Comment by tylerjroach** [comment]
Hi @licaon-kter I see what you mean. I'll get back to you with an answer shortly.

**Comment by licaon-kter** [comment]
ref: https://gitlab.com/fdroid/fdroid-suss/-/merge_requests/23/diffs

For F-Droid we can't include apps that depend on non-FOSS licensed code.

**Comment by phantumcode** [comment]
@licaon-kter We've updated the the license name in the POM file to Apache 2.0.  The change will be reflected our next release.

**Comment by licaon-kter** [comment]
Ok, so looking again at https://mvnrepository.com/artifact/com.amazonaws/aws-android-sdk-auth-core/2.77.0 it's Apache 2.0 :+1: 

now, reading again
> the Amazon Cognito Identity Provider aws-android-sdk-cognitoidentityprovider subcomponent being licensed under the Amazon Software License

and looking at https://mvnrepository.com/artifact/com.amazonaws/aws-android-sdk-cognitoidentityprovider/2.77.0 we have the opposite issue, this is marked as Apache 2.0 when it should not, right?

**Comment by phantumcode** [comment]
We'll update the License.txt file to match.  See https://github.com/aws-amplify/aws-sdk-android/pull/3634

**Comment by mattcreaser** [comment]
The license has been updated in the SDK [2.77.1](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.77.1) release.
