### ISSUE TITLE
Hi, does aws-sdk-android 2.73.0 support JDK17 and JDK21?

### ISSUE THREAD

**Issue by ElisabethJing** [aws-amplify/aws-sdk-android#3607]
Hi, does aws-sdk-android 2.73.0 support JDK17 and JDK21?

**Comment by lawmicha** [comment]
Hi @ElisabethJing, I didn't see in the README.md that we explicitly mention which JDK versions are supported. The best way to verify is to pull in the modules that you need and have the JDK version set to 17 or 21 and compile. Let us know if you have more specific requirements or if you are seeing some issues.
