### ISSUE TITLE
16 KB Support for Android 15

### ISSUE THREAD

**Issue by kunal-jaggi** [aws-amplify/aws-sdk-android#3626]
Hi, Android 15 is introducing a 16 KB page size development mode and asking new apps to work in this mode, so that future devices can use 16 KB pages. You may want to ensure your SDK works in this mode, so that app developers using this software package don't have to update themselves. Thank you!

Read more at https://developer.android.com/16kb-page-size.

**Comment by tylerjroach** [comment]
I believe the only native library is with IoT and we will track any efforts necessary in this issue: https://github.com/aws-amplify/aws-sdk-android/issues/3624.

If there is a concern about any other libs in the SDK, please let us know
