### ISSUE TITLE
Test Messaging and Campaigns not sending push since today to Android devices

### ISSUE THREAD

**Issue by MewanWA** [aws-amplify/aws-sdk-android#3635]
**State your question**
I am getting an error regarding usage of deprecated API when I try to send a Test Push Notification via AWS Pinpoint. My question is basically, do we need to update our SDK version or is this something AWS needs to from their end? Even through segments, notifications do not seem to be received on Android while iOS works as expected.

The error is below:

`Message not sent: We weren't able to send your push message to da...Rlq.
Request Id 89 : [daz...Rlq: PERMANENT_FAILURE {"errorMessage":"Invalid Credentials","channelType":"GCM","pushProviderStatusCode":"301","pushProviderError":"FCM is rejecting requests because of deprecation of the legacy API","pushProviderResponse":"{\"error\":\"Deprecated endpoint, see https:\\/\\/firebase.google.com\\/docs\\/cloud-messaging\\/migrate-v1\"}"}]`

**Which AWS Services are you utilizing?**
Pinpoint

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
- Pinpoint SDK Version: com.amazonaws:aws-android-sdk-pinpoint:2.69.0
- AmplifyCore version com.amplifyframework:core:1.4.1

**Device Information (please complete the following information):**
 - Device: Simulator and Samsung Galaxy A04e
 - Android 10-12
 - Specific to simulators: No

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by tylerjroach** [comment]
It appears that you need to reconfigure your Firebase + Amplify connect with Firebase's service account key (json) file. Firebase shut down legacy API usage.

See this page for the guide to use the service account key instead: https://docs.amplify.aws/gen1/android/sdk/push-notifications/setup-push-service/. See this notice from Firebase: https://firebase.google.com/docs/cloud-messaging/migrate-v1

**Comment by MewanWA** [comment]
That seemed to be the issue. Thank you @tylerjroach!
