### ISSUE TITLE
Android -TransferUtility to upload file on wifi data only

### ISSUE THREAD

**Issue by aditimodi04** [aws-amplify/aws-sdk-android#365]
How to manage amazon s3 file uploading on wifi data only. Don't want to upload on Mobile data

**Comment by aditimodi04** [comment]
How to manage amazon s3 file uploading on wifi data only. Don't want to upload on Mobile data

**Comment by kvasukib** [comment]
Hi @aditimodi04, 

Thanks for reporting to us. Currently, the SDK doesn't allow to specify the network configuration (wifi/cellular). But you could use the network connectivity APIs from Android OS to check for the network connection, pause/resume transfers accordingly. We will take it as a feature request.

**Comment by kvasukib** [comment]
Pull Request #230 addresses this issue. We will update this thread when the pull request is merged.

**Comment by vishal-rai** [comment]
@kvasukib Is this feature available now?

**Comment by tntkhang** [comment]
@kvasukib Is this feature still not available yet?

**Comment by kvasukib** [comment]
@aditimodi04 @vishal-rai @tntkhang This feature has been implemented and released in `2.11.` version of the SDK. See [CHANGELOG](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.11.1) for more information.

**Comment by muellerfr** [comment]
This feature has been released. Please try it out and open a new issue if you are observing and issues or have questions.
