### ISSUE TITLE
How to use X.509 to get iot shadow information by Android iot SDK?

### ISSUE THREAD

**Issue by pwa16000** [aws-amplify/aws-sdk-android#448]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
IoT
* In what version of SDK are you facing the problem?
2.6.18
* Is the issue limited to Simulators / Actual Devices?
No
* Can your problem be resolved if you bump to a higher version of SDK?
No
* Is this problem related to specific Android/OS version?
No
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.
I have equipment which use X.509 to connect to AWS Iot， but from AWS IoT android SDK, looks only AWSIotDataClient support shadow operation but AWSIotDataClient can only use AWSCredentials or AWSCredentialsProvider to get an instance. 

So if I use X.509, I can not get shadow information from AWS Android SDK. is that true?

Or if I use X.509, is there any other better way to get shadow other than subscribing branch like $aws/things/myLightBulb/shadow/update/accepted? whatever subscribe branch not an easy way to handle shadow information.

* Please include a stacktrace if applicable.
Not Applicable.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by cbommas** [comment]
hello @pwa16000 

You are correct - the supported mechanisms to get device shadow information is the AWSIotDataClient, which requires AWS credentials,  and the subscriptions using MQTT.

Can you provide further information on the difficulties you are facing. Your feedback would be very valuable in making improvements so that the SDK and the service is easy to use.

**Comment by pwa16000** [comment]
Hello, @cbommas

My case was, my device use X.509 certificate to connect to AWS IoT, but it also wants to get/update/delete shadow, If I use MQTT subscribe/publish to do this, it can do shadow related operation but does not as easy as AWSIotDataClient.

I think that where an MQTT connection can operate a shadow or not depend on the policy which was attached to x.509 certificate. 

I also saw a python SDK (https://s3.amazonaws.com/aws-iot-device-sdk-python-docs/sphinx/html/index.html), which support operate both on MQTT connection and shadow at same time.

above is what my understanding.

Thanks
Philip

**Comment by kvasukib** [comment]
Hi @pwa16000, Just to correct my understanding of the problem., are you saying that you want to use AWSIotDataClient to do shadow related operations (get/update/delete) using the X.509 certificate and the policy attached to the certificate instead of the AWSCredentials or AWSCredentialsProvider?

**Comment by pwa16000** [comment]
Hi, @kvasukib, Thanks for your replay.

Yes, I  want to use AWSIotDataClient to do shadow related operations (get/update/delete) using the X.509 certificate and the policy attached to the certificate instead of the AWSCredentials or AWSCredentialsProvider?

**Comment by kvasukib** [comment]
We will take it as a feature request to support X.509 certificate and the policy attached to the certificate with the `AWSIotDataClient`.

**Comment by jamesonwilliams** [comment]
Closing this feature request due to lack of activity. If you are interested in seeing this feature implemented, please vote 👍 on the original post, here: https://github.com/aws-amplify/aws-sdk-android/issues/448#issue-316456795.
