### ISSUE TITLE
AWS IOT connectivity issues on WiFi

### ISSUE THREAD

**Issue by 2math** [aws-amplify/aws-sdk-android#458]
### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS IOT
* In what version of SDK are you facing the problem?
2.6.14 and 2.6.19
* Is the issue limited to Simulators / Actual Devices?
Actual Devices
* Can your problem be resolved if you bump to a higher version of SDK?
Partly 
* Is this problem related to specific Android/OS version?
No
* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

The app is sending data on each second.
After an hour of work the SDK loses connection and keeps trying to reconnect, but never succeed
on v2.6.14, today I have changed to v2.6.19 and connection appears after 3 min and 184 attempts. 
This happens only when the device is connected through WiFi.
My devices are 2m away from the router and there is internet on the WiFi connection for sure.
At this point if I turn off the Wifi on the device, then the SDK connects immediately trough the Mobile Internet. Turning on WiFi leads to same reconnecting issue, if I turn off the Mobile net. 
After a few hours the SDK connects trough WiFi like there was never a problem(this was with v2.6.14
today on v2.6.19 reconnects in 3min).
Happens on Nexus 5x(8.1.0) and Samsung S8+(8.0)

* Please include a stacktrace if applicable.
05-15 12:08:43.090 I/AWSIotMqttManager: metrics collection is enabled, username: ?SDK=Android&Version=2.6.19
05-15 12:08:43.091 I/AWSIotMqttManager: resetting reconnect attempt and retry time
05-15 12:08:43.664 W/AWSIotMqttManager: onFailure: connection failed.
05-15 12:08:43.665 I/AWSIotMqttManager: schedule Reconnect attempt 0 of -1 in 1 seconds.
05-15 12:08:44.668 I/AWSIotMqttManager: attempting to reconnect to mqtt broker
05-15 12:08:44.723 W/AWSIotMqttManager: Reconnect failed 
05-15 12:08:44.723 I/AWSIotMqttManager: schedule Reconnect attempt 1 of -1 in 1 seconds.
05-15 12:08:45.726 I/AWSIotMqttManager: attempting to reconnect to mqtt broker
05-15 12:08:45.886 W/AWSIotMqttManager: Reconnect failed 
05-15 12:08:45.887 I/AWSIotMqttManager: schedule Reconnect attempt 2 of -1 in 1 seconds.
05-15 12:08:46.892 I/AWSIotMqttManager: attempting to reconnect to mqtt broker
05-15 12:08:46.930 W/AWSIotMqttManager: Reconnect failed 
05-15 12:08:46.931 I/AWSIotMqttManager: schedule Reconnect attempt 3 of -1 in 1 seconds.
05-15 12:08:47.935 I/AWSIotMqttManager: attempting to reconnect to mqtt broker
05-15 12:08:47.991 W/AWSIotMqttManager: Reconnect failed 
**_Here I disable WiFi_**
05-15 12:08:51.098 I/AWSIotMqttManager: attempting to reconnect to mqtt broker
05-15 12:08:52.859 I/AWSIotMqttManager: Reconnect successful
05-15 12:08:52.860 I/AWSIotMqttManager: Auto-resubscribe is enabled. Resubscribing to previous topics.
05-15 12:08:53.359 I/AWSIotMqttManager: delivery is complete
05-15 12:08:53.955 I/AWSIotMqttManager: message arrived on topic: notifications/353626078661282
**_Here I enable WiFi(so far so good, because the connection continue on 3G I guess)_**
05-15 12:10:15.742 I/AWSIotMqttManager: message arrived on topic: notifications/353626078661282
   -- Some work--
**_Here I disable Mobile net_**
05-15 12:10:17.046 W/AWSIotMqttManager: connection is Lost
05-15 12:10:17.051 I/AWSIotMqttManager: resetting reconnect attempt and retry time
05-15 12:10:17.056 I/AWSIotMqttManager: schedule Reconnect attempt 0 of -1 in 1 seconds.
05-15 12:10:18.064 I/AWSIotMqttManager: attempting to reconnect to mqtt broker
05-15 12:10:18.237 W/AWSIotMqttManager: Reconnect failed 
05-15 12:10:18.239 I/AWSIotMqttManager: schedule Reconnect attempt 1 of -1 in 1 seconds.
05-15 12:10:19.243 I/AWSIotMqttManager: attempting to reconnect to mqtt broker
05-15 12:10:19.278 W/AWSIotMqttManager: Reconnect failed 
**_After 184  attempts is Reconnected successful, this wasn't even happening before, probably
because I was using 2.6.14 and today switched to 2.6.19_**
05-15 12:13:36.531 W/AWSIotMqttManager: Reconnect failed 
05-15 12:13:36.534 I/AWSIotMqttManager: schedule Reconnect attempt 184 of -1 in 1 seconds.
05-15 12:13:37.541 I/AWSIotMqttManager: attempting to reconnect to mqtt broker
05-15 12:13:38.750 I/AWSIotMqttManager: Reconnect successful
05-15 12:13:38.751 I/AWSIotMqttManager: Auto-resubscribe is enabled. Resubscribing to previous topics.
05-15 12:13:40.881 I/AWSIotMqttManager: delivery is complete

Here are my configurations:
            mqttManager = new AWSIotMqttManager(clientId, AWSConstants.CLIENT_ENDPOINT);
            mqttManager.setDrainingInterval(1000L);//send offline msg if was queued in last 1000 mills
            mqttManager.setAutoReconnect(true);//default
            mqttManager.setAutoResubscribe(true);//default
            mqttManager.setMaxAutoReconnectAttepts(-1);//forever
            mqttManager.setReconnectRetryLimits(1, 1);//check to reconnect each second

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by 2math** [comment]
Is it possible to have some limitations from my internet provider?
Although it happens to me and my colegues in the office and at home,
also is reported from the client.
It is interesting that in such a case, when I set one device as access point and the others are connected to it through WiFi is working fine.

**Comment by cbommas** [comment]
hello @2math 
It is possible that there are some firewall blocking rules enabled in your network. Just to help analyze this further, how are you connecting? Is it through websocket (connectUsingWebSocketWithClientId) or the connection using the certificate mutual-authentication mechanism (connectWithClientId)?

Connecting with the websocket uses port 80, where as the certificate based connection uses port 8883. I would expect port 80 to not be blocked on most networks; port 8883 is less clear cut. If you are using the cert, can you try connecting with the websocket and let me know?

**Comment by 2math** [comment]
Hi @cbommas ,
Thank you for your help.
Here is how I connect :
`    
        try {
                mqttManager.connect(AWSCognitoService.getShared().getCredentialsProvider(), new 
                AWSIotMqttClientStatusCallback() {
                    @Override
                    public void onStatusChanged(final AWSIotMqttClientStatus status,
                                                final Throwable throwable) {
                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                onStatusChanged.onSuccess(status.name());

                                if (status == AWSIotMqttClientStatus.Connected) {
                                    subscribeToTopic();
                                    isConnected = true;
                                } else if (status == AWSIotMqttClientStatus.ConnectionLost) {
                                    isConnected = false;
                                } else if (status == AWSIotMqttClientStatus.Reconnecting) {
                                    isConnected = false;
                                }
                            }
                        });
                    }
                });
            } catch (final Exception e) {
                if (e instanceof NotAuthorizedException) {
                    AWSCognitoService.getShared().refreshSession();

                    connectМqttManager();
                }
            }
`

I see in the connect method that the endpoint is :
endpoint = String.format("%s.iot.%s.%s:443", accountEndpointPrefix, region.getName(),
                        region.getDomain());

Are you aking me to use connect(KeyStore keyStore, final AWSIotMqttClientStatusCallback statusCallback) instead?
I see then is formatted as: 
mqttBrokerURL = String
                .format("ssl://%s.iot.%s.%s:8883", accountEndpointPrefix, region.getName(),
                        region.getDomain());

**Comment by kvasukib** [comment]
@2math Hi Galeen, Sorry for the delayed response. We have done stability improvements to the AWS SDK for iOS - IoT. Can you upgrade to the latest and check if that fixes your issue? Please let us know if you have any feedback.

**Comment by NightOwlCoder** [comment]
hey there @mananchh, we are experiencing exact the same situation.
we are implementing a fleet of android tablets that will use IoT MQTT for "calling home".

But every one of the devices that has WiFi on looses connection and never reconnects anymore until WiFi is turned off.

Did you found out anything that could help?

**Comment by mananchh** [comment]
Hey @NightOwlCoder, we haven't got past this.

Although we did find a precise scenario, this is happening with mobile data + WiFi where in the mobile cellular service provider is a specific (Jio - Gujarat, India). 

The combination of mobile data + WiFi on android devices works perfectly fine with any cellular service provider except the one mentioned previously.

The tried the same cellular provider (Jio) but with service in a different region (Maharashtra, India) and it worked fine along with WiFi.

We even issued a new SIM in Gujarat region, but the results did not change, mobile data + WiFi led to connectivity problems just like mentioned previously.

I'm not sure what is blocking the IOT connection, as other applications still work seamlessly on the same android devices with the same mobile data + WiFi combination.

**Comment by NightOwlCoder** [comment]
Hey @kvasukib , any way for to help diagnose this?

My customer just found a second network location that is having the same experience.

I was wondering what would happen if we change to 

`MQTT + WebSocket | SigV4 | 443`

as this table says?

![image](https://user-images.githubusercontent.com/13557039/48235283-2ae18600-e372-11e8-9e61-1c5e30ebf2d5.png)

from: https://docs.aws.amazon.com/iot/latest/developerguide/protocols.html

any help/doc on configuring the system that way?

**Comment by NightOwlCoder** [comment]
Hey there @kvasukib, I'm risking losing the contract here.
Right now, we have 4 different locations, all `WIFI only`, where connection **never** happens.

We have tested everything we could WIFI related, and every other app works fine, we have data and a good speed on all sites.

Is there anything I could do to help investigate this?
Even an alpha version will help me here, I need to show progress....

**Comment by kvasukib** [comment]
@NightOwlCoder Can you email me at karthba at amazon dot com? We can jump into a call to investigate the issue further?

**Comment by mananchh** [comment]
Hey @NightOwlCoder, were you able to get way past this with kvasukib's help?

**Comment by muellerfr** [comment]
Hi @mananchh,

We never received an email from @NightOwlCoder, so we were not able to resolve the issue with him. There can be many different reasons for connection issues, and we are still investigating. Are the logs  errors you are seeing the same as the one posted by @2math?

**Comment by NightOwlCoder** [comment]
@kvasukib @mananchh @muellerfr hey guy, sorry for the long delay, but I had to go onsite with customer to solve this issue.

In the end, it all boils down to bad date/time on the tablets we are using!

Looks like a difference over 5 minutes makes all hell broke loose on SSL handshaking.

I implemented a `fix date time on load` method, and so far, I'm happy to say I manage to kep my contract! 🕺 

Unfortunately, I have no log of that time, because hen I was inside their premises, they did not allow me to take anything...

Hope this helps you guys, available to chat more if you want.

.Night

**Comment by mananchh** [comment]
Hi @muellerfr ,

Yes the log error we are seeing are same as posted by @2math.

We are still experiencing the reported scenario and the number of problems reported is growing slowly, it would be really helpful if there is any fix available sometime soon.

We have an additional scenario with a particual iPhone, where unfortunately the IOT connection never happens via WiF or mobile data. We tried different scenarios to troubleshoot (no SIM, airplane mode, WiFi off, mobile data off and WiFi connected, soft reset, app uninstall and install) but nothing helped.
Is there anything troubleshoot step from anyone which could help us identify the cause with this?

@NightOwlCoder , I set the date back 3 days but the connection was still successful. I'm surprised to see a different of 5 mins had your connection jammed.

**Comment by mananchh** [comment]
Hi Guys,

We have one more never connecting scenario.

On the Redmi Note 5 with Airtel (Tamil Nadu region) mobile data, the IoT connection never happens. This is a dual SIM phone, with Airtel SIM in tray 1 and Vodafone SIM in tray 2.

When the user switches mobile data from Airtel to Vodafone, the IoT connection works perfectly fine.

We have tried the PubSub connection app and the scenario was replicated with it too. We have a screen recording with the PubSub app with Airtel mobile data enabled.

Request your quick response on this, we need to get back to the client on this.


[Aitel Connection.zip](https://github.com/aws-amplify/aws-sdk-android/files/2709667/Aitel.Connection.zip)

**Comment by desokroshan** [comment]
@2math We have made some improvements to the IoT SDK. Can you please update to the latest version of the SDK and check if the issue persists.

@mananchh @staticmain750 The IoT SDK is agnostic of the specific connection details. Connection failures can be caused due to a variety reasons and its difficult to root cause the issue without more detailed logs. We are updating the SDK to pass all the reconnection exceptions to the users so it can be logged more readily. I will update this thread once we have released the changes.

**Comment by desokroshan** [comment]
@2math @mananchh @staticmain750 We have made a couple of changes to the SDK. 
Firstly, the SDK now propagate and log connection/reconnection errors to the developer even if SDK attempts an automatic reconnect. This would help us know the specific exception which caused the connection failure. Currently, even though the stacktrace may look similar but the underlying issue might be different. So its difficult to root cause the connection issue from the stack trace you have shared.
Secondly, we have updated the SDK to invoke publish callback, if provided, or throw an exception if an error condition is encountered in invoking publish.
Can you please try with the latest version of the SDK(2.10.0) and let me know if the issue persists.

**Comment by osamaazmat** [comment]
@mananchh did you guys manage to resolve this issue? If yes what steps did you take?

**Comment by mananchh** [comment]
@osamaazmat we were not able to resolve this issue, the user changed the phone and things are fine with the new phone. Port was not an issue for sure and I can confidently say that because ONLY this 1 handset would not connect over  Wi-FI while many other handsets would connect smoothly; also this 1 handset would not connect over ANY Wi-FI network

**Comment by osamaazmat** [comment]
@mananchh I understand, we faced a similar issue. Still trying to get to the bottom of it. I'll definitely check if its a phone issue. Thankyou for the reply.

**Comment by jamesonwilliams** [comment]
@osamaazmat & @mananchh Please check https://github.com/aws-amplify/aws-sdk-android/issues/2105 and its closed duplicates. Many connectivity issues with IoT appear to be related to lack of IPv6 support on various networks.

**Comment by mananchh** [comment]
@jamesonwilliams we have experienced connectivity issues due to lack of IPv6 from network providers but the issue discussed here is different, details mentioned [https://github.com/aws-amplify/aws-sdk-android/issues/458#issuecomment-428848482](url)

**Comment by osamaazmat** [comment]
@jamesonwilliams we are facing this issue on iOS as well in different regions. I'll take a look at the IPV6 connectivity issues as well. Could this also be a blocked port issue?
