### ISSUE TITLE
AWS Auth compatibility for API 22 and lower

### ISSUE THREAD

**Issue by anggrayudi** [aws-amplify/aws-sdk-android#471]
Hi there, please add compatibility for pre-Marshmallow devices, i.e. API 22 and lower to these dependencies:

````gradle
implementation ('com.amazonaws:aws-android-sdk-auth-ui:2.6.20@aar') { transitive = true }
implementation ('com.amazonaws:aws-android-sdk-auth-google:2.6.20@aar') { transitive = true }
````

Targetting API 23 for development is a bad choice because it just has 39.3% of market share. We developers need at least API 18 which has 91.4% of market share. You cannot force us to use the latest API. We want to develop our apps accross the worlds.

I am sure that you have a smart team and will add this compatibility soon.

This is the error message I got after using those dependencies:

    Manifest merger failed : uses-sdk:minSdkVersion 18 cannot be smaller than version 23 declared in library [com.amazonaws:aws-android-sdk-auth-ui:2.6.20] as the library might be using APIs not available in 18

**Comment by devganiyahitesh1** [comment]
+1

**Comment by hzdi** [comment]
+1
Should support API 16 as well, lot of people in third world countries have devices with API 16.

**Comment by KhaledSoliman** [comment]
+1

**Comment by iPaulPro** [comment]
Minimum should be API 21 at least.

Guys, it's simply not worth supporting anything under API 19 anymore. In fact, I don't believe anyone should spend time supporting anything under 21, at this point. However, API 23 as a minimum is extremely aggressive and almost-certainly not necessary.

**Comment by muellerfr** [comment]
Hello @anggrayudi,

I have added this as a feature request in our backlog and have submitted it to the team for prioritization. I do not have specific timeline that I can share at this point. We will let you know, either on this thread, or through a forum announcement when the feature is released in the SDK.

**Comment by cadam7** [comment]
+1

**Comment by anggrayudi** [comment]
Well, it is over than a month and no update. Everyone actually can't wait too long.

**Comment by palpatim** [comment]
Re-opening this feature request so we can continue to gather community interest in this feature, to help us accurately prioritize it against other work on the SDK.

**Comment by drwjf** [comment]
Minimum should be API 21 at least. Please.

**Comment by markorakita** [comment]
I understand that **aws-android-sdk-auth-ui** requires API 23, but I don't understand why does **aws-android-sdk-auth-google** require API 23 when **aws-android-sdk-auth-facebook** requires only API 15? It seems really unnecessary.

If we don't use your hosted UI, if we provide our own UI and just call federatedSignIn() from AWSMobileClient, can we use **aws-android-sdk-auth-google** and force usage with **tools:overrideLibrary="com.amazonaws.mobile.auth.google"**?

**Comment by anggrayudi** [comment]
It's been 8 months and nothing's changed. I don't know what's wrong with AWS Amplify team. Is it difficult to change minSdkVersion to 21 for **aws-android-sdk-auth-google**? Is this repository completely an open source project so that Amazon does not need pay you? Or do you lack of members so that you can't handle this large project with a small team? Let me know if I can join you.

You are going to lose with Firebase soon. They always listen to their customers. I am frustated watching this slow team.

**Comment by DonPepone** [comment]
For which reason the min sdk is 23? I didn't find a specific class or functionality requiring min sdk 23. 
It's a considerable constraint unless you write you owns UI. But you loose one of the advantages to adopt the framework.

**Comment by iPaulPro** [comment]
This is not a feature request. It's a common sense change that should have never been an issue. It's honestly ridiculous that we're still waiting for this. It's almost a year now.

**Comment by TechTeam12** [comment]
Any update on this? This is a major issue with the API since many devices still run Lollipop.

**Comment by hummatli** [comment]
Android Studio offers 16+ for basic Android App. I think the supprot has to SDK 16+

**Comment by SoyJorgeDiaz5** [comment]
2020 and still waiting for this update, I agree with @iPaulPro and  @drwjf, at least API 21 :(

**Comment by dakshsrivastava-papajohns** [comment]
> I understand that **aws-android-sdk-auth-ui** requires API 23, but I don't understand why does **aws-android-sdk-auth-google** require API 23 when **aws-android-sdk-auth-facebook** requires only API 15? It seems really unnecessary.
> 
> If we don't use your hosted UI, if we provide our own UI and just call federatedSignIn() from AWSMobileClient, can we use **aws-android-sdk-auth-google** and force usage with **tools:overrideLibrary="com.amazonaws.mobile.auth.google"**?

 Did anyone try this if it works?

**Comment by anggrayudi** [comment]
@dakshsrivastava-papajohns I tried. It causes runtime crash.

**Comment by danielwilson1702** [comment]
Well this is a load of nonsense - I cannot use the S3 transfer functionality because of [some auth library](https://github.com/awslabs/aws-sdk-android-samples/blob/a9bcd8736f94beea465f39b5d27d6dfea644b734/S3TransferUtilitySample/build.gradle#L40) I have no interest in has a min sdk of 23 (for apparently no good reason either?)

We are stuck with a min sdk of 17 developing for a large POS company that simply cannot update their devices. I guess I will have to try and manually upload files.

**Comment by iPaulPro** [comment]
Yeah these Amazon devs clearly don't care about issues here since they just use webviews for their awful apps.

It's been years and no answer.

**Comment by jpignata** [comment]
Howdy! Amazon dev here. Sorry for the long radio silence on this issue – I'd be frustrated, too. We're discussing the best way to approach the concerns in this issue right now and will work on this over the week to provide a more substantive update.

@danielwilson1702 The only sign-in/sign-up methods which currently require API level 23+ are the drop-in UI (aws-android-sdk-auth-ui) and Google federated sign-in (aws-android-sdk-auth-google). If you authenticate with any of the other methods, you can exclude those dependencies and use `minSdkVersion` 15.

Happy to chat via text if you have time via Discord or other medium. Contact details are in my [README](https://gist.github.com/jpignata/404b0141c70aebee6ab62292fbe649c5).

**Comment by secretshardul** [comment]
2 years but issue still open. Are they waiting for API 22 to catch up?

**Comment by TrekSoft** [comment]
This issue has been resolved and the dependencies lowered to API 14
