### ISSUE TITLE
There should be a way to invoke a particular version/alias of a lambda function, without duplicating the interface for each version/alias 

### ISSUE THREAD

**Issue by fahmad2** [aws-amplify/aws-sdk-android#530]
Duplicate of https://github.com/aws/aws-sdk-android/issues/303

### To help us solve your problem better, please answer the following list of questions.

* What service are you using?
AWS Mobile SDK

* In what version of SDK are you facing the problem?
com.amazonaws:aws-android-sdk-mobile-client:2.6.+@aar'
'com.amazonaws:aws-android-sdk-core:2.6.31'
'com.amazonaws:aws-android-sdk-lambda:2.6.30'

* Is the issue limited to Simulators / Actual Devices?
Simulators

* Can your problem be resolved if you bump to a higher version of SDK?
No

* Is this problem related to specific Android/OS version?
No

* Can you give us steps to reproduce with a minimal, complete, and verifiable example? Please include any specific network conditions that might be required to reproduce the problem.

* Please include a stacktrace if applicable.

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/mobile/sdkforandroid/developerguide/). You can also simplify your process of creating an application by using [Mobile Hub](https://console.aws.amazon.com/mobilehub/home#/).

**Comment by desokroshan** [comment]
@fahmad2 ,
I have added this as a feature request in our backlog and have submitted it to the team for prioritization. I do not have specific timeline that I can share at this point. We will let you know, either on this thread, or through a forum announcement when the feature is released in the SDK.

**Comment by fahmad2** [comment]
@desokroshan,

Thank you for the response. Also need functionality to allow invocation of specific aliases in the Policy document for a specific Role under IAM. Currently, I can not allow a specific identity_pool to invoke a lambda with a specific alias. This issue came up while invoking a lambda using the Android SDK (com.amazonaws:aws-android-sdk-lambda:2.6.30).

Currently, if I add the ARN of the lambda function with the Alias, the android sdk is unable to invoke it.
Throws an error on arn:aws:lambda:<region>:<account-id>:function:<lambda-name>:<alias-name>
But works fine with
arn:aws:lambda:<region>:<account-id>:function:<lambda-name>

**Comment by kvasukib** [comment]
@fahmad2 Thank you for your detailed response. This issue has been tagged as a feature request to acknowledge your comment.

**Comment by richardmcclellan** [comment]
While we do maintain this SDK with bug fixes and security updates, we generally won't be adding new features, as our primary focus is on the [Amplify](https://github.com/aws-amplify/amplify-android/) library.

For this particular feature request, instead of querying AWS Lambda directly from your Android app, I would suggest creating a REST API (API Gateway) with `Amplify.API`, which then calls your Lambda function.  Within your API Gateway configuration, you can control which Lambda function version is called.
