### ISSUE TITLE
Is it possible to use FirebaseAuth with Cognito to authenticate user for access to S3?

### ISSUE THREAD

**Issue by gauravk95** [aws-amplify/aws-sdk-android#540]
**Question:**
I would like to use, the already authenticated user via FirebaseAuth using the Google+ and Facebook method, as the credential provider for the uploading objects to S3 via Cognito Mode. 
Is it possible? If yes, can you refer me the docs or share some info here.

I am aware that we can allow unauthorized access, to make it work, without signing in to google+ or facebook via Cognito. I can also use AWS credentials(IAM User) directly, but its a security risk on android, so a bad option.

I am trying to find a secure way to put the object on the AWS S3 without having to go through the extra authentication step for Cognito(because using Firebase for Authentication).

**Which AWS Services are you utilizing?**
 - S3

**Environment:**
 - SDK Version: 2.7.4

**Device Information:**
 - Device: All
 - Android Version:  Lollipop 5.0

**Comment by kvasukib** [comment]
@gauravk95 Thank you for reporting to us. Sorry for the inconvenience caused. It is not possible to integrate a Firebase Auth user with S3 without federating with Cognito / STS. You can setup your Identity provider as a OIDC provider on Cognito console and you can federate the user's token with Cognito Identities and then you can use the Cognito credentials with S3.

**Comment by gauravk95** [comment]
Thanks. Will try this out.

**Comment by gauravk95** [comment]
I did try out the OIDC, but found that it works fine for Google Login, but has issues with Facebook login(Researched a bit online, and found that Facebook doesn't use OpenId (uses some proprietary Auth mechanism based on OAuth 2.0).

What are the alternatives for the Auth Providers that do not support OpenId? Or is there any other way to do this. I need to support both the Facebook and Google login.

Thanks in Advance!

**Comment by minbi** [comment]
Hi @gauravk95 ,

We support federated sign-in with Google and Facebook.
If you plan on obtaining the Facebook token in your app, you can use.

```
AWSMobileClient.getInstance().federatedSignIn(IdentityProvider.FACEBOOK.toString(), facebookToken);
```

You can read more about in our updated documentation linked [here](https://aws-amplify.github.io/docs/android/authentication#federated-sign-in).

**Comment by muellerfr** [comment]
This issue has been closed because of inactivity. Please open a new issue if are still encountering problems.

**Comment by jasan-s** [comment]
@gauravk95  i wanted to use firebaseAuth for web in cognito. were you ever able to get it working for android?

**Comment by subhadippramanik** [comment]
@gauravk95 Did you get some solution? I have pretty much similar use case. I am still searching for a proper solution.
