### ISSUE TITLE
Wrong video orientation in Kinesis Stream

### ISSUE THREAD

**Issue by desokroshan** [aws-amplify/aws-sdk-android#544]
**State your question**
Hi,
I am using Kinesis Video for live as well as on demand video playback in an android application. One thing i am stuck on now is getting wrong orientation while playing the video url.

**Which AWS Services are you utilizing?**
Kinesis
**Provide code snippets (if applicable)**

```java
AndroidCameraMediaSourceConfiguration.builder()
.withCameraId(String.valueOf(cameraId))
.withEncodingMimeType("video/avc")
.withHorizontalResolution(320)
.withVerticalResolution(240)
.withCameraFacing(1)
.withIsEncoderHardwareAccelerated(true)
.withFrameRate(FRAMERATE_20)
.withRetentionPeriodInHours(RETENTION_PERIOD_48_HOURS)
.withEncodingBitRate(BITRATE_384_KBPS)
.withCameraOrientation(0)
.withNalAdaptationFlags(StreamInfo.NalAdaptationFlags.NAL_ADAPTATION_ANNEXB_CPD_AND_FRAME_NALS)
.withIsAbsoluteTimecode(false));
```

Above is the configuration for media. Please help!

**Comment by desokroshan** [comment]
Opened originally by @gerahimanshu

**Comment by MushMal** [comment]
@desokroshan, there are two issues related to the orientation.

1) The dynamic orientation switching during streaming. This can't be done in a simple fashion as the encoder needs to be re-configured - a new CPD (Codec Private Data) needs to be submitted. This will break streaming. In this case, the streaming needs to stop/start behind the scene with a new static orientation configuration which would produce the proper CPD.
2) The first point leads us to the second point - static orientation configuration. We have not yet wired up the orientation to the encoder - this is something that we will be looking at soon. No ETA for it at this stage.
