### ISSUE TITLE
[Android]pack the KEYSTORE file as part of the APK

### ISSUE THREAD

**Issue by desokroshan** [aws-amplify/aws-sdk-android#549]
AWS androidIoT : Publish/Subscribe sample

Where to keep the "KEYSTORE_PATH" file while building the APK.

I have tried in asset/aws/iot_keystore_aws folder, but unable to the get the folder path from AssetManager.

Sample example has the path of : KEYSTORE_PATH = context?.getFilesDir()!!.getPath()

Here the gitHub :https://github.com/awslabs/aws-sdk-android-samples/tree/master/AndroidPubSub

I'm following the Using an off-device keystore

Steps 1:Import certificate and private key into PKCS12 keystore.
Steps 2:Convert PKCS12 keystore to a BKS (BouncyCastle) keystore.
Steps 3: List aliases in keystore to verify (optional).
Steps 4:Push to Android Emulator (optional).
 adb push <keystore name>.bks /data/user/0/your_app_dir_goes_here/files/<keystore name>
 
Note :  App is working perfectly , but how to pack the KEYSTRORE file as part of the APK

**Comment by desokroshan** [comment]
[Original Issue](https://github.com/awslabs/aws-sdk-android-samples/issues/249) opened by @arunkk-git.

**Comment by sunchunqiang** [comment]
Hi @arunkk-git 
AWSIotKeystoreHelper APIs do not support read the file from APK assets, so you should not pack the KEYSTRORE file as part of the APK. There is also a security issue if you pack the KEYSTRORE file as part of the APK.

**Comment by sunchunqiang** [comment]
Hi @arunkk-git 

androidIoT APIs do not support use a KEYSTONE file inside the APK, so you cannot pack the KEYSTRORE file as part of the APK. There is also a security issue if the keystore file is in the APK.

**Comment by arunkk-git** [comment]
_Sorry for delay in reply._
I don't  have any requirement to put KEYSTORE file as part of the APK,
Then how to  read key 

_from Code :_ 
 ****// To load cert/key from keystore on filesystem**
        **try {
            if (AWSIotKeystoreHelper.isKeystorePresent(KEYSTORE_PATH, KEYSTORE_NAME)) {}****

**Comment by desokroshan** [comment]
@arunkk-git Apologies for the delayed response. If you wish to bundle keystore as part of the apk file, you can add it as a resource in res/raw folder of your Android Studio project. You can access it as ```getResources().openRawResource(R.raw.<keystore_name>)``` and write it to the KEYSTORE_PATH.

**Comment by desokroshan** [comment]
Closing this thread due to inactivity. Please feel free to re-open or open a new issue if you have follow-up questions. Thanks.
