### ISSUE TITLE
Crash on  : ClientConfiguration clientConfig = new ClientConfiguration();

### ISSUE THREAD

**Issue by Janart08** [aws-amplify/aws-sdk-android#562]
java.lang.ExceptionInInitializerError
        at com.amazonaws.util.VersionInfoUtils.getUserAgent(VersionInfoUtils.java:77)

**Comment by Janart08** [comment]
implementation 'com.amazonaws:aws-android-sdk-s3:2.7.6'
    implementation('com.amazonaws:aws-android-sdk-mobile-client:2.7.+@aar') { transitive = true }
    implementation('com.amazonaws:aws-android-sdk-auth-userpools:2.7.+@aar') { transitive = true }

ya same line

**Comment by minbi** [comment]
I'm using the following code and can't reproduce. Can you provide the code that shows this error?

```
AWSMobileClient.getInstance().initialize(this, new AWSStartupHandler() {
    @Override
    public void onComplete(AWSStartupResult awsStartupResult) {
        Log.d(TAG, "onComplete: ");
        TransferUtility transferUtility = TransferUtility.builder()
                .context(getApplicationContext())
                .s3Client(new AmazonS3Client(AWSMobileClient.getInstance().getCredentialsProvider()))
                .awsConfiguration(new AWSConfiguration(getApplicationContext()))
                .build();
        try {
            transferUtility.upload("public/test.file", File.createTempFile("test", "file"));
            Log.d(TAG, "onComplete: uploaded file");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}).execute();
```

**Comment by Janart08** [comment]
AWSCredentials credentials = new BasicAWSCredentials(accesskey,
secretkey);
        ClientConfiguration clientConfig = *new
ClientConfiguration()*; // this creating
the crash
        AmazonS3 s3Client = new AmazonS3Client(credentials, clientConfig);
        return s3Client;

**Comment by minbi** [comment]
Hi @Janart08 ,

I'm not seeing the same issue you are.
If you are using Android Studio, please try `Rebuild Project` and then running. Also, you may delete the `build` folders in the project. Recently, I upgraded to Android Studio 3.2 and found some of my projects stopped building. In that case, I invalidated the Android Studio cache and re-built the project.

Another note, you have the `...mobile-client:2.7.+` syntax. I tried with that as well, but for debugging, can you pin the version to `2.7.7`.

PS
I edited your answer to be exactly what I ran.

**Comment by kyletough** [comment]
I have run into the same crash. It has occurred on my Pixel2XL and an emulator with both running Android 9.0 and it crashes on load with the initialisation of `ClientConfiguration clientConfig = new ClientConfiguration();` in the instantiation of the Cognito UserPool

I was running `2.6.25` but have now updated to `2.8.1` with it still occurring. The line shown above is the same place it is occurring.

**Comment by kyletough** [comment]
I have dug a little deeper within the stack trace and the bottom half refers to Apache Logging.

```
Caused by: java.lang.RuntimeException: Stub!
        at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:14)
        at com.amazonaws.logging.ApacheCommonsLogging.<init>(ApacheCommonsLogging.java:36)
        at com.amazonaws.logging.LogFactory.getLog(LogFactory.java:40)
        at com.amazonaws.util.VersionInfoUtils.<clinit>(VersionInfoUtils.java:41)
        at com.amazonaws.util.VersionInfoUtils.getUserAgent(VersionInfoUtils.java:77) 
        at com.amazonaws.ClientConfiguration.<clinit>(ClientConfiguration.java:43) 
```

**Comment by minbi** [comment]
Hi @kyletough ,

I see the problem. Thank you for the detailed logs. We will update this thread when we have a fix.

**Comment by minbi** [comment]
Hi @Janart08 @kyletough ,

We have released a fix in version 2.8.2 of the SDK. Can you check whether this fixes the issue for you?

**Comment by kyletough** [comment]
Hi @minbi ,

Thanks for the quick turn around. I have tried the 2.8.2 SDK update and it did fix the issue for me.

**Comment by muellerfr** [comment]
Excellent!
