### ISSUE TITLE
com.amazonaws.mobile.auth.ui.SignInUI-  Phone Number Formatting Validation Improvement (Country Code)

### ISSUE THREAD

**Issue by BillBunting** [aws-amplify/aws-sdk-android#564]
**Which AWS Services is the feature request for?**
com.amazonaws.mobile.auth.ui.SignInUI;
i.e. 
SignInUI signinUI = (SignInUI) AWSMobileClient.getInstance().getClient(AuthenticatorActivity.this, SignInUI.class);

**Is your feature request related to a problem? Please describe.**
End users are unable to create accounts and subsequently do not use the app or contact support because they are confused by the requirement to enter a + and country code with Phone Number format (+15551234567).

The current validation message reads "Sign up failed. Invalid phone number format". 

Some end users do not generally understand the requirement to enter a plus to start a phone number and are subsequently confused and often frustrated enough to not sign-up. 

**Describe the solution you'd like**
If the user enters a phone number without "+" or "+1" then simply add it before submitting for validation, assume USA, or, determine the country by IP address location or other means and assume a local phone number or add a country code.  Or, make the error message more descriptive. 

**Describe alternatives you've considered**
None, not in control of this code.

**Additional context**
None.

**Comment by minbi** [comment]
Hi @BillBunting ,

I will take this request to the team to discuss how we might be able to support this functionality.

**Comment by BillBunting** [comment]
Please continue to work on this issue.  Entering a phone number that requires a '+' is tedious and very confusing to most USA users.  It requires the user to immediately switch keyboard views to find the '+'.  Many users get frustrated and abandon the app because of the poor sign-up experience! Please add code to detect a USA formatted number and automatically add the +1 as needed or otherwise fix this issue.

**Comment by BillBunting** [comment]
Grooming old issues: For the app I work on, I removed the ability for users to create new username/password accounts via AWS Cognito com.amazonaws.mobile.auth.ui.SignInUI due to this and related issues with the UX. Grooming my issues, closing. (New users of my app are only be offered Facebook or Google sign-in, existing Cognito userpool users may sign-in with their existing username/password.
