### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: length=1442; regionStart=-1; regionLength=1443

### ISSUE THREAD

**Issue by zhouxuemeng1988** [aws-amplify/aws-sdk-android#570]
```java
java.lang.ArrayIndexOutOfBoundsException: length=1442; regionStart=-1; regionLength=1443
	at com.android.org.conscrypt.util.ArrayUtils.checkOffsetAndCount(ArrayUtils.java:34)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:691)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketFrame.<init>(WebSocketFrame.java:169)
	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketReceiver.run(WebSocketReceiver.java:98)
	at java.lang.Thread.run(Thread.java:818)
```

com.amazonaws:aws-android-sdk-iot
 - SDK Version: [e.g. 2.6.28]

**Device Information (please complete the following information):**
SUPPORTED_64_BIT_ABIS=[Ljava.lang.String;@b17e422
versionCode=77
BOARD=xmen
BOOTLOADER=unknown
devicesId=ba2edc61731a394e
TYPE=user
ID=MHC19J
TIME=1528270472000
BRAND=Xiaomi
TAG=Build
SERIAL=14074680091842
HARDWARE=amlogic
SUPPORTED_ABIS=[Ljava.lang.String;@4faaeb3
CPU_ABI=armeabi-v7a
RADIO=unknown
IS_DEBUGGABLE=false
MANUFACTURER=xiaomi
SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@3e1dded
TAGS=release-keys
CPU_ABI2=armeabi
UNKNOWN=unknown
USER=jenkins
FINGERPRINT=Xiaomi/xmen/xmen:6.0.1/MHC19J/514:user/release-keys
HOST=c3-mitv-bsp-build02.bj
PRODUCT=xmen
versionName=3.1.6
DISPLAY=8.6.6.514
MODEL=MiTV4A
DEVICE=xmen

Occasional problem

**Comment by sunchunqiang** [comment]
Hi @zhouxuemeng1988 
Thanks for reporting the issue.
Does "Occasional problem" mean the issue happen some time? 
Which AWS service are you using? Can you provide a code snippet that leaded to the crash?

**Comment by muellerfr** [comment]
@zhouxuemeng1988, it looks like this crash happens with IoT. Do you have sample code or better yet repo steps?

**Comment by zhouxuemeng1988** [comment]
@sunchunqiang @muellerfr 
`long currentTime = System.currentTimeMillis() / 1000;
        //距离上次mqtt崩溃时间大于24小时才开启aws-mqtt消息连接
        long awsCrashTime = SharedPreference.get(this).getDate("aws_Crash_long", 0L);
        LogUtils.d("RNAwsIot", awsCrashTime + "");
        LogUtils.d("RNAwsIot", (currentTime - awsCrashTime) + "");

        if (currentTime - awsCrashTime > 24 * 3600) {
            initS3();
            AwsLotModule.getInstance().initialize(this);
            AwsLotModule.getInstance().connect("us-west-2:2009**********0aa9", "*******.iot.us-west-2.amazonaws.com", "us-west-2", new AwsLotModule.MessageStateLisenter() {
                @Override
                public void onStateChange(String status) {
                    switch (status) {
                        case "Connecting":
                            break;
                        case "Connected": {
                            // RNAwsIot.publish('abc', 'Z001');
                            Log.d(TAG, "RNAwsIot---Connected");
                            AwsLotModule.getInstance().subscribe("screen_" + code, new AwsLotModule.MessageLisenter() {
                                @Override
                                public void onMessage(String message) {
                                    handleMessage(message, "aws");
                                }
                            });
                        }
                        break;
                        case "Reconnecting":
                        case "ConnectionLost":
                        case "Disconnected":
                        default:
                            break;
                    }
                }
            });
        }`




`package com.gochinatv.ad.awslot;

import android.content.Context;
import android.os.Handler;
import android.os.Looper;
import android.util.Log;

import com.amazonaws.AmazonClientException;
import com.amazonaws.auth.CognitoCachingCredentialsProvider;
import com.amazonaws.mobileconnectors.iot.AWSIotMqttClientStatusCallback;
import com.amazonaws.mobileconnectors.iot.AWSIotMqttManager;
import com.amazonaws.mobileconnectors.iot.AWSIotMqttNewMessageCallback;
import com.amazonaws.mobileconnectors.iot.AWSIotMqttQos;
import com.amazonaws.regions.Regions;
import com.taobao.weex.WXEnvironment;

import java.io.UnsupportedEncodingException;
import java.util.UUID;


public class AwsLotModule {
    private static final String LOG_TAG = "AwsLotModule";
    String clientId;
    AWSIotMqttManager mqttManager;
    CognitoCachingCredentialsProvider credentialsProvider;

    Long checkConnectionTime;
    String statusCallBack;

    String cognitoPoolId;
    String endPoint;
    String myRegion;

    //CrashHandler实例
    private static AwsLotModule INSTANCE = new AwsLotModule();
    //程序的Context对象
    private Context mContext;

    /**
     * 保证只有一个AwsLotModule实例
     */
    private AwsLotModule() {
    }

    /**
     * 获取CrashHandler实例 ,单例模式
     */
    public static AwsLotModule getInstance() {
        return INSTANCE;
    }

    public void initialize(Context context) {
        mContext = context;
        clientId = UUID.randomUUID().toString();
        checkConnectionTime = System.currentTimeMillis();
        final Handler handler = new Handler(Looper.getMainLooper());
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
//                Log.e(LOG_TAG, "连接检查");
                if (System.currentTimeMillis() - checkConnectionTime > 5 * 60 * 1000 && statusCallBack == "Connected") {
                    mqttManager.disconnect();
                    connect(cognitoPoolId, endPoint, myRegion, null);
//                    Log.e(LOG_TAG, "连接失效");
                } else {
//                    Log.e(LOG_TAG, "连接正常");
                }
                handler.postDelayed(this, 5 * 60 * 1000);
            }
        }, 5 * 60 * 1000);
    }


    public void connect(String cognito_pool_id, String end_point, String region, final MessageStateLisenter stateLisenter) {
        cognitoPoolId = cognito_pool_id;
        endPoint = end_point;
        myRegion = region;

//        int timeoutConnection = 10 * 1000;
//        ClientConfiguration clientConfiguration = new ClientConfiguration();
//        clientConfiguration.setMaxErrorRetry(2);
//        clientConfiguration.setConnectionTimeout(timeoutConnection);
//        clientConfiguration.setSocketTimeout(timeoutConnection);
//        clientConfiguration.setProtocol(Protocol.HTTP);

        try {

            credentialsProvider = new CognitoCachingCredentialsProvider(
                WXEnvironment.getApplication().getApplicationContext(),
                cognito_pool_id,
                Regions.fromName(region)
//                    Regions.fromName(region), clientConfiguration
            );
            mqttManager = new AWSIotMqttManager(clientId, end_point);
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        mqttManager.connect(credentialsProvider, new AWSIotMqttClientStatusCallback() {
                            @Override
                            public void onStatusChanged(final AWSIotMqttClientStatus status,
                                                        final Throwable throwable) {
                                checkConnectionTime = System.currentTimeMillis();
                                statusCallBack = "Disconnected";
                                if (status == AWSIotMqttClientStatus.Connecting) {
                                    Log.e(LOG_TAG, "Connecting...");
                                    statusCallBack = "Connecting";
                                } else if (status == AWSIotMqttClientStatus.Connected) {
                                    Log.e(LOG_TAG, "Connected");
                                    checkConnectionTime = System.currentTimeMillis();
                                    statusCallBack = "Connected";
                                } else if (status == AWSIotMqttClientStatus.Reconnecting) {
                                    if (throwable != null) {
                                        Log.e(LOG_TAG, "Connection error.", throwable);
                                    }
                                    statusCallBack = "Reconnecting";
                                    Log.e(LOG_TAG, "Reconnecting");
                                } else if (status == AWSIotMqttClientStatus.ConnectionLost) {
                                    if (throwable != null) {
                                        Log.e(LOG_TAG, "Connection error.", throwable);
                                        throwable.printStackTrace();
                                    }
                                    statusCallBack = "ConnectionLost";
                                    Log.e(LOG_TAG, "Connection lost");
                                } else {
                                    Log.e(LOG_TAG, "Disconnected");
                                }

                                if (stateLisenter != null)
                                    stateLisenter.onStateChange(statusCallBack);
                            }
                        });
                    } catch (AmazonClientException e) {
                        Log.e(LOG_TAG, "Connection AmazonClientException111.", e);
                    } catch (Exception e) {
                        Log.e(LOG_TAG, "Connection error1111.", e);
                    }
                }
            }).start();
        } catch (AmazonClientException e) {
            Log.e(LOG_TAG, "Connection AmazonClientException.", e);
        } catch (Exception e) {
            Log.e(LOG_TAG, "Connection error2222.", e);
        }

    }

    public void disConnect() {
        try {
            mqttManager.disconnect();
        } catch (Exception e) {
            Log.e(LOG_TAG, "Disconnect error.", e);
        }
    }

    public void publish(String msg, String topic) {
        try {
            mqttManager.publishString(msg, topic, AWSIotMqttQos.QOS0);
        } catch (Exception e) {
            Log.e(LOG_TAG, "Publish error.", e);
        }
    }

    public void subscribe(String topic, final MessageLisenter lisenter) {
        try {
            mqttManager.subscribeToTopic(topic, AWSIotMqttQos.QOS1, new AWSIotMqttNewMessageCallback() {
                @Override
                public void onMessageArrived(final String topic, final byte[] data) {
                    try {
                        String message = new String(data, "UTF-8");
//                        Log.e(LOG_TAG, "Message arrived:");
//                        Log.e(LOG_TAG, "Topic: " + topic);
                            Log.e(LOG_TAG, "Message: " + message);
//                        Map map = new HashMap();
//                        map.put("topic", topic);
//                        map.put("message", message);
                        lisenter.onMessage(message);
                    } catch (UnsupportedEncodingException e) {
                        Log.e(LOG_TAG, "Message encoding error.", e);
                    } catch (Exception e) {
                        Log.e(LOG_TAG, "check_alive--Message encoding Exception.", e);
                    }
                }
            });

            mqttManager.subscribeToTopic("check_alive", AWSIotMqttQos.QOS0, new AWSIotMqttNewMessageCallback() {
                @Override
                public void onMessageArrived(String topic, byte[] data) {
                    try {
                        String message = new String(data, "UTF-8");
//                        LogUtils.e(LOG_TAG, "check_alive--Message: " + message);
                        checkConnectionTime = System.currentTimeMillis();
                    } catch (UnsupportedEncodingException e) {
                        Log.e(LOG_TAG, "check_alive--Message encoding error.", e);
                    } catch (Exception e) {
                        Log.e(LOG_TAG, "check_alive--Message encoding Exception.", e);
                    }
                }
            });
        } catch (com.amazonaws.AmazonClientException e) {
            Log.e(LOG_TAG, "Subscription error-AmazonClientException.", e);
        } catch (Exception e) {
            Log.e(LOG_TAG, "Subscription error.", e);
        }
    }

    public interface MessageLisenter {
        void onMessage(String message);
    }

    public interface MessageStateLisenter {
        void onStateChange(String state);
    }

}
`

**Comment by kvasukib** [comment]
@zhouxuemeng1988 You are invoking connect from a background thread. The connect accepts the callback where the connection status is reported. 
Can you look at your logs to see if the connection was established? 
And if the connection is available when the publish/subscribe operation was happening? 
Do you think the exception you get is during a publish or a subscribe?
