### ISSUE TITLE
How to get file from S3 for an SDK

### ISSUE THREAD

**Issue by Ovadia-B** [aws-amplify/aws-sdk-android#573]
I am developing an SDK and I need some remote storage, without creating a API server.

Currently I am using BasicAWSCredentials with static Access & Secret Key, but when an app that uses the SDK uploads to the Google Play console, there is an Security warning. 

I wanted to know if there is way to use S3 without the static keys to avoid the security vulnerability.

**Comment by kvasukib** [comment]
@Ovadia-B Thank you for reporting to us. You can use Amazon Cognito Federated Identities by creating an Identity Pool. You can follow the [Authentication](https://aws-amplify.github.io/docs/android/authentication) guide in AWS Amplify to setup an Identity Pool and retrieve the AWSCredentials that are required for accessing S3.

Once you have finished setting up the [Authentication](https://aws-amplify.github.io/docs/android/authentication) in your app, you can follow the [Storage](https://aws-amplify.github.io/docs/android/storage) guide to see how it interacts with the `TransferUtility` to upload and download files.

In short, you would be constructing `TransferUtility` like this:

```java
TransferUtility transferUtility =
            TransferUtility.builder()
                .context(getApplicationContext())
                .awsConfiguration(AWSMobileClient.getInstance().getConfiguration())
                .s3Client(new AmazonS3Client(AWSMobileClient.getInstance()))
                .build();
```

**Comment by Ovadia-B** [comment]
Thank for your feedback, but Using Cognito require a login using (google, facebook etc.), and I am developing an SDK for other develops and apps.

I can't see how Cognito can help in that case.
