### ISSUE TITLE
Retry strategy for TransferUtility

### ISSUE THREAD

**Issue by CodingInfinite** [aws-amplify/aws-sdk-android#576]
**AmazonS3Client is not using my ClientConfiguartion. I'm uploading some songs to S3 and on slow Internet my songs are not uploded and failed several times. Although in my ClientConfiguration I have 0 maxRetry but don't know why it retries multiple time.**

**I'm using AWS S3 SDK and dependency version is 2.8.+**

**Device Information (please complete the following information):**
 - Infinix S3
 - Android Version: [26]
 - Specific to simulators:

**My Code For ClientConfiguration**

```kotlin
    private fun getClientConfiguration(): ClientConfiguration {
        val clientConfiguration = ClientConfiguration()
        clientConfiguration.withMaxErrorRetry(0)
            .withConnectionTimeout(5000)
            .withSocketTimeout(10000)
        return clientConfiguration
    }
```

**And the AmazonS3Client**

```kotlin
private fun getS3Client(): AmazonS3Client  {

        if (sS3Client == null) {
            sS3Client = AmazonS3Client(basicAwsCredentials(), getClientConfiguration()).apply {
                setS3ClientOptions(
                    S3ClientOptions
                        .builder()
                        .setAccelerateModeEnabled(true)
                        .build()
                )
                setBucketAccelerateConfiguration(
                    Constants.BUCKET_NAME,
                    BucketAccelerateConfiguration(BucketAccelerateStatus.Enabled)
                )
            }
        }
        return sS3Client as AmazonS3Client
    } 
```

**Comment by CodingInfinite** [comment]
Any update on this issue..?

**Comment by kvasukib** [comment]
@CodingInfinite Sorry for the delayed response. What exception were you getting for your upload and how many times was the upload retried? Can you post the exception message and stacktrace?

**Comment by CodingInfinite** [comment]
The application retried three times when the error occurs. Also, one more thing I got during upload when I cancel the upload after that when I start again the uploading it never uploads until I restart my application.

That's how I cancel the upload.

`transferUtility?.cancelAllWithType(TransferType.UPLOAD)`

**Comment by kvasukib** [comment]
To cancel the upload, you can do `transferUtility.cancel(transferObserver.getId());`

**Comment by CodingInfinite** [comment]
Yes, first I do the same what you suggested but canceling the upload with id cancels successfully but never able to upload again until I restart my application.

In my Activity onCreate method, I start the TransferUtilty service.

`startService(Intent(context, TransferService::class.java))`

I have this scenario where I need to upload multiple songs to Amazon S3 and below is my method for upload songs.

```
fun uploadParty(uploadPartyModel: UploadPartyModel) {
      launch(context = coroutineContext) {
            try {
                val folderName = amazonS3Utility.getFolderName(uploadPartyModel.partyTitle)
                for (musicModel in uploadPartyModel.uploadMusicModels) {
                    val file = musicModel.file
                    launch {
                        val transferObserver =
                            transferUtility.upload(AmazonS3Utility.BUCKET_NAME, folderName.plus(file?.name), file)
                        transferObserver.setTransferListener(transferListener)
                    }
                }
            } catch (e: java.lang.Exception) {
                _songsUploader.postValue(UploadState.Failed)
            }
        }
    }
```

That's how I cancel the upload.

```
fun cancelUploads() {
           job.cancel()
           transferUtility?.cancelAllWithType(TransferType.UPLOAD)
  }
```

The above **cancelUpload** method successfully cancel all the upload songs but after cancelation when I again call my **uploadParty** method it never starts uploading.

**Comment by CodingInfinite** [comment]
Any feedback on this....?

**Comment by kvasukib** [comment]
@CodingInfinite Sorry for the delayed response. Once the upload is cancelled, you cannot resume it again. You need to start a new upload. However if you want to resume an upload, you need to pause it by calling `transferUtility.pause`.

`TransferUtility` doe not retry the failed transfers. I will file a feature request to the team for the retry functionality in `TransferUtility`. The retries you set in `ClientConfiguration` is only honored at the layer where the HTTP request is being sent to S3. If the HTTP request resulted in an error which is retryable, then the retries count and policy set in `ClientConfiguration` will be honored. However if the error is at the `TransferUtility` layer, then it's a missing feature.

**Comment by kvasukib** [comment]
Tracking this issue in #616. So closing this issue.

**Comment by elvalelucho** [comment]
honorMaxErrorRetryInClientConfig must be configurated TRUE on RetryPolicy
