### ISSUE TITLE
Single Device login

### ISSUE THREAD

**Issue by muellerfr** [aws-amplify/aws-sdk-android#585]
Opened originally by @ali-mehmood-10p at https://github.com/awslabs/aws-sdk-android-samples/issues/270

**State your question**

Is it possible to restrict a single device login, if a user logs in from another device, can we invoke the previously granted access/refresh tokens? If yes, please advise.

**Which AWS Services are you utilizing?**

AWS Cognito

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by kvasukib** [comment]
@ali-mehmood-10p Can you provide more details on your issue, version of SDK and a code snippet?
