### ISSUE TITLE
 AWS Auth compatibility for API 22 and lower

### ISSUE THREAD

**Issue by anggrayudi** [aws-amplify/aws-sdk-android#590]
This issue is regarding to #471. It's been 6 month since I asked this feature request. I always open this github page everyday to see something new, but nothing changed. You still have no time to fix this compatibility issue on API 22 and lower. At least, you can make it for API 19. We developers are suffering to wait this feature.

I thought you have a big and great team, but I am wrong. "AWS SDK for Android Team" is slow and I think you will be lost with Firebase soon. People will move to Google Cloud (or Firebase) if this problem continues. Technology grows really fast. If your team lacks members, let me know. At least, tell us the reason behind it. Are you having trouble with Google, or other companies? We must be transparent. Don't give us a false hope.

**Comment by palpatim** [comment]
Thanks for your feedback @anggrayudi. I hear your frustration (as well as that expressed by others on #471. Unfortunately, although this remains in our feature request backlog, I don't have any update on a timeline for delivery.

I will re-open #471 so we can continue to gather community interest in this feature, to help us accurately prioritize it against other work on the SDK. In the meantime, I will close this issue so we can keep conversation consolidated on the main thread of discussion.
