### ISSUE TITLE
Encrypt CognitoIdentityProviderCache data

### ISSUE THREAD

**Issue by ejmsk** [aws-amplify/aws-sdk-android#598]
Currently the SDK stores information using android shared preferences without any type of encryption. Stored data includes: username, client id, access token, id token, refresh token, etc.
The class that manages this information doesn’t provide any option to encrypt the stored data or to avoid persisting it in the shared preferences.
This seems a big security concern for the android platform. I believe in iOS you are using the keystore to keep this data safe so why not do the same with android?

**Comment by minbi** [comment]
Hi @ejmsk ,

The SDK currently stores the listed information in the SharedPreferences with private mode. This will only allow applications that wrote the value to read it (unless root/mount the disk). The Android Keystore was introduced in API level 18 which is higher than the minimum (11) that is currently supported by our SDK, but we can look into making encryption available when the SDK is used on higher API levels.

Cognito does allow for global signout if you suspect that a session or its tokens have been compromised.

**Comment by kvasukib** [comment]
@ejmsk We have an update on this feature in `2.12.3` version of the SDK. Please read our [CHANGELOG](https://github.com/aws-amplify/aws-sdk-android/blob/master/CHANGELOG.md#release-2123) for further information. I would recommend you to do adequate testing with the new version of the SDK and let uw know if you have any feedback. Thank you for the patience.

**Comment by ejmsk** [comment]
Thanks for the update @kvasukib. Will test the new update in the next days.

**Comment by kvasukib** [comment]
Closing the issue. Please feel free to open a new one if you see any issues during your testing.
