### ISSUE TITLE
Chrome tab customization

### ISSUE THREAD

**Issue by rlatapy-luna** [aws-amplify/aws-sdk-android#605]
**Which AWS Services is the feature request for?**
Cognito Auth

**Is your feature request related to a problem? Please describe.**
Need to set toolbar color on chrome custom tab

**Describe the solution you'd like**
Add color setter or full builder, see https://github.com/rlatapy-luna/aws-sdk-android/commit/80a7d2607faeadffc779a20540cef71e0c535d63

**Comment by rohandubal** [comment]
Hello @rlatapy-luna 

Thanks for reaching out. Could you please open a PR to this repo so that we can look into it and merge it if all good?

Thanks,
Rohan

**Comment by rlatapy-luna** [comment]
Sure thank you https://github.com/aws-amplify/aws-sdk-android/pull/608

**Comment by minbi** [comment]
Closing this in favor of #608
