### ISSUE TITLE
How to logout from CognitoCachingCredentialsProvider?

### ISSUE THREAD

**Issue by rafagan** [aws-amplify/aws-sdk-android#610]
After call the methods `clearCredentials` and `clear`, the class still returns the credentials and identityId from session.

How can I make it logout successfully?

**Comment by minbi** [comment]
Hi @rafagan ,

Can you provide some information about your setup? If you have unauthenticated access enabled on your Cognito Identity Pool enabled, then the `CognitoCachingCredentialsProvider` will retrieve a guest session and provide guest credentials; this would happen after you clear the ones available from a signed-in session.

**Comment by rafagan** [comment]
Basically, when I logout using the two methods, the `CognitoCachingCredentialsProvider` maintains the identityId from previous session and the credentials too. And if I login in the sequence, it returns these old credentials even after login.
 
The only way I've found to make this work is restart the Android app at logout. This time, the API clear some weird cache in memory and starts working.

The unauthenticated access is currently disabled. If you have another tip or question, please ask and I'll provide the answer.

**Comment by minbi** [comment]
I would recommend trying `AWSMobileClient` documented [here](https://aws-amplify.github.io/docs/android/authentication). This is the new client that we are migrating users towards. It would be better if you are starting out to start there.

We have tests for the scenario you are experiencing and believe it wouldn't be a problem with the new client. [Test found here](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-mobile-client/src/androidTest/java/com/amazonaws/mobile/client/AWSMobileClientTest.java#L275)

**Comment by rafagan** [comment]
OMG... Days spending a lot of time in garbage and plain old code :(

At least, this documentation is one of the bests I have seen in AWS.

**Comment by muellerfr** [comment]
@rafagan, is the `AWSMobileClient` working for you?

**Comment by rafagan** [comment]
Actually I'll need to migrate soon, for now I need to delivery the product next week and stay with the awful bugs :/

**Comment by muellerfr** [comment]
Hi @rafagan, please go ahead and integrate with the 'AWSMobileClient', which is our recommended solution. If you are still encountering problems, please open another issue.
