### ISSUE TITLE
TransferService foreground promotion

### ISSUE THREAD

**Issue by pedrovarela86** [aws-amplify/aws-sdk-android#613]
**Is your feature request related to a problem? Please describe.**
Android Oreo+ has background restrictions, starting the transfer service from an app in background is not possible. Thus the service should be promoted within few seconds to foreground in order to continue running or the system will kill it.

**Describe the solution you'd like**
The transfer service must provides a way to promote it to foreground

**Describe alternatives you've considered**
I am going to extend transfer service

**Additional context**
NA

**Comment by kvasukib** [comment]
@pedrovarela86 The foreground feature is released in `2.11.0` version of the SDK. Please read our [CHANGELOG](https://github.com/aws-amplify/aws-sdk-android/blob/master/CHANGELOG.md#release-2110) and [Documentation](https://aws-amplify.github.io/docs/android/storage#supporting-transferservice-on-oreo-and-above) for detailed information on the change. We advise you to perform testing and understand the behavior before upgrading the SDK.
