### ISSUE TITLE
S3 TransferUtility: Transfers don't seem to resume after termination, are always included in list

### ISSUE THREAD

**Issue by hipwelljo** [aws-amplify/aws-sdk-android#618]
**Describe the bug**
In my app I have started an upload, then manually terminated the app, then reopened the app. In the `onResult` callback from `initialize` I can see there is 1 transfer in the list provided by `getTransfersWithType(UPLOAD)` and its state is `IN_PROGRESS`. I then call `resumeAllWithType(UPLOAD);`. I wait a long while then rerun the app and I see the transfer is still provided in the list of upload transfers and it has the same status. I expected it to resume and upload since I have a good internet connection, and no longer be included in the list of transfers on the next run. 

I was following along the SDK guide to implement resuming support. Perhaps I am missing something though. Currently I am not seeing any logs of state change, progress, or errors upon resuming the transfers. I am assuming though I need to set transfer listeners for these right (to monitor upload progress and state changes), or are they preserved from the previous session? Seems something else is wrong, even without listeners I would think it would upload upon resume.

**To Reproduce**
1. Start to upload a file
2. Force close the app from the recent apps screen before the upload completes
3. Rerun the app, triggering `resumeAllWithType(UPLOAD)`
4. Wait a long while giving it sufficient time to upload the file
5. Rerun the app and examine `getTransfersWithType(UPLOAD)`

**Which AWS service(s) are affected?**
S3 TransferUtility

**Expected behavior**
The transfer should have been resumed, successfully uploaded, and thus it shouldn't be in the list of transfers upon running again

**Environment:**
 - SDK Version: 2.9.0

**Device Information:**
 - Device: Google Pixel
 - Android Version: 7.1.2
 - Specific to simulators: No

**Code:**
To initialize and resume transfers in the startup activity's `onCreate`:
```
        AWSMobileClient.getInstance().initialize(getApplicationContext(), new Callback<UserStateDetails>() {
            @Override
            public void onResult(UserStateDetails result) {
                Log.d(TAG, "AWSMobileClient initialized. User State is " + result.getUserState());

                TransferUtility transferUtility =
                        TransferUtility.builder()
                                .context(getApplicationContext())
                                .awsConfiguration(AWSMobileClient.getInstance().getConfiguration())
                                .s3Client(new AmazonS3Client(AWSMobileClient.getInstance()))
                                .build();

                List<TransferObserver> observerList = transferUtility.getTransfersWithType(UPLOAD);
                //TODO: Need to set listeners?

                Log.d(TAG, "Upload transfers count: " + observerList.size());
                Log.d(TAG, "Upload transfers: " + observerList.toString());

                transferUtility.resumeAllWithType(UPLOAD);
            }

            @Override
            public void onError(Exception e) {
                Log.e(TAG, "Initialization error.", e);
            }
        });

        getApplicationContext().startService(new Intent(getApplicationContext(), TransferService.class));
```

To upload the file:
```
        TransferUtility transferUtility =
                TransferUtility.builder()
                        .context(context.getApplicationContext())
                        .awsConfiguration(AWSMobileClient.getInstance().getConfiguration())
                        .s3Client(new AmazonS3Client(AWSMobileClient.getInstance()))
                        .build();

        final String filename = "image_" + randomAlphaNumeric(10) + ".jpg";

        File file = scaleImage(uri, context.getCacheDir().getPath() + File.separator + filename);

        TransferObserver transferObserver = transferUtility.upload("bucketname", filename, file);
        transferObserver.setTransferListener(new TransferListener() {
            @Override
            public void onStateChanged(int id, TransferState state) {
                Log.d(TAG, "Upload state changed to " + state);
            }

            @Override
            public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                float percentDonef = ((float) bytesCurrent / (float) bytesTotal) * 100;
                int percentDone = (int)percentDonef;

                Log.d(TAG, "ID:" + id + " bytesCurrent: " + bytesCurrent
                        + " bytesTotal: " + bytesTotal + " " + percentDone + "%");
            }

            @Override
            public void onError(int id, Exception ex) {
                Log.e(TAG, ex);
            }
        });
```

**Logs:**
```
Upload transfers count: 1
Upload transfers: [TransferObserver{id=1, bucket='bucketname', key='image_jdvx8ewITz.jpg', bytesTotal=34094, bytesTransferred=0, transferState=IN_PROGRESS, filePath='/data/user/0/com.x.x/cache/image_jdvx8ewITz.jpg'}]```

**Comment by hipwelljo** [comment]
Thanks for the reply. Ok I added both in for safe measure and tried again. I force quit the app while a transfer was ongoing, reopened it and the following was logged:
```
AWSMobileClient initialized. User State is GUEST
Upload transfers count: 1
Upload transfers: [TransferObserver{id=1, bucket='bucketname', key='image_le5Ec6Tub5.jpg', bytesTotal=48392, bytesTransferred=48392, transferState=IN_PROGRESS, filePath='/data/data/com.mycompany.myapp/cache/cropped781448780.jpg'}]
Transfer ID: 1 ; Transfer State: IN_PROGRESS; Transfer Progress: 48392
```
The photo didn't resume uploading - no progress was reported, nothing else was logged. If I rerun the app that same transfer is included in the array.

**Comment by kvasukib** [comment]
@hipwelljo I'm seeing bytesTotal=48392, bytesTransferred=48392. So does this mean that the transfer completed, but the state changed callback is not yet triggered? Can you share the complete class/activity which is invoked when the app restarts?

**Comment by hipwelljo** [comment]
It looks like that one did upload successfully - it's in the s3 bucket. So it's strange it is still included in the list with an IN_PROGRESS state. I tried it again and force quit the app before it completed the transfer and here's the log for that upon reopening the app. No further logs appeared.
```
AWSMobileClient initialized. User State is SIGNED_OUT
Upload transfers count: 1
Upload transfers: [TransferObserver{id=1, bucket='bucketname', key='image_cWhYVSGbEP.jpg', bytesTotal=59381, bytesTransferred=0, transferState=IN_PROGRESS, filePath='/data/data/com.mycompany.myapp/cache/cropped781448780.jpg'}]
Transfer ID: 1 ; Transfer State: IN_PROGRESS; Transfer Progress: 0
```

**Comment by hipwelljo** [comment]
Here's that activity invoked when the app is opened.
```
public class SplashActivity extends AppCompatActivity {

    private static final String TAG = "SplashActivity";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        AWSMobileClient.getInstance().initialize(getApplicationContext(), new Callback<UserStateDetails>() {
            @Override
            public void onResult(UserStateDetails result) {
                DpsLog.d(TAG, "AWSMobileClient initialized. User State is " + result.getUserState());

                TransferUtility transferUtility =
                        TransferUtility.builder()
                                .context(getApplicationContext())
                                .awsConfiguration(AWSMobileClient.getInstance().getConfiguration())
                                .s3Client(new AmazonS3Client(AWSMobileClient.getInstance()))
                                .build();

                List<TransferObserver> observerList = transferUtility.getTransfersWithType(UPLOAD);

                DpsLog.d(TAG, "Upload transfers count: " + observerList.size());
                DpsLog.d(TAG, "Upload transfers: " + observerList.toString());

                transferUtility.resumeAllWithType(UPLOAD); //resume any uploads that were paused on app termination

                for (TransferObserver observer: observerList) {
                    observer.refresh();
                    DpsLog.d(TAG, "Transfer ID: " + observer.getId() + " ; Transfer State: " + observer.getState() + "; Transfer Progress: " + observer.getBytesTransferred());
                }

                //OR
                for (TransferObserver observer: observerList) {
                    observer.setTransferListener(new TransferListener() {
                        @Override
                        public void onStateChanged(int id, TransferState state) {
                            DpsLog.d(TAG, "Upload state changed to " + state);
                        }

                        @Override
                        public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                            float percentDonef = ((float) bytesCurrent / (float) bytesTotal) * 100;
                            int percentDone = (int)percentDonef;

                            DpsLog.d(TAG, "ID:" + id + " bytesCurrent: " + bytesCurrent
                                    + " bytesTotal: " + bytesTotal + " " + percentDone + "%");
                        }

                        @Override
                        public void onError(int id, Exception ex) {
                            DpsLog.e(TAG, ex);
                        }
                    });
                }
            }

            @Override
            public void onError(Exception e) {
                DpsLog.e(TAG, "Initialization error.", e);
            }
        });

        getApplicationContext().startService(new Intent(getApplicationContext(), TransferService.class));

        finish();
    }
```

**Comment by kvasukib** [comment]
@hipwelljo It's possible that the `TransferObserver` object has a stale state. Observer needs to be refreshed in order to get the accurate information. Can you do a `transferObserver.refresh()` before accessing any state in the observer? Did you get the `onStateChanged()` callback?

**Comment by hipwelljo** [comment]
Okay, I moved this block of code
```
for (TransferObserver observer: observerList) {
    observer.refresh();
    Log.d(TAG, "Transfer ID: " + observer.getId() + " ; Transfer State: " + observer.getState() + "; Transfer Progress: " + observer.getBytesTransferred());
}
```
immediately after `List<TransferObserver> observerList = transferUtility.getTransfersWithType(UPLOAD);`

and tried it again, but I get the same result. No, `onStateChanged()` is not triggered, no other info is logged from any of the listener callbacks.

**Comment by kvasukib** [comment]
@hipwelljo Can we get into a call so we can root cause the issue faster? You can drop me an email at: karthba at amazon dot com? We can discuss both the issues you have raised.

**Comment by hipwelljo** [comment]
That did the trick thanks! What do you think about the last paragraph?

I do see that failed transfers are included in this list upon relaunching the app. So I am resuming all of the previously failed transfers even though they were retried (and probably eventually succeeded). So now I have a lot of duplicate photos uploaded. Should I 'delete' a transfer before manually retrying it or what's the right thing to do here? Thanks!

**Comment by hipwelljo** [comment]
Hm this is tricky because when a transfer fails I start a new transfer to try it again, and the key/filename is not the same. So when I open the app the next time and go to resume uploads, if I look at the failed transfers none of them will exist in S3 by that key however it probably did succeed with a different key. Perhaps the logic can be changed to use the previous key. But I would like to avoid querying for the object metadata for each failed transfer too, since transfers could continually fail many times on repeat so there could be a lot of transfers in the failed state on the next app launch, and there may not be a good enough connection to determine if it exists or not.

I do see an API to `deleteTransferRecord()` by id. If I were to delete the failed transfer and then start a new transfer for that file, naively it seems that would solve this problem, do you see any harm in that?

**Comment by kvasukib** [comment]
@hipwelljo Yes, you can use `deleteTransferRecord` to remove the transfer record from the persistence store. I would test and see if it's working as this will leave an inconsistency in the state that is stored in memory vs disk.

**Comment by hipwelljo** [comment]
Testing has been going well with that in place, it's resuming the appropriate transfers on app relaunch. Is there a way to remove it from the in-memory store in addition to deleting from disk? Or otherwise mark this transfer as being 'completed' in that I'm not interested in keeping it around anymore.

**Comment by kvasukib** [comment]
@hipwelljo Thank you for confirming. I will check into the code and let you know about the in-memory state. Regardless, any inconsistency in the state is a bug and we should be tracking it.

**Comment by kvasukib** [comment]
Can you verify if you did the following?

```java
transferObserver =
                transferUtility.upload(
                        key,
                        tempFile);

        // Attach a listener to the observer to get state update and progress notifications
        transferObserver.setTransferListener( new TransferListener() {
            @Override
            public void onStateChanged(int id, TransferState state) {
                Log.i(LOG_TAG, "onStateChanged = " + state);

                if (TransferState.FAILED == state) {
                    transferObserver = transferUtility.resume(transferObserver.getId());
                    transferObserver.setTransferListener(this); // Setting to `this` may retry infinitely when the upload keeps failing. You can also set a brand new TransferListener object here.
                }
            }

            @Override
            public void onProgressChanged(int id, long bytesCurrent, long bytesTotal) {
                float percentDonef = ((float) bytesCurrent / (float) bytesTotal) * 100;
                int percentDone = (int)percentDonef;

                Log.i(LOG_TAG, "ID:" + id + " bytesCurrent: " + bytesCurrent
                        + " bytesTotal: " + bytesTotal + " " + percentDone + "%");
            }

            @Override
            public void onError(int id, Exception ex) {
                // Handle errors
                ex.printStackTrace();
            }
        });
```

**Comment by hipwelljo** [comment]
I only call `upload` for the original transfer request. I then attach a listener as you've shown. Then in `onStateChanged` I have:
```
if (state == TransferState.FAILED) {
    TransferUtility transferUtility = ...;
    TransferObserver newTransferObserver = transferUtility.resume(id);
    newTransferObserver.setTransferListener(new TransferListener() {
        //...
    }
}
```

The hope is `resume()` would start the upload transfer again but it does not seem to do that.

**Comment by kvasukib** [comment]
@hipwelljo If it's a single-part upload, resume and upload would do the same thing. Our granularity of restoration is 5MB, i.e TransferUtility will remember what is the last 5MB chunk that has been successfully uploaded to resume from that point. Did you try calling `upload` again and did that work?

**Comment by hipwelljo** [comment]
I have found that `resume()` does work if I wait a second to call it instead of immediately calling it in `onStateChanged`.
```
TransferListener listener = this;
new Handler().postDelayed(new Runnable() {
    @Override
    public void run() {
        Log.d(TAG, "Retrying photo upload for " + id);
        TransferUtility transferUtility = getTransferUtility(context);
        TransferObserver newTransferObserver = transferUtility.resume(id);
        newTransferObserver.setTransferListener(listener);
    }
}, 1000);
```

**Comment by kvasukib** [comment]
@hipwelljo I believe it's a race condition between the previous transfer for the same file that is terminating (success/failure/`onStateChanged`) and the new transfer that is being started. I am looking into the bug where there is an inconsistency in the callback being invoked.

**Comment by kvasukib** [comment]
@hipwelljo I have made some improvements to `TransferUtility` in `2.11.` and `2.12.0`. Can you upgrade and test and let me know if there is any feedback?

**Comment by hipwelljo** [comment]
Can confirm I am able to resume a failed transfer without the 1 second delay in 2.12.0. It seems this issue can be closed. Thanks!!
