### ISSUE TITLE
AutoReconnecting is not working

### ISSUE THREAD

**Issue by Akefhabbal** [aws-amplify/aws-sdk-android#620]
**Describe the bug**
The app couldn't reconnect to the Amazon after the connection come back again in the version 2.8.+
but it is working fine with the older version 2.7.+
**Which AWS service(s) are affected?**
I am using Android Pub/Sub example.

**Environment(please complete the following information):**
 - SDK Version: [2.8.+]

**Device Information (please complete the following information):**
 - Real Device and Emulator with API 17 and 22

**Comment by desokroshan** [comment]
@Akefhabbal Thanks for reporting the issue. This has been previously reported in [Issue#584](https://github.com/aws-amplify/aws-sdk-android/issues/584). We have released a fix for this in the version 2.9.1. Closing, please feel free to reopen if the issue still exists.
