### ISSUE TITLE
AWSMobileClient showSignIn is blocking android UI

### ISSUE THREAD

**Issue by CriPstian** [aws-amplify/aws-sdk-android#628]
Hello,

I encountered a situation that, it is not a bug, rather it is a documentation/naming issue in my opinion.
The `showSignIn` function from `AWSMobileClient` is blocking the UI and fails to load the sign in screen.

**Reason why I encountered this**
Since I already registered listeners on user's state changes, I did not need to have a callback to run when user finished signing in.
Because I previously used the other methods available, that did not block the UI, I tried this one with the following signature.
```Java
public UserStateDetails showSignIn(final Activity callingActivity) throws Exception
```

**What I suggest**
* Providing such a method, that does not require a callback, since we already registered listeners on the user's state.
* Naming of existing method could change to something easier to understand the behaviour (since it is rather different than the other overloads.

Thank you

**Comment by minbi** [comment]
Hi @CriPstian ,

I see how this can be confusing and the API does seem to be misbehaving. I will followup on this thread with some more investigation.

Overall, the methods that provide callbacks are initiating a background thread and running the associated code in the background and coming back through the callback. The methods that do not have a callback are calling the code on the current thread. This allows for developers to choose their own thread management either Thread, AsyncTask, some form of RxJava.

**Comment by minbi** [comment]
After investigating this issue, the synchronous method has an undesirable effect of blocking the UI thread if it is initiated on the UI thread. Then when the method tries to start manipulate the UI it is blocked. Therefore this method cannot be used on the UI thread like the other methods that have a callback version. I will add a note in the javadoc that the synchronous method must be used on a background thread.

The reasons from previous post still apply for providing this API.

**Comment by minbi** [comment]
Hi,

SDK release 2.12.7 address this issue. We have added the following enhancements:

>Annotated methods that are designed to be called from UI thread or from a background thread with `@AnyThread` and `@WorkerThread`, respectively

You may see all changes in the [changelog](https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md#release-2127)
