### ISSUE TITLE
Get SUB after sign-up but before first sign-in 

### ISSUE THREAD

**Issue by desokroshan** [aws-amplify/aws-sdk-android#635]
**Which AWS Services is the feature request for?**
Cognito

**Is your feature request related to a problem? Please describe.**
No

Add support in the SDK for returning cognito-generated SUB after a sign-up call and before first sign-in is done. SUB is present in the response from Cognito after a sign-up call is made. This feature was requested in the following stackoverflow post : 
https://stackoverflow.com/questions/53861141/how-to-get-sub-from-a-aws-cognito-token

**Comment by crj92** [comment]
Just following this, is there any update on this, Thanks in advance.

**Comment by natnaelw** [comment]
Any updates on this? was this feature added to cognito?

**Comment by desokroshan** [comment]
We will track this in https://github.com/aws-amplify/aws-sdk-android/issues/1041. Closing this as duplicate.
