### ISSUE TITLE
Where is UnlinkIdentity function?

### ISSUE THREAD

**Issue by KateLeeCandy** [aws-amplify/aws-sdk-android#645]
https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_UnlinkIdentity.html
We found UnlinkIdentity function in doc, but can not find it on current aws android sdk ( v2.10.1 ) 

Only found it before 2.2.0...but we want to implement the latest version.
https://abi-laboratory.pro/?view=compat_report&lang=java&l=aws-android-sdk-core&v1=2.1.10&v2=2.2.0&obj=a5bf7&kind=bin#Removed

**Comment by palpatim** [comment]
We're treating this as a bug. We'll update this thread when we have an update.

**Comment by palpatim** [comment]
We have a fix for this and are preparing it for an upcoming release.

**Comment by palpatim** [comment]
@KateLeeCandy 

This was released in [2.11.1](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.11.1). Thanks for bringing it to our attention!
