### ISSUE TITLE
TransferUtility video uploading percent above 100 % 

### ISSUE THREAD

**Issue by mukeshdadarwal** [aws-amplify/aws-sdk-android#667]
**Describe the bug**

**To Reproduce**

**Which AWS service(s) are affected?**

**Expected behavior**

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version:def aws_version = "2.11.+"

**Device Information (please complete the following information):**
 - Device: Samsung SM -J701F
 - Android Version: 7.1
 - Specific to simulators:

**Additional context**

**Comment by palpatim** [comment]
Assigning to @kvasukib to look at as part of the investigation into #611, if relevant.

**Comment by mukeshdadarwal** [comment]
> @mukeshdadarwal Sorry for the inconvenience caused.
> What is the version of the SDK you are using?
> What is the size of the file being uploaded?
> Does this happen when the transfer is interrupted and resumed and then eventually completes?
> Can you describe the scenario when you are noticing it?

SDk version is "2.11.+"
File size 632 MB
Yes transfer is interrupted 3 - 4 times and percent goes to 176%  
 total bytes => 663100390
bytesTransferred => 1167465446

**Comment by kvasukib** [comment]
@mukeshdadarwal Thank you for the quick response. I am currently working on the Progress reporting related issues in `TransferUtility`. I will track this issue as well.

**Comment by kvasukib** [comment]
@mukeshdadarwal This issue has been fixed in `2.11.1`. Please upgrade to the latest and let us know if it works.
