### ISSUE TITLE
Java 8 lambdas: Split c.a.m.c.Callback into SuccessCallback and FailureCallback

### ISSUE THREAD

**Issue by ghost** [aws-amplify/aws-sdk-android#672]
**Is your feature request related to a problem? Please describe.**
Unable to use lambdas for callbacks, forcing to create anonymous interface implementations.

**Describe the solution you'd like**
Create SuccessCallback and FailureCallback interfaces, and overload all methods that acccept Callback to also accept a pair of these

**Additional context**
This is to facilitate usage of lambdas instead of annoying anonymous classes

**Comment by cbommas** [comment]
@doom777 
Thank you for posting your feature request. I will discuss this with the team and update this thread once I have more information.

**Comment by richardmcclellan** [comment]
Great suggestion!    All of the APIs in the [Amplify Libraries](https://docs.amplify.aws/lib/q/platform/android) are designed this way, so I suggest migrating to Amplify.    This SDK is maintained with bug fixes and security updates, but we aren't adding any major new functionality in the SDKs, so we won't be updating the callbacks in this project.
