### ISSUE TITLE
When can a session token be invalid?

### ISSUE THREAD

**Issue by ukevgen** [aws-amplify/aws-sdk-android#678]
**When can a session token be invalid?**

**Cognito**

**Environment(please complete the following information):**
 - SDK Version: cognitoidentityprovider:2.11.0

I know that token is a live during an hour, but I have the next situation
![image](https://user-images.githubusercontent.com/17047537/51898556-ce629580-23b9-11e9-8ab6-d0e4929c7271.png)

How correctly we need to update token and in with cases?

**Comment by sunchunqiang** [comment]
Hi @ukevgen , You can use Refresh token  in this case. If you can provide some snip of your code, we can give you more advices.

**Comment by minbi** [comment]
Hi @ukevgen ,

Do you still require help on this issue? If so, please provide some more detail in your setup such as a code sample and use-case.

Generally, the id and access token expire after 1 hour from creation. You may request new tokens using the refresh token. The refresh token expiry is configured by your settings. If the refresh token has expired as well, then you will need the user to sign-in again.

If you have not already checked it out, please see `AWSMobileClient`. This client handles refreshing tokens when they expire and notifies you when the user needs to sign-in again. See [documentation](https://aws-amplify.github.io/docs/android/authentication)
