### ISSUE TITLE
aws-java-sdk - user sign in fails

### ISSUE THREAD

**Issue by AnandhiRaghuraman** [aws-amplify/aws-sdk-android#680]
I am using aws_java-sdk 1.11.360, I am able to sign up but sign in fails with this exception
Incorrect username or password. My Request Id is ID: 2be0b181-2450-11e9-a15b-3d35ecadad5f
I am using temporary password coded in my properties file to sign in and was receiving a challenge NEW_PASSWORD_REQUIRED, to which i responded with a new password.
The code was working fine for 3 users and then stopped working and started to throw above exception.
Now i deleted that user pool, identity pool and created new. But still not working. This problem was observed from 28th Jan 2019. 
my code:
	        Map<String,String> authParams = new HashMap<String,String>();
	        authParams.put(USERNAME, username);
	        authParams.put(PASSWORD, password);
	
	        AdminInitiateAuthRequest authRequest = new AdminInitiateAuthRequest()
	                .withAuthFlow(AuthFlowType.ADMIN_NO_SRP_AUTH)
	                .withAuthParameters(authParams)
	                .withClientId(cognitoConfig.getClientId())
	                .withUserPoolId(cognitoConfig.getUserPoolId());
	
	        AdminInitiateAuthResult authResponse = cognitoClient.adminInitiateAuth(authRequest);

fails and throws 
"Incorrect username or password. (Service: AWSCognitoIdentityProvider; Status Code: 400; Error Code: NotAuthorizedException; Request ID: cd861ea7-2460-11e9-9ffb-4782f5158535)",

**Comment by minbi** [comment]
Hi @AnandhiRaghuraman ,

We don't support the AWS Java SDK on the Android platform. However, I will check with the service team regarding these request ids.

**Comment by minbi** [comment]
Hi @AnandhiRaghuraman ,

The service team has followed up with a few insights and a few questions.
Insights:
- There may be an eventual consistency scenario here. Do you encounter the same exception if you delay the admin action until 30min to 1 hr after sign-up?
- Has the password expired? The default expiry is set for 7 days on sign-up.

Troubleshooting:
If the above still prevent you from having a successful call, can you provide another request id with a timestamp of when the request was made. And can you provide the region your pool is in?
