### ISSUE TITLE
Get versionID after Upload with TransferUtility

### ISSUE THREAD

**Issue by guillaume-tgl** [aws-amplify/aws-sdk-android#682]
**State your question**
I'm trying to migrate from `TransferManager` to `TransferUtility` but I can't see a way to get the result versionId after uploading a file. With `TransferManager`, I would simply get it from the `UploadResult` but there is no such thing with `TransferUtility`. How can I get this versionId after an Upload?

**Which AWS Services are you utilizing?**
S3

**Environment(please complete the following information):**
 - SDK Version: 2.6.31

**Comment by sunchunqiang** [comment]
Currently, it is not possible to retrieve versionId using TransferUtility. You can have to  use AmazonS3Client.putObject  or TransferManager to upload a file and get versionId

**Comment by kvasukib** [comment]
@guillaume-tgl Sorry for the inconvenience caused. TransferUtility doesn't return the `PutObjectResult` or the `UploadPartResult` objects that are returned from the upload operations (`putObject` or `uploadPart`). I will take this request to the team and see if we can support this or not.

Meanwhile, one way I could think of is to use `listVersion` in `AmazonS3Client`.

```java
            // Retrieve the list of versions. If the bucket contains more versions
            // than the specified maximum number of results, Amazon S3 returns
            // one page of results per request.
            ListVersionsRequest request = new ListVersionsRequest()
                .withBucketName(bucketName)
                .withMaxResults(2);
            VersionListing versionListing = s3Client.listVersions(request); 
            int numVersions = 0, numPages = 0;
            while(true) {
                numPages++;
                for (S3VersionSummary objectSummary : 
                    versionListing.getVersionSummaries()) {
                    System.out.printf("Retrieved object %s, version %s\n", 
                                            objectSummary.getKey(), 
                                            objectSummary.getVersionId());
                    numVersions++;
                }
                // Check whether there are more pages of versions to retrieve. If
                // there are, retrieve them. Otherwise, exit the loop.
                if(versionListing.isTruncated()) {
                    versionListing = s3Client.listNextBatchOfVersions(versionListing);
                }
                else {
                    break;
                }
            }
            System.out.println(numVersions + " object versions retrieved in " + numPages + " pages");
```

What is the use-case you are trying to solve by getting the versionId of the object uploaded?

**Comment by guillaume-tgl** [comment]
Thanks for your answers. We will finally avoid using `TransferUtility` since we don't need most of its features and keep using `TransferManager`. We use the `versionId` because we store some metadata about the file on our API and we want to make sure our API is pointing to the right version of the file on S3.

**Comment by minbi** [comment]
Hi @guillaume-tgl ,

The TransferManager is deprecated and we are planning on removing it at some point in the future. 
It would be valuable to us to prioritize migrating missing functionality into the TransferUtility. Are there any other features that you are currently using that you know are missing?

**Comment by guillaume-tgl** [comment]
Yes, another feature I would really like has already been asked: #291 
With `TransferManager`, I currently make a PUT request synchronously in my own background thread with the following code:
```
UploadResult result = transferManager.upload(request).waitForUploadResult();
```

But there doesn't seem to be an equivalent with `TransferUtility`.
