### ISSUE TITLE
AWS Cognito Token Refresh in iOS and Android

### ISSUE THREAD

**Issue by Kuppa** [aws-amplify/aws-sdk-android#683]
Hi Team,
I am using aws cognitoidentityprovider sdk v2.8 in my andorid application and I got the token expired after 1 hour. I tried to find the documentation to refresh the token in background but I couldn't. 
Can you please share me the document or function to refresh the token in Android and iOS?

**Comment by xanscale** [comment]
same problem. 

in theory just call `getCurrentUser().getSession` and if needed is ask refresh but actually fail by

```
W/System.err: com.amazonaws.mobileconnectors.cognitoidentityprovider.exceptions.CognitoInternalErrorException: Failed to authenticate user
W/System.err:     at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getCachedSession(CognitoUser.java:859)
W/System.err:     at com.amazonaws.mobileconnectors.cognitoidentityprovider.CognitoUser.getSession(CognitoUser.java:742)
```

**Comment by sunchunqiang** [comment]
Hi @Kuppa  
From v2.8,  we have launched a new `AWSMobileClient`, which will work with Cognito Userpools and provides methods like `getTokens()` which will automatically attempt to refresh the token then retrieving.
A full details can be found in [Documentation](https://aws-amplify.github.io/docs/android/authentication)

**Comment by sunchunqiang** [comment]
Hi @xanscale 
Is it caused by that the refresh token is expired? How long is your refresh token expiration?

**Comment by Kuppa** [comment]
> Hi @Kuppa
> From v2.8, we have launched a new `AWSMobileClient`, which will work with Cognito Userpools and provides methods like `getTokens()` which will automatically attempt to refresh the token then retrieving.
> A full details can be found in [Documentation](https://aws-amplify.github.io/docs/android/authentication)

Hi @sunchunqiang Thanks for the quick response. But currently I am not using the AWSMobileClient for my Android application. I am using the below gradle dependency '    implementation 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.8.+''. With this aws sdk, is there any way to get the refresh token by running background service in the app?

Please do needful...

**Comment by xanscale** [comment]
@sunchunqiang i found the problem, but i do not explain this.

[here](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html#amazon-cognito-user-pools-using-the-refresh-token) we can read:

> The Mobile SDK for iOS and the Mobile SDK for Android automatically refresh your ID and access tokens if there is a valid (non-expired) refresh token present, **and the ID and access tokens have a minimum remaining validity of 5 minutes**. If the refresh token is expired, your app user must reauthenticate by signing in again to your user pool.

so, base on 1 hour duration of access/ID token if user do not use app al least 1 time for hour, i cant refresh anymore.

WHY????

PS pls be quick, we found this anomaly 2 days before delivery

**Comment by minbi** [comment]
Hi @xanscale ,

Thanks for diving into this issue. We will add this to our tasks.

**Comment by minbi** [comment]
We added annotations to specify which thread to call the corresponding methods on in SDK release 2.12.7. Thanks for the report.
