### ISSUE TITLE
Attempt to call signOut may lead to NPE

### ISSUE THREAD

**Issue by andrey-chorniy** [aws-amplify/aws-sdk-android#691]
**Describe the bug**
App receives notification and attempts to call `signOut` on `AWSMobileClient` which was not initialized before.

**To Reproduce**
Try to call `AWSMobileClient.getInstance().signOut()` on AWSMobileClient which is not yet initialized
In our case app get PushNotification (in `FirebaseMessagingService`) and as a reaction to it should signOut current user. But as long `AwsMobileClient` was not initialized at this point (application wakes up from notification)
Exception is thrown: 
```
java.lang.NullPointerException: 
  at com.amazonaws.mobile.client.AWSMobileClient.signOut (AWSMobileClient.java:828)
```

**Which AWS service(s) are affected?**
AwsMobileClient

**Expected behavior**
We expect that `AwsMobileClient` should not fail in that case, since we actually want to sign-out and not going to use it after that. 

**Environment(please complete the following information):**
- SDK Version: 2.10.1

**Device Information (please complete the following information):**
- Device: [Samsung SM-J710FN, Xiaomi Mi5s]
- Android Version: [7.0, 8.0]

**Comment by minbi** [comment]
Hi @andrey-chorniy ,

We can investigate making the sign-out independent of initialization. However, without initializing the client, the sign-out may be faulty and not clear the correct credentials from the client.

**Comment by markorakita** [comment]
@minbi Could you please at least provide us with some way to check if AWSMobileClient is initialized so we don't need to do try/catch on AWSMobileClient.getInstance().signOut()?

**Comment by minbi** [comment]
Hi @markorakita ,

I will discuss with the team about adding this method. For the time being, a side-effect of initialization is that the AWSConfiguration object is set. So, `AWSMobileClient.getInstance().getConfiguration()` being null would be an indicator it is not initialized.

**Comment by markorakita** [comment]
Great, thank you for the tip @minbi !

**Comment by raphkim** [comment]
Hello, this issue appears to be stale and outdated. Please feel free to reopen this issue if you feel that your issue has not been sufficiently addressed.
