### ISSUE TITLE
Getting Invalid Grant Error Social Sign Up 

### ISSUE THREAD

**Issue by faizanmirza** [aws-amplify/aws-sdk-android#695]
1) Facing issue when signing up with new user on social sign up using federated identities. When user create a new facebook/google user on web page on custom tab using aws congito auth library, the sdk do not register new user instead return "Invalid Grant" Error. Please note that user is created on facebook but not with aws cause of the error.

2) If user put app in background or switch to another app, custom tab is close. Due to which sign up process is incomplete. A case i encounter is when user view verification code of google on message app and when come back to login page to enter it, it was closed so unable to sign up every time. 

3) Sign Up with new facebook user, login on facebook with it using custom tab, error returns "Invaild request"

Testing it on latest android device with sdk version 2.6.20.

**Comment by kvasukib** [comment]
@faizanmirza Thank you for reporting to us. I am looking into the issue. I will have an update soon.

**Comment by minbi** [comment]
1. Do you have a client secret enabled? If so, have you passed it into the client?
