### ISSUE TITLE
[S3] How to set a custom endpoint?

### ISSUE THREAD

**Issue by LittleHans8** [aws-amplify/aws-sdk-android#699]
**State your question**

In Java for intance, we have the following which works:
```
AWSCredentials credentials = new BasicAWSCredentials(
            "YourAccessKeyID",
            "YourSecretAccessKey");
    AmazonS3 s3client = new AmazonS3Client(credentials);
    s3client.setEndpoint("http://someendpoing.com");
```
Can I do the same in AWSS3 Android?

**Which AWS Services are you utilizing?**
S3

**Environment(please complete the following information):**
 - SDK Version: 2.12.0

**Device Information (please complete the following information):**
 - Device: Pixel XL
 - Android Version: Nougat 7.1.2

**Comment by kvasukib** [comment]
@LittleHans8 Thank you for reporting to us. Yes, it is possible to do the same through the `AmazonS3Client` in `aws-android-sdk-s3`. 

For example:

```java
AWSCredentials awsCredentials = new BasicAWSCredentials("access-key", "secret-access-key");
AmazonS3 s3Client = new AmazonS3Client(awsCredentials));
s3Client.setEndpoint("endpoint");
```

However I advise you to do the following:

1) Embedding access key and secret access key that are long-lived in the mobile app is not secure. Instead, you could use Amazon Cognito Identities to retrieve a set of short-lived temporary credentials from Cognito based on an identity pool-id. 

2) Why do you need to set an endpoint? `AmazonS3Client` accepts the region as a parameter and uses it to form the endpoint to connect to. If you need acceleration enabled endpoint, you could pass acceleration-enabled as an option to `AmazonS3Client`. In short, the SDK takes care of forming the endpoint.

```java
AWSCredentialsProvider awsCredentialsProvider = new CognitoCachingCredentialsProvider(getApplicationContext(), "identity-pool-id", Regions.US_WEST_2);
        AmazonS3 s3Client = new AmazonS3Client(awsCredentialsProvider, Region.getRegion(Regions.US_WEST_2));
```

Let me know if you have any questions.
