### ISSUE TITLE
Dx Warnings

### ISSUE THREAD

**Issue by vivekkiran** [aws-amplify/aws-sdk-android#7]
Dx warning: Ignoring InnerClasses attribute for an anonymous inner class
(com.amazonaws.javax.xml.stream.xerces.util.SecuritySupport12$4) that doesn't come with an
associated EnclosingMethod attribute. This class was probably produced by a
compiler that did not target the modern .class file format. The recommended
solution is to recompile the class from source, using an up-to-date compiler
and without specifying any "-target" type options. The consequence of ignoring
this warning is that reflective operations on this class will incorrectly
indicate that it is _not_ an inner class.

**Comment by aldevet** [comment]
Is there any updates on this?
