### ISSUE TITLE
Identify User uniquely without signing in

### ISSUE THREAD

**Issue by ZYHZ100** [aws-amplify/aws-sdk-android#708]
**State your question**
Can anyone help me with this question?
Is there any method using cognito user pool without signing in process?

**Which AWS Services are you utilizing?**
cognito user pool 

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by ZYHZ100** [comment]
without signing in process. Sorry for misspelling

**Comment by kvasukib** [comment]
@ZYHZ100 Thank you for reporting to us. We are looking into the issue.

**Comment by kvasukib** [comment]
@ZYHZ100 Can you describe your use-case? Are you trying to identify the user who has just signed up but not signed in yet through the app?

**Comment by ZYHZ100** [comment]
@kvasukib 
Hi, I want to identify users who use this app in this phone without signing up and signing in which means that user pools just will not collect user information.
After thinking alternative solutions for a while, can it realize by using DynamoDB or using UUID of android? of android?

**Comment by supreme96** [comment]
@ZYHZ100 maybe you would want to look into using Cognito Identity Pools. It allows your guest users to have unauthenticated identities (https://docs.aws.amazon.com/cognito/latest/developerguide/identity-pools.html#enable-or-disable-unauthenticated-identities).

**Comment by muellerfr** [comment]
@ZYHZ100 You are correct. You can  generate UUID and then register that with your device details in DynamoDB, or you could also use Pinpoint, which generates a UUID for each device.
