### ISSUE TITLE
[S3] How to specify the type of network connection in TransferUtility

### ISSUE THREAD

**Issue by ZYHZ100** [aws-amplify/aws-sdk-android#709]
**State your question**

I want to ask when transfer utility is interrupted when there is no network and then it will resume when there is network connected. Can I specify the wifi not data? Thank you~

**Which AWS Services are you utilizing?**

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by kvasukib** [comment]
@ZYHZ100 Thank you for reporting to us. Yes, this is possible with specifying the type of network connection that can be used to connect to Amazon S3. This feature was introduced in `2.11.0`. 

See [CHANGELOG](https://github.com/aws-amplify/aws-sdk-android/blob/master/CHANGELOG.md#release-2111) for the release notes on this feature.

TransferNetworkConnectionType.ANY >>> Any network 
TransferNetworkConnectionType.WIFI >>> Wifi only
TransferNetworkConnectionType.MOBILE >>> Mobile Data only

```java
            TransferUtilityOptions transferUtilityOptions = new TransferUtilityOptions(
                    <num-of-threads>,
                    TransferNetworkConnectionType.WIFI);
            TransferUtility transferUtility = TransferUtility.builder()
                    .context(getApplicationContext())
                    .s3Client(new AmazonS3Client(credentialsProvider, region))
                    .awsConfiguration(new AWSConfiguration(getApplicationContext()))
                    .transferUtilityOptions(transferUtilityOptions)
                    .build();
```
