### ISSUE TITLE
How protect PoolId in awsconfiguration.json?

### ISSUE THREAD

**Issue by luych888** [aws-amplify/aws-sdk-android#711]
**State your question**
Hi Team:

I'm app developer and use polly android sdk.
I have a question, when I write my PolId in awsconfiguration.json in "raw" folder, after I release my app, other user just need unzip my apk and get my PolId in  awsconfiguration.json, if he use my PolId in his app, I will pay for him, so how can I protect my PolId？

Expect your replay!

Best Regards!
Lu
**Which AWS Services are you utilizing?**
Polly
**Provide code snippets (if applicable)**
```
{
  "Version": "1.0",
  "IdentityManager": {
    "Default": {}
  },
  "CredentialsProvider": {
    "CognitoIdentity": {
      "Default": {
        "PoolId": "us-west-2:XXXX",
        "Region": "us-west-2"
      }
    }
  }
}
```
**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]

  aws_version = "2.12.+"

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators:

HUAWEI P20 Pro

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by kvasukib** [comment]
@luych888 Thank you for reporting to us. We are discussing this issue internally with the team. I will post an update here when I have more information.

**Comment by luych888** [comment]
Hi Kvasukib:

Thanks for your investigating this issue.
Any update?

Best Regards!
Yongchun Lu

**Comment by kvasukib** [comment]
@luych888 Sorry for the delayed response. I am currently working on this and will provide an update soon.

**Comment by kvasukib** [comment]
@luych888 I have submitted a PR #1002 to allow passing a `JSONObject` containing the configuration from the `awsconfiguration.json` file. You can store the information in JSONObject in your own secure mechanism and provide it at runtime through the constructor.

**Comment by kvasukib** [comment]
@luych888 The fix to add a new constructor has been released in `2.13.6` version of the SDK. Please upgrade and let us know if it solves your problem.

**Comment by luych888** [comment]
Dear Kvasukib,

Thank you so much!

We will try it as soon as possible!

Best Regards!
Yongchun Lu

**Comment by luych888** [comment]
Dear Kvasukib，

The solution is work， please help close this issue！

Thanks again~
