### ISSUE TITLE
Accelerate Mode Enabled to video not upload in only nokia 

### ISSUE THREAD

**Issue by mukeshdadarwal** [aws-amplify/aws-sdk-android#712]
**Describe the bug**
Accelerate Mode Enabled to video not upload in android

aws_version 2.11.+

 - 2.11.+
 - Nokia 6.1 
 - Android Version: Pie 9.0

**Additional context**
video not upload a particular WiFi network if i change WiFi network uploading start

**Comment by sunchunqiang** [comment]
Hi @mukeshdadarwal 
Can you give more detail on how to reproduce the issue?  Are you using S3 to upload the video? Does accelerate Mode mean  Amazon S3 Transfer Acceleration? Can the issue be reproduced if accelerate Mode is disabled?

**Comment by mukeshdadarwal** [comment]
Yes i'm using S3 to upload 
Amazon S3 Transfer Acceleration  Enable to video not upload a particular WiFi network if i change WiFi network uploading start in same device

**Comment by sunchunqiang** [comment]
Hi @mukeshdadarwal 
Should I reproduce your issue with below steps
1. enable Transfer Acceleration for a  S3 bucket
2. turn off WiFi network 
3. start app to upload files to the S3 bucket
4. turn on WiFi network
5. check the files can be uploaded to the S3 bucket. 
My another question is  Can the issue be reproduced if accelerate Mode is disabled?

**Comment by mukeshdadarwal** [comment]
1. Already  enable Transfer Acceleration on  S3 bucket
2. Yes i follow your all step but can't upload video 

 My another question is  if the issue is reproduced when accelerate Mode is disabled?
Ans.=>  accelerate Mode is disabled to video upload properly.


this issue only occurred only single device and particular WiFi network  if i change WiFi video upload properly in case of Transfer Acceleration enable or  disabled both mode. 

i'm using your s3 transfer utility sample code but can't upload

**Comment by kvasukib** [comment]
@mukeshdadarwal I would recommend you to check your network settings and firewall policies? When you enable transfer acceleration from the client side, the SDK sends request to a different endpoint. Can you check if your network policies block requests to certain endpoints?
