### ISSUE TITLE
Wrong exception type when resetting password for unconfirmed user

### ISSUE THREAD

**Issue by markorakita** [aws-amplify/aws-sdk-android#713]
**Describe the bug**
When AWSMobileClient.getInstance().forgotPassword() is called for user who is not confirmed, instead of UserNotConfirmedException we get InvalidParameterException. All the other auth functions are returning UserNotConfirmedException in such case, so this is bug in my opinion.

**To Reproduce**
- Finish AWSMobileClient.getInstance().signUp() for some username and password
- Skip the AWSMobileClient.getInstance().confirmSignUp() step
- Call the AWSMobileClient.getInstance().forgotPassword() with that username

**Which AWS service(s) are affected?**
com.amazonaws.mobile.client

**Expected behavior**
Expected behavior is UserNotConfirmedException to be thrown. With InvalidParameterException we have to parse error message in order to figure out if it was unconfirmed user, or some other parameter issue, and parsing error messages is pretty much unreliable and frowned upon.

**Screenshots**
Here is exception that is being thrown:
![image](https://user-images.githubusercontent.com/25534110/53028260-cfda2780-3466-11e9-9132-70d260e73381.png)

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.11.0
 - Device: Any
 - Android Version: 9
 - Specific to simulators: No

**Additional context**
Only calling AWSMobileClient API, not using AWS Auth UI.

**Comment by minbi** [comment]
HI @markorakita ,

This may be an eventual consistency issue with the service. I can follow up with the service team. Can you provide the follow?

1. Cognito region
2. request id
3. timestamp of the request

I do see a request id in the screenshot, you could provide the hour of day that you got the exception and the region you are using.

**Comment by minbi** [comment]
The technical reason for InvalidParameterException is because the user is considered a parameter in this API because forgotPassword does not require the user to be signed-in to be able to use.

The difference with UserNotConfirmedException is that the user is confirmed at this point, but the email/phone required for password reset is not verified.

Please let me know if this satisfies the request or if there is any other justifications I can convey to the service team to be more convincing.

**Comment by markorakita** [comment]
@minbi Thanks for checking with the service team! Let me try to give some more context on this issue.

Please notice inconsistency between next two cases:
- If you call **AWSMobileClient.getInstance().signIn()** function with invalid username you will get **UserNotFoundException**. If you call it with valid username which was not yet confirmed, you will get **UserNotConfirmedException**.
- If you call **AWSMobileClient.getInstance().forgotPassword()** function with invalid username you will get **UserNotFoundException**. If you call it with valid username which was not yet confirmed, you will get **InvalidParameterException**.

Both functions do not require you to be signed-in to be able to use, both functions react to the case when user is existing but not yet verified, they react with different exception.

If forgotPassword() was throwing **InvalidParameterException** in both cases when username is invalid or when it is not verified user, than I would understand their line of reasoning. But this way it is totally inconsistent. Why not throw proper exception when you already have it and when you are doing it for the case of invalid user? Why require of developers to dig in into exception message to parse the proper cause of exception when you already have a proper exception class to use?

**Comment by minbi** [comment]
I have relayed this request to the service team and will update when I hear back.

**Comment by minbi** [comment]
Hi @markorakita ,

We will not be able to change to the service since this would be a breaking change for the current customers who may already have the logic you referenced deployed. We will make note of this case for future client development.

**Comment by markorakita** [comment]
I understand, thank you for discussing this with the service team @minbi !
