### ISSUE TITLE
Can DynamoDB primary key be automatically setted and returned after inserting a new item with primary key "null"?

### ISSUE THREAD

**Issue by ZYHZ100** [aws-amplify/aws-sdk-android#714]
**State your question**

can DynamoDB primary key be automatically setted and returned after inserting a new item with primary key "null"?

Just like the int primary key with auto-increment in MySQL ?
 
**Which AWS Services are you utilizing?**

**Provide code snippets (if applicable)**

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.25]

**Device Information (please complete the following information):**
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators:

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by ZYHZ100** [comment]
I am wondering what if when app is connecting to DynamoDB and inserting data, network is interrupted? Thank you very much?

**Comment by minbi** [comment]
Hi @ZYHZ100 ,

Amazon DynamoDB does not support this natively. However, if you use a service like AWS AppSync in front of DynamoDB, AppSync does have an auto-id feature that will generate a unique id for each item.

If the network is interrupted during an insert you will need to retry the request when network is available. AWS AppSync clients have the ability to persist the request and retry once online.

**Comment by ZYHZ100** [comment]
@minbi Hi, thank you! Is there related tutorial or sample which I can refer to?

**Comment by minbi** [comment]
The docs should walk you through some basic use cases https://aws-amplify.github.io/docs/android/api

**Comment by muellerfr** [comment]
@ZYHZ100 - Looks like the issue has been resolved. If you still need help, please open another issue.
