### ISSUE TITLE
AWSMobileClient change password always return onError even if change password result is success.

### ISSUE THREAD

**Issue by HayTran94** [aws-amplify/aws-sdk-android#716]
**Describe the bug**
Use AWSMobileClient to change password, it always return onError even if new password is applied (changing password is success). In this case, the received exception is null object.

**To Reproduce**
```
AWSMobileClient.getInstance().changePassword(oldPassword, proposedPassword, new Callback<Void>() {
            @Override
            public void onResult(Void result) {
                // Never be called, even if changing password is success.
            }
            @Override
            public void onError(Exception e) {
               // Always called, even if change password is success.
            }
        });

```
**Which AWS service(s) are affected?**
AWSMobileClient

**Expected behavior**
When changing password is success, onResult should be called properly.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version:  2.12.0
 - Device: Motorola Z Play (XT1635-02)
 - Android Version: 8.0.0

**Comment by minbi** [comment]
Hi @HayTran94 ,

Thanks you for the report, we will fix this in an upcoming release

**Comment by minbi** [comment]
Hi @HayTran94 ,

Please see if SDK release 2.12.1 fixes this issue for you.

**Comment by HayTran94** [comment]
OK, the SDK 2.12.1 fixed my issue. Thank you for your quickly support. Love the team!
