### ISSUE TITLE
Manifest merger failed : uses-sdk:minSdkVersion 21 cannot be smaller than version 23 declared in library

### ISSUE THREAD

**Issue by aslamhossin** [aws-amplify/aws-sdk-android#737]
For the AWSMobileClient alone you can have a minimum SDK version of 15, but for the drop-in UI you will need a minimum of 23 set in your build.gradle:
I wanna know what is the reason for what min SDK  is 23?

**Comment by desokroshan** [comment]
@aslamhossin Thanks for reaching out. We already have an [issue](https://github.com/aws-amplify/aws-sdk-android/issues/471) tracking request to reduce the minSdkVersion for using drop-in UI. Please feel free to upvote the issue to help up prioritize it accordingly.
