### ISSUE TITLE
Support for multiple topic subscription in one single subscribe call

### ISSUE THREAD

**Issue by bxpan** [aws-amplify/aws-sdk-android#747]
**Which AWS Services is the feature request for?**
AWS IoT

**Is your feature request related to a problem? Please describe.**
Currently, there's no API to subscribe multiple mqtt topic in one single subscribe call, even though the underlining paho mqtt does support multiple topic subscription.
https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-iot/src/main/java/com/amazonaws/mobileconnectors/iot/AWSIotMqttManager.java#L1084

**Describe the solution you'd like**
Expose a new API in the SDK to call the API in paho mqtt implementation that takes an array of topics as argument. 
https://github.com/eclipse/paho.mqtt.java/blob/master/org.eclipse.paho.client.mqttv3/src/main/java/org/eclipse/paho/client/mqttv3/IMqttAsyncClient.java#L537

**Describe alternatives you've considered**
A workaround is for the user of the SDK to call the subscribe API multiple times, once for each topic subscription. The drawback is that instead of one mqtt message going out to the mqtt server, multiple mqtt subscribe messages are sent.

**Additional context**

**Comment by hectomg** [comment]
This is currently supported. This should be closed.

Regards

**Comment by trycatchx** [comment]
currently "subscribeToTopic" is not support "String[] topic"

@hectomg
