### ISSUE TITLE
Wait for PUBACK from APP client before sending PUBACK to AWS IoT

### ISSUE THREAD

**Issue by bxpan** [aws-amplify/aws-sdk-android#749]
**Which AWS Services is the feature request for?**
AWS IoT

**Is your feature request related to a problem? Please describe.**
Currently, the SDK sends PUBACK immediately back to AWS IoT after receiving a publish message from AWS IoT. As a result, the application does not have any control to send the PUBACK only after the received publish message is successfully handled

**Describe the solution you'd like**
Delay sending the PUBACK in the SDK , until the app has confirmed the receiving and processing of the publish message.  Provide an API which the app can call after it has received the publish message, and the SDK can then sends the PUBACK back to AWS IoT.

**Comment by sktimalsina** [comment]
Apologies for very late response. Technically, as the underlying library implements `MqttCallback` interface and the `PUBACK` is sent only when its `messageArrived` callback is returned, you can process the message before returning from the callback. However, it is not recommended as the MQTT client calls synchronously. Additionally, any new messages are still permitted to arrive while waiting for `PUBACK`. This will build a back up in memory and in network. 
Hence, it is ideal to use `PUBACK` to just Acknowledge the receipt of the message not the additional processing which can be vaguely large.

Closing the ticket for now.
