### ISSUE TITLE
Documentation for aws-android-sdk-sns

### ISSUE THREAD

**Issue by PDACN** [aws-amplify/aws-sdk-android#751]
Hi,
in [Amplify Android Docs](https://aws-amplify.github.io/docs/android/start) I can't find documentation about **aws-android-sdk-sns** 
can you provide this documentation?

([Amplify Android Docs](https://aws-amplify.github.io/docs/android/start) don't provide documentation for more AWS libraries contained in [aws-sdk-android](https://github.com/aws-amplify/aws-sdk-android))

Thank you

**Comment by desokroshan** [comment]
@PDACN Thank you reaching out. We do not have documentation for every SDK module in the repository. You can however refer to the [SNS API reference](https://aws-amplify.github.io/aws-sdk-android/docs/reference/com/amazonaws/services/sns/package-summary.html) for the different APIs that the service exposes. You can also look at the [SNS integration tests](https://github.com/aws-amplify/aws-sdk-android/tree/master/aws-android-sdk-sns-test/src/androidTest/java/com/amazonaws) for samples usages of those APIs.
