### ISSUE TITLE
AWS S3 uploaded files not showing

### ISSUE THREAD

**Issue by svvashishtha** [aws-amplify/aws-sdk-android#758]
**Describe the bug**
I have a background task that uploads text files to s3 bucket. Recently some of the files that were uploaded on the s3 bucket are not visible on the management console. 

**To Reproduce**
Unable to reproduce in test environment. This happened with our production application.

**Code to upload files**
```
final TransferObserver observer = s3Utils.getTransferUtility().
                            upload(Constants.BUCKET_NAME,
                                    destination[0],
                                    compressedFile);
                    observer.setTransferListener(new TransferListener() {
                        @Override
                        public void onStateChanged(int i, @NonNull TransferState transferState) {
                            if (transferState.equals(TransferState.IN_PROGRESS)) {
                                Log.d(SYNC_TAG, "file upload in progress " +
                                        observer.getAbsoluteFilePath());
                            } else if (transferState.equals(TransferState.FAILED) ||
                                    transferState.equals(TransferState.WAITING_FOR_NETWORK)) {
                                HashMap<String, String> customEventAttrs = new HashMap<>();
                                customEventAttrs.put(AppConstants.FabricEventsConstants.REASON, "TransferState = " +
                                        transferState.name());
                                AnswersLogger.logEventToAnswer(AppConstants.
                                        FabricEventsConstants.FILE_UPLOAD_FAILED, customEventAttrs);
                                s3Utils.getTransferUtility().cancel(i);
                            } else if (transferState.equals(TransferState.COMPLETED)) {
                                Log.d(SYNC_TAG, "upload complete");
                               //start doing other things here
                            }
                        }

                        @Override
                        public void onProgressChanged(int i, long l, long l1) {
                            Log.d(SYNC_TAG, "progress: " + i + " " + l + " " + l1);
                        }

                        @Override
                        public void onError(int i, @NonNull Exception e) {
                            HashMap<String, String> customEventAttrs = new HashMap<>();
                            customEventAttrs.put(AppConstants.FabricEventsConstants.REASON, e.getMessage());
                            AnswersLogger.logEventToAnswer(AppConstants.
                                    FabricEventsConstants.FILE_UPLOAD_FAILED, customEventAttrs);
                        }
                    });
```

**Which AWS service(s) are affected?**
S3
**Expected behavior**
Uploaded files should be visible on management console.

**Screenshots**
Not applicable.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.10.0
 - Device: One plus 5T
 - Android Version: 8
 - Specific to simulators: No

**Comment by kvasukib** [comment]
@svvashishtha Sorry for the inconvenience caused.

Do you have any data on the files that are missing on the S3 Management console?
Is there a correlation among the files that are missing? Like size of the file, content-type of the file, name of the file, name of the key?

Also, do you see state and progress updates for the transfers in your app? If you can pull the logs from the app where the issue is reproduced, can you see if the transfer succeeded with state `TransferState.COMPLETED`?

**Comment by svvashishtha** [comment]
@kvasukib All files are text files. The only correlation between files is that they were uploaded in a single run of the service that uploads files to s3.
Transfer succeeded with state TransferState.COMPLETED because the step after uploading files(acknowledging file upload to our server via a REST API call) was executed for all of these files.

**Comment by kvasukib** [comment]
@svvashishtha Thank you for the quick response. Can you check if the object exists using `s3Client.doesObjectExist(bucketName, key)` after you get the state `TransferState.COMPLETED `?

What is the size of the file being uploaded? Do you get any exception in the `onError` callback? Have you noticed any error in your logcat?
