### ISSUE TITLE
Authenticated requests with Cognito and ApiGateway

### ISSUE THREAD

**Issue by tobiasschuerg** [aws-amplify/aws-sdk-android#767]
**State your question**
How can I make authenticated requests via api gateway or rather how to set up the CredentialsProvider?

I have an amazon generated api which I'm trying to set up, but authentication does not work.
I followed this guide: https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-generate-sdk-android.html
(implementation details below)

**Which AWS Services are you utilizing?**
- Cognito
- ApiGateway

**Provide code snippets (if applicable)**
Registration via CognitoUserPool works. Same goes for sign in.

On successful sign in I receive a `CognitoUserSession` which contains a valid `jwtToken` which I use to create credentialsProvider for the `ApiFactory`:

```kotlin
val credentialsProvider = CognitoCachingCredentialsProvider(context, identityPoolId, region)
credentialsProvider.logins = mapOf("cognito-idp.eu-central-1.amazonaws.com/$userPoolId" to jwtToken)

val api = ApiClientFactory()
    .apiKey(API_KEY)
    .credentialsProvider(credentialsProvider)
    .build(DevClient::class.java)

api.get(Transactions) // works fine

api.post(transaction)
```

The api has two methods  (one GET which requires no auth and a POST method which requires auth).
The GET method works fine, as ist does not need auth, but I don't get the POST one to work - returns 401 unauthorized - and if I look at the request, the the `jwtToken` is not part of the request.

> // returns com.amazonaws.mobileconnectors.apigateway.ApiClientException: {"message":"Unauthorized"}
     (Service: DevClient; Status Code: 401; Error Code: null; Request ID: acff23de-3f56-11e9-9c88-c13e47b5ed68)

If I debug into and use the `jwtToken` via Postman everything works fine.

**Environment(please complete the following information):**
 - `compileSdkVersion 28`
 - aws dependencies:
```
    compile "com.amazonaws:aws-android-sdk-apigateway-core:2.12.0"
    compile 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.12.0'
```

**Device Information (please complete the following information):**
Probably doesn't matter (Emulator, Pixel, Pixel 3)

**Comment by kvasukib** [comment]
@tobiasschuerg Thank you for reporting to us. 

After you set the token in the logins map, you need to call `refresh` in order to receive the credentials based on the authenticated role. The following code assumes that you want to use Cognito Federated Identities (Authenticated Identities) to authenticate your request to APIGateway.

```
val credentialsProvider = CognitoCachingCredentialsProvider(context, identityPoolId, region)
credentialsProvider.logins = mapOf("cognito-idp.eu-central-1.amazonaws.com/$userPoolId" to jwtToken)
credentialsProvider.refresh()

val api = ApiClientFactory()
    .apiKey(API_KEY)
    .credentialsProvider(credentialsProvider)
    .build(DevClient::class.java)

api.get(Transactions) // works fine

api.post(transaction)
```

However if you want to use Cognito UserPools as the authorizer mechanism for authenticating your calls to APIGateway without federating into Cognito Identities, you need to pass the JWT Token received from UserPools in the headers map while making a request to APIGateway.

Which of these two methods are you trying to use?

**Comment by tobiasschuerg** [comment]
Thank you already for your response! I think user pools should be the authorizer.

Where can I set the headers? 
Neither `ApiClientFactory` nor my generated api provides something like `setHeaders`?

**Comment by kvasukib** [comment]
@tobiasschuerg Thank you for the quick response. Here is the code.

```java
//Pass in null for credentialsProvider
apiClient = new ApiClientFactory()
    .credentialsProvider(null)
    .build(YOUR_API_CLIENT_NAME.class);

//Updated function with arguments and code updates
public void doInvokeAPI(String token) {

ApiRequest localRequest =
    new ApiRequest(apiClient.getClass().getSimpleName())
        .withPath(path)
        .withHttpMethod(HttpMethodName.valueOf(method))
        .withHeaders(headers)
        .addHeader("Content-Type", "application/json")
        .addHeader("Authorization", token)  //Use JWT token
        .withParameters(parameters);

}
```

**Comment by tobiasschuerg** [comment]
I don't get it to work :-(

```kotlin
val id = 1234
val content = "{\"transaction_id\": \"2\",\"amount\": 1.5}"

val request = ApiRequest(apiClient.javaClass.simpleName)
    .withPath("/accounts/$id/transactions")
    .withHttpMethod(HttpMethodName.POST)
    // .withHeaders(headers)
    .addHeader("Content-Type", "application/json")
    .addHeader("Authorization", "Bearer $token")
    // .withParameters(params)
    .withBody(content)

val response: ApiResponse = apiClient.execute(request)
Log.d("SDK", "Response $response")
```
If running the above code, it throws an exception:
> Error com.amazonaws.mobileconnectors.apigateway.ApiClientException: expected 0 bytes but received 37 (Service: null; Status Code: 0; Error Code: null; Request ID: null)

When profiling the request, I see that the url is correct and theauthorization header is set correctly. However, it seems as no body is sent?!?


But if I do the same request using OkHttp, it just works fine:
```kotlin
val id = 1234
val content = "{\"transaction_id\": \"2\",\"amount\": 1.5}"

val client = OkHttpClient()
val mediaType = MediaType.parse("application/json")
val body = RequestBody.create(mediaType, content)
val request = Request.Builder()
    .url("https://xxxxxxxx.execute-api.eu-central-1.amazonaws.com/dev/accounts/$id/transactions")
    .post(body)
    .addHeader("Content-Type", "application/json")
    .addHeader("Authorization", "Bearer $token")
    .build()

val response = client.newCall(request).execute()
Log.d("HTTP", "Response $response")
```

Some questions I have:
1. Is ApiGateway meant to be used with user pools?
2. why is there no `ApiClientFactory.setSession()` oder `setToken()` method?
3. If I do it like you suggested, where is the advantage of using the SDK at all?

**Comment by kvasukib** [comment]
@tobiasschuerg Thank you for the detailed response. You need to supply the `content-length` header.

```java
.addHeader("Content-Length", length)
```

You can take a look at our [integration tests](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-apigateway-test/src/androidTest/java/com/amazonaws/mobileconnectors/apigateway/ApiClientFactoryIntegrationTest.java#L114) for high-level APIs which will create the requests boilerplate for you.

**Comment by tobiasschuerg** [comment]
@kvasukib thanks again

With the setting the content-length manually it now works 🎆 

However, with having to manually specify the urls, path, parse the json response, and everything... I'm still wondering what the advante of the apigateway on android side is or if it normally should be used only in combination with identity pools?

**Comment by kvasukib** [comment]
@tobiasschuerg Sorry for the delayed response. I agree with you that the Auth integration with API Gateway is not developer friendly and easy to use. We will take this feedback to the team to investigate on how to improve this integration.
