### ISSUE TITLE
Regression in Reset Password Workflow introduced in 2.12.1

### ISSUE THREAD

**Issue by tw-john** [aws-amplify/aws-sdk-android#769]
**Describe the bug**
Regression introduced in CognitoUser in commit of 2019-02-22.

Regression results in consistent "Authentication failed due to an internal error: PASSWORD_VERIFIER challenge encountered not at the start of authentication flow" error message being returned during password reset workflow.

This regression was introduced by the removal of the return statement at line 2365 of CognitoUser which results in the startWithUserSrpAuth method continuing to handleChallenge when it previously did not.

**Comment by minbi** [comment]
Hi @tw-john ,

This is a duplicate of #722 . We will have a release soon to fix this issue. If you want to try out the fix, it is staged on branch mc-2

**Comment by tw-john** [comment]
Good to know. I'll just stick to 2.12.0 until it is released.
