### ISSUE TITLE
com.amazonaws.http.UrlHttpClient does not set proxy settings

### ISSUE THREAD

**Issue by BigFab** [aws-amplify/aws-sdk-android#785]
**Describe the bug**
I am building a S3Client to which I am passing some proxy settings (host and port) through the ClientConfiguration. The S3Client constructor I am using (credentials + region + clientConfiguration) leads to using a **UrlHttpClient**. The instantiation of this class does not take into account the proxy settings defined in the ClientConfiguration.
As a workaround, I have to build a **ApacheHttpClient** that is taking these settings into consideration (silently using the HttpClientFactory which the UrlHttpConnection is not).

**To Reproduce**
A code sample or steps:
```java
    private AmazonS3Client getS3Client() {
        if (mS3Client == null) {
            ClientConfiguration clientConfig = new ClientConfiguration();
            clientConfig.setProtocol(Protocol.HTTPS);
            clientConfig.setProxyHost("proxy.xxxxx.com");
            clientConfig.setProxyPort(8888);

            final BasicAWSCredentials basicAWSCredentials = new BasicAWSCredentials(ACCESS_KEY, SECRET_KEY);

            mS3Client = new AmazonS3Client(basicAWSCredentials, Region.getRegion(Regions.fromName(REGION)), clientConfig);
        }
        return mS3Client;
    }

```

**Which AWS service(s) are affected?**
S3 (potentially more if using this same core classes)

**Expected behavior**
I am expecting that UrlHttpConnection is taking into consideration the settings that are provided in the ClientConfiguration.

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.12.4
 - Device: Sony XZ1
 - Android Version: 8.1
 - Specific to simulators: No

**Additional context**
I am trying to run the S3Client through a proxy under a VPN.

**Comment by desokroshan** [comment]
@BigFab Thanks for bringing this to our attention. I have added it to our backlog for prioritization. Will keep you posted with any progress on the issue. Thanks!

**Comment by BigFab** [comment]
@desokroshan Cool, thanks :)

**Comment by sulewicz** [comment]
This is also affecting Pinpoint SDK.
Any reason why ApacheHttpClient is not used instead?
At least this is how I managed to solve it for now.

**Comment by div5yesh** [comment]
Please use custom HttpClients if you want to set proxy settings.

Closing this issue as workaround exists and the issue has been inactive for some time. Please create a new issue if you have additional questions.
