### ISSUE TITLE
Minimized SDK

### ISSUE THREAD

**Issue by Akefhabbal** [aws-amplify/aws-sdk-android#789]
**State your question**
I use the SDK library which has so many functions more than 17000 which makes me have to use multidex in android, is there a minimized library that I can use? I'm using this library to PubSub messages on MQTT.

**Which AWS Services are you utilizing?**
aws-android-sdk-iot
aws-android-sdk-mobile-client

**Provide code snippets (if applicable)**
aws_version = "2.12.+"
implementation "com.amazonaws:aws-android-sdk-iot:$aws_version"
implementation "com.amazonaws:aws-android-sdk-mobile-client:$aws_version"

**Environment(please complete the following information):**
 - SDK Version: 2.12.+

**Comment by rohandubal** [comment]
Hello @Akefhabbal 

Sorry that you are having issues using the SDK. Could you please tell the functionality in AWSMobileClient which you are using? 

If you are only using Cognito Identity without authentication, you could just depend on `aws core` which can help reduce the library size. If you are using the auth features, then unfortunately we do not have other smaller library.

Thanks,
Rohan

**Comment by Akefhabbal** [comment]
Hello @rohandubal 

Thanks for you answer. Actually, I'm using authentication.

I hope you will make a minimized on in the future.

Regards.
Akef.

**Comment by richardmcclellan** [comment]
More than two years have past since this issue was opened, and so this is not as much of a concern for most developers as it was back then.  Multidex can be enabled as long as your target API is 21+, which covers 94.1% of Android devices today.  API 21 is the default target API in the current version of Android Studio, as well.
