### ISSUE TITLE
Using TransferNetworkLossHandler receiver with targetSdk 24 and up (N+) results in a lint warning

### ISSUE THREAD

**Issue by MarcBernstein** [aws-amplify/aws-sdk-android#795]
**Describe the bug**
Adding the TransferNetworkLossHandler receiver to AndroidManifest.xml shows a warning about using deprecated functionality when `targetSdk` is >= 24.

**To Reproduce**
With an app that uses a `targetSdk` value of 24 or higher:
1. Add the TransferNetworkLossHandler receiver to AndroidManifest.xml:
```
<receiver android:name="com.amazonaws.mobileconnectors.s3.transferutility.TransferNetworkLossHandler">
  <intent-filter>
    <action android:name="android.net.conn.CONNECTIVITY_CHANGE" />
  </intent-filter>
</receiver>
```
2. Run `./gradlew lint`
3. See the lint report output:
```
Battery Life Issues
../../src/main/AndroidManifest.xml:22: Declaring a broadcastreceiver for android.net.conn.CONNECTIVITY_CHANGE is deprecated for apps targeting N and higher. In general, apps should not rely on this broadcast and instead use JobScheduler or GCMNetworkManager.
``

**Which AWS service(s) are affected?**
The SDK itself.

**Expected behavior**
I'd expect a solution that doesn't use deprecated Android functionality.

**Screenshots**
N/A

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.12.4
 - Device: N/A (build/platform issue)
 - Android Version: API 24+
 - Specific to simulators: No

**Additional context**
None.

**Comment by kvasukib** [comment]
@MarcBernstein Thank you for reporting to us. For apps targeting 24 and above, I would recommend you to register the broadcast receiver through code and not via manifest.

You can refer how to do this in [`TransferService`](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-s3/src/main/java/com/amazonaws/mobileconnectors/s3/transferutility/TransferService.java#L104)

In short, you could create an instance of the handler and register from your app.

```java
TransferNetworkLossHandler transferNetworkLossHandler = TransferNetworkLossHandler.getInstance(getApplicationContext());

getApplicationContext().registerReceiver(this.transferNetworkLossHandler, new 
    IntentFilter(ConnectivityManager.CONNECTIVITY_ACTION));
```

**Comment by MarcBernstein** [comment]
Thanks @kvasukib. Is this functionality required, or optional? I noticed error log messages before I set up the TransferNetworkLossHandler in my app, but I'm not quite sure if it's mandatory or not.

After removing the calls altogether, I don't see any errors being logged about it so I'm guessing there was something else going on and it's not required to register this receiver unless we desire it?

**Comment by kvasukib** [comment]
@MarcBernstein Thank you for the quick response. As you rightly pointed out, this is an optional feature. `TransferNetworkLossHandler` listens for network connectivity changes and pauses the on-going transfers when the network is offline and resumes them when the network comes back online. 

When you use `TransferService` or wrap the call to `TransferNetworkLossHandler` in a service of your choice, this functionality can be exercised irrespective of the app being in background or foreground.

**Comment by MarcBernstein** [comment]
Thanks for the info.

**Comment by Priyanka-Mohanty** [comment]
CONNECTIVITY_ACTION was deprecated in API level 28.
