### ISSUE TITLE
Region object for Stockholm - eu_north_1 is missing.

### ISSUE THREAD

**Issue by kkflf** [aws-amplify/aws-sdk-android#797]
**Describe the bug**
I am trying to use the new Stockholm region (eu_north_1) with S3 in Android. I can use the Regions.EU_NORTH_1 enum, but I cannot retrieve any Region object based on this enum.

This is the regions available in `RegionUtils.jav List<Region> regions`:
regions = {ArrayList@6445}  size = 18
 0 = {Region@6447} "ap-northeast-1"
 1 = {Region@6448} "ap-northeast-2"
 2 = {Region@6449} "ap-south-1"
 3 = {Region@6450} "ap-southeast-1"
 4 = {Region@6451} "ap-southeast-2"
 5 = {Region@6452} "ca-central-1"
 6 = {Region@6453} "eu-central-1"
 7 = {Region@6454} "eu-west-1"
 8 = {Region@6455} "eu-west-2"
 9 = {Region@6456} "eu-west-3"
 10 = {Region@6457} "sa-east-1"
 11 = {Region@6458} "us-east-1"
 12 = {Region@6459} "us-east-2"
 13 = {Region@6460} "us-west-1"
 14 = {Region@6461} "us-west-2"
 15 = {Region@6462} "cn-north-1"
 16 = {Region@6463} "cn-northwest-1"
 17 = {Region@6464} "us-gov-west-1"

There are no eu-north-1 on the above list.

I am using com.amazonaws:aws-android-sdk-s3:2.12.5 and com.amazonaws:aws-android-sdk-core:2.12.5.

**To Reproduce**
```
// I can create an Regions object based on the region string. This will return Regions.EU_NORTH_1:
`Regions regions = Regions.fromName("eu_north_1");`

// I can not get a Region object based on the Regions object. This is returning null.
`Region region = Region.getRegion(regions);`
```

**Which AWS service(s) are affected?**
S3

**Expected behavior**
I would expect to be able to retrieve a Region object for eu_north_1.

**Environment Information (please complete the following information):**
implementation 'com.amazonaws:aws-android-sdk-s3:2.12.5'
implementation 'com.amazonaws:aws-android-sdk-core:2.12.5'
minSdkVersion 26
targetSdkVersion 28
buildToolsVersion '28.0.3'

**Comment by kvasukib** [comment]
@kkflf Thank you for reporting to us. Sorry for the inconvenience caused. I have submitted a PR #798 to fix this issue.

**Comment by kkflf** [comment]
Thank you for the quick feedback! I appreciate it!

**Comment by minbi** [comment]
Hi,

Please see if SDK release 2.12.7 fixes this issue for you. We have added the following fix:

>Fixed support for EU (Stockholm) region - eu-north-1 by adding to RegionDefaults

You may see all changes in the [changelog](https://github.com/aws/aws-sdk-android/blob/master/CHANGELOG.md#release-2127)
