### ISSUE TITLE
How I can get JWT token from social login with AWSMobileClient 

### ISSUE THREAD

**Issue by HayTran94** [aws-amplify/aws-sdk-android#799]
**State your question**
Currently, I am using AWSMobileClient to authenticate my user and I use JWT token retrieved from User Pool to access my Web server.  But now I need integrate Facebook login to my app. I realized that if I integrate social login to User Pool, I can get JWT token, otherwise, I just get IdentityId and AWS Credential. I also found that AWSMobile docs state that ' the federation feature in the AWSMobileClient supports Cognito Identity Pools only'. So how i can get JWT token from social login with AWSMobileClient

**Which AWS Services are you utilizing?**
AWSMobileClient

**Environment(please complete the following information):**
 - SDK Version: 2.12.0+

**Comment by minbi** [comment]
Hi @HayTran94 ,

The AWSMobileClient does not support retrieving tokens from a different social provider. If you need a token that has been used for federation, you may check [getDetails()](https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-mobile-client/src/main/java/com/amazonaws/mobile/client/UserStateDetails.java#L37) for a map of the federation details.

**Comment by HayTran94** [comment]
Hi @minbi ,
Now, I need a client token to authenticate with a backend server.  So does AWS support admin SDK to convert Identity Id to token being used? If not, could you suggest me some ways to resolve this problem. Thank you very much.

**Comment by minbi** [comment]
Once you have completed a `federatedSignIn()` or `signIn()` with a Cognito Identity Pool configured in your `awsconfiguration.json` the calls to AWS services should be authorized.

```
AmazonS3 s3 = AmazonS3Client(AWSMobileClient.getInstance(), Region.getRegion(Regions.US_EAST_1));
```

**Comment by HayTran94** [comment]
> Once you have completed a `federatedSignIn()` or `signIn()` with a Cognito Identity Pool configured in your `awsconfiguration.json` the calls to AWS services should be authorized.
> 
> ```
> AmazonS3 s3 = AmazonS3Client(AWSMobileClient.getInstance(), Region.getRegion(Regions.US_EAST_1));
> ```

My problem is an access token to access my own backend server in EC2, not AWS services.

**Comment by minbi** [comment]
If you are accessing a server that you have setup, then you can decide the security protocol you need to authenticate your users. Some options may include validating the User Pools token, validating the AWS credentials, or using AppSync or API Gateway to front your server. This depends on your security requirements.

**Comment by HayTran94** [comment]
Thank for your suggestion. So do you need to close this issue?
