### ISSUE TITLE
v2.0.5 Another initialisation error

### ISSUE THREAD

**Issue by ctjhai** [aws-amplify/aws-sdk-android#8]
I am using AWS S3 SDK (v2.0.5) on my Android project. It runs fine without Proguard, however, with Proguard it throws the following exceptions:

<pre>
08-28 12:39:39.054: W/dalvikvm(5152): Exception Ljava/lang/IllegalStateException; thrown while initializing Lcom/amazonaws/internal/config/InternalConfig$Factory;
08-28 12:39:39.064: W/dalvikvm(5152): threadid=10: thread exiting with uncaught exception (group=0x418de378)
08-28 12:39:39.074: E/AndroidRuntime(5152): FATAL EXCEPTION: AsyncTask #1
08-28 12:39:39.074: E/AndroidRuntime(5152): java.lang.RuntimeException: An error occured while executing doInBackground()
08-28 12:39:39.074: E/AndroidRuntime(5152):     at android.os.AsyncTask$3.done(AsyncTask.java:299)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at java.lang.Thread.run(Thread.java:856)
08-28 12:39:39.074: E/AndroidRuntime(5152): Caused by: java.lang.ExceptionInInitializerError
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.amazonaws.ServiceNameFactory.getServiceName(SourceFile:34)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.amazonaws.AmazonWebServiceClient.computeServiceName(SourceFile:707)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.amazonaws.AmazonWebServiceClient.getServiceNameIntern(SourceFile:680)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.amazonaws.AmazonWebServiceClient.computeSignerByURI(SourceFile:282)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.amazonaws.AmazonWebServiceClient.setEndpoint(SourceFile:160)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.amazonaws.services.s3.AmazonS3Client.setEndpoint(SourceFile:472)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.amazonaws.services.s3.AmazonS3Client.init(SourceFile:444)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.amazonaws.services.s3.AmazonS3Client.<init>(SourceFile:340)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.amazonaws.services.s3.AmazonS3Client.<init>(SourceFile:320)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.company.app.service.S3Client.<init>(SourceFile:29)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.company.app.service.S3Client.getInstance(SourceFile:120)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at aeo.a(SourceFile:396)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at aeo.doInBackground(SourceFile:264)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at android.os.AsyncTask$2.call(AsyncTask.java:287)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
08-28 12:39:39.074: E/AndroidRuntime(5152):     ... 5 more
08-28 12:39:39.074: E/AndroidRuntime(5152): Caused by: java.lang.IllegalStateException: Fatal: Failed to load the internal config for AWS Java SDK
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.amazonaws.internal.config.InternalConfig$Factory.<clinit>(SourceFile:236)
08-28 12:39:39.074: E/AndroidRuntime(5152):     ... 20 more
08-28 12:39:39.074: E/AndroidRuntime(5152): Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of com.amazonaws.internal.config.Builder, problem: abstract types either need to be mapped to concrete types, have custom deserializer, or be instantiated with additional type information
08-28 12:39:39.074: E/AndroidRuntime(5152):  at [Source: jar:file:/data/app/com.company.app-1.apk!/awssdk_config_default.json; line: 9, column: 18] (through reference chain: com.amazonaws.internal.config.InternalConfigJsonHelper["serviceSigners"]->com.amazonaws.internal.config.JsonIndex["config"])
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(SourceFile:624)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(SourceFile:115)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SourceFile:375)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(SourceFile:107)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(SourceFile:308)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(SourceFile:121)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(SourceFile:147)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(SourceFile:18)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SourceFile:375)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(SourceFile:98)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(SourceFile:308)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(SourceFile:121)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(SourceFile:2796)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.fasterxml.jackson.databind.ObjectMapper.readValue(SourceFile:1919)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.amazonaws.internal.config.InternalConfig.loadfrom(SourceFile:182)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.amazonaws.internal.config.InternalConfig.load(SourceFile:199)
08-28 12:39:39.074: E/AndroidRuntime(5152):     at com.amazonaws.internal.config.InternalConfig$Factory.<clinit>(SourceFile:230)
08-28 12:39:39.074: E/AndroidRuntime(5152):     ... 20 more
</pre>

Any idea how to solve this?

The above exceptions were thrown regardless of whether I linked my app with the debug or release JAR files.

I saw that there is another issue on initialisation error https://github.com/aws/aws-sdk-android-v2/issues/2, I did try that, but no luck. 

The settings of my Proguard are as follows:

<pre>
##---------------Begin: proguard configuration common for all Android apps ----------
-optimizationpasses 2
-dontusemixedcaseclassnames
-dontskipnonpubliclibraryclasses
-dontskipnonpubliclibraryclassmembers
-dontpreverify
-verbose
-dump class_files.txt
-printseeds seeds.txt
-printusage unused.txt
-printmapping mapping.txt
-optimizations !code/simplification/arithmetic,!code/simplification/cast,!field/*,!class/merging/*

-allowaccessmodification
-keepattributes *Annotation*
-renamesourcefileattribute SourceFile
-keepattributes SourceFile,LineNumberTable
-repackageclasses ''

-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.app.backup.BackupAgentHelper
-keep public class * extends android.preference.Preference
-keep public class com.android.vending.licensing.ILicensingService
-dontnote com.android.vending.licensing.ILicensingService

# Explicitly preserve all serialization members. The Serializable interface
# is only a marker interface, so it wouldn't save them.
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}

# Preserve all native method names and the names of their classes.
-keepclasseswithmembernames class * {
    native <methods>;
}

-keepclasseswithmembernames class * {
    public <init>(android.content.Context, android.util.AttributeSet);
}

-keepclasseswithmembernames class * {
    public <init>(android.content.Context, android.util.AttributeSet, int);
}

# Preserve static fields of inner classes of R classes that might be accessed
# through introspection.
-keepclassmembers class **.R$* {
  public static <fields>;
}

# Preserve the special static methods that are required in all enumeration classes.
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

-keep public class * {
    public protected *;
}

-keep class * implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator *;
}

# The support library contains references to newer platform versions.
# Don't warn about those in case this app is linking against an older
# platform version.  We know about them, and they are safe.
-dontwarn android.support.**

# Remove all logs:
-assumenosideeffects class android.util.Log {
    public static boolean isLoggable(java.lang.String, int);
    public static int v(...);
    public static int i(...);
    public static int w(...);
    public static int d(...);
    public static int e(...);
}

##---------------End: proguard configuration common for all Android apps ----------

# AWS SDK
-keep class org.apache.commons.logging.**               { *; }
-keep class com.amazonaws.services.sqs.QueueUrlHandler  { *; }
-keep class com.amazonaws.javax.xml.transform.sax.*     { public *; }
-keep class com.amazonaws.javax.xml.stream.**           { *; }
-keep class com.amazonaws.services.**.model.*Exception* { *; }
-keep class com.amazonaws.internal.**                   { *; }
-keep class org.codehaus.**                             { *; }
-keep class org.joda.convert.*                          { *; }
-keep class org.joda.time.tz.Provider                   { *; }
-keep class org.joda.time.tz.NameProvider               { *; }
-keepattributes Signature,*Annotation*,EnclosingMethod
-keepnames class com.fasterxml.jackson.** { *; }
-keepnames class com.amazonaws.** { *; }

-dontwarn com.amazonaws.auth.policy.conditions.S3ConditionFactory
-dontwarn org.joda.time.**
-dontwarn com.fasterxml.jackson.databind.**
-dontwarn javax.xml.stream.events.**
-dontwarn org.codehaus.jackson.**
-dontwarn org.apache.commons.logging.impl.**
-dontwarn org.apache.http.conn.scheme.**
-dontwarn org.apache.http.annotation.**
-dontwarn org.ietf.jgss.**
-dontwarn org.w3c.dom.bootstrap.**

-dontnote com.amazonaws.services.sqs.QueueUrlHandler

# httpmime-4.3.3
-keepnames class org.apache.** {*;}
-keep public class org.apache.** {*;}

# This dnsjava class uses old Sun API
-dontnote org.xbill.DNS.spi.DNSJavaNameServiceDescriptor
-dontwarn org.xbill.DNS.spi.DNSJavaNameServiceDescriptor

# aSmack specific configuration
-keep class de.measite.smack.AndroidDebugger { *; }
-keep class * implements org.jivesoftware.smack.initializer.SmackInitializer
-keep class * implements org.jivesoftware.smack.provider.IQProvider
-keep class * implements org.jivesoftware.smack.provider.PacketExtensionProvider
-keep class * extends org.jivesoftware.smack.packet.Packet
-keep class org.jivesoftware.smack.XMPPConnection
-keep class org.jivesoftware.smack.XMPPTCPConnection
-keep class org.jivesoftware.smack.ReconnectionManager
-keep class org.jivesoftware.smackx.muc.MultiUserChat
-keep class org.jivesoftware.smackx.iqlast.LastActivityManager
-keep class org.jivesoftware.smackx.ping.PingManager
-keep class org.jivesoftware.smackx.privacy.PrivacyListManager
-keep class org.jivesoftware.smackx.time.EntityTimeManager
-keep class org.jivesoftware.smackx.vcardtemp.VCardManager
-keep class org.jivesoftware.smackx.chatmarkers.ChatMarkerManager

# Misc
-dontnote android.os.SystemProperties
-dontnote sun.security.pkcs11.SunPKCS11

# Google Play Services
-keep class * extends java.util.ListResourceBundle {
    protected java.lang.Object[][] getContents();
}

-keep public class com.google.android.gms.common.internal.safeparcel.SafeParcelable {
    public static final *** NULL;
}

-keepnames @com.google.android.gms.common.annotation.KeepName class *
-keepclassmembernames class * {
    @com.google.android.gms.common.annotation.KeepName *;
}

-keepnames class * implements android.os.Parcelable {
    public static final ** CREATOR;
}
</pre>

Look forward to any suggestions/comments on this. Many thanks

**Comment by loosemoose** [comment]
-dontshrink is not a suitable workaround. We need to identify the actual classes/members we need to keep in the proguard file. Is this documented properly anywhere? I found the following article, but it is incomplete as I still get the error...
http://mobile.awsblog.com/post/Tx2OC71PFCTC63E/Using-ProGuard-with-the-AWS-SDK-for-Android
