### ISSUE TITLE
 AmazonS3Client(credentialsProvider) is deprecated

### ISSUE THREAD

**Issue by Priyanka-Mohanty** [aws-amplify/aws-sdk-android#802]
AmazonS3Client s3Client = new AmazonS3Client(credentialsProvider); was deprecated?
Function 
val config = AWSConfiguration(context)
                val credentialsProvider = CognitoCachingCredentialsProvider(context, config)
                val s3Client = AmazonS3Client(credentialsProvider)
                transferUtility = TransferUtility.builder()
                    .awsConfiguration(config)
                    .context(context)
                    .s3Client(s3Client)
                    .build()
How to configure the AWS3client?

**Comment by minbi** [comment]
Use `AmazonS3Client(CredentialsProvider, Region)`

**Comment by Priyanka-Mohanty** [comment]
<img width="781" alt="Screen Shot 2019-03-22 at 11 01 55 AM" src="https://user-images.githubusercontent.com/19835715/54802674-56666c80-4c92-11e9-81a4-b0e3a151b6d4.png">

it showing error

**Comment by ppamorim** [comment]
Probably because the type you are using is not the same.

**Comment by kvasukib** [comment]
@Priyanka-Mohanty You need to pass the region information through the `com.amazonaws.regions.Region` object.

```java
s3Client = new AmazonS3Client(credentials, Region.getRegion(Regions.US_WEST_2));
```

**Comment by Priyanka-Mohanty** [comment]
Thanks...its working @kvasukib

**Comment by mbk820** [comment]
@kvasukib hey, should I use 'CredentialsProvider' with my secret key in my live application, anyone can decompile the APK and get my secret and access keys,
What is the right way to initialize the s3 client and use the s3 bucket storage?
Even in AWS documentation, the deprecated method is mentioned. Please guide.

**Comment by pranav-credencys** [comment]
@mbk820  You can encrypt access key and secret key instead of put it directly in the code.

**Comment by credencys-maitri** [comment]
@mbk820  you can use encryption technique i.e. AES encryption to encrypt Access Key and Secret key, instead of putting it directly in the code.

The way which @kvasukib have provided to use AmazonS3Client is the best. You can move forward with that.

Hope this will help.
