### ISSUE TITLE
Error updating sink with frame

### ISSUE THREAD

**Issue by guillermoAlv** [aws-amplify/aws-sdk-android#805]
I'm trying run the AmazonKinesisVideoDemoApp, i'm finding problems when i run it on virtual devices, when i run it on my mobile it works.
I've tested on two virtual devices:

Nexus S, API 23
Nexus S, API 27
No one works

It seems that first get an StatusCode: 0x30000005 error and the a StatusCode: 0x3200000c
Im using the Staging release 2.12.5
Please find attached the log file:
[logs.txt](https://github.com/aws-amplify/aws-sdk-android/files/2991176/logs.txt)

**Comment by minbi** [comment]
Hi @guillermoAlv ,

Thanks for attaching the logs. I am following up with our team about the issue found here.

**Comment by aaron-freshwater-aws** [comment]
Hi Guillermo!

You can find the error codes documented here:
https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/producer-sdk-errors.html

Based on the two error codes you are seeing, it looks like your emulator is not producing correct video time codes.  You will need to troubleshoot to determine why the correct data is not being fed to the SDK.

thanks!
Aaron
