### ISSUE TITLE
aws-android-sdk-cognitoauth: CustomTabs crash when using a provider with client Certificate

### ISSUE THREAD

**Issue by hufon** [aws-amplify/aws-sdk-android#810]
**Describe the bug**
We use an SAML ADFS identity provider that requires an authentication via client certificate.
When chromes open a popup to choose the certificate, we click on "Authorize".
The  callback AuthHandler is never called.

**To Reproduce**
A code sample or steps:
```
* Set up a cognito user pool
* Set up an identity which require a client certificate
*  Build/Setup/Launch the AWSCognitoAuthDemo android application
* Click on Sign In
* Choose the certificate click on authorize
```

**Which AWS service(s) are affected?**
Cognito User Pool
**Expected behavior**
The user should be authenticated

**Screenshots**
https://youtu.be/7wfjejfSPt4

**Environment Information (please complete the following information):**
- Reproduced on Emulators Android 8, 5
- Reproduced on Galaxy Tabs

** Additional Info **
Logcat
`03-22 13:26:57.380 7415-7461/com.android.chrome W/cr_ChildProcessConn: onServiceDisconnected (crash or killed by oom): pid=7550`

**Comment by minbi** [comment]
Hi @hufon ,

I'm just trying to diagnose if this is a SDK issue or service issue. In the app, do you receive the intent in your `onResume` method?

**Comment by hufon** [comment]
Yes the onResume is called

The log : 
`03-25 10:09:57.458 3725-3725/com.amazonaws.cognito.android.samples.authdemo E/CognitoAuthDemo: onResume: null`

**Comment by hufon** [comment]
For information, if i you choose "Open in browser", it works.

**Comment by minbi** [comment]
This may be an issue with CustomTabs. We will have to investigate making another browser available for use.

**Comment by eeatonaws** [comment]
@hufon are you still observing the issue with the latest version of the AWS SDK for Android?
