### ISSUE TITLE
Cognito Auth isAuthenticated always returning false

### ISSUE THREAD

**Issue by bluetrickpt** [aws-amplify/aws-sdk-android#813]
**Describe the bug**
Function isAuthenticated() from cognitoauth returns always false even after successful login.

**To Reproduce**
Download and configure the cognitoauth sample for android https://github.com/awslabs/aws-sdk-android-samples. 
Add the following line to the onSuccess of the AuthHandler:
```
Log.d(TAG, "Is user signed = " + auth.isAuthenticated());
```
Authenticate and see the logs. _false_ is returned even after a successful login.

**Which AWS service(s) are affected?**
cognitoauth

**Expected behavior**
isAuthenticated() should return true after a successful login.

**Environment Information (please complete the following information):**
 - AWS Cognito Auth SDK Version: 2.12.+
 - Device: Simulator, but should occur in any
 - Android Version: 9.0 (haven't tried in others, but suspect that the same will occur)

**Additional context**
This only occurs in the latest version of cognito auth sdk (2.12.+). In version 2.11.+ isAuthenticated() works as expected.
Similar issue to https://github.com/aws-amplify/aws-sdk-android/issues/508 but that one was probably fixed long ago.

**Comment by minbi** [comment]
Hi @bluetrickpt ,

We'll need to investigate and report back. Thanks for the report.

**Comment by minbi** [comment]
It's not clear where the issue might be. I'm seeing a potential bug in the caching layer, but it does not explain why `isAuthenticated()` would be false if you are receiving a `onSuccess` callback. Both of those methods rely on the same mechanism to retrieve the tokens (which are used to determine isAuthenticated).

Are you migrating between 2.11.+ and 2.12.+ on the emulator?

**Comment by bluetrickpt** [comment]
When I first tested, I was migrating from 2.11.+ to 2.12.+ on the emulator. However, in a fresh virtual device (just created for this purpose), 2.12.+ also returns `false`. Just tested the same for API level 28, 27 and the bug is present in all, so I'm assuming the API does not influence.

Were you not able to reproduce the bug? Thank you for looking into this.

**Comment by minbi** [comment]
We were not able to reproduce the issue. We did release a patch for one of the issues in the caching layer and also made the a suspected issue more apparent by throwing the exception. Please see SDK version 2.12.7 or 2.13.0

**Comment by minbi** [comment]
Hi @bluetrickpt ,

The previous statement is retracted. We were able to get a reproduction. We will have a fix soon.

**Comment by rohandubal** [comment]
Hello @bluetrickpt 

We have fixed this issue with SDK release `2.13.1`. Please try it out and let us know if it works for you.

Best,
Rohan

**Comment by bluetrickpt** [comment]
I confirm that the issue is fixed in 2.13.1. 
Thank you very much for looking into this.
(Apologies for closing the issue before commenting)
