### ISSUE TITLE
Missing IoTJobsDataPlane http client

### ISSUE THREAD

**Issue by ysyyork** [aws-amplify/aws-sdk-android#863]
**Which AWS Services is the feature request for?**
IoT Jobs

**Is your feature request related to a problem? Please describe.**
Currently I can only use the AwsMqttClient to update job execution status. Mqtt is hard to manage when this is more like client-server pattern. I have to subscribe and then unsubscribe the client and for some reason it's causing thread interruption etc especially I'm calling this within a rxjava chain with multiple different running thread. 

**Describe the solution you'd like**
There is already a IotJobsDataPlaneClient in the java sdk which leverage http for updating job execution. altho right now I can use that lib but that's kind messy cus I have to have both the android sdk and java sdk together in my repo. It's confusing especially in that they both have a lot of class name in common. 

**Describe alternatives you've considered**
like above

**Additional context**

**Comment by kvasukib** [comment]
@ysyyork Thank you for reporting to us. Currently the AWS SDK for Android does not have the low-level service client for AWS IoT Jobs API. I have tagged it as a feature request.

Have you considered using MQTT over WebSockets which connects to 443 port over websockets transport using HTTPS?
