### ISSUE TITLE
DynamoDBMapper attributes with arbitrary type, BOOL or N as Double

### ISSUE THREAD

**Issue by BillBunting** [aws-amplify/aws-sdk-android#887]
**State your question**

I have a DynamoDB table with items containing an attribute that was saved using the DynamoDBMapper via iOS. The iOS app saves `@property (nonatomic, strong) NSNumber *_archived;` as either a number or a boolean data type in DynamoDB via AWSDynamoDBObjectMapper.  So, as a result, I have an attribute that is sometimes a Number (N) and sometimes a Boolean (B) in DynamoDB. Unfortunately, with the code already in production, I can not change this behavior. 

When the value for `archived` is zero, it is saved as a Boolean equal to false (NO in iOS). When the value is non negative, it is saved as a timestamp (seconds since epoch, a date). In iOS AWSDynamoDBObjectModel successfully unmarshalls the data into a NSNumber (even when a Boolean in DynamoDB; the Boolean value becomes 0 in the NSNumber). 

I would like the same ability in Android. I would like to map a BOOL or Number in DynamoDB to a Double (or double).

In Android, the java class implements serializable and has an member variable `private Double _archived; `

How can I successfully unmarshall values that may be either BOOL or Number (N) in DynamoDB?  When unmarshalling a boolean, a false value would be set to 0.  Any positive value is treated as a Double. No values will be true, but if so, they would be unmarshalled as 1. 

I have tried to using `@DynamoDBMarshalling(marshallerClass = ArchiveMarshaller.class)` but the class is never called before the exception (shown below) is thrown. 

**Which AWS Services are you utilizing?**
DynamoDB

**Provide code snippets (if applicable)**
```
    private Double _archived; 

    @DynamoDBAttribute(attributeName = "archived")
    //@DynamoDBMarshalling(marshallerClass = ArchiveMarshaller.class) Did not help
    public Double getArchived() {
        return _archived;
    }
    public void setArchived(final Double _archived) {
        this._archived = _archived;
    }

// then, later in the code, they are loaded

final PaginatedQueryList<ModDO> result = mapper.query(ModDO.class,
                    queryExpression);

```
Exception
```
2019-04-08 16:39:08.396 8376-8579/com.buntingsoftware.modlist E/AWSErrorHandlerHelper:ModListFragment: com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMappingException: Expected N in value {BOOL: false} when invoking public void com.amazonaws.models.nosql.ModDO.setArchived(java.lang.Double)
2019-04-08 16:39:08.396 8376-8579/com.buntingsoftware.modlist W/System.err: com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMappingException: Expected N in value {BOOL: false} when invoking public void com.amazonaws.models.nosql.ModDO.setArchived(java.lang.Double)
2019-04-08 16:39:08.396 8376-8579/com.buntingsoftware.modlist W/System.err:     at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.unmarshallers.NUnmarshaller.typeCheck(NUnmarshaller.java:29)
2019-04-08 16:39:08.396 8376-8579/com.buntingsoftware.modlist W/System.err:     at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.unmarshallers.DoubleUnmarshaller.typeCheck(DoubleUnmarshaller.java:23)
2019-04-08 16:39:08.396 8376-8579/com.buntingsoftware.modlist W/System.err:     at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.unmarshallers.NullableUnmarshaller.typeCheck(NullableUnmarshaller.java:46)
2019-04-08 16:39:08.396 8376-8579/com.buntingsoftware.modlist W/System.err:     at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.ConversionSchemas$StandardItemConverter.unmarshall(ConversionSchemas.java:568)
2019-04-08 16:39:08.396 8376-8579/com.buntingsoftware.modlist W/System.err:     at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.ConversionSchemas$StandardItemConverter.setValue(ConversionSchemas.java:436)
2019-04-08 16:39:08.396 8376-8579/com.buntingsoftware.modlist W/System.err:     at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.ConversionSchemas$StandardItemConverter.unconvert(ConversionSchemas.java:420)
2019-04-08 16:39:08.396 8376-8579/com.buntingsoftware.modlist W/System.err:     at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper.privateMarshallIntoObject(DynamoDBMapper.java:852)
2019-04-08 16:39:08.396 8376-8579/com.buntingsoftware.modlist W/System.err:     at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper.marshallIntoObjects(DynamoDBMapper.java:894)
2019-04-08 16:39:08.396 8376-8579/com.buntingsoftware.modlist W/System.err:     at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.PaginatedQueryList.<init>(PaginatedQueryList.java:74)
2019-04-08 16:39:08.396 8376-8579/com.buntingsoftware.modlist W/System.err:     at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper.query(DynamoDBMapper.java:2442)
2019-04-08 16:39:08.396 8376-8579/com.buntingsoftware.modlist W/System.err:     at com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBMapper.query(DynamoDBMapper.java:2399)
```

**Environment(please complete the following information):**
 - SDK Version: implementation 'com.amazonaws:aws-android-sdk-ddb:2.13.1'

**Device Information (please complete the following information):**
 - Device: Any
 - Android Version: minSdkVersion 23, complied 28
 - Specific to simulators: No

**Comment by desokroshan** [comment]
@BillBunting I will need to investigate possible ways to unmarshall dynamoDB type BOOL or Number to a double in android. I have tagged it as a question for now. Will post the results of my investigation here. Thanks!

**Comment by BillBunting** [comment]
@desokroshan , any progress or updates on this issue? Thank you.

**Comment by desokroshan** [comment]
@BillBunting My hunch was that either there was a bug in the `@DynamoDBMarshalling` annotation or that its usage was incorrect. I tried using the annotation to map DynamoDB type String to java type Double and it worked as expected and your usage of it seems just fine. In your case I would expect the `@DynamoDBMarshalling` annotation to be invoked at the very least. What is the type of `archived` attribute in the dynamoDB table. Is it of type `BOOL` or `Number`. Given that you see the exception before the marshaller is triggered, I suspect it might be something in the way that the query operation is being invoked. Can you please share the following : 

1. Type of the attribute `archived` in DynamoDB table
2. Snippet for the CRUD operation that gives above mentioned exception
3. ArchiveMarshaller code. This might not be helpful since you mentioned that the exception occurs even before the marshaller is invoked but might help in reproducing the issue.

At this point, `@DynamoDBMarshalling` annotation seems to the way to go. I will try to reproduce the error on my end and also investigate if there are any alternatives to achieve your use case.

**Comment by BillBunting** [comment]
@desokroshan , thank you for your help. Below is the info you requested.

1. Type of the "archived" attribute in DynamoDB table as viewed in the AWS console is sometimes a Number and other times a Boolean. The data type is Number (as set in the iPhone version of the app as follows)

```
@interface Mod : AWSDynamoDBObjectModel <AWSDynamoDBModeling>

+ (NSDictionary *)JSONKeyPathsByPropertyKey;

@property (nonatomic, strong) NSString *_userId;
@property (nonatomic, strong) NSString *_name;
... CUT ...
@property (nonatomic, strong) NSNumber *_archived;

@end

NS_ASSUME_NONNULL_END
```

The value is assigned as follows as a NSNumber with a value of the date or zero (NO):

```
-(void)updateArchivedValue {
    if (_archiveSwitch.on == YES) {
        NSDate *now = [NSDate date];
        _mod._archived = [NSNumber numberWithDouble:[now timeIntervalSince1970]];
    } else {
        _mod._archived = [NSNumber numberWithBool:NO];
    }
}
```

The iPhone app has no problem reading in the value as a NSNumber. 

2. The Android app loads the value as follows. Below you can also see my attempt at using `DynamoDBMarshalling` but the code is not reached since the error is thrown earlier.

```
public class ModDO implements Serializable {
    private String _userId;
    ... CUT ...
    private double _archived; 


    @DynamoDBAttribute(attributeName = "archived")
    @DynamoDBIgnore
    //@DynamoDBMarshalling(marshallerClass = ArchiveMarshaller.class)  (DID NOT WORK: ERROR OCCURS PRIOR! )
    public double getArchived() {
        return _archived;
    }
    public void setArchived(final double _archived) {
        this._archived = _archived;
    }

//    static public class ArchiveValue {
//        private Double value;
//        public ArchiveValue(Boolean b) {
//            if (b.booleanValue() == true) this.value = 1.0;
//            if (b.booleanValue() == false) this.value = 0.0;
//        }
//        public ArchiveValue(Double d) {
//            this.value = d;
//        }
//        public ArchiveValue() {this.value = null;}
//
//        public Double getValue() {return value;}
//    }
//
//    static public class ArchiveMarshaller implements DynamoDBMarshaller<ArchiveValue> {
//
//        @Override
//        public String marshall(ArchiveValue d) {
//            if (d == null) return null;
//            if (d.getValue() == null) return "false";
//            if (d.getValue().doubleValue() == 0.0) return "false";
//            return d.toString();
//        }
//
//        @Override
//        public ArchiveValue unmarshall(Class<ArchiveValue> archiveType, String stringValue) {
//            if (stringValue == null) return null;
//            if (stringValue.equals("false")) return new ArchiveValue(0.0);
//            return new ArchiveValue(new Double(stringValue));
//        }
//    }

```

So, maybe a workaround would be to force the iPhone app or DynamoDB to set the type correctly and consistently for the value?  or set it thought configuration? Ideally, I should be able to use the DynamoDBMarshaller as I wrote in the code above, but unfortunately, the code is not called prior to the exception.

**Comment by desokroshan** [comment]
@BillBunting Thanks for the all the details. Your code looks just fine and your custom marshaller should have been invoked. I would still need to investigate what causes the DoubleUnmarshaller to be invoked and yield the stack trace that you have shared. Would it be possible for you to reproduce the issue with this sample app : 

https://github.com/awslabs/aws-sdk-android-samples/tree/bf648d2f7702c72bbe3c67f168468c3e861eb713/DynamoDBMapper_UserPreference_Cognito

It would be easier for me to investigate if I have a precise reproduction. 
As you mentioned the fastest way to unblock yourself would be to update the behavior of your iOS app to set the type of `archived` consistently in DynamoDB.

**Comment by BillBunting** [comment]
@desokroshan , thank you for looking at the code.  I don't have the resources at this time to set up and test the bug in the demo application.  I put it in my backlog.

**Comment by palpatim** [comment]
Flagging this to autoclose for now. @BillBunting if you're able to find time to provide a repro sample, please feel free to reopen this issue or file a new one linked to this issue.

**Comment by BillBunting** [comment]
For future reference, a custom marshaller can only handle a string type in DynamoDB (@DynamoDBMarshalling). The iOS version of my app was marshaling a NSNumber to either a Boolean or a Number in DynamoDB.
