### ISSUE TITLE
Service: AWSSecurityTokenService; Status Code: 403; Error Code: AccessDenied; Request ID: 83bfc431-3733-11e4-90c0-6dbe37b9d930)

### ISSUE THREAD

**Issue by perceptinfotech** [aws-amplify/aws-sdk-android#9]
Hello,

I am uploading photo on s3 amazon using provided demo code. and used v2 library. But while selecting photo application goes force close. and i got below error.

java.lang.RuntimeException: Unable to create service com.amazonaws.demo.s3_transfer_manager.network.NetworkService: com.amazonaws.AmazonServiceException: Not authorized to perform sts:AssumeRoleWithWebIdentity (Service: AWSSecurityTokenService; Status Code: 403; Error Code: AccessDenied; Request ID: 83bfc431-3733-11e4-90c0-6dbe37b9d930)

How to solve this..! 

Thanks

**Comment by ronakmehta1989** [comment]
Hi,
I am still having above problem 

Error message : 

E/AmazonClientManager(1457): Error, wipeCredentialsOnAuthError calledcom.amazonaws.AmazonServiceException: Not authorized to perform sts:AssumeRoleWithWebIdentity (Service: AWSSecurityTokenService; Status Code: 403; Error Code: AccessDenied; Request ID: 85fe151a-bde1-11e4-b173-97e98b8c64fb)

I have to upload image/video as well as I've to write same in database too.

Previous Trust Relationship 
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": [
          "codedeploy.us-west-2.amazonaws.com",
          "codedeploy.us-east-1.amazonaws.com"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}

Till here I can upload image/upload using AmazoS3Client in Android. But I can't insert data into DB. I'm simply using amazon demo. 

Note : Constants file is updated successfully with real values.

New trust Relationship :

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Federated": "cognito-identity.amazonaws.com"
      },
      "Action": "sts:AssumeRoleWithWebIdentity"
    }
  ]
}

But , I guess error is same.
Please let me know if I'm going wrong.
