### ISSUE TITLE
How to see the User Attributes under Endpoint Attributes on Pinpoint console?

### ISSUE THREAD

**Issue by abdullahmehmood** [aws-amplify/aws-sdk-android#902]
**State your question**
How can I see the "User Attributes" under the "EndPoint Profile Attributes"on Pinpoint console?

**Which AWS Services are you utilizing?**
I am using the Pinpoint Android sdk. And also sending the UserID in Endpoint User Profile and updating the endpoint. But unable to see the UserID in User attributes. I able to see the custom attributes of Endpoint but not the User attributes.

**Provide code snippets (if applicable)**

Updating the Endpoint Profile with the below code:

TargetingClient targetingClient = pinpointManager.getTargetingClient();
EndpointProfile endpointProfile = targetingClient.currentEndpoint();
EndpointProfileUser endpointProfileUser = new EndpointProfileUser();
endpointProfileUser.setUserId(myUserID);
endpointProfile.setUser(endpointProfileUser);
targetingClient.updateEndpointProfile(endpointProfile);

**Comment by kvasukib** [comment]
@abdullahmehmood I have added a test to our SDK to test this functionality to see if there is any bug in the SDK. I don't see any issues so far. I have engaged with the Pinpoint service team to see if there is an discrepancy in seeing this information on the console. Thank you for your patience.

**Comment by kvasukib** [comment]
@abdullahmehmood Closing the issue. Please feel free to comment/re-open if you find any more information.
