### ISSUE TITLE
AWS S3 Upload Failed in Android

### ISSUE THREAD

**Issue by deepakrokz** [aws-amplify/aws-sdk-android#903]
**Describe the bug**
Getting these errors for different users and device

> com.amazonaws.AmazonClientException: Unable to execute HTTP request: timeout

> com.amazonaws.services.s3.model.AmazonS3Exception: Your socket connection to the server was not read

> Your socket connection to the server was not read from or written to within the timeout period. Idle

> Unable to execute HTTP request: Unable to resolve host "cognito-identity.ap-southeast-1.amazonaws.co

> com.amazonaws.AmazonClientException: Unable to execute HTTP request: connect timed out

**To Reproduce**
A code sample or steps:
```
This is the way of connection being set
private static CognitoCachingCredentialsProvider getCredProvider(Context context) {
        if (sCredProvider == null) {
            ClientConfiguration clientConfiguration = new ClientConfiguration();
            clientConfiguration.setConnectionTimeout(5000);
            clientConfiguration.setSocketTimeout(5000);
            sCredProvider = new CognitoCachingCredentialsProvider(
                    context.getApplicationContext(),
                    Constants.COGNITO_POOL_ID,
                    Regions.fromName(Constants.COGNITO_POOL_REGION), clientConfiguration);
        }
        return sCredProvider;
    }

    /**
     * Gets an instance of a S3 client which is constructed using the given
     * Context.
     *
     * @param context An Context instance.
     * @return A default S3 client.
     */
    public static AmazonS3Client getS3Client(Context context) {
        if (sS3Client == null) {

            ClientConfiguration configuration = new ClientConfiguration();
            configuration.setMaxErrorRetry(3);
            configuration.setConnectionTimeout(5000);
            configuration.setSocketTimeout(5000);
            configuration.setProtocol(Protocol.HTTP);

            sS3Client = new AmazonS3Client(getCredProvider(context.getApplicationContext()), configuration);
            sS3Client.setRegion(Region.getRegion(Regions.AP_SOUTHEAST_1));
//            sS3Client.setRegion(Region.getRegion(Regions.fromName(Constants.BUCKET_REGION)));
        }
        return sS3Client;
    }
```

**Which AWS service(s) are affected?**

**Expected behavior**
I am using the latest SDKs to connect with S3
 implementation 'com.amazonaws:aws-android-sdk-s3:2.13.2'
    implementation("com.amazonaws:aws-android-sdk-mobile-client:2.13.2") { transitive = true }

I have done a lot of research but unable to get it resolved, these errors are increasing day by day and users are facing problems and lack of confidence is being generated with our product.
Please reply quick 

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: 2.12.0 & 2.13.2
 - Device: SM-J600G, Redmi Note 4, Redmi Note 6 Pro etc.
 - Android Version:  8.0.0, 7.0, 8.1.0 etc.
 - Specific to simulators: Haven't tried on simulator

**Additional context**
Please help me to resolved this. Many thanks for your help.

**Comment by kvasukib** [comment]
@deepakrokz Sorry for the inconvenience caused.

These errors occur the following conditions:-

1) The device is offline while the transfer is in progress.
2) The device is in a poor network condition where the connection opened by SDK to Amazon S3 is idle for more than 20 seconds (Amazon S3's idle connection timeout).

Under these circumstances the SDK reports the exception thrown by the Android networking layer. However if you used a `TransferNetworkLossHandler` or `TransferService`, the SDK will set the transfer state to `WAITING_FOR_NETWORK`.

Are you getting the `onStateChanged()` callback in the `TransferListener` with the state set to `WAITING_FOR_NETWORK`?

**Comment by deepakrokz** [comment]
Hi @kvasukib ,
Thanks for getting back, I am not sure cause this problem is not coming in my phone, it's in several users. I will try to generate and update you in my phone.

**Comment by kvasukib** [comment]
@deepakrokz Can you upgrade to the latest version of the SDK? We have fixed few bugs in this area in the latest releases.

**Comment by deepakrokz** [comment]
Hi Again, 
Yes, I upgraded to latest version i.e. 2.13.2 but issue is there. In a poor network, it is being generated but when it comes back in good internet connection still no upload get fired.

**Comment by kvasukib** [comment]
@deepakrokz Can you post a code snippet of how you are starting an upload and resuming it? Are you using a `TransferNetworkLossHandler` or `TransferService` from your app?

**Comment by deepakrokz** [comment]
Hi @kvasukib 
Sorry for the delay in response, I am using TransferService.
I am starting this service in Application class 
startService(new Intent(mInstance.getApplicationContext(), TransferService.class));

and about retry and upload handling using this code intialization
`private void initData() {
        transferRecordMaps.clear();
        // Use TransferUtility to get all upload transfers.
        observers = transferUtility.getTransfersWithType(TransferType.UPLOAD);
        TransferListener listener = new UploadListener();
        for (TransferObserver observer : observers) {

            // For each transfer we will will create an entry in
            // transferRecordMaps which will display
            // as a single row in the UI
            HashMap<String, Object> map = new HashMap<String, Object>();
            Util.fillMap(map, observer, false);
            transferRecordMaps.add(map);

            // Sets listeners to in progress transfers
            if (TransferState.WAITING.equals(observer.getState())
                    || TransferState.WAITING_FOR_NETWORK.equals(observer.getState())
                    || TransferState.IN_PROGRESS.equals(observer.getState())) {
                observer.setTransferListener(listener);
            }
        }
    }`

please review

**Comment by lamster2018** [comment]
it not works

implementation "com.amazonaws:aws-android-sdk-core:2.16.11"
    implementation "com.amazonaws:aws-android-sdk-s3:2.16.11"

android 7.1
use wifi, network is good.

```
private void initAwsClient(UploadToken token, Context context) {
        BasicSessionCredentials basicSessionCredentials = new BasicSessionCredentials(
                token.accessId,
                token.accessSecret,
                token.securityToken
        );
        com.amazonaws.ClientConfiguration configuration = new com.amazonaws.ClientConfiguration();
        configuration.setMaxErrorRetry(3);
        configuration.setConnectionTimeout(60 * 1000); // 连接超时，默认15秒
        configuration.setSocketTimeout(60 * 1000); // socket超时，默认15秒
        configuration.setProtocol(Protocol.HTTP);
        configuration.setMaxConnections(10);// 最大并发请求，默认10个
        Region region = Region.getRegion(token.region);
        AmazonS3Client s3Client = new AmazonS3Client(basicSessionCredentials, region, configuration);
        if (mTransferUtility == null) {
            mTransferUtility = TransferUtility.builder()
                    .s3Client(s3Client)
                    .context(context.getApplicationContext())
                    .build();
        }
```
