### ISSUE TITLE
How to check if the user login first time

### ISSUE THREAD

**Issue by alphaDroid89** [aws-amplify/aws-sdk-android#904]
In my Mobile app am working with AWS Cogito for user authentication, in that is possible to check or get whether the user login the first time.

**Comment by palpatim** [comment]
@alphaDroid89 

Can you clarify your question a bit? Do you mean "Whether the user logged in for the first time in a given session?" or "Whether this is the first time the user has ever logged into my app on this device?" or "Whether this is the first time the user has ever logged into my authentication system in any way?

Also, can you provide more details around your setup? Are you using Cognito Identity Pools or User Pools?

**Comment by alphaDroid89** [comment]
@palpatim, thanks for your response, actually "Whether this is the first time the user has ever logged into my authentication system in any way?" - am using "User Pool" sorry am not exposing those details

**Comment by palpatim** [comment]
@alphaDroid89 

The SDK doesn't offer this specifically. You could consider using a [Lambda Trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-triggers.html) to update a custom attribute at the appropriate stage of your user's sign-up lifecycle, and inspect that.

**Comment by alphaDroid89** [comment]
@palpatim Thank you so much, let me try as the way you suggested.

**Comment by palpatim** [comment]
Thanks, please let us know if it works for you.
