### ISSUE TITLE
Subscribe not receive All messages

### ISSUE THREAD

**Issue by habahbehbassam** [aws-amplify/aws-sdk-android#905]
**Chat App**

**Which AWS Services are you utilizing?**
 'com.amazonaws:aws-android-sdk-core:2.13.2'
 'com.amazonaws:aws-android-sdk-appsync:2.7.8'
 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.1'
 'org.eclipse.paho:org.eclipse.paho.android.service:1.1.1'

**Provide code snippets (if applicable)**

1. Added MqttService to manifests 
`<service android:name="org.eclipse.paho.android.service.MqttService" />`

2. Create AppSync Client 

```
syncClient = AWSAppSyncClient.builder()
                .context(context)
                .cognitoUserPoolsAuthProvider(() -> token.get())
                .awsConfiguration(new AWSConfiguration(context))
                .subscriptionsAutoReconnect(true)
                .build();

```
3. Create Subscription Call
```
syncClient.subscribe(
                SubscribeByUserIdSubscription.builder()
                        .receiver_user_id(receiverUserId)
                        .build()
        );
```
4. Call Subscription in new Thread and wait new Messages 

```
 new Thread(() ->
                tAppSyncSubscriptionCall.execute(new AppSyncSubscriptionCall.Callback<T>() {
                    @Override
                    public void onResponse(@Nonnull Response<T> response) {
                        handleGraphQlSuccessResponse(null,response);
                    }

                    @Override
                    public void onFailure(@Nonnull ApolloException e) {
                        handleGraphQlFailureResponse(null,e);
                    }

                    @Override
                    public void onCompleted() {
                        handleOnCompleted();
                    }
                })).start();
```

**Device Information (please complete the following information):**
 - Device: [Samsung S9 , Samsung S7, Huawei trt-L21A]
 - Android Version: [7.0 , 8.0.0 , 9]

**Comment by palpatim** [comment]
@habahbehbassam Thanks for moving this over to the [AppSync issues page](https://github.com/awslabs/aws-mobile-appsync-sdk-android/issues/154). I am closing this issue as a duplicate so we can track it in the correct place.

**Comment by habahbehbassam** [comment]
Ok thanks :)
