### ISSUE TITLE
Method threw 'com.amazonaws.mobileconnectors.apigateway.ApiClientException' exception. Cannot evaluate $Proxy2.toString()

### ISSUE THREAD

**Issue by kktheavi** [aws-amplify/aws-sdk-android#910]
I am getting exception while creating client object.

Exception:
Method threw 'com.amazonaws.mobileconnectors.apigateway.ApiClientException' exception.
Cannot evaluate $Proxy2.toString()

CODE:
```kotlin
val factory= ApiClientFactory()
factory.credentialsProvider(awsInstance.credentialsProvider)
factory.apiKey("flzINhh5cg7fUEkgZAf9z3rP2M5KmBWn2L5uAFyu")
var client=factory.build(RegistrationAndLoginvClient::class.java)
```

**Comment by palpatim** [comment]
@kktheavi 

Can you provide more detail around this? 

**Environment Information (please complete the following information):**
 - AWS Android SDK Version: [e.g. 2.6.25]
 - Device: [e.g. Pixel XL, Simulator]
 - Android Version: [e.g. Nougat 7.1.2]
 - Specific to simulators: [e.g. Yes/No]

**Comment by kktheavi** [comment]
AWS Android SDK Version:2.13.2
Device: all device(samsung galaxy On8, motorola power one,xiaomi mi4 )
Android Version: (from marshmallow to pie)
Specific to simulators: not using simulator, testing on real device

**Comment by kktheavi** [comment]
HI Roshan,

Can you help me out, I have not get any solution. @desokroshan @palpatim

**Comment by desokroshan** [comment]
@kktheavi I will try to reproduce the issue and share my findings. Meanwhile it will be helpful if you can share more information such as more detailed stacktrace.

**Comment by kktheavi** [comment]
Hi Roshan,

Here is code for creating client object.

val factory = ApiClientFactory();
val credentialsProvider = CognitoCachingCredentialsProvider(this,"us-east-1:b60930a0-1aba-4952-a376-998818bxxxxx",Regions.US_EAST_1)
factory.credentialsProvider(credentialsProvider)
val client = factory.build(ConfirmVerificationStatusvClient::class.java)

while creating client object, I got this exception:
Method threw 'com.amazonaws.mobileconnectors.apigateway.ApiClientException' exception. Cannot evaluate  @$Proxy2.toString() @desokroshan @palpatim

**Comment by kktheavi** [comment]
Hello Roshan,

I had sent my code and error , can you help me out.
@desokroshan @palpatim

**Comment by asinghnw** [comment]
Hello Roshan,

I am having the same issue too. Here is my code
`        new AsyncTask<Void, Void, Void>() {
            @Override
            protected Void doInBackground(Void... params) {

                CognitoUserSession session1 = AppHelper.getCurrSession();
                String idToken1 = session1.getIdToken().getJWTToken();
                Map<String, String> logins = new HashMap<String, String>();
                //fill it with Cognito User token
                logins.put("cognito-idp.us-east-2.amazonaws.com/us-east-xxxxxx", idToken1);


                CognitoCachingCredentialsProvider credentialsProvider1 = new CognitoCachingCredentialsProvider(
                        getApplicationContext(),
                        "us-east-2:xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx", // Identity pool ID
                        Regions.US_EAST_2 // Region
                );

                credentialsProvider1.setLogins(logins);

                ApiClientFactory factory = new ApiClientFactory().credentialsProvider(credentialsProvider1);

                final RegistergatewayClient client = factory.build(RegistergatewayClient.class);

                client.registerGatewayPost();

                return null;
            }
        }.execute();`

@kktheavi @palpatim @desokroshan @jpignata @jpeddicord 

Anyone who has figured this out please update the solution here.

Thanks in advance

**Comment by eeatonaws** [comment]
Using the code you provided and the latest version of the AWS SDK for Android, I only observe the error when debugging the app but not when running the app. If you are using Android Studio, you can fix the error when debugging the app by right clicking on the `proxy` variable in the debugger and selecting “View as” and then “Object”. This will display the variable in the debugger as an object rather than trying to use its `toString()` method, which in this case isn’t supported.
