### ISSUE TITLE
Delete a remote data

### ISSUE THREAD

**Issue by shengMR** [aws-amplify/aws-sdk-android#918]
Hi, I am having a problem during the use, try to delete a specified data in the remote S3 on the phone, but I can not find a method in the API, how can I delete it?

**Comment by palpatim** [comment]
@shengMR 

If you're using TransferUtility, there is not a method exposed for that action. You can use the AWS S3 SDK directly and access the [`deleteObject` or `deleteObjects` API](https://aws-amplify.github.io/aws-sdk-android/docs/reference/com/amazonaws/services/s3/AmazonS3Client.html#deleteObject-com.amazonaws.services.s3.model.DeleteObjectRequest-)

Hope this helps.

**Comment by shengMR** [comment]
Yes, I am using TransferUtility, I didn't find the corresponding Api, now I try to use the method you said, thank you

**Comment by kvasukib** [comment]
@shengMR Thank you for the response. Please feel free to re-open if you have any questions.
