### ISSUE TITLE
Upload to S3 bucket a photo from android app.

### ISSUE THREAD

**Issue by sunithapremjee** [aws-amplify/aws-sdk-android#923]
I am trying to upload to S3bucket a photo from my android app.Please let me know what am I missing.I couldn't find anything in my S3 bucket and TransferState.COMPLETED == state is never called so save() function to update DynamoDb string data is also not getting called.

**Comment by sunithapremjee** [comment]
![Uploadingfrom_AndroidApp_to_S3](https://user-images.githubusercontent.com/9869417/56775374-d3569b80-6794-11e9-9250-ccc1c88ce3e2.png)

**Comment by kvasukib** [comment]
@sunithapremjee Thank you for opening a new issue. Can you add the log statement as follows:-

```java
observer.setTransferListener(new TransferListener() {
    public void onStateChanged(int id, TransferState state) {
        Log.(TAG, "State = " + state);

        // .... other code
    }
});
```

and see if you are seeing the updates for `WAITING`, `IN_PROGRESS`, etc.?

**Comment by broakenmedia** [comment]
Same here! Reverting back to a previous version (2.13.0 in our case, but i believe any version before 2.13.3 will work based on when the issue started happening and 2.13.3's release date) restored everything back to working order.

**Comment by broakenmedia** [comment]
Well, this gets even more curious. Now that it's working, I just re-built the app with the latest SDK again and it's still working. It's almost as though the latest version is not pulling down credentials required for uploading, downgrading to the previous version allowed them to be stored and then re-updating means the latest SDK can use the now stored credentials

**Comment by kvasukib** [comment]
@broakenmedia `2.13.3` should fix the issue. We fixed a bug in `2.13.3` where a transfer could get stuck under certain circumstances. Can you try the latest version?

**Comment by broakenmedia** [comment]
@kvasukib It's in 2.13.3 that the issue began!

**Comment by kvasukib** [comment]
@broakenmedia Sorry for the delayed response. Are you still facing the issue in `2.13.4` version of the SDK?
