### ISSUE TITLE
Expose the sessionPresent flag in MQTT CONNACK messages

### ISSUE THREAD

**Issue by aleist** [aws-amplify/aws-sdk-android#925]
**Which AWS Services is the feature request for?**
IOT

**Is your feature request related to a problem? Please describe.**
There does not seem to be a way to retrieve the sessionPresent flag from the CONNACK message, which means I don't know if a session has been continued and so I have to always re-subscribe to topics.

**Describe the solution you'd like**
The flag is available from the IMqttToken that is passed to the connection callback by the underlying Paho client. The AWSIotMqttManager would simply have to extract the information contained therein and make it accessible through its own API.

**Describe alternatives you've considered**
Using the Paho client directly.

**Additional context**
aws-android-sdk-iot version 2.13.3

**Comment by palpatim** [comment]
Thanks for the request, we'll add this to our backlog of feature requests and update when we have more information. In the meantime, can you clarify your use case?

Are you looking for advice on when it is necessary to reconnect? That is, if the IoT client managed certain types of reconnections automatically, you wouldn't want to be notified until those automatic retry attempts had been exhausted, right?

**Comment by aleist** [comment]
Thanks for your reply. What I am missing is the ability to determine if a persistent session with the broker exists and has been resumed when I set the clean session flag to false in the initial connection request from my app. The auto reconnection behaviour is fine as long as the app is running, but if the device or app restarts for some reason, then the app has to explicitly initiate the connection again and I would like to avoid resubscribing to topics unless necessary.

The AWSIoTMqttClientStatusCallback already gets invoked to inform my app about auto-reconnection attempts, and I am aware that I can set the number of these attempts with setMaxAutoReconnectAttempts (including -1 == forever).

**Comment by aleist** [comment]
To add to my previous message: In addition to exposing the sessionPresent flag, it would be great if the auto-resubscribe functionality triggered by a successful auto-reconnect were to also take this flag into account and only resubscribe if necessary (sessionPresent == false). Especially given that, from what I can tell, it doesn't even bundle multiple topics in a single subscribe message, but sends one message per topic.

**Comment by richardmcclellan** [comment]
This was added in [AWS SDK for Android 2.19.3](https://github.com/aws-amplify/aws-sdk-android/releases/tag/release_v2.19.3) :tada:
