### ISSUE TITLE
AWSMobileClient change password always return onError in Kotlin.

### ISSUE THREAD

**Issue by JeetSA** [aws-amplify/aws-sdk-android#926]
**Describe the bug**
While changing the password it is returning error but the password is changed successfully. The method I used is "changePassword()". The error is as follow:
"java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter signInResult"

I am using kotlin for development. But after that I tried "changePassword()" method in a java file it was working. So this is a "Kotlin specific issue".

**To Reproduce**
A code sample:
```
AWSMobileClient.getInstance().
changePassword(oldPassword, confirmPassword, object : Callback<Void> {
            override fun onResult(signInResult: Void) {
                ...
            }
            override fun onError(e: Exception) {
                ...
            }
        })
```
**Expected behavior**

If I enter proper details it should call onResult, but it is calling "onError" with error 
```
"java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter signInResult".
```

**Environment Information (please complete the following information):**
 - AWS android sdk core Version: 2.13.2
 - AWS android sdk appsync Version: 2.7.9
 - Device: all devices

**Comment by palpatim** [comment]
AFAIK, we don't officially support Kotlin, but my understanding is that it should "just work" assuming our APIs are internally consistent. Assigning to @desokroshan for investigation.

**Comment by tvanmanh** [comment]
@JeetSA have you solved this problem. I faced it too.

**Comment by JeetSA** [comment]
@tvanmanh I haven't solved it yet but what I have done is I have specifically called that function from a java file and it works.

**Comment by minbi** [comment]
Hi @JeetSA @tvanmanh ,

If you change the method signature to be optional it works fine.

```
AWSMobileClient.getInstance().
changePassword(oldPassword, confirmPassword, object : Callback<Void> {
            override fun onResult(signInResult: Void?) {
                ...
            }
            override fun onError(e: Exception) {
                ...
            }
        })
```

This is a corner-case we'll have to investigate.

**Comment by tvanmanh** [comment]
Thanks so much!

Vào Th 6, 7 thg 6, 2019 vào lúc 03:11 minbi <notifications@github.com> đã
viết:

**Comment by JeetSA** [comment]
It is working fine. Thanks @tvanmanh for your support.

**Comment by UbaidKhan91** [comment]
My code is
    fun changePassword(existingPassword: String, newPassword: String) {

        getActivityContext()?.showLoader()


        AWSMobileClient.getInstance()
            .changePassword(existingPassword, newPassword, object : Callback<Void> {
                override fun onResult(signInResult: Void) {
                    ThreadUtils.runOnUiThread(Runnable {
                        getActivityContext()?.hideLoader()
                        getActivityContext()?.onBackPressed()
                    })
                }

                override fun onError(e: Exception) {
                    ThreadUtils.runOnUiThread(Runnable {
                        Log.d("errorAWS",e.toString())
                        getActivityContext()?.hideLoader()

                    })
                }
            })
    } but error can you please help me

**Comment by JeetSA** [comment]
@UbaidKhan91 

You just need to change the parameter of ```onResult``` function from ```signInResult: Void``` to ```signInResult: Void?``` and it will work. :)

**Comment by UbaidKhan91** [comment]
> @UbaidKhan91
> 
> You just need to change the parameter of `onResult` function from `signInResult: Void` to `signInResult: Void?` and it will work. :)

iam chnaging but error shown

**Comment by JeetSA** [comment]
@UbaidKhan91 Can you please share some more details about the error?
