### ISSUE TITLE
AmazonS3Client seems to be making too many GET requests

### ISSUE THREAD

**Issue by markorakita** [aws-amplify/aws-sdk-android#929]
**State your question**
I've created a bucket with 8 files, and I've used "AmazonS3Client.getObject(new GetObjectRequest(bucketName, fileKey), destination)" to download each of them in my app. When I checked cost explorer for my AWS account, it says I've used **431 GET Requests of Amazon S3**. I am trying to understand how it happened.
- Is it possible that getObject function is retrying download causing too many GET requests?
- Or maybe it is downloading files in small portions, and each portion counts towards one GET request?
- Does browsing the bucket in S3 console web site count as GET requests?
- Any other ideas how this might have happened? I am pretty much lost. With this pace I will pretty soon use up all of my 20,000 requests in the free tier :/

**Which AWS Services are you utilizing?**
Amazon S3

**Provide code snippets (if applicable)**
```
// I am calling this to construct the S3 client:
AmazonS3Client amazonS3Client = new AmazonS3Client(awsMobileClient, Region.getRegion(Regions.US_EAST_1));
// Then I am calling this 8 times, once for each of my files.
ObjectMetadata metadata = m_amazonS3Client.getObject(new GetObjectRequest(bucketName, fileKey), destination);
```

**Environment(please complete the following information):**
 - SDK Version: 2.13.2

**Device Information (please complete the following information):**
 - Device: Huawei Mate 10pro
 - Android Version: Pie 9.0

**Comment by markorakita** [comment]
Now it grew to 440 GET requests and also "Put, Copy, Post or List Requests of Amazon S3" category in my bill grew from 80 to 90.

Literally only thing my app did in the meantime was constructing the AmazonS3Client every time it starts with:
`AmazonS3Client amazonS3Client = new AmazonS3Client(awsMobileClient, Region.getRegion(Regions.US_EAST_1));`

and I also browsed the bucket on the [s3 console web site](https://s3.console.aws.amazon.com).

I am infinitely confused right now. Is maybe AmazonS3Client constructor accessing the buckets, doing something there?

I also have in my awsconfiguration.json these two snippets:
```
"UserFileManager": {
    "Default": {
      "Bucket": <bucket name undisclosed>,
      "Region": "us-east-1"
    }
  },
"S3TransferUtility": {
    "Default": {
      "Bucket": <bucket name undisclosed>,
      "Region": "us-east-1"
    }
  },
```

Maybe some of those are causing the aws sdk to access the S3 every time the app starts?

**Comment by kvasukib** [comment]
@markorakita Sorry for the inconvenience caused.

The `AmazonS3Client` constructors do not make any network requests to Amazon S3. So just the object constructions should not make any network requests to your bucket.

If `getObject()` is retrying, you could see that in the debug logs in Logcat. Every network request made by `getObject()` is logged at `DEBUG` level and you should be able to see the request and headers associated with it.

**_Is it possible that getObject function is retrying download causing too many GET requests?_**

If the getObject operation came back with a retryable exception such as 429 (ThrottlingException) or 500 (Internal Server Error), the SDK does a maximum of 3 retries at the HTTP Client layer.

**_Or maybe it is downloading files in small portions, and each portion counts towards one GET request?_**

We have a buffer at the HTTP Client layer which downloads X bytes of data over the network and writes to a file.

In-spite of how may network calls the SDK makes to S3 to fetch the data, S3 charges based on the amount of data transferred. For example $X per GB of data transferred.

_**Does browsing the bucket in S3 console web site count as GET requests?**_

 Browsing in the S3 console does not charge you a GET request. However if you download a file from the bucket through the console, you will be charged.


_**Any other ideas how this might have happened? I am pretty much lost. With this pace I will pretty soon use up all of my 20,000 requests in the free tier :/**_

Can I know what AWS Region you created the bucket in? And what is the AWS Region you are passing in to the `AmazonS3Client` constructor?

What is the storage class of your object?

**Comment by markorakita** [comment]
Hi @kvasukib thank you for your response!

I've also contacted billing support and I've got this response:
> Every interaction with console is listed as a request as the data is being pulled from S3 to your Interface for example, opening the console, viewing the buckets, checking content of the buckets. S3 is designed primarily for storage and retrieval of data.

While what you said is true in terms of browsing not making a GetObject request, lot of other requests seem to fall under "GET requests" category in the bill. I also found out that when you go to the billing history for certain month, instead of "GET requests" it says **"GET and all other requests under the monthly global free tier"**.
> Browsing in the S3 console does not charge you a GET request. However if you download a file from the bucket through the console, you will be charged.

I've also browsed my S3 requests using Cost Explorer and there I could see exactly how much requests I've made of each API function, and there I realized that lot of requests seem to fall under "GET requests" category in the bill. Requests like: ReadBucketServerSideEncryption, ReadBucketReplication, ReadBucketPublicAccessBlock, ReadBucketPolicy, ReadBucketCors, ReadBucketAnalytics...

Tons of these requests are being sent simply by browsing the S3 console, and **it isn't noted anywhere in the documentation or on the S3 console web site**. I guess it isn't such a problem for paying customers since those requests are pretty cheap, but for free tier users it matters since it quickly drains the 20,000 requests limit.

**Comment by kvasukib** [comment]
@markorakita Thank you for the detailed response. I understand your concern better now. I would recommend following up with the AWS Customer Support to resolve the conversation and provider suggestions to them on having a more granular billing.

**Comment by markorakita** [comment]
Customer support told me to open a thread on the forum since they don't have enough technical knowledge about S3 API and billing, so I opened one [here](https://forums.aws.amazon.com/thread.jspa?threadID=302709).

Closing this thread now, thanks for your responses!
