### ISSUE TITLE
Login view does not work on devices with small screens

### ISSUE THREAD

**Issue by haraldF** [aws-amplify/aws-sdk-android#945]
**Describe the bug**

following your example at:

https://aws.amazon.com/blogs/mobile/integrating-amazon-cognito-with-the-android-accountmanager-api/ 

we were able to successfully integrate Cognito login in the Androids Account system settings. The UI works on the consumer phones, however, not on our Android Automotive build and neither on Android devices with constrained screen sizes. I've attached three screen shots showing the cognito SignInView

https://ibb.co/NNSHt3K
https://ibb.co/SXwJL0b
https://ibb.co/4fFqB0K

**To Reproduce**

Use the account manager example as stated above on a device with constrained size, e.g. the QVGA AVD or an "always landscape" device.

**Which AWS service(s) are affected?**

Cognito login

**Expected behavior**

The view would show the usual Username / Password entry boxes and a "Sign In" button

**Screenshots**

See above:

https://ibb.co/NNSHt3K
https://ibb.co/SXwJL0b
https://ibb.co/4fFqB0K

**Environment Information (please complete the following information):**

SDK:

```
    implementation 'com.amazonaws:aws-android-sdk-core:2.12.6'
    implementation 'com.amazonaws:aws-android-sdk-auth-core:2.12.6@aar'
    implementation 'com.amazonaws:aws-android-sdk-auth-ui:2.12.6@aar'
    implementation 'com.amazonaws:aws-android-sdk-auth-ui:2.12.6@aar'
    implementation 'com.amazonaws:aws-android-sdk-auth-userpools:2.12.6@aar'
    implementation 'com.amazonaws:aws-android-sdk-auth-google:2.12.6@aar'
    implementation 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.12.6'
    implementation('com.amazonaws:aws-android-sdk-cognitoauth:2.12.+@aar') { transitive = true }
```

 - Device: Any device with "always landscape" or constrained vertical space
 - Android Version: 9
 - Specific to simulators: No

**Additional context**

**Comment by palpatim** [comment]
@haraldF 

Thanks for your report. We're already tracking this in #523, and have this as a feature request on our backlog.
