### ISSUE TITLE
getTokens does not support retrieving tokens while signed-out

### ISSUE THREAD

**Issue by mdaslamHossin** [aws-amplify/aws-sdk-android#948]
**I am trying to get tokens but showing an error message which is irrelevant I think. Please help me if anyone faces the same problem. **
Code Snippet below: 
```kotlin
fun getTokenResponse() {
    AWSMobileClient.getInstance().getTokens(object : Callback<Tokens> {
      override fun onResult(result: Tokens?) {
        runOnUiThread {
          result?.let {
            val tokenResponse = TokenResponse()
            tokenResponse.idToken = it.idToken.tokenString
            tokenResponse.refreshToken = it.refreshToken.tokenString
            tokenResponse.accessToken = it.accessToken.tokenString
            appPrefernceHelper.saveTokenResponse(tokenResponse)
          }
        }

      }

      override fun onError(e: Exception) {
        Timber.e("Error Token ${e.message}")
      }

    })
  }
```

**Comment by minbi** [comment]
Hi @mdaslamHossin ,

Can you provide some more details? The tokens will not be available when signed-out. They are cleared when you call signOut.

**Comment by aslamhossin** [comment]
@minbi 
I have also tried below way 
`AWSMobileClient.getInstance().addUserStateListener { details ->
      details.userState?.let {
        when (it) {
          UserState.SIGNED_IN -> {
            runOnUiThread {
              try {
                val tokenResponse = TokenResponse()
                val tokens = AWSMobileClient.getInstance().tokens
                tokenResponse.idToken = tokens.idToken.tokenString
                tokenResponse.refreshToken = tokens.refreshToken.tokenString
                tokenResponse.accessToken = tokens.accessToken.tokenString
                appPrefernceHelper.saveTokenResponse(tokenResponse)
                Timber.e("Saving Token Init  $tokenResponse")
              } catch (e: Exception) {
                Timber.e("${e.cause}")
              }

            }

          }

          UserState.SIGNED_OUT -> {

          }
          else -> {

          }
        }
      }
    }`

**Comment by minbi** [comment]
Hi @aslamhossin ,

How are you trying to sign-in? If you are using `federatedSignIn` token retrieval is not currently supported.

Sample code:
```
AWSMobileClient.getInstance().initialize(applicationContext, object: Callback<UserStateDetails> {
    override fun onResult(result: UserStateDetails?) {
        // Clear out previous session for this example
        AWSMobileClient.getInstance().signOut()

        // Attach a listener
        AWSMobileClient.getInstance().addUserStateListener {
            runOnUiThread {
                val tokens = AWSMobileClient.getInstance().getTokens()
                tokens.idToken.tokenString
            }
        }
        
        // Sign-in
        AWSMobileClient.getInstance().signIn("userA", "passA", null)
    }

    override fun onError(e: Exception?) {
        e?.printStackTrace()
    }
})
```

**Comment by aslamhossin** [comment]
> Hi @aslamhossin ,
> 
> How are you trying to sign-in? If you are using `federatedSignIn` token retrieval is not currently supported.
> 
> Sample code:
> 
> ```
> AWSMobileClient.getInstance().initialize(applicationContext, object: Callback<UserStateDetails> {
>     override fun onResult(result: UserStateDetails?) {
>         // Clear out previous session for this example
>         AWSMobileClient.getInstance().signOut()
> 
>         // Attach a listener
>         AWSMobileClient.getInstance().addUserStateListener {
>             runOnUiThread {
>                 val tokens = AWSMobileClient.getInstance().getTokens()
>                 tokens.idToken.tokenString
>             }
>         }
>         
>         // Sign-in
>         AWSMobileClient.getInstance().signIn("userA", "passA", null)
>     }
> 
>     override fun onError(e: Exception?) {
>         e?.printStackTrace()
>     }
> })
> ```

Is there any exception caught? In my case, it was my in configuration.json, so please recheck your configuration JSON and removed the unused part from it otherwise it will try to configure unused part and failed.

**Comment by minbi** [comment]
Thanks for the followup.

For future readers:
The AWSMobileClient will read all relevant parts of the awsconfiguration.json and use all relevant parts. If there are resources identified in your awsconfiguration.json that are not configured to work together they should be removed in the case of AWSMobileClient.

Closing this issue.
