### ISSUE TITLE
Error in initializing the CognitoCachingCredentialsProvider : NullPointerException on getSharedPreferences 

### ISSUE THREAD

**Issue by NassB** [aws-amplify/aws-sdk-android#952]
**Describe the bug**
NullPointerException when I am trying to integrate a User Pool with an Identity Pool like in the documentation https://docs.aws.amazon.com/cognito/latest/developerguide/tutorial-integrating-user-pools-android.html?shortFooter=true#tutorial-integrating-user-pools-getting-aws-credentials-android.

The NullPointerException is 

> E/CognitoCachingCredentialsProvider: Error in initializing the CognitoCachingCredentialsProvider. java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
[...]
> Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:174)
at com.amazonaws.internal.keyvaluestore.AWSKeyValueStore.setPersistenceEnabled(AWSKeyValueStore.java:118)
at com.amazonaws.internal.keyvaluestore.AWSKeyValueStore.<init>(AWSKeyValueStore.java:108)
at com.amazonaws.auth.CognitoCachingCredentialsProvider.initialize(CognitoCachingCredentialsProvider.java:425)
at com.amazonaws.auth.CognitoCachingCredentialsProvider.<init>(CognitoCachingCredentialsProvider.java:190) 

**To Reproduce**
I am using 
`CognitoCachingCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(this, identityPoolId, cognitoRegion);`

And I set the logins in onSuccess callback from AuthenticationHandler 
` AuthenticationHandler authenticationHandler = new AuthenticationHandler() {`
`@Override`
`public void onSuccess(CognitoUserSession cognitoUserSession, CognitoDevice device) {`
`AwsHelper.setCurrSession(cognitoUserSession);`
`Map<String, String> logins = new HashMap<>();`
`logins.put("cognito-idp."+cognitoRegion+".amazonaws.com/"+ userPoolId, cognitoUserSession.getIdToken().getJWTToken());`
`credentialsProvider.setLogins(logins);`
`}`

`AwsHelper.getPool().getUser(username).getSessionInBackground(authenticationHandler);`

**Which AWS service(s) are affected?**

_cognitoidentityprovider_

**Environment Information (please complete the following information):**

AWS Android SDK Version: 

app build.gradle
> implementation 'com.amazonaws:aws-android-sdk-core:2.13.4'
> implementation 'com.amazonaws:aws-android-sdk-appsync:2.8.3'
> implementation 'com.amazonaws:aws-android-sdk-cognitoidentityprovider:2.13.4'

project build.gradle
> classpath 'com.amazonaws:aws-android-sdk-appsync-gradle-plugin:2.8.3'

Device: Sony Xperia XZ1
Android Version: 9.0.0 API 28

**Comment by NassB** [comment]
Ok so I was able to initialized CognitoCachingCredentialsProvider, my credentialsProvider object was not initialized in onCreate method this is why I got this NullPointerException.... (This is what I call a 
'lack of sleep error' 😅)

But I got in the logcat :

> D/CognitoCachingCredentialsProvider: Loading credentials from SharedPreferences
D/CognitoCachingCredentialsProvider: No valid credentials found in SharedPreferences
D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences
D/CognitoCachingCredentialsProvider: Clearing credentials from SharedPreferences

I thought that my current Cognito user registered in my specific user group would be registered in my identity group. But my user has not been added to my identity group. I do not know if I'm doing things right or if in the end what I'm trying to do is not possible from the application.

**Comment by kvasukib** [comment]
@NassB When you create the `CognitoCachingCredentialsProvider` object, do you have a valid Android application / activity context that you pass in during object construction?

**Comment by NassB** [comment]
Yes I create `CognitoCachingCredentialsProvider` in the onSuccess callback in 
`AuthenticationHandler authenticationHandler = new AuthenticationHandler() {...}` 
with 
`credentialsProvider = new CognitoCachingCredentialsProvider(getApplicationContext(), identityPoolId, cognitoRegion);`

**Comment by kvasukib** [comment]
@NassB This issue is mainly because the context passed in through `CognitoCachingCredentialsProvider` to `AWSKeyValueStore` is null. If you pass in a non-null valid context, you shouldn't be seeing this issue any more.

**Comment by NassB** [comment]
Yes that what I am doing now like I said in my previous message

> Yes I create `CognitoCachingCredentialsProvider` in the onSuccess callback in
> `AuthenticationHandler authenticationHandler = new AuthenticationHandler() {...}`
> with
> `credentialsProvider = new CognitoCachingCredentialsProvider(getApplicationContext(), identityPoolId, cognitoRegion);`

So I dont have the issue anymore. Thanks.
