### ISSUE TITLE
AWS API gateway giving 403 error in response with message "forbidden"

### ISSUE THREAD

**Issue by JeetSA** [aws-amplify/aws-sdk-android#968]
**I am using aws api gateway for calling external API. I am always getting status code 403 and response "{"message":"Forbidden"}". **

```java
        // Create api client
        AWSCredentialsProvider credentialsProvider = new CognitoCachingCredentialsProvider(
                context, // get the context for the current activity
                "xxxxxxx", // your identity pool id
                Regions.xxxx  //Region
        );
        final EchoClient apiClient = new ApiClientFactory()
                .credentialsProvider(credentialsProvider)
                .build(EchoClient.class);

        // Create components of api request
        final String method = "GET";
        final String path = "https://xxxx/students";

        final Map parameters = new HashMap<>();
        parameters.put("lang", "en_US");

        final Map headers = new HashMap<>();
        headers.put("Content-Type", "application/json");
        headers.put("Authorization", "Bearer " + token);
        // Use components to create the api request
        ApiRequest localRequest =
                new ApiRequest(apiClient.getClass().getSimpleName())
                        .withPath(path)
                        .withHttpMethod(HttpMethodName.valueOf(method))
                        .withHeaders(headers)
                        .withParameters(parameters);

        final ApiRequest request = localRequest;

        // Make network call on background thread
        new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    LogUtils.d(
                            "Invoking API w/ Request : " +
                                    request.getHttpMethod() + ":" +
                                    request.getPath());

                    final ApiResponse response = apiClient.execute(request);

                    final InputStream responseContentStream = response.getContent();

                    if (responseContentStream != null) {
                        final String responseData = IOUtils.toString(responseContentStream);
                        LogUtils.d("Response : " + responseData);
                    }

                    LogUtils.d(response.getStatusCode() + " " + response.getStatusText());

                } catch (final Exception exception) {
                    LogUtils.e(exception.getMessage());
                    exception.printStackTrace();
                }
            }
        }).start();
```

**I am using below sdk:**
```
 - com.amazonaws:aws-android-sdk-apigateway-core:2.13.2
 - com.amazonaws:aws-android-sdk-mobile-client:2.13.+@aar
 - com.amazonaws:aws-android-sdk-auth-userpools:2.13.+@aar
```

Can anyone tell me what am I doing wrong and can anyone please share any demo for calling external API from AWS API gateway?

**Comment by kvasukib** [comment]
@JeetSA Sorry for the inconvenience caused.

Does the Unauthenticated / Authenticated role attached to the Cognito Identity Pool has permissions to access APIGateway API you have configured?

Also can you call `credentialsProvider.getCredentials()` to see if you are able to retrieve AWS Credentials without any error?

**Comment by JeetSA** [comment]
@kva
Thanks for the feedback.

1) Yes, both roles are attached to the Cognito Identity Pool and it has permissions to access the gateway.

2) Yes, I am able to get create retrieve AWS Credentials without any error.

One more thing which I observed while debugging is when I create "apiClient" object, it is returning "Method threw 'com.amazonaws.mobileconnectors.apigateway.ApiClientException' exception. Cannot evaluate $Proxy3.toString()" but the rest of the code executes and it is returning error 403 along with the message "forbidden".

**Comment by owen9825** [comment]
I noticed with the AWS libraries that sometimes, there'll be a `403 Permission denied` response even when it should've really been `404`, since the URL was incorrect.

**Comment by tendynewbies** [comment]
Hi @JeetSA ,
Greetings!!

I am also facing similar issue while accessing API-Gateway, using amilfy-android library.
Did you get any resolution for this issue?

Request you to please share, I really need it ver much.

**Comment by JeetSA** [comment]
Hello @tendynewbies 

Here you need to add a session token for AWS to get access for the API. To add a session token, I have changed the `credentialsProvider` variable from `CognitoCachingCredentialsProvider` to `StaticCredentialsProvider`.

Here is the code block in kotlin.

`val credentialsProvider = StaticCredentialsProvider(BasicSessionCredentials(AWSMobileClient.getInstance().awsCredentials.awsAccessKeyId, AWSMobileClient.getInstance().awsCredentials.awsSecretKey, (AWSMobileClient.getInstance().awsCredentials as BasicSessionCredentials).sessionToken))`

This might help you. :)

**Comment by tendynewbies** [comment]
Thanks @JeetSA,

I got your point, how you achieved this.
But, I'm afraid I am using amplify-android library for [REST API](https://docs.amplify.aws/lib/restapi/fetch/q/platform/android) calls, which is having similar issue.

I think, I'll have to look for an alternate like custom HttpClient OR aws-android-sdk-mobile-client, in case I don't get solution on [issue](https://github.com/aws-amplify/amplify-android/issues/644).

BUT, Thanks again for suggesting an alternate.
