### ISSUE TITLE
NumberFormatException thrown in CognitoCachingCredentialsProvider

### ISSUE THREAD

**Issue by markacoss** [aws-amplify/aws-sdk-android#972]
An issue currently affecting our production app where a NumbersFormatException is being thrown in CognitoCachingCredentialsProvider. In this release we moved from AWS Android SDK version 2.7.0 to 2.13.4. 

```
Fatal Exception: java.lang.IllegalStateException: Error in initializing the CognitoCachingCredentialsProvider. 
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.initialize(CognitoCachingCredentialsProvider.java:434)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.<init>(CognitoCachingCredentialsProvider.java:383)
Caused by java.lang.NumberFormatException: null
       at java.lang.Long.parseLong(Long.java:557)
       at java.lang.Long.parseLong(Long.java:636)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.loadCachedCredentials(CognitoCachingCredentialsProvider.java:590)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.initialize(CognitoCachingCredentialsProvider.java:430)
       at com.amazonaws.auth.CognitoCachingCredentialsProvider.<init>(CognitoCachingCredentialsProvider.java:383)
```

Exceptions are thrown while getting the credentialsProvider prior to making a Lambda call and getting an AmazonS3Client to use in TransferUtility.

This issue seems intermittent and does not happen all time and has been difficult to reproduce. Our crash reporting has been picking up this exception and has occurred more than once for some users. 

 - AWS Android SDK Version: 2.13.4
 - Device: Range of devices from Pixel 2 to Samsungs.
 - Android Version: so far only Android 9 devices has been reported
 - Specific to simulators: No

**Comment by hvar90** [comment]
i am having the error 
`java.lang.IllegalStateException: Error in initializing the CognitoCachingCredentialsProvider.`
on version 2.13.4

**Comment by kvasukib** [comment]
@markacoss Sorry for the inconvenience caused. From the code snippet, 

```java
        if (awsKeyValueStore.get(namespace(EXP_KEY)) != null) {
            sessionCredentialsExpiration = new Date(
                    Long.parseLong(awsKeyValueStore.get(namespace(EXP_KEY))));
        } else {
            sessionCredentialsExpiration = new Date(0);
        }
```

We check if the store has a key EXP_KEY with a non-null value and then read it and parse it as Long. It's possible that there is a race condition where if check succeeded however before we could retrieve the key-value pair, the key could have been cleared.

Is there a chance that your app is calling `CognitoCachingCredentialsProvider.clearCredentials()` while initializing is running in parallel?

**Comment by hvar90** [comment]
i have this error because i am creating CognitoCachingCredentialsProvider on many threads in parallel
if i use this on the method 
```
ReentrantLock lock = new ReentrantLock();
lock.lock();
/////////////////////////
lock.unlock();
```
will it resolve the problem ???

**Comment by kvasukib** [comment]
@hvar90 I would recommend synchronizing on the refresh(), clear(), getCredentials() operation if you are creating credentials providers objects for the same Cognito identity pool id. Let me know how it works after you try it out.

**Comment by hvar90** [comment]
do you mean synchronizing only on the call refresh()?
something like this ? 
```
ReentrantLock lock = new ReentrantLock();
lock.lock();
credentialsProvider.refresh();
lock.unlock();
```

**Comment by kvasukib** [comment]
Yes. I would recommend synchronizing on any call that mutates the data stored in SharedPreferences: `refresh()`, `clear()`, `getCredentials()`. 

Alternatively, you could create a `CognitoCachingCredentialsProvider` object upon app startup and pass it between activities or have a reference to it which can be accessed in other activities and this avoids creating the object several times.

**Comment by hvar90** [comment]
i though the alternative 
create CognitoCachingCredentialsProvider object upon app startup but i dont know how to have a reference to that object
the onle way i know is with a static variable but i dont know if that is a good solution

**Comment by markacoss** [comment]
@kvasukib Thanks for addressing this quickly. Appreciate that. Yes there is a possibility that there might be a race condition so I'll look into that. Our current AWS credentials provider calls have been setup like this prior to me starting at the company 15 months ago and this is the first time I have seen this issue. Have your changed the way this works internally in your later SDKs releases? To have happy customers I tried rolling back to version 2.7.0 but due to a SQL DB upgraded I had to settle with version 2.11.1. So far no issue with that version.  Would like to understand what might have changed in the SDK and at which version to help with avoiding further issues. I'll now make it a priority to rework the calls. Thanks for your recommendations too.

**Comment by hvar90** [comment]
@kvasukib 
i realized that refresh() is a syncronized method so i think  is necessary  synchronizing onCognitoCachingCredentialsProvider  constructor  too 
```
@Override
    public void refresh() {
    	credentialsLock.writeLock().lock();
    	try {
    		super.refresh();

    		// null check before saving credentials
    		if (sessionCredentialsExpiration != null) {
    			saveCredentials(sessionCredentials,
    					sessionCredentialsExpiration.getTime());
    		}
    	} finally {
    		credentialsLock.writeLock().unlock();
    	}
    }
```
https://github.com/aws-amplify/aws-sdk-android/blob/master/aws-android-sdk-core/src/main/java/com/amazonaws/auth/CognitoCachingCredentialsProvider.java

**Comment by hvar90** [comment]
@markacoss it is true, the only version working well is  2.11.1

**Comment by kvasukib** [comment]
@markacoss Thank you for the detailed analysis.We made changes in `2.12.+` version of the SDK to store the credentials securely by encrypting them before storing in `SharedPreferences`. As part of this, the information will be encrypted before storing and decrypted after retrieving. This is the main change made in `2.12.+` version of the SDK.

**Comment by markacoss** [comment]
@kvasukib Thanks for sharing that. Appreciate it.

**Comment by kvasukib** [comment]
@markacoss Checking if you are able to reproduce the issue locally? If so, can you share the steps to reproduce?

**Comment by markacoss** [comment]
@kvasukib I did experience the issue a few times when first switching to the new library but have not been able to reproduce again. Sorry not very helpful.

**Comment by kvasukib** [comment]
@markacoss Thank you for the response. I will add the closing soon label to this issue for now. Please feel free to re-open when you are able to reproduce it locally and if you get logs and crash report. Thanks.
