### ISSUE TITLE
When there are multiple groups added or there is no group added in user , I am not getting sign in state.

### ISSUE THREAD

**Issue by JeetSA** [aws-amplify/aws-sdk-android#979]
When I am creating a user from AWS cognito console, there is an option to add a group. When we do not add any group I am not able to get tokens after sign in. 

If only one group is added, it is working properly.

When there are multiple groups, I am facing the same issue.

The error which I am getting while getting token is "getTokens does not support retrieving tokens while signed-out".

**To Reproduce**
Create a user in aws cognito console and add 2 groups into that user. After that sign in from app from that user and try to get tokens by "getToken" method.

**I am using below sdk:**
- com.amazonaws:aws-android-sdk-apigateway-core:2.13.2
 - com.amazonaws:aws-android-sdk-mobile-client:2.13.+@aar
 - com.amazonaws:aws-android-sdk-auth-userpools:2.13.+@aar

**Comment by minbi** [comment]
Hi @JeetSA ,

When you call `signIn()` is the `onResult` or `onError` called? If the sign-in failed then this behavior is expected.

If the `onError` is called can you provide the entire stacktrace for the exception returned?
